snode.c: net::socket::stream::tls::SocketConnector< SocketT > Class Template Reference
net::socket::stream::tls::SocketConnector< SocketT > Class Template Reference
#include <SocketConnector.h>
Public Types
using SocketConnection = stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Types inherited from net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >
using SocketConnection = stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
SocketConnector (const std::shared_ptr< const SocketContextFactory > &socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketConnector () override
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >
SocketConnector (const std::shared_ptr< const SocketContextFactory > &socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from net::DescriptorEventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Attributes
SSL_CTX * ctx = nullptr
Protected Attributes inherited from net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >
std::function< void(int err)> onError
std::map< std::string, std::any > options
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >
void destruct ()
Protected Member Functions inherited from net::ConnectEventReceiver
ConnectEventReceiver (long timeout=10)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketConnector< SocketT >
Definition at line 41 of file SocketConnector.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::tls::SocketConnector< SocketT >::Socket = typename SocketConnection::Socket
Definition at line 44 of file SocketConnector.h.
SocketAddress
template<typename SocketT > using net::socket::stream::tls::SocketConnector< SocketT >::SocketAddress = typename Socket::SocketAddress
Definition at line 45 of file SocketConnector.h.
SocketConnection
template<typename SocketT > using net::socket::stream::tls::SocketConnector< SocketT >::SocketConnection = stream::tls::SocketConnection<SocketT>
Definition at line 43 of file SocketConnector.h.
Constructor & Destructor Documentation
SocketConnector()
template<typename SocketT > net::socket::stream::tls::SocketConnector< SocketT >::SocketConnector (const std::shared_ptr< const SocketContextFactory > & socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Definition at line 47 of file SocketConnector.h.
                 : stream::SocketConnector<SocketConnection>(
                       socketContextFactory,
                       onConnect,
                       [onConnected, this](SocketConnection* socketConnection) -> void { // onConnect
                           SSL* ssl = socketConnection->startSSL(this->ctx);
                           if (ssl != nullptr) {
                               ssl_set_sni(ssl, this->options);
                               SSL_set_connect_state(ssl);
                               socketConnection->doSSLHandshake(
                                   [onConnected, socketConnection](void) -> void { // onSuccess
                                       LOG(INFO) << "SSL/TLS initial handshake success";
                                       onConnected(socketConnection);
                                   },
                                   [this](void) -> void { // onTimeout
                                       LOG(WARNING) << "SSL/TLS initial handshake timed out";
                                       this->onError(ETIMEDOUT);
                                   },
                                   [this](int sslErr) -> void { // onError
                                       ssl_log("SSL/TLS initial handshake failed", sslErr);
                                       this->onError(-sslErr);
                                   });
                           } else {
                               socketConnection->SocketConnection::SocketReader::disable();
                               ssl_log_error("SSL/TLS initialization failed");
                               this->onError(-SSL_ERROR_SSL);
                           }
                       },
                       [onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                           socketConnection->stopSSL();
                           onDisconnect(socketConnection);
                       },
                       options) {
                 ctx = ssl_ctx_new(options, false);
             }
References net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::onConnected, net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::onError, net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::socketConnection, net::socket::stream::tls::ssl_log(), and net::socket::stream::tls::ssl_set_sni().
~SocketConnector()
template<typename SocketT > net::socket::stream::tls::SocketConnector< SocketT >::~SocketConnector () inline override virtual
Reimplemented from net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >.
Definition at line 90 of file SocketConnector.h.
{
                 ssl_ctx_free(ctx);
             }
References net::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
connect()
template<typename SocketT > void net::socket::stream::tls::SocketConnector< SocketT >::connect (const SocketAddress & remoteAddress, const SocketAddress & bindAddress, const std::function< void(int)> & onError) inline
Definition at line 94 of file SocketConnector.h.
{
                 if (ctx == nullptr) {
                     errno = EINVAL;
                     onError(errno);
                     stream::SocketConnector<SocketConnection>::destruct();
                 } else {
                     stream::SocketConnector<SocketConnection>::connect(remoteAddress, bindAddress, onError);
                 }
             }
References net::socket::stream::SocketConnector< SocketConnectionT >::connect(), and net::socket::stream::SocketConnector< SocketConnectionT >::destruct().
Member Data Documentation
ctx
template<typename SocketT > SSL_CTX* net::socket::stream::tls::SocketConnector< SocketT >::ctx = nullptr protected
Definition at line 105 of file SocketConnector.h.
The documentation for this class was generated from the following file:
net/socket/stream/tls/SocketConnector.h