snode.c: web::ws::server::WSContext Class Reference
web::ws::server::WSContext Class Reference
#include <WSContext.h>
Static Public Member Functions
static WSContext * create (web::http::server::Request &req, web::http::server::Response &res)
Protected Member Functions
WSContext (web::ws::WSSubProtocol *wSSubProtocol, web::ws::WSSubProtocol::Role role)
~WSContext () override
Protected Member Functions inherited from web::ws::WSContext
WSContext (web::ws::WSSubProtocol *wSSubProtocol, web::ws::WSSubProtocol::Role role)
Protected Member Functions inherited from net::socket::stream::SocketProtocol
SocketProtocol ()=default
virtual ~SocketProtocol ()=default
Protected Member Functions inherited from web::ws::WSReceiver
void begin ()
uint64_t readOpcode (char *junk, uint64_t junkLen)
uint64_t readLength (char *junk, uint64_t junkLen)
uint64_t readELength (char *junk, uint64_t junkLen)
uint64_t readMaskingKey (char *junk, uint64_t junkLen)
uint64_t readPayload (char *junk, uint64_t junkLen)
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Protected Member Functions inherited from web::ws::WSTransmitter
WSTransmitter (bool masking)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
Additional Inherited Members
Public Member Functions inherited from net::socket::stream::SocketProtocol
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void close ()
void switchSocketProtocol (SocketProtocol *socketProtocol)
void setTimeout (int timeout)
Public Member Functions inherited from web::ws::WSReceiver
void receive (char *junk, std::size_t junkLen)
Static Public Attributes inherited from web::ws::WSContext
static web::ws::subprotocol::WSSubProtocolSelector selector
Protected Types inherited from web::ws::WSReceiver
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Protected Attributes inherited from web::ws::WSContext
web::ws::WSSubProtocol * wSSubProtocol
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
Protected Attributes inherited from web::ws::WSReceiver
enum web::ws::WSReceiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
Detailed Description
Definition at line 32 of file WSContext.h.
Constructor & Destructor Documentation
WSContext()
web::ws::server::WSContext::WSContext (web::ws::WSSubProtocol * wSSubProtocol, web::ws::WSSubProtocol::Role role) protected
Definition at line 37 of file WSContext.cpp.
         : web::ws::WSContext(wSSubProtocol, role) {
     }
~WSContext()
web::ws::server::WSContext::~WSContext () override protected virtual
Reimplemented from web::ws::WSContext.
Member Function Documentation
create()
WSContext * web::ws::server::WSContext::create (web::http::server::Request & req, web::http::server::Response & res) static
Definition at line 50 of file WSContext.cpp.
{
         std::string subProtocol = req.header("sec-websocket-protocol");
         web::ws::subprotocol::WSSubProtocolPluginInterface* wSSubProtocolPluginInterface =
             selector.select(subProtocol, web::ws::WSSubProtocol::Role::SERVER);
         web::ws::server::WSContext* wSContext = nullptr;
         if (wSSubProtocolPluginInterface != nullptr) {
             web::ws::WSSubProtocol* wSSubProtocol = wSSubProtocolPluginInterface->create();
             if (wSSubProtocol != nullptr) {
                 wSContext = new web::ws::server::WSContext(wSSubProtocol, web::ws::WSSubProtocol::Role::SERVER);
                 if (wSContext != nullptr) {
                     res.set("Upgrade", "websocket");
                     res.set("Connection", "Upgrade");
                     res.set("Sec-WebSocket-Protocol", subProtocol);
                     web::ws::serverWebSocketKey(req.header("sec-websocket-key"), [&res](char* key) -> void {
                         res.set("Sec-WebSocket-Accept", key);
                     });
                     res.status(101); // Switch Protocol
                 } else {
                     res.status(500);
                 }
             } else {
                 res.status(500); // Internal Server Error
             }
         } else {
             res.status(404); // Not found
         }
         return wSContext;
     }
References web::ws::subprotocol::WSSubProtocolPluginInterface::create, web::http::server::Request::header(), web::ws::subprotocol::WSSubProtocolSelector::select(), web::ws::WSContext::selector, web::ws::WSSubProtocol::SERVER, web::ws::serverWebSocketKey(), web::http::server::Response::set(), web::http::server::Response::status(), and web::ws::WSContext::wSSubProtocol.
Referenced by web::http::server::Response::upgrade().
The documentation for this class was generated from the following files:
web/ws/server/WSContext.h
web/ws/server/WSContext.cpp