snode.c: web::http::server::SocketContext Class Reference
web::http::server::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Types
using SocketConnection = net::socket::stream::SocketConnection
Public Member Functions
SocketContext (net::socket::stream::SocketConnection *socketConnection)
SocketContext (const SocketContext &)=delete
SocketContext & operator= (const SocketContext &)=delete
virtual void sendToPeerCompleted ()=0
virtual void terminateConnection ()=0
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketContext (const SocketContextFactory &socketContextFactory)
void setTimeout (int timeout)
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
virtual void onConnected ()
virtual void onDisconnected ()
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnection *socketConnection)
virtual ~SocketContext ()=default
Detailed Description
Definition at line 38 of file SocketContext.h.
Member Typedef Documentation
SocketConnection
using web::http::server::SocketContext::SocketConnection = net::socket::stream::SocketConnection
Definition at line 40 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext() [1/2]
web::http::server::SocketContext::SocketContext (net::socket::stream::SocketConnection * socketConnection) inline
Definition at line 42 of file SocketContext.h.
             : net::socket::stream::SocketContext(socketConnection) {
         }
SocketContext() [2/2]
web::http::server::SocketContext::SocketContext (const SocketContext &) delete
Member Function Documentation
operator=()
SocketContext& web::http::server::SocketContext::operator= (const SocketContext &) delete
sendToPeerCompleted()
virtual void web::http::server::SocketContext::sendToPeerCompleted () pure virtual
Implemented in web::http::server::SocketContextT< RequestT, ResponseT >.
Referenced by web::http::server::Response::enqueue().
terminateConnection()
virtual void web::http::server::SocketContext::terminateConnection () pure virtual
Implemented in web::http::server::SocketContextT< RequestT, ResponseT >.
Referenced by web::http::server::Response::enqueue(), web::http::server::Response::error(), and express::Response::sendFile().
The documentation for this class was generated from the following file:
web/http/server/SocketContext.h