snode.c: net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
#include <SocketConnectionT.h>
Public Types
using SocketReader = SocketReaderT
using SocketWriter = SocketWriterT
using SocketAddress = SocketAddressT
Public Member Functions
void setTimeout (int timeout) override
const SocketAddress & getRemoteAddress () const
const SocketAddress & getLocalAddress () const
std::string getLocalAddressAsString () const override
std::string getRemoteAddressAsString () const override
void sendToPeer (const char *junk, std::size_t junkLen) override
void sendToPeer (const std::string &data) override
std::size_t readFromPeer (char *junk, std::size_t junkLen) override
void close () final
SocketContext * getSocketContext () override
void switchSocketContext (const SocketContextFactory &socketContextFactory) override
Protected Member Functions
SocketConnectionT (int fd, const std::shared_ptr< const SocketContextFactory > &socketContextFactory, const SocketAddress &localAddress, const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void()> &onDisconnect)
virtual ~SocketConnectionT ()
Protected Member Functions inherited from net::socket::stream::SocketConnection
SocketConnection ()=default
virtual ~SocketConnection ()=default
Private Member Functions
SocketConnectionT ()=delete
void readEvent () override
void writeEvent () override
void unobserved () override
Private Attributes
SocketContext * socketContext = nullptr
SocketAddress localAddress {}
SocketAddress remoteAddress {}
std::function< void()> onDisconnect
Additional Inherited Members
Protected Attributes inherited from net::socket::stream::SocketConnection
friend SocketContext
Detailed Description
template<typename SocketReaderT, typename SocketWriterT, typename SocketAddressT>
class net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >
Definition at line 38 of file SocketConnectionT.h.
Member Typedef Documentation
SocketAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 47 of file SocketConnectionT.h.
SocketReader
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketReader = SocketReaderT
Definition at line 45 of file SocketConnectionT.h.
SocketWriter
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketWriter = SocketWriterT
Definition at line 46 of file SocketConnectionT.h.
Constructor & Destructor Documentation
SocketConnectionT() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnectionT () private delete
SocketConnectionT() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnectionT (int fd, const std::shared_ptr< const SocketContextFactory > & socketContextFactory, const SocketAddress & localAddress, const SocketAddress & remoteAddress, const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void()> & onDisconnect) inline protected
Definition at line 50 of file SocketConnectionT.h.
             : SocketReader([this](int errnum) -> void {
                 socketContext->onReadError(errnum);
                 SocketWriter::disable();
             })
             , SocketWriter([this](int errnum) -> void {
                 socketContext->onWriteError(errnum);
                 SocketReader::disable();
             })
             , socketContext(socketContextFactory->create(this))
             , localAddress(localAddress)
             , remoteAddress(remoteAddress)
             , onDisconnect(onDisconnect) {
             SocketConnectionT::attach(fd);
             SocketReader::enable(fd);
             SocketWriter::enable(fd);
             onConnect(localAddress, remoteAddress);
             socketContext->onConnected();
         }
~SocketConnectionT()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > virtual net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::~SocketConnectionT () inline protected virtual
Definition at line 75 of file SocketConnectionT.h.
{
             socketContext->onDisconnected();
             onDisconnect();
             delete socketContext;
         }
Member Function Documentation
close()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::close () inline final virtual
Implements net::socket::stream::SocketConnection.
Definition at line 115 of file SocketConnectionT.h.
{
             //            SocketReader::disable();
             //            SocketReader::shutdown();
             SocketWriter::shutdown();
         }
References net::socket::stream::SocketWriter< SocketT >::shutdown().
getLocalAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getLocalAddress () const inline
Definition at line 91 of file SocketConnectionT.h.
{
             return localAddress;
         }
getLocalAddressAsString()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::string net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getLocalAddressAsString () const inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 95 of file SocketConnectionT.h.
{
             return localAddress.toString();
         }
getRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getRemoteAddress () const inline
Definition at line 87 of file SocketConnectionT.h.
{
             return remoteAddress;
         }
getRemoteAddressAsString()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::string net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getRemoteAddressAsString () const inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 99 of file SocketConnectionT.h.
{
             return remoteAddress.toString();
         }
getSocketContext()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketContext* net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getSocketContext () inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 121 of file SocketConnectionT.h.
{
             return socketContext;
         }
readEvent()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::readEvent () inline override private
Definition at line 138 of file SocketConnectionT.h.
{
             socketContext->receiveFromPeer();
         }
readFromPeer()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::size_t net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::readFromPeer (char * junk, std::size_t junkLen) inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 111 of file SocketConnectionT.h.
{
             return SocketReader::readFromPeer(junk, junkLen);
         }
References net::socket::stream::SocketReader< SocketT >::readFromPeer().
sendToPeer() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::sendToPeer (const char * junk, std::size_t junkLen) inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 103 of file SocketConnectionT.h.
{
             SocketWriter::sendToPeer(junk, junkLen);
         }
References net::socket::stream::SocketWriter< SocketT >::sendToPeer().
sendToPeer() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::sendToPeer (const std::string & data) inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 107 of file SocketConnectionT.h.
{
             sendToPeer(data.data(), data.size());
         }
setTimeout()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::setTimeout (int timeout) inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 82 of file SocketConnectionT.h.
{
             SocketReader::setTimeout(timeout);
             SocketWriter::setTimeout(timeout);
         }
References net::DescriptorEventReceiver::setTimeout().
switchSocketContext()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::switchSocketContext (const SocketContextFactory & socketContextFactory) inline override virtual
Implements net::socket::stream::SocketConnection.
Definition at line 125 of file SocketConnectionT.h.
{
             SocketContext* newSocketContext = socketContextFactory.create(this);
             if (newSocketContext != nullptr) {
                 socketContext->onDisconnected();
                 socketContext = newSocketContext;
                 socketContext->onConnected();
             } else {
                 VLOG(0) << "Switch socket context unsuccessull: new socket context not created";
             }
         }
References net::socket::stream::SocketContextFactory::create(), net::socket::stream::SocketContext::onConnected(), and net::socket::stream::SocketContext::onDisconnected().
unobserved()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::unobserved () inline override private
Definition at line 146 of file SocketConnectionT.h.
{
             delete this;
         }
writeEvent()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::writeEvent () inline override private
Definition at line 142 of file SocketConnectionT.h.
{
             SocketWriter::doWrite();
         }
References net::socket::stream::SocketWriter< SocketT >::doWrite().
Member Data Documentation
localAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::localAddress {} private
Definition at line 152 of file SocketConnectionT.h.
onDisconnect
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::function<void()> net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::onDisconnect private
Definition at line 155 of file SocketConnectionT.h.
remoteAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::remoteAddress {} private
Definition at line 153 of file SocketConnectionT.h.
socketContext
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketContext* net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::socketContext = nullptr private
Definition at line 150 of file SocketConnectionT.h.
The documentation for this class was generated from the following file:
net/socket/stream/SocketConnectionT.h