snode.c: http::Client< SocketClientT > Class Template Reference
http::Client< SocketClientT > Class Template Reference
#include <Client.h>
Public Types
using SocketClient = SocketClientT
using SocketConnection = typename SocketClient::SocketConnection
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
Client (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(ServerRequest &)> &onRequestBegin, const std::function< void(ServerResponse &)> &onResponseReady, const std::function< void(int, const std::string &)> &onResponseError, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void connect (const std::string &request, const SocketAddress &remoteAddress, const std::function< void(int err)> &onError) const
void get (const std::string &ipOrHostname, unsigned short port, const std::string &path, const std::function< void(int err)> &onError)
void post (const std::string &ipOrHostname, unsigned short port, const std::string &path, const std::string &body, const std::function< void(int err)> &onError)
Protected Attributes
std::function< void(SocketConnection *)> onConnect
std::function< void(ServerRequest &)> onRequestBegin
std::function< void(ServerResponse &)> onResponseReady
std::function< void(int, const std::string &)> onResponseError
std::function< void(SocketConnection *)> onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename SocketClientT>
class http::Client< SocketClientT >
Definition at line 39 of file Client.h.
Member Typedef Documentation
Socket
template<typename SocketClientT > using http::Client< SocketClientT >::Socket = typename SocketConnection::Socket
Definition at line 43 of file Client.h.
SocketAddress
template<typename SocketClientT > using http::Client< SocketClientT >::SocketAddress = typename Socket::SocketAddress
Definition at line 44 of file Client.h.
SocketClient
template<typename SocketClientT > using http::Client< SocketClientT >::SocketClient = SocketClientT
Definition at line 41 of file Client.h.
SocketConnection
template<typename SocketClientT > using http::Client< SocketClientT >::SocketConnection = typename SocketClient::SocketConnection
Definition at line 42 of file Client.h.
Constructor & Destructor Documentation
Client()
template<typename SocketClientT > http::Client< SocketClientT >::Client (const std::function< void(SocketConnection *)> & onConnect, const std::function< void(ServerRequest &)> & onRequestBegin, const std::function< void(ServerResponse &)> & onResponseReady, const std::function< void(int, const std::string &)> & onResponseError, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 46 of file Client.h.
                                                           {{}})
             : onConnect(onConnect)
             , onRequestBegin(onRequestBegin)
             , onResponseReady(onResponseReady)
             , onResponseError(onResponseError)
             , onDisconnect(onDisconnect)
             , options(options) {
         }
Member Function Documentation
connect()
template<typename SocketClientT > void http::Client< SocketClientT >::connect (const std::string & request, const SocketAddress & remoteAddress, const std::function< void(int err)> & onError) const inline
Definition at line 60 of file Client.h.
{
             errno = 0;
             SocketClient socketClient(
                 [request,
                  onRequestBegin = this->onRequestBegin,
                  onResponseReady = this->onResponseReady,
                  onResponseError = this->onResponseError](SocketConnection* socketConnection) -> void { // onConstruct
                     ClientContext* clientContext = new ClientContext(socketConnection, onResponseReady, onResponseError);
                     clientContext->setRequest(request);
                     socketConnection->template setContext<ClientContext*>(clientContext);
                     onRequestBegin(clientContext->serverRequest);
                 },
                 [](SocketConnection* socketConnection) -> void { // onDestruct
                     socketConnection->template getContext<ClientContext*>([](ClientContext* clientContext) -> void {
                         delete clientContext;
                     });
                 },
                 [onConnect = this->onConnect](SocketConnection* socketConnection) -> void { // onConnect
                     onConnect(socketConnection);
                     socketConnection->template getContext<ClientContext*>([&socketConnection](ClientContext* clientContext) -> void {
                         socketConnection->enqueue(clientContext->getRequest());
                     });
                 },
                 [onDisconnect = this->onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                     onDisconnect(socketConnection);
                 },
                 [](SocketConnection* socketConnection, const char* junk, std::size_t junkSize) -> void { // onRead
                     socketConnection->template getContext<ClientContext*>([junk, junkSize](ClientContext* clientContext) -> void {
                         clientContext->receiveResponseData(junk, junkSize);
                     });
                 },
                 [](SocketConnection* socketConnection, int errnum) -> void { // onReadError
                     if (errnum != 0) {
                         PLOG(ERROR) << "Server: " << socketConnection->getRemoteAddress().host() << " (" << errnum << ")";
                     } else {
                         VLOG(0) << "Server: EOF";
                     }
                 },
                 [](SocketConnection* socketConnection, int errnum) -> void { // onWriteError
                     if (errnum != 0) {
                         PLOG(ERROR) << "Server: " << socketConnection->getRemoteAddress().host() << " (" << errnum << ")";
                     } else {
                         VLOG(0) << "Server: EOF";
                     }
                 },
                 this->options);
             socketClient.connect(remoteAddress, onError);
         }
References http::ClientContext::getRequest(), http::Client< SocketClientT >::onConnect, http::Client< SocketClientT >::onDisconnect, http::Client< SocketClientT >::onRequestBegin, http::Client< SocketClientT >::onResponseError, http::Client< SocketClientT >::onResponseReady, http::Client< SocketClientT >::options, http::ClientContext::receiveResponseData(), http::ClientContext::serverRequest, and http::ClientContext::setRequest().
Referenced by http::Client< SocketClientT >::get(), and http::Client< SocketClientT >::post().
get()
template<typename SocketClientT > void http::Client< SocketClientT >::get (const std::string & ipOrHostname, unsigned short port, const std::string & path, const std::function< void(int err)> & onError) inline
Definition at line 113 of file Client.h.
{
             std::string request = "GET " + path + " HTTP/1.1\r\nHost: " + ipOrHostname + "\r\nConnection: close\r\n\r\n";
             SocketAddress remoteAddress(ipOrHostname, port);
             connect(request, remoteAddress, onError);
         }
References http::Client< SocketClientT >::connect().
post()
template<typename SocketClientT > void http::Client< SocketClientT >::post (const std::string & ipOrHostname, unsigned short port, const std::string & path, const std::string & body, const std::function< void(int err)> & onError) inline
Definition at line 121 of file Client.h.
{
             int contentLength = body.length();
             std::string request = "POST " + path + " HTTP/1.1\r\nHost: " + ipOrHostname +
                                   "\r\nContent-Length: " + std::to_string(contentLength) + "\r\nConnection: close\r\n\r\n" + body;
             SocketAddress remoteAddress(ipOrHostname, port);
             connect(request, remoteAddress, onError);
         }
References http::Client< SocketClientT >::connect().
Member Data Documentation
onConnect
template<typename SocketClientT > std::function<void(SocketConnection*)> http::Client< SocketClientT >::onConnect protected
Definition at line 137 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
onDisconnect
template<typename SocketClientT > std::function<void(SocketConnection*)> http::Client< SocketClientT >::onDisconnect protected
Definition at line 141 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
onRequestBegin
template<typename SocketClientT > std::function<void(ServerRequest&)> http::Client< SocketClientT >::onRequestBegin protected
Definition at line 138 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
onResponseError
template<typename SocketClientT > std::function<void(int, const std::string&)> http::Client< SocketClientT >::onResponseError protected
Definition at line 140 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
onResponseReady
template<typename SocketClientT > std::function<void(ServerResponse&)> http::Client< SocketClientT >::onResponseReady protected
Definition at line 139 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
options
template<typename SocketClientT > std::map<std::string, std::any> http::Client< SocketClientT >::options protected
Definition at line 142 of file Client.h.
Referenced by http::Client< SocketClientT >::connect().
The documentation for this class was generated from the following file:
http/Client.h