snode.c: net::pipe::Sink Class Reference
net::pipe::Sink Class Reference abstract
#include <Sink.h>
Public Member Functions
Sink ()
virtual ~Sink ()
virtual void receive (const char *junk, std::size_t junkLen)=0
virtual void eof ()=0
virtual void error (int errnum)=0
void connect (Source &source)
void disconnect (Source &source)
Protected Attributes
Source * source
Detailed Description
Definition at line 32 of file Sink.h.
Constructor & Destructor Documentation
Sink()
net::pipe::Sink::Sink ()
Definition at line 29 of file Sink.cpp.
         : source(nullptr) {
     }
~Sink()
net::pipe::Sink::~Sink () virtual
Definition at line 33 of file Sink.cpp.
                 {
         if (source != nullptr) {
             source->disconnect(*this);
         }
     }
References net::pipe::Source::disconnect(), and source.
Member Function Documentation
connect()
void net::pipe::Sink::connect (Source & source)
Definition at line 39 of file Sink.cpp.
{
         this->source = &source;
     }
References source.
Referenced by net::pipe::Source::connect().
disconnect()
void net::pipe::Sink::disconnect (Source & source)
Definition at line 43 of file Sink.cpp.
{
         if (&source == this->source) {
             this->source = nullptr;
         }
     }
References source.
Referenced by net::pipe::Source::~Source().
eof()
virtual void net::pipe::Sink::eof () pure virtual
Implemented in web::http::server::Response, and web::http::client::Request.
Referenced by net::pipe::Source::eof().
error()
virtual void net::pipe::Sink::error (int errnum) pure virtual
Implemented in web::http::server::Response, and web::http::client::Request.
Referenced by net::pipe::Source::error().
receive()
virtual void net::pipe::Sink::receive (const char * junk, std::size_t junkLen) pure virtual
Implemented in web::http::server::Response, and web::http::client::Request.
Referenced by net::pipe::Source::send().
Member Data Documentation
source
Source* net::pipe::Sink::source protected
Definition at line 45 of file Sink.h.
Referenced by connect(), disconnect(), and ~Sink().
The documentation for this class was generated from the following files:
net/pipe/Sink.h
net/pipe/Sink.cpp