snode.c: express::middleware::JsonMiddleware Class Reference
express::middleware::JsonMiddleware Class Reference
#include <JsonMiddleware.h>
Public Member Functions
JsonMiddleware (const JsonMiddleware &)=delete
JsonMiddleware & operator= (const JsonMiddleware &)=delete
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router & operator= (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::string &path, const Router &router)
Router & use (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::string &path, const Router &router)
Router & all (const Router &router)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::string &path, const Router &router)
Router & get (const Router &router)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::string &path, const Router &router)
Router & put (const Router &router)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::string &path, const Router &router)
Router & post (const Router &router)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::string &path, const Router &router)
Router & del (const Router &router)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::string &path, const Router &router)
Router & connect (const Router &router)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::string &path, const Router &router)
Router & options (const Router &router)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::string &path, const Router &router)
Router & trace (const Router &router)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::string &path, const Router &router)
Router & patch (const Router &router)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::string &path, const Router &router)
Router & head (const Router &router)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Protected Member Functions
JsonMiddleware ()
Protected Member Functions inherited from express::Router
void dispatch (express::Request &req, express::Response &res)
Static Protected Member Functions
static const class JsonMiddleware & instance ()
Friends
const class JsonMiddleware & JsonMiddleware ()
Detailed Description
Definition at line 31 of file JsonMiddleware.h.
Constructor & Destructor Documentation
JsonMiddleware() [1/2]
express::middleware::JsonMiddleware::JsonMiddleware () protected
Definition at line 33 of file JsonMiddleware.cpp.
{
         use([] MIDDLEWARE(req, res, next) {
             try {
                 // parse body string with json library
                 // store it as type json from nlohmann library
                 nlohmann::json json = nlohmann::json::parse(req.body, req.body + req.contentLength);
                 // set all the json data as attributes in the request object
                 req.setAttribute<nlohmann::json>(json);
             } catch (nlohmann::detail::parse_error& error) {
                 // silently fail if body is not json
             }
             next();
         });
     }
References MIDDLEWARE, and express::Router::use().
Referenced by instance().
JsonMiddleware() [2/2]
express::middleware::JsonMiddleware::JsonMiddleware (const JsonMiddleware &) delete
Member Function Documentation
instance()
const class JsonMiddleware & express::middleware::JsonMiddleware::instance () static protected
Definition at line 53 of file JsonMiddleware.cpp.
{
         if (jsonMiddleware == nullptr) {
             jsonMiddleware = std::shared_ptr<JsonMiddleware>(new JsonMiddleware());
         }
         return *jsonMiddleware;
     }
References express::middleware::jsonMiddleware, and JsonMiddleware().
Referenced by JsonMiddleware.
operator=()
JsonMiddleware& express::middleware::JsonMiddleware::operator= (const JsonMiddleware &) delete
Friends And Related Function Documentation
JsonMiddleware
const class JsonMiddleware& JsonMiddleware () friend
Definition at line 62 of file JsonMiddleware.cpp.
{
         return JsonMiddleware::instance();
     }
References instance().
The documentation for this class was generated from the following files:
express/middleware/JsonMiddleware.h
express/middleware/JsonMiddleware.cpp