snode.c: web::websocket::SocketContext< SubProtocolT > Class Template Reference
web::websocket::SocketContext< SubProtocolT > Class Template Reference
#include <SocketContext.h>
Public Types
enum class Role { SERVER , CLIENT }
using SubProtocol = SubProtocolT
Public Member Functions
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
Protected Member Functions
SocketContext (net::socket::stream::SocketConnection *socketConnection, SubProtocol *subProtocol, Role role)
SocketContext ()=delete
SocketContext (const SocketContext &)=delete
SocketContext & operator= (const SocketContext &)=delete
virtual ~SocketContext ()=default
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnection *socketConnection)
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
ssize_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketContext (SocketContextFactory *socketContextFactory)
void setTimeout (int timeout)
Protected Member Functions inherited from web::websocket::Receiver
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Protected Member Functions inherited from web::websocket::Transmitter
Transmitter (bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Protected Attributes
SubProtocol * subProtocol
Private Types
enum OpCode { CLOSE = 0x08 , PING = 0x09 , PONG = 0x0A }
Private Member Functions
void sendClose (const char *message, std::size_t messageLength)
void onMessageStart (int opCode) override
void onFrameReceived (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
ssize_t readFrameData (char *junk, std::size_t junkLen) override
void onConnected () override
void onDisconnected () override
void sendFrameData (uint8_t data) override
void sendFrameData (uint16_t data) override
void sendFrameData (uint32_t data) override
void sendFrameData (uint64_t data) override
void sendFrameData (const char *frame, uint64_t frameLength) override
void onReceiveFromPeer () override
void onReadError (int errnum) override
void onWriteError (int errnum) override
Private Attributes
bool closeSent = false
int opCodeReceived = 0
std::string pongCloseData
Detailed Description
template<typename SubProtocolT>
class web::websocket::SocketContext< SubProtocolT >
Definition at line 43 of file SocketContext.h.
Member Typedef Documentation
SubProtocol
template<typename SubProtocolT > using web::websocket::SocketContext< SubProtocolT >::SubProtocol = SubProtocolT
Definition at line 48 of file SocketContext.h.
Member Enumeration Documentation
OpCode
template<typename SubProtocolT > enum web::websocket::SocketContext::OpCode private
Enumerator
CLOSE
PING
PONG
Definition at line 266 of file SocketContext.h.
 { CLOSE = 0x08, PING = 0x09, PONG = 0x0A };
Role
template<typename SubProtocolT > enum web::websocket::SocketContext::Role strong
Enumerator
SERVER
CLIENT
Definition at line 50 of file SocketContext.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
SocketContext() [1/3]
template<typename SubProtocolT > web::websocket::SocketContext< SubProtocolT >::SocketContext (net::socket::stream::SocketConnection * socketConnection, SubProtocol * subProtocol, Role role) inline protected
Definition at line 53 of file SocketContext.h.
             : net::socket::stream::SocketContext(socketConnection)
             , Transmitter(role == Role::CLIENT)
             , subProtocol(subProtocol) {
         }
SocketContext() [2/3]
template<typename SubProtocolT > web::websocket::SocketContext< SubProtocolT >::SocketContext () protected delete
SocketContext() [3/3]
template<typename SubProtocolT > web::websocket::SocketContext< SubProtocolT >::SocketContext (const SocketContext< SubProtocolT > &) protected delete
~SocketContext()
template<typename SubProtocolT > virtual web::websocket::SocketContext< SubProtocolT >::~SocketContext () protected virtual default
Reimplemented from net::socket::stream::SocketContext.
Reimplemented in web::websocket::server::SocketContext, and web::websocket::client::SocketContext.
Member Function Documentation
getLocalAddressAsString()
template<typename SubProtocolT > std::string web::websocket::SocketContext< SubProtocolT >::getLocalAddressAsString () const inline
Definition at line 114 of file SocketContext.h.
{
             return net::socket::stream::SocketContext::getLocalAddressAsString();
         }
References net::socket::stream::SocketContext::getLocalAddressAsString().
getRemoteAddressAsString()
template<typename SubProtocolT > std::string web::websocket::SocketContext< SubProtocolT >::getRemoteAddressAsString () const inline
Definition at line 117 of file SocketContext.h.
{
             return net::socket::stream::SocketContext::getRemoteAddressAsString();
         }
References net::socket::stream::SocketContext::getRemoteAddressAsString().
onConnected()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onConnected () inline override private virtual
Reimplemented from net::socket::stream::SocketContext.
Definition at line 201 of file SocketContext.h.
{
             subProtocol->onConnected();
         }
References web::websocket::SocketContext< SubProtocolT >::subProtocol.
onDisconnected()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onDisconnected () inline override private virtual
Reimplemented from net::socket::stream::SocketContext.
Definition at line 204 of file SocketContext.h.
{
             subProtocol->onDisconnected();
         }
References web::websocket::SocketContext< SubProtocolT >::subProtocol.
onFrameReceived()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onFrameReceived (const char * junk, uint64_t junkLen) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 146 of file SocketContext.h.
{
             switch (opCodeReceived) {
                 case OpCode::CLOSE:
                     [[fallthrough]];
                 case OpCode::PING:
                     [[fallthrough]];
                 case OpCode::PONG:
                     pongCloseData += std::string(junk, static_cast<std::size_t>(junkLen));
                     break;
                 default:
                     std::size_t junkOffset = 0;
                     do {
                         std::size_t sendJunkLen =
                             (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                         subProtocol->onMessageData(junk + junkOffset, sendJunkLen);
                         junkOffset += sendJunkLen;
                     } while (junkLen - junkOffset > 0);
                     break;
             }
         }
References web::websocket::SocketContext< SubProtocolT >::opCodeReceived, web::websocket::SocketContext< SubProtocolT >::pongCloseData, and web::websocket::SocketContext< SubProtocolT >::subProtocol.
onMessageEnd()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onMessageEnd () inline override private virtual
Implements web::websocket::Receiver.
Definition at line 167 of file SocketContext.h.
{
             switch (opCodeReceived) {
                 case OpCode::CLOSE:
                     if (closeSent) { // active close
                         closeSent = false;
                         VLOG(0) << "Close confirmed from peer";
                     } else { // passive close
                         VLOG(0) << "Close request received - replying with close";
                         sendClose(pongCloseData.data(), pongCloseData.length());
                         pongCloseData.clear();
                     }
                     break;
                 case OpCode::PING:
                     sendPong(pongCloseData.data(), pongCloseData.length());
                     pongCloseData.clear();
                     break;
                 case OpCode::PONG:
                     subProtocol->onPongReceived();
                     break;
                 default:
                     subProtocol->onMessageEnd();
                     break;
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, web::websocket::SocketContext< SubProtocolT >::opCodeReceived, web::websocket::SocketContext< SubProtocolT >::pongCloseData, web::websocket::SocketContext< SubProtocolT >::sendClose(), web::websocket::SocketContext< SubProtocolT >::sendPong(), and web::websocket::SocketContext< SubProtocolT >::subProtocol.
onMessageError()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onMessageError (uint16_t errnum) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 191 of file SocketContext.h.
{
             subProtocol->onMessageError(errnum);
             sendClose(errnum);
         }
References web::websocket::SocketContext< SubProtocolT >::sendClose(), and web::websocket::SocketContext< SubProtocolT >::subProtocol.
onMessageStart()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onMessageStart (int opCode) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 131 of file SocketContext.h.
{
             opCodeReceived = opCode;
             switch (opCode) {
                 case OpCode::CLOSE:
                     [[fallthrough]];
                 case OpCode::PING:
                     [[fallthrough]];
                 case OpCode::PONG:
                     break;
                 default:
                     subProtocol->onMessageStart(opCode);
                     break;
             }
         }
References web::websocket::Receiver::opCode, web::websocket::SocketContext< SubProtocolT >::opCodeReceived, and web::websocket::SocketContext< SubProtocolT >::subProtocol.
onReadError()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onReadError (int errnum) inline override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 249 of file SocketContext.h.
{
             if (errnum != 0) {
                 PLOG(INFO) << "OnReadError:";
             }
         }
onReceiveFromPeer()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onReceiveFromPeer () inline override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 246 of file SocketContext.h.
{
             Receiver::receive();
         }
References web::websocket::Receiver::receive().
onWriteError()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::onWriteError (int errnum) inline override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 254 of file SocketContext.h.
{
             if (errnum != 0) {
                 PLOG(INFO) << "OnWriteError:";
             }
         }
operator=()
template<typename SubProtocolT > SocketContext& web::websocket::SocketContext< SubProtocolT >::operator= (const SocketContext< SubProtocolT > &) protected delete
readFrameData()
template<typename SubProtocolT > ssize_t web::websocket::SocketContext< SubProtocolT >::readFrameData (char * junk, std::size_t junkLen) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 196 of file SocketContext.h.
{
             return readFromPeer(junk, junkLen);
         }
References net::socket::stream::SocketContext::readFromPeer().
sendClose() [1/2]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendClose (const char * message, std::size_t messageLength) inline private
Definition at line 125 of file SocketContext.h.
{
             sendMessage(8, message, messageLength);
             close();
         }
References net::socket::stream::SocketContext::close(), and web::websocket::SocketContext< SubProtocolT >::sendMessage().
sendClose() [2/2]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) inline
Definition at line 90 of file SocketContext.h.
{
             char* closePayload = const_cast<char*>(reason);
             std::size_t closePayloadLength = reasonLength;
             if (statusCode != 0) {
                 closePayload = new char[reasonLength + 2];
                 *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
                 closePayloadLength += 2;
                 if (reasonLength > 0) {
                     memcpy(closePayload + 2, reason, reasonLength);
                 }
             }
             sendClose(closePayload, closePayloadLength);
             if (statusCode != 0) {
                 delete[] closePayload;
             }
             setTimeout(CLOSE_SOCKET_TIMEOUT);
             closeSent = true;
         }
References CLOSE_SOCKET_TIMEOUT, web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::setTimeout().
Referenced by web::websocket::SocketContext< SubProtocolT >::onMessageEnd(), and web::websocket::SocketContext< SubProtocolT >::onMessageError().
sendFrameData() [1/5]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendFrameData (const char * frame, uint64_t frameLength) inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 232 of file SocketContext.h.
{
             if (!closeSent) {
                 std::size_t frameOffset = 0;
                 do {
                     std::size_t sendJunkLen =
                         (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                     sendToPeer(frame + frameOffset, sendJunkLen);
                     frameOffset += sendJunkLen;
                 } while (frameLength - frameOffset > 0);
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [2/5]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendFrameData (uint16_t data) inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 214 of file SocketContext.h.
{
             if (!closeSent) {
                 uint16_t sendData = htobe16(data);
                 sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint16_t));
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [3/5]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendFrameData (uint32_t data) inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 220 of file SocketContext.h.
{
             if (!closeSent) {
                 uint32_t sendData = htobe32(data);
                 sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint32_t));
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [4/5]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendFrameData (uint64_t data) inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 226 of file SocketContext.h.
{
             if (!closeSent) {
                 uint64_t sendData = htobe64(data);
                 sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint64_t));
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [5/5]
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendFrameData (uint8_t data) inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 209 of file SocketContext.h.
{
             if (!closeSent) {
                 sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
             }
         }
References web::websocket::SocketContext< SubProtocolT >::closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendMessage()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) inline
Definition at line 66 of file SocketContext.h.
{
             Transmitter::sendMessage(opCode, message, messageLength);
         }
References web::websocket::Receiver::opCode, and web::websocket::Transmitter::sendMessage().
Referenced by web::websocket::SocketContext< SubProtocolT >::sendClose(), web::websocket::SocketContext< SubProtocolT >::sendPing(), and web::websocket::SocketContext< SubProtocolT >::sendPong().
sendMessageEnd()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendMessageEnd (const char * message, std::size_t messageLength) inline
Definition at line 78 of file SocketContext.h.
{
             Transmitter::sendMessageEnd(message, messageLength);
         }
References web::websocket::Transmitter::sendMessageEnd().
sendMessageFrame()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendMessageFrame (const char * message, std::size_t messageLength) inline
Definition at line 74 of file SocketContext.h.
{
             Transmitter::sendMessageFrame(message, messageLength);
         }
References web::websocket::Transmitter::sendMessageFrame().
sendMessageStart()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) inline
Definition at line 70 of file SocketContext.h.
{
             Transmitter::sendMessageStart(opCode, message, messageLength);
         }
References web::websocket::Receiver::opCode, and web::websocket::Transmitter::sendMessageStart().
sendPing()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) inline
Definition at line 82 of file SocketContext.h.
{
             sendMessage(9, reason, reasonLength);
         }
References web::websocket::SocketContext< SubProtocolT >::sendMessage().
sendPong()
template<typename SubProtocolT > void web::websocket::SocketContext< SubProtocolT >::sendPong (const char * reason = nullptr, std::size_t reasonLength = 0) inline
Definition at line 86 of file SocketContext.h.
{
             sendMessage(10, reason, reasonLength);
         }
References web::websocket::SocketContext< SubProtocolT >::sendMessage().
Referenced by web::websocket::SocketContext< SubProtocolT >::onMessageEnd().
Member Data Documentation
closeSent
template<typename SubProtocolT > bool web::websocket::SocketContext< SubProtocolT >::closeSent = false private
Definition at line 260 of file SocketContext.h.
Referenced by web::websocket::SocketContext< SubProtocolT >::onMessageEnd(), web::websocket::SocketContext< SubProtocolT >::sendClose(), and web::websocket::SocketContext< SubProtocolT >::sendFrameData().
opCodeReceived
template<typename SubProtocolT > int web::websocket::SocketContext< SubProtocolT >::opCodeReceived = 0 private
Definition at line 262 of file SocketContext.h.
Referenced by web::websocket::SocketContext< SubProtocolT >::onFrameReceived(), web::websocket::SocketContext< SubProtocolT >::onMessageEnd(), and web::websocket::SocketContext< SubProtocolT >::onMessageStart().
pongCloseData
template<typename SubProtocolT > std::string web::websocket::SocketContext< SubProtocolT >::pongCloseData private
Definition at line 264 of file SocketContext.h.
Referenced by web::websocket::SocketContext< SubProtocolT >::onFrameReceived(), and web::websocket::SocketContext< SubProtocolT >::onMessageEnd().
subProtocol
template<typename SubProtocolT > SubProtocol* web::websocket::SocketContext< SubProtocolT >::subProtocol protected
Definition at line 122 of file SocketContext.h.
Referenced by web::websocket::SocketContext< SubProtocolT >::onConnected(), web::websocket::SocketContext< SubProtocolT >::onDisconnected(), web::websocket::SocketContext< SubProtocolT >::onFrameReceived(), web::websocket::SocketContext< SubProtocolT >::onMessageEnd(), web::websocket::SocketContext< SubProtocolT >::onMessageError(), and web::websocket::SocketContext< SubProtocolT >::onMessageStart().
The documentation for this class was generated from the following file:
web/websocket/SocketContext.h