snode.c: net::socket::stream::SocketReader< SocketT > Class Template Reference
net::socket::stream::SocketReader< SocketT > Class Template Reference abstract
#include <SocketReader.h>
Public Types
using Socket = SocketT
Protected Member Functions
SocketReader (const std::function< void(int)> &onError)
virtual ~SocketReader ()=default
void shutdown ()
ssize_t readFromPeer (char *junk, std::size_t junkLen)
bool continueReadImmediately () override
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from net::EventReceiver
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
SocketReader ()=delete
virtual ssize_t read (char *junk, std::size_t junkLen)=0
virtual int getError ()=0
Private Attributes
std::function< void(int)> onError
std::vector< char > readBuffer
bool markShutdown = false
Additional Inherited Members
Public Member Functions inherited from net::EventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Detailed Description
template<typename SocketT>
class net::socket::stream::SocketReader< SocketT >
Definition at line 40 of file SocketReader.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::SocketReader< SocketT >::Socket = SocketT
Definition at line 46 of file SocketReader.h.
Constructor & Destructor Documentation
SocketReader() [1/2]
template<typename SocketT > net::socket::stream::SocketReader< SocketT >::SocketReader () private delete
SocketReader() [2/2]
template<typename SocketT > net::socket::stream::SocketReader< SocketT >::SocketReader (const std::function< void(int)> & onError) inline explicit protected
Definition at line 49 of file SocketReader.h.
             : onError(onError) {
         }
~SocketReader()
template<typename SocketT > virtual net::socket::stream::SocketReader< SocketT >::~SocketReader () protected virtual default
Member Function Documentation
continueReadImmediately()
template<typename SocketT > bool net::socket::stream::SocketReader< SocketT >::continueReadImmediately () inline override protected virtual
Reimplemented from net::ReadEventReceiver.
Reimplemented in net::socket::stream::tls::SocketReader< SocketT >.
Definition at line 103 of file SocketReader.h.
{
             return !readBuffer.empty();
         }
References net::socket::stream::SocketReader< SocketT >::readBuffer.
Referenced by net::socket::stream::legacy::SocketReader< SocketT >::continueReadImmediately(), and net::socket::stream::tls::SocketReader< SocketT >::continueReadImmediately().
getError()
template<typename SocketT > virtual int net::socket::stream::SocketReader< SocketT >::getError () private pure virtual
Implemented in net::socket::stream::tls::SocketReader< SocketT >, and net::socket::stream::legacy::SocketReader< SocketT >.
Referenced by net::socket::stream::SocketReader< SocketT >::readFromPeer().
read()
template<typename SocketT > virtual ssize_t net::socket::stream::SocketReader< SocketT >::read (char * junk, std::size_t junkLen) private pure virtual
Implemented in net::socket::stream::tls::SocketReader< SocketT >, and net::socket::stream::legacy::SocketReader< SocketT >.
Referenced by net::socket::stream::SocketReader< SocketT >::readFromPeer().
readFromPeer()
template<typename SocketT > ssize_t net::socket::stream::SocketReader< SocketT >::readFromPeer (char * junk, std::size_t junkLen) inline protected
Definition at line 67 of file SocketReader.h.
{
             if (markShutdown) {
                 Socket::shutdown(Socket::shutdown::RD);
                 markShutdown = false;
             }
             ssize_t ret = 0;
             if (readBuffer.empty()) {
                 static char data[MAX_READ_JUNKSIZE];
                 ssize_t retRead = read(data, MAX_READ_JUNKSIZE);
                 if (retRead <= 0) {
                     if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
                         ReadEventReceiver::disable();
                         onError(getError());
                         ret = -1;
                     } else {
                         ret = 0;
                     }
                 } else {
                     readBuffer.insert(readBuffer.end(), data, data + retRead);
                 }
             }
             if (!readBuffer.empty()) {
                 ret = static_cast<ssize_t>(std::min(junkLen, readBuffer.size()));
                 std::copy(readBuffer.begin(), readBuffer.begin() + ret, junk);
                 readBuffer.erase(readBuffer.begin(), readBuffer.begin() + ret);
             }
             return ret;
         }
References net::EventReceiver::disable(), net::socket::stream::SocketReader< SocketT >::getError(), net::socket::stream::SocketReader< SocketT >::markShutdown, MAX_READ_JUNKSIZE, net::socket::stream::SocketReader< SocketT >::onError, net::socket::stream::SocketReader< SocketT >::read(), and net::socket::stream::SocketReader< SocketT >::readBuffer.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::readFromPeer().
shutdown()
template<typename SocketT > void net::socket::stream::SocketReader< SocketT >::shutdown () inline protected
Definition at line 55 of file SocketReader.h.
{
             if (isSuspended() || !isEnabled()) {
                 Socket::shutdown(Socket::shutdown::RD);
             } else {
                 markShutdown = true;
             }
         }
References net::EventReceiver::isEnabled(), net::EventReceiver::isSuspended(), and net::socket::stream::SocketReader< SocketT >::markShutdown.
Member Data Documentation
markShutdown
template<typename SocketT > bool net::socket::stream::SocketReader< SocketT >::markShutdown = false private
Definition at line 114 of file SocketReader.h.
Referenced by net::socket::stream::SocketReader< SocketT >::readFromPeer(), and net::socket::stream::SocketReader< SocketT >::shutdown().
onError
template<typename SocketT > std::function<void(int)> net::socket::stream::SocketReader< SocketT >::onError private
Definition at line 110 of file SocketReader.h.
Referenced by net::socket::stream::SocketReader< SocketT >::readFromPeer().
readBuffer
template<typename SocketT > std::vector<char> net::socket::stream::SocketReader< SocketT >::readBuffer private
Definition at line 112 of file SocketReader.h.
Referenced by net::socket::stream::SocketReader< SocketT >::continueReadImmediately(), and net::socket::stream::SocketReader< SocketT >::readFromPeer().
The documentation for this class was generated from the following file:
net/socket/stream/SocketReader.h