snode.c: web::websocket::client::SocketContextUpgradeFactory Class Reference
web::websocket::client::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
void destroy (SocketContext *socketContext)
Public Member Functions inherited from web::http::client::SocketContextUpgradeFactory
virtual void prepare (Request &request)=0
void checkRefCount () final
Public Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
void prepare (Request &request, Response &response)
SocketContextUpgradeFactory< Request, Response >::Role getRole ()
void destroy ()
Static Public Member Functions
static void link ()
Static Public Member Functions inherited from web::http::client::SocketContextUpgradeFactory
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Private Member Functions
void prepare (web::http::client::Request &request) override
std::string name () override
SocketContext * create (net::socket::stream::SocketConnection *socketConnection) override
Additional Inherited Members
Public Types inherited from web::http::client::SocketContextUpgradeFactory
using Resquest = web::http::client::Request
using Reponse = web::http::client::Response
Public Types inherited from web::http::SocketContextUpgradeFactory< Request, Response >
enum class Role
using Request = Request
using Response = Response
Protected Member Functions inherited from web::http::client::SocketContextUpgradeFactory
SocketContextUpgradeFactory ()
Protected Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
SocketContextUpgradeFactory (Role role)
~SocketContextUpgradeFactory () override=default
void incRefCount ()
void decRefCount ()
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Protected Attributes inherited from web::http::SocketContextUpgradeFactory< Request, Response >
Request * request
Response * response
std::size_t refCount
Detailed Description
Definition at line 41 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
SocketContextUpgradeFactory() [2/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
create()
SocketContext * web::websocket::client::SocketContextUpgradeFactory::create (net::socket::stream::SocketConnection * socketConnection) override private virtual
Implements net::socket::stream::SocketContextFactory.
Definition at line 58 of file SocketContextUpgradeFactory.cpp.
{
         std::string subProtocolName = response->header("sec-websocket-protocol");
         SocketContext* socketContext = nullptr;
         web::websocket::client::SubProtocolFactory* subProtocolFactory = SubProtocolFactorySelector::instance()->select(subProtocolName);
         if (subProtocolFactory != nullptr) {
             SubProtocol* subProtocol = subProtocolFactory->createSubProtocol();
             if (subProtocol != nullptr) {
                 socketContext = new SocketContext(socketConnection, subProtocol);
                 if (socketContext != nullptr) {
                     incRefCount();
                     socketContext->setSocketContextUpgradeFactory(this);
                     subProtocol->setSocketContext(socketContext);
                     subProtocol->setSubProtocolFactory(subProtocolFactory);
                 } else {
                     subProtocolFactory->deleteSubProtocol(subProtocol);
                 }
             }
         }
         if (socketContext == nullptr) {
             checkRefCount();
         }
         return socketContext;
     }
References web::http::client::SocketContextUpgradeFactory::checkRefCount(), web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol(), web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::http::SocketContextUpgradeFactory< Request, Response >::incRefCount(), web::websocket::client::SubProtocolFactorySelector::instance(), web::http::SocketContextUpgradeFactory< Request, Response >::response, web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSocketContext(), web::websocket::client::SocketContext::setSocketContextUpgradeFactory(), and web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSubProtocolFactory().
destroy()
void web::websocket::client::SocketContextUpgradeFactory::destroy (SocketContext * socketContext)
Definition at line 42 of file SocketContextUpgradeFactory.cpp.
{
         SubProtocol* subProtocol = socketContext->getSubProtocol();
         SubProtocolFactory* subProtocolFactory = subProtocol->getSubProtocolFactory();
         if (subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
             SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
         }
         decRefCount();
     }
References web::http::SocketContextUpgradeFactory< Request, Response >::decRefCount(), web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::SocketContext< SubProtocolT >::getSubProtocol(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSubProtocolFactory(), web::websocket::client::SubProtocolFactorySelector::instance(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Referenced by web::websocket::client::SocketContext::~SocketContext().
link()
void web::websocket::client::SocketContextUpgradeFactory::link () static
Definition at line 90 of file SocketContextUpgradeFactory.cpp.
{
         static bool linked = false;
         if (!linked) {
             web::http::client::SocketContextUpgradeFactory::link("websocket", websocketClientContextUpgradeFactory);
             linked = true;
         }
     }
References web::http::client::SocketContextUpgradeFactory::link(), and web::websocket::client::websocketClientContextUpgradeFactory().
name()
std::string web::websocket::client::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< Request, Response >.
Definition at line 54 of file SocketContextUpgradeFactory.cpp.
{
         return "websocket";
     }
operator=()
SocketContextUpgradeFactory& web::websocket::client::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
prepare()
void web::websocket::client::SocketContextUpgradeFactory::prepare (web::http::client::Request & request) override private
Definition at line 35 of file SocketContextUpgradeFactory.cpp.
{
         unsigned char ebytes[16];
         getentropy(ebytes, 16);
         request.set("Sec-WebSocket-Key", base64::base64_encode(ebytes, 16));
     }
References base64::base64_encode(), and web::http::SocketContextUpgradeFactory< Request, Response >::request.
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgradeFactory.h
web/websocket/client/SocketContextUpgradeFactory.cpp