snode.c: net::socket::InetAddress Class Reference
net::socket::InetAddress Class Reference
#include <InetAddress.h>
Classes
struct addr
Public Member Functions
InetAddress ()
InetAddress (const InetAddress &ina)
InetAddress (const std::string &ipOrHostname)
InetAddress (const std::string &ipOrHostname, uint16_t port)
InetAddress (unsigned short port)
InetAddress (const struct sockaddr_in &addr)
unsigned short port () const
std::string host () const
std::string ip () const
std::string serv () const
~InetAddress ()=default
InetAddress & operator= (const InetAddress &ina)
const struct sockaddr_in & getSockAddr () const
Detailed Description
Definition at line 48 of file InetAddress.h.
Constructor & Destructor Documentation
InetAddress() [1/6]
net::socket::InetAddress::InetAddress ()
Definition at line 33 of file InetAddress.cpp.
{
         addr.sin_family = AF_INET;
         addr.sin_port = htons(0);
         addr.sin_addr.s_addr = htonl(INADDR_ANY);
     }
InetAddress() [2/6]
net::socket::InetAddress::InetAddress (const InetAddress & ina)
Definition at line 73 of file InetAddress.cpp.
{
         memcpy(&addr, &ina.addr, sizeof(struct sockaddr_in));
     }
InetAddress() [3/6]
net::socket::InetAddress::InetAddress (const std::string & ipOrHostname) explicit
Definition at line 51 of file InetAddress.cpp.
{
         struct hostent* he = gethostbyname(ipOrHostname.c_str());
         if (he == nullptr) {
             throw bad_hostname(ipOrHostname);
         }
         addr.sin_family = AF_INET;
         addr.sin_port = htons(0);
         memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
     }
InetAddress() [4/6]
net::socket::InetAddress::InetAddress (const std::string & ipOrHostname, uint16_t port) explicit
Definition at line 39 of file InetAddress.cpp.
{
         struct hostent* he = gethostbyname(ipOrHostname.c_str());
         if (he == nullptr) {
             throw bad_hostname(ipOrHostname);
         }
         addr.sin_family = AF_INET;
         addr.sin_port = htons(port);
         memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
     }
References port().
InetAddress() [5/6]
net::socket::InetAddress::InetAddress (unsigned short port) explicit
Definition at line 63 of file InetAddress.cpp.
{
         addr.sin_family = AF_INET;
         addr.sin_port = htons(port);
         addr.sin_addr.s_addr = htonl(INADDR_ANY);
     }
References port().
InetAddress() [6/6]
net::socket::InetAddress::InetAddress (const struct sockaddr_in & addr) explicit
Definition at line 69 of file InetAddress.cpp.
{
         memcpy(&this->addr, &addr, sizeof(struct sockaddr_in));
     }
~InetAddress()
net::socket::InetAddress::~InetAddress () default
Member Function Documentation
getSockAddr()
const struct sockaddr_in & net::socket::InetAddress::getSockAddr () const
Definition at line 110 of file InetAddress.cpp.
{
         return addr;
     }
Referenced by net::socket::tcp::Socket::bind(), and net::socket::tcp::SocketClient< legacy::SocketConnection >::connect().
host()
std::string net::socket::InetAddress::host () const
Definition at line 89 of file InetAddress.cpp.
{
         char host[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&addr), sizeof(addr), host, 256, NULL, 0, 0);
         return std::string(host);
     }
ip()
std::string net::socket::InetAddress::ip () const
Definition at line 96 of file InetAddress.cpp.
{
         char ip[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&addr), sizeof(addr), ip, 256, NULL, 0, NI_NUMERICHOST);
         return std::string(ip);
     }
operator=()
InetAddress & net::socket::InetAddress::operator= (const InetAddress & ina)
Definition at line 77 of file InetAddress.cpp.
{
         if (this != &ina) {
             memcpy(&addr, &ina.addr, sizeof(struct sockaddr_in));
         }
         return *this;
     }
port()
unsigned short net::socket::InetAddress::port () const
Definition at line 85 of file InetAddress.cpp.
{
         return (ntohs(addr.sin_port));
     }
Referenced by InetAddress().
serv()
std::string net::socket::InetAddress::serv () const
Definition at line 103 of file InetAddress.cpp.
{
         char serv[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&addr), sizeof(addr), NULL, 0, serv, 256, 0);
         return std::string(serv);
     }
The documentation for this class was generated from the following files:
net/socket/InetAddress.h
net/socket/InetAddress.cpp