snode.c: web::http::client::ClientContextBase Class Reference
web::http::client::ClientContextBase Class Reference abstract
#include <ClientContext.h>
Public Member Functions
virtual ~ClientContextBase ()=default
virtual void sendRequestData (const char *buf, std::size_t len)=0
virtual Request & getRequest ()=0
virtual void terminateConnection ()=0
virtual void requestCompleted ()=0
Public Member Functions inherited from net::socket::stream::SocketProtocol
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void close ()
void switchSocketProtocol (SocketProtocol *socketProtocol)
void setTimeout (int timeout)
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketProtocol
SocketProtocol ()=default
virtual ~SocketProtocol ()=default
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
Detailed Description
Definition at line 42 of file ClientContext.h.
Constructor & Destructor Documentation
~ClientContextBase()
virtual web::http::client::ClientContextBase::~ClientContextBase () virtual default
Member Function Documentation
getRequest()
virtual Request& web::http::client::ClientContextBase::getRequest () pure virtual
Implemented in web::http::client::ClientContext< RequestT, ResponseT >.
requestCompleted()
virtual void web::http::client::ClientContextBase::requestCompleted () pure virtual
Implemented in web::http::client::ClientContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue().
sendRequestData()
virtual void web::http::client::ClientContextBase::sendRequestData (const char * buf, std::size_t len) pure virtual
Implemented in web::http::client::ClientContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue().
terminateConnection()
virtual void web::http::client::ClientContextBase::terminateConnection () pure virtual
Implemented in web::http::client::ClientContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue(), and web::http::client::Request::error().
The documentation for this class was generated from the following file:
web/http/client/ClientContext.h