snode.c: web::ws::SubProtocolInterface Class Reference
web::ws::SubProtocolInterface Class Reference abstract
#include <SubProtocolInterface.h>
Public Member Functions
virtual ~SubProtocolInterface ()=default
virtual std::string name ()=0
virtual web::ws::SubProtocol::Role role ()=0
virtual web::ws::SubProtocol * create (web::http::server::Request &, web::http::server::Response &)=0
virtual void destroy (web::ws::SubProtocol *)=0
Detailed Description
Definition at line 38 of file SubProtocolInterface.h.
Constructor & Destructor Documentation
~SubProtocolInterface()
virtual web::ws::SubProtocolInterface::~SubProtocolInterface () virtual default
Member Function Documentation
create()
virtual web::ws::SubProtocol* web::ws::SubProtocolInterface::create (web::http::server::Request & , web::http::server::Response &) pure virtual
Referenced by web::ws::server::SocketContext::create().
destroy()
virtual void web::ws::SubProtocolInterface::destroy (web::ws::SubProtocol *) pure virtual
Implemented in web::ws::subprotocol::echo::server::EchoInterface.
name()
virtual std::string web::ws::SubProtocolInterface::name () pure virtual
Implemented in web::ws::subprotocol::echo::server::EchoInterface.
Referenced by web::ws::SubProtocolSelector::registerSubProtocol().
role()
virtual web::ws::SubProtocol::Role web::ws::SubProtocolInterface::role () pure virtual
Implemented in web::ws::subprotocol::echo::server::EchoInterface.
Referenced by web::ws::SubProtocolSelector::registerSubProtocol().
The documentation for this class was generated from the following file:
web/ws/SubProtocolInterface.h