snode.c: web::http::Parser Class Reference
web::http::Parser Class Reference abstract
#include <Parser.h>
Public Member Functions
Parser (net::socket::stream::SocketContext *socketContext, const enum HTTPCompliance &compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()=default
void parse ()
Protected Types
enum class HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum class ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Protected Member Functions
virtual void reset ()
virtual void begin ()=0
virtual enum ParserState parseStartLine (const std::string &line)=0
virtual enum ParserState parseHeader ()=0
virtual enum ParserState parseContent (char *content, std::size_t size)=0
virtual enum ParserState parsingError (int code, const std::string &reason)=0
Protected Attributes
enum web::http::Parser::HTTPCompliance hTTPCompliance
enum web::http::Parser::ParserState parserState = ParserState::BEGIN
char * content = nullptr
std::size_t contentLength = 0
std::map< std::string, std::string > headers
Static Protected Attributes
static std::regex httpVersionRegex
Private Member Functions
std::size_t readStartLine ()
std::size_t readHeaderLine ()
void splitHeaderLine (const std::string &line)
std::size_t readContent ()
Private Attributes
net::socket::stream::SocketContext * socketContext = nullptr
bool EOL {false}
std::string line
std::size_t contentRead = 0
char contentJunk [16384] {}
Friends
enum HTTPCompliance operator| (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
enum HTTPCompliance operator& (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
Detailed Description
Definition at line 43 of file Parser.h.
Member Enumeration Documentation
HTTPCompliance
enum web::http::Parser::HTTPCompliance : unsigned short strong protected
Enumerator
RFC1945
RFC2616
RFC7230
RFC7231
RFC7232
RFC7233
RFC7234
RFC7235
RFC7540
RFC7541
Definition at line 45 of file Parser.h.
                                    : unsigned short {
             RFC1945 = 0x01 << 0, // HTTP 1.0
             RFC2616 = 0x01 << 1, // HTTP 1.1
             RFC7230 = 0x01 << 2, // Message Syntax and Routing
             RFC7231 = 0x01 << 3, // Semantics and Content
             RFC7232 = 0x01 << 4, // Conditional Requests
             RFC7233 = 0x01 << 5, // Range Requests
             RFC7234 = 0x01 << 6, // Caching
             RFC7235 = 0x01 << 7, // Authentication
             RFC7540 = 0x01 << 8, // HTTP 2.0
             RFC7541 = 0x01 << 9  // Header Compression
         } hTTPCompliance;
ParserState
enum web::http::Parser::ParserState strong protected
Enumerator
BEGIN
FIRSTLINE
HEADER
BODY
ERROR
Definition at line 68 of file Parser.h.
 { BEGIN, FIRSTLINE, HEADER, BODY, ERROR } parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
Parser()
web::http::Parser::Parser (net::socket::stream::SocketContext * socketContext, const enum HTTPCompliance & compliance = HTTPCompliance::RFC2616 | HTTPCompliance::RFC7230) explicit
Definition at line 37 of file Parser.cpp.
         : hTTPCompliance(compliance)
         , socketContext(socketContext) {
     }
~Parser()
virtual web::http::Parser::~Parser () virtual default
Member Function Documentation
begin()
virtual void web::http::Parser::begin () protected pure virtual
Implemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
Referenced by parse().
parse()
void web::http::Parser::parse ()
Definition at line 52 of file Parser.cpp.
{
         std::size_t consumed = 0;
         bool parsingError = false;
         do {
             switch (parserState) {
                 case ParserState::BEGIN:
                     parserState = ParserState::FIRSTLINE;
                     begin();
                     [[fallthrough]];
                 case ParserState::FIRSTLINE:
                     consumed = readStartLine();
                     break;
                 case ParserState::HEADER:
                     consumed = readHeaderLine();
                     break;
                 case ParserState::BODY:
                     consumed = readContent();
                     break;
                 case ParserState::ERROR:
                     parsingError = true;
                     reset();
                     break;
             };
         } while (consumed > 0 && !parsingError && parserState != ParserState::BEGIN);
     }
References BEGIN, begin(), BODY, ERROR, FIRSTLINE, HEADER, parserState, parsingError(), readContent(), readHeaderLine(), readStartLine(), and reset().
parseContent()
virtual enum ParserState web::http::Parser::parseContent (char * content, std::size_t size) protected pure virtual
Implemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
parseHeader()
virtual enum ParserState web::http::Parser::parseHeader () protected pure virtual
Implemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
Referenced by readHeaderLine().
parseStartLine()
virtual enum ParserState web::http::Parser::parseStartLine (const std::string & line) protected pure virtual
Implemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
Referenced by readStartLine().
parsingError()
virtual enum ParserState web::http::Parser::parsingError (int code, const std::string & reason) protected pure virtual
Implemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
Referenced by parse(), readHeaderLine(), and splitHeaderLine().
readContent()
std::size_t web::http::Parser::readContent () private
Definition at line 184 of file Parser.cpp.
{
         if (contentRead == 0) {
             content = new char[contentLength];
         }
         std::size_t contentJunkLen =
             (contentLength - contentRead < MAX_CONTENT_JUNK_LEN) ? contentLength - contentRead : MAX_CONTENT_JUNK_LEN;
         contentJunkLen = socketContext->readFromPeer(contentJunk, contentJunkLen);
         if (contentJunkLen > 0) {
             if (contentRead + contentJunkLen <= contentLength) {
                 memcpy(content + contentRead, contentJunk, contentJunkLen); // NOLINT(clang-analyzer-core.NonNullParamChecker)
                 contentRead += contentJunkLen;
                 if (contentRead == contentLength) {
                     parserState = parseContent(content, contentLength);
                     delete[] content;
                     content = nullptr;
                     contentRead = 0;
                 }
             } else {
                 parserState = parsingError(400, "Content to long");
                 if (content != nullptr) {
                     delete[] content;
                     content = nullptr;
                 }
             }
         }
         return contentJunkLen;
     }
Referenced by parse().
readHeaderLine()
std::size_t web::http::Parser::readHeaderLine () private
Definition at line 103 of file Parser.cpp.
{
         std::size_t consumed = 0;
         std::size_t ret = 0;
         do {
             char ch = 0;
             ret = socketContext->readFromPeer(&ch, 1);
             if (ret > 0) {
                 if (ch == '\r' || ch == '\n') {
                     consumed++;
                     if (ch == '\n') {
                         if (EOL) {
                             splitHeaderLine(line);
                             line.clear();
                             if (parserState != ParserState::ERROR) {
                                 parserState = parseHeader();
                             }
                             EOL = false;
                         } else {
                             if (line.empty()) {
                                 if (parserState != ParserState::ERROR) {
                                     parserState = parseHeader();
                                 }
                             } else {
                                 EOL = true;
                             }
                         }
                     }
                 } else if (EOL) {
                     if (std::isblank(ch)) {
                         if ((hTTPCompliance & HTTPCompliance::RFC7230) == HTTPCompliance::RFC7230) {
                             parserState = parsingError(400, "Header Folding");
                         } else {
                             line += ch;
                             consumed++;
                         }
                     } else {
                         splitHeaderLine(line);
                         line.clear();
                         line += ch;
                         consumed++;
                     }
                     EOL = false;
                 } else {
                     line += ch;
                     consumed++;
                 }
             }
         } while (ret > 0 && parserState == ParserState::HEADER);
         return consumed;
     }
References EOL, ERROR, HEADER, hTTPCompliance, line, parseHeader(), parserState, parsingError(), net::socket::stream::SocketContext::readFromPeer(), RFC7230, socketContext, and splitHeaderLine().
Referenced by parse().
readStartLine()
std::size_t web::http::Parser::readStartLine () private
Definition at line 79 of file Parser.cpp.
{
         std::size_t consumed = 0;
         std::size_t ret = 0;
         do {
             char ch = 0;
             ret = socketContext->readFromPeer(&ch, 1);
             if (ret > 0) {
                 consumed += ret;
                 if (ch == '\r' || ch == '\n') {
                     if (ch == '\n') {
                         parserState = parseStartLine(line);
                         line.clear();
                     }
                 } else {
                     line += ch;
                 }
             }
         } while (ret > 0 && parserState == ParserState::FIRSTLINE);
         return consumed;
     }
References FIRSTLINE, line, parserState, parseStartLine(), net::socket::stream::SocketContext::readFromPeer(), and socketContext.
Referenced by parse().
reset()
void web::http::Parser::reset () protected virtual
Reimplemented in web::http::server::RequestParser, and web::http::client::ResponseParser.
Definition at line 42 of file Parser.cpp.
{
         parserState = ParserState::BEGIN;
         headers.clear();
         contentLength = 0;
         if (content != nullptr) {
             delete[] content;
             content = nullptr;
         }
     }
References BEGIN, content, contentLength, headers, and parserState.
Referenced by parse(), web::http::client::ResponseParser::reset(), and web::http::server::RequestParser::reset().
splitHeaderLine()
void web::http::Parser::splitHeaderLine (const std::string & line) private
Definition at line 157 of file Parser.cpp.
{
         if (!line.empty()) {
             std::string field;
             std::string value;
             std::tie(field, value) = httputils::str_split(line, ':');
             if (field.empty()) {
                 parserState = parsingError(400, "Header-field empty");
             } else if (std::isblank(field.back()) || std::isblank(field.front())) {
                 parserState = parsingError(400, "White space before or after header-field");
             } else if (value.empty()) {
                 parserState = parsingError(400, "Header-value of field \"" + field + "\" empty");
             } else {
                 httputils::to_lower(field);
                 httputils::str_trimm(value);
                 if (headers.find(field) == headers.end()) {
                     headers.insert({field, value});
                 } else {
                     headers[field] += "," + value;
                 }
             }
         } else {
             parserState = parsingError(400, "Header-line empty");
         }
     }
References headers, line, parserState, parsingError(), httputils::str_split(), httputils::str_trimm(), and httputils::to_lower().
Referenced by readHeaderLine().
Friends And Related Function Documentation
operator&
enum HTTPCompliance operator& (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 184 of file Parser.cpp.
{
         return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) & static_cast<unsigned short>(c2));
     }
operator|
enum HTTPCompliance operator| (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 184 of file Parser.cpp.
{
         return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) | static_cast<unsigned short>(c2));
     }
Member Data Documentation
content
char* web::http::Parser::content = nullptr protected
Definition at line 80 of file Parser.h.
Referenced by reset().
contentJunk
char web::http::Parser::contentJunk[16384] {} private
Definition at line 98 of file Parser.h.
contentLength
std::size_t web::http::Parser::contentLength = 0 protected
Definition at line 81 of file Parser.h.
Referenced by reset().
contentRead
std::size_t web::http::Parser::contentRead = 0 private
Definition at line 97 of file Parser.h.
EOL
bool web::http::Parser::EOL {false} private
Definition at line 93 of file Parser.h.
Referenced by readHeaderLine().
headers
std::map<std::string, std::string> web::http::Parser::headers protected
Definition at line 82 of file Parser.h.
Referenced by reset(), and splitHeaderLine().
hTTPCompliance
enum web::http::Parser::HTTPCompliance web::http::Parser::hTTPCompliance protected
Referenced by readHeaderLine().
httpVersionRegex
std::regex web::http::Parser::httpVersionRegex static protected
Definition at line 69 of file Parser.h.
line
std::string web::http::Parser::line private
Definition at line 96 of file Parser.h.
Referenced by readHeaderLine(), readStartLine(), and splitHeaderLine().
parserState
enum web::http::Parser::ParserState web::http::Parser::parserState = ParserState::BEGIN protected
Referenced by parse(), readHeaderLine(), readStartLine(), reset(), and splitHeaderLine().
socketContext
net::socket::stream::SocketContext* web::http::Parser::socketContext = nullptr private
Definition at line 85 of file Parser.h.
Referenced by readHeaderLine(), and readStartLine().
The documentation for this class was generated from the following files:
web/http/Parser.h
web/http/Parser.cpp