snode.c: web::websocket::server::SocketContextUpgradeFactory Class Reference
web::websocket::server::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
void deleteSubProtocol (SubProtocol *subProtocol)
Public Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
virtual void prepare (Request &request, Response &response)
SocketContextUpgradeFactory< Request, Response >::Role getRole ()
void destroy ()
Static Public Member Functions
static void link ()
Private Member Functions
std::string name () override
SocketContext * create (net::socket::stream::SocketConnection *socketConnection) override
Private Attributes
std::size_t refCount = 0
Additional Inherited Members
Public Types inherited from web::http::server::SocketContextUpgradeFactory
using Resquest = web::http::server::Request
using Reponse = web::http::server::Response
Public Types inherited from web::http::SocketContextUpgradeFactory< Request, Response >
enum class Role
using Request = Request
using Response = Response
Protected Member Functions inherited from web::http::server::SocketContextUpgradeFactory
SocketContextUpgradeFactory ()
Protected Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
SocketContextUpgradeFactory (Role role)
~SocketContextUpgradeFactory () override=default
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Protected Attributes inherited from web::http::SocketContextUpgradeFactory< Request, Response >
Request * request
Response * response
Role role
Detailed Description
Definition at line 38 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
SocketContextUpgradeFactory() [2/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
create()
SocketContext * web::websocket::server::SocketContextUpgradeFactory::create (net::socket::stream::SocketConnection * socketConnection) override private virtual
Implements net::socket::stream::SocketContextFactory.
Definition at line 51 of file SocketContextUpgradeFactory.cpp.
{
         std::string subProtocolName = request->header("sec-websocket-protocol");
         SocketContext* socketContext = nullptr;
         web::websocket::server::SubProtocolFactory* subProtocolFactory = SubProtocolFactorySelector::instance()->select(subProtocolName);
         if (subProtocolFactory != nullptr) {
             SubProtocol* subProtocol = subProtocolFactory->createSubProtocol();
             if (subProtocol != nullptr) {
                 socketContext = new SocketContext(socketConnection, subProtocol);
                 if (socketContext != nullptr) {
                     refCount++;
                     socketContext->setSocketContextUpgradeFactory(this);
                     subProtocol->setSocketContext(socketContext);
                     subProtocol->setSubProtocolFactory(subProtocolFactory);
                     response->set("Upgrade", "websocket");
                     response->set("Connection", "Upgrade");
                     response->set("Sec-WebSocket-Protocol", subProtocolName);
                     response->set("Sec-WebSocket-Accept", base64::serverWebSocketKey(request->header("sec-websocket-key")));
                     response->status(101).end(); // Switch Protocol
                 } else {
                     subProtocolFactory->deleteSubProtocol(subProtocol);
                     response->set("Connection", "close");
                     response->status(500).end(); // Internal Server Error
                 }
             } else {
                 response->set("Connection", "close");
                 response->status(404).end(); // Not Found
             }
         } else {
             response->set("Connection", "close");
             response->status(404).end(); // Not Found
         }
         if (refCount == 0) {
             web::http::server::SocketContextUpgradeFactorySelector::instance()->unload(this);
         }
         return socketContext;
     }
References web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol(), web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::http::server::SocketContextUpgradeFactorySelector::instance(), web::websocket::server::SubProtocolFactorySelector::instance(), refCount, web::http::SocketContextUpgradeFactory< Request, Response >::request, web::http::SocketContextUpgradeFactory< Request, Response >::response, web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), base64::serverWebSocketKey(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSocketContext(), web::websocket::server::SocketContext::setSocketContextUpgradeFactory(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSubProtocolFactory(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
deleteSubProtocol()
void web::websocket::server::SocketContextUpgradeFactory::deleteSubProtocol (SubProtocol * subProtocol)
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
         SubProtocolFactory* subProtocolFactory = subProtocol->getSubProtocolFactory();
         if (subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
             SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
         }
         --refCount;
         if (refCount == 0) {
             web::http::server::SocketContextUpgradeFactorySelector::instance()->unload(this);
         }
     }
References web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSubProtocolFactory(), web::http::server::SocketContextUpgradeFactorySelector::instance(), web::websocket::server::SubProtocolFactorySelector::instance(), refCount, web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Referenced by web::websocket::server::SocketContext::~SocketContext().
link()
void web::websocket::server::SocketContextUpgradeFactory::link () static
Definition at line 98 of file SocketContextUpgradeFactory.cpp.
{
         static bool linked = false;
         if (!linked) {
             web::http::server::SocketContextUpgradeFactorySelector::instance()->link("websocket", websocketServerContextUpgradeFactory);
             linked = true;
         }
     }
References web::http::server::SocketContextUpgradeFactorySelector::instance(), web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link(), and web::websocket::server::websocketServerContextUpgradeFactory().
name()
std::string web::websocket::server::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< Request, Response >.
Definition at line 47 of file SocketContextUpgradeFactory.cpp.
{
         return "websocket";
     }
operator=()
SocketContextUpgradeFactory& web::websocket::server::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
Member Data Documentation
refCount
std::size_t web::websocket::server::SocketContextUpgradeFactory::refCount = 0 private
Definition at line 55 of file SocketContextUpgradeFactory.h.
Referenced by create(), and deleteSubProtocol().
The documentation for this class was generated from the following files:
web/websocket/server/SocketContextUpgradeFactory.h
web/websocket/server/SocketContextUpgradeFactory.cpp