snode.c: express::WebAppT< ServerT > Class Template Reference
express::WebAppT< ServerT > Class Template Reference
#include <WebAppT.h>
Public Types
using Server = ServerT
using SocketServer = typename Server::SocketServer
using SocketConnection = typename SocketServer::SocketConnection
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
WebAppT (const std::map< std::string, std::any > &options={{}})
WebAppT (const Router &router, const std::map< std::string, std::any > &options={{}})
void listen (uint16_t port, const std::function< void(int err)> &onError=nullptr) override
void listen (const std::string &host, uint16_t port, const std::function< void(int err)> &onError=nullptr) override
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router & operator= (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::string &path, const Router &router)
Router & use (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & use (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::string &path, const Router &router)
Router & all (const Router &router)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & all (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::string &path, const Router &router)
Router & get (const Router &router)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & get (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::string &path, const Router &router)
Router & put (const Router &router)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & put (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::string &path, const Router &router)
Router & post (const Router &router)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & post (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::string &path, const Router &router)
Router & del (const Router &router)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & del (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::string &path, const Router &router)
Router & connect (const Router &router)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & connect (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::string &path, const Router &router)
Router & options (const Router &router)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & options (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::string &path, const Router &router)
Router & trace (const Router &router)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & trace (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::string &path, const Router &router)
Router & patch (const Router &router)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & patch (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::string &path, const Router &router)
Router & head (const Router &router)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Router & head (const std::function< void(Request &req, Response &res, express::State &state)> &lambda)
Protected Attributes
Server server
std::function< void(const SocketAddress &, const SocketAddress &)> _onConnect = nullptr
std::function< void(SocketConnection *)> _onConnected = nullptr
std::function< void(SocketConnection *)> _onDisconnect = nullptr
Protected Attributes inherited from express::Router
std::shared_ptr< RouterDispatcher > routerDispatcher
Additional Inherited Members
Static Public Member Functions inherited from express::WebApp
static void init (int argc, char *argv[])
static int start ()
static void stop ()
Protected Member Functions inherited from express::WebApp
WebApp (const Router &router)
Detailed Description
template<typename ServerT>
class express::WebAppT< ServerT >
Definition at line 39 of file WebAppT.h.
Member Typedef Documentation
Server
template<typename ServerT > using express::WebAppT< ServerT >::Server = ServerT
Definition at line 41 of file WebAppT.h.
Socket
template<typename ServerT > using express::WebAppT< ServerT >::Socket = typename SocketConnection::Socket
Definition at line 44 of file WebAppT.h.
SocketAddress
template<typename ServerT > using express::WebAppT< ServerT >::SocketAddress = typename Socket::SocketAddress
Definition at line 45 of file WebAppT.h.
SocketConnection
template<typename ServerT > using express::WebAppT< ServerT >::SocketConnection = typename SocketServer::SocketConnection
Definition at line 43 of file WebAppT.h.
SocketServer
template<typename ServerT > using express::WebAppT< ServerT >::SocketServer = typename Server::SocketServer
Definition at line 42 of file WebAppT.h.
Constructor & Destructor Documentation
WebAppT() [1/2]
template<typename ServerT > express::WebAppT< ServerT >::WebAppT (const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 47 of file WebAppT.h.
                                                            {{}})
             : WebAppT(Router(), options) {
         }
WebAppT() [2/2]
template<typename ServerT > express::WebAppT< ServerT >::WebAppT (const Router & router, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 51 of file WebAppT.h.
                                                                                  {{}})
             : WebApp(router)
             , server(
                   [&onConnect = this->_onConnect](const SocketAddress& localAddress,
                                                   const SocketAddress& remoteAddress) -> void { // onConnect
                       if (onConnect) {
                           onConnect(localAddress, remoteAddress);
                       }
                   },
                   [&onConnected = this->_onConnected](SocketConnection* socketConnection) -> void { // onConnected
                       if (onConnected) {
                           onConnected(socketConnection);
                       }
                   },
                   [routerDispatcher = this->routerDispatcher](express::Request& req,
                                                               express::Response& res) -> void { // onRequestReady
                       req.extend();
                       routerDispatcher->dispatch(req, res);
                   },
                   [this](SocketConnection* socketConnection) -> void { // onDisconnect
                       if (_onDisconnect != nullptr) {
                           _onDisconnect(socketConnection);
                       }
                   },
                   options) {
         }
Member Function Documentation
listen() [1/2]
template<typename ServerT > void express::WebAppT< ServerT >::listen (const std::string & host, uint16_t port, const std::function< void(int err)> & onError = nullptr) inline override virtual
Implements express::WebApp.
Definition at line 82 of file WebAppT.h.
{
             server.listen(host, port, onError);
         }
References express::WebAppT< ServerT >::server.
listen() [2/2]
template<typename ServerT > void express::WebAppT< ServerT >::listen (uint16_t port, const std::function< void(int err)> & onError = nullptr) inline override virtual
Implements express::WebApp.
Definition at line 78 of file WebAppT.h.
{
             server.listen(port, onError);
         }
References express::WebAppT< ServerT >::server.
onConnect()
template<typename ServerT > void express::WebAppT< ServerT >::onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect) inline
Definition at line 86 of file WebAppT.h.
{
             _onConnect = onConnect;
         }
References express::WebAppT< ServerT >::_onConnect.
onConnected()
template<typename ServerT > void express::WebAppT< ServerT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 90 of file WebAppT.h.
{
             _onConnected = onConnected;
         }
References express::WebAppT< ServerT >::_onConnected.
onDisconnect()
template<typename ServerT > void express::WebAppT< ServerT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 94 of file WebAppT.h.
{
             _onDisconnect = onDisconnect;
         }
References express::WebAppT< ServerT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename ServerT > std::function<void(const SocketAddress&, const SocketAddress&)> express::WebAppT< ServerT >::_onConnect = nullptr protected
Definition at line 101 of file WebAppT.h.
Referenced by express::WebAppT< ServerT >::onConnect().
_onConnected
template<typename ServerT > std::function<void(SocketConnection*)> express::WebAppT< ServerT >::_onConnected = nullptr protected
Definition at line 102 of file WebAppT.h.
Referenced by express::WebAppT< ServerT >::onConnected().
_onDisconnect
template<typename ServerT > std::function<void(SocketConnection*)> express::WebAppT< ServerT >::_onDisconnect = nullptr protected
Definition at line 103 of file WebAppT.h.
Referenced by express::WebAppT< ServerT >::onDisconnect().
server
template<typename ServerT > Server express::WebAppT< ServerT >::server protected
Definition at line 99 of file WebAppT.h.
Referenced by express::WebAppT< ServerT >::listen().
The documentation for this class was generated from the following file:
express/WebAppT.h