snode.c: http::ClientContext Class Reference
http::ClientContext Class Reference
#include <ClientContext.h>
Public Types
using SocketConnection = net::socket::stream::SocketConnectionBase
Public Member Functions
ClientContext (SocketConnection *socketConnection, const std::function< void(ServerResponse &)> &onResponse, const std::function< void(int status, const std::string &reason)> &onError)
void receiveResponseData (const char *junk, std::size_t junkLen)
void setRequest (const std::string &request)
const std::string & getRequest ()
Public Attributes
ServerRequest serverRequest
ServerResponse serverResponse
Protected Attributes
SocketConnection * socketConnection
std::string request
Private Attributes
ResponseParser parser
Detailed Description
Definition at line 40 of file ClientContext.h.
Member Typedef Documentation
SocketConnection
using http::ClientContext::SocketConnection = net::socket::stream::SocketConnectionBase
Definition at line 42 of file ClientContext.h.
Constructor & Destructor Documentation
ClientContext()
http::ClientContext::ClientContext (SocketConnection * socketConnection, const std::function< void(ServerResponse &)> & onResponse, const std::function< void(int status, const std::string &reason)> & onError)
Definition at line 32 of file ClientContext.cpp.
         : socketConnection(socketConnection)
         , parser(
               [](void) -> void {
               },
               [this](const std::string& httpVersion, const std::string& statusCode, const std::string& reason) -> void {
                   serverResponse.httpVersion = httpVersion;
                   serverResponse.statusCode = statusCode;
                   serverResponse.reason = reason;
               },
               [this](const std::map<std::string, std::string>& headers, const std::map<std::string, http::CookieOptions>& cookies) -> void {
                   serverResponse.headers = &headers;
                   serverResponse.cookies = &cookies;
               },
               [this](char* content, std::size_t contentLength) -> void {
                   serverResponse.body = content;
                   serverResponse.contentLength = contentLength;
               },
               [this, onResponse](http::ResponseParser& parser) -> void {
                   onResponse(serverResponse);
                   parser.reset();
               },
               [onError](int status, const std::string& reason) -> void {
                   onError(status, reason);
               }) {
     }
Member Function Documentation
getRequest()
const std::string & http::ClientContext::getRequest ()
Definition at line 69 of file ClientContext.cpp.
{
         return request;
     }
Referenced by http::Client< SocketClientT >::connect().
receiveResponseData()
void http::ClientContext::receiveResponseData (const char * junk, std::size_t junkLen)
Definition at line 61 of file ClientContext.cpp.
{
         parser.parse(junk, junkLen);
     }
Referenced by http::Client< SocketClientT >::connect().
setRequest()
void http::ClientContext::setRequest (const std::string & request)
Definition at line 65 of file ClientContext.cpp.
{
         this->request = request;
     }
Referenced by http::Client< SocketClientT >::connect().
Member Data Documentation
parser
ResponseParser http::ClientContext::parser private
Definition at line 63 of file ClientContext.h.
request
std::string http::ClientContext::request protected
Definition at line 56 of file ClientContext.h.
serverRequest
ServerRequest http::ClientContext::serverRequest
Definition at line 59 of file ClientContext.h.
Referenced by http::Client< SocketClientT >::connect().
serverResponse
ServerResponse http::ClientContext::serverResponse
Definition at line 60 of file ClientContext.h.
socketConnection
SocketConnection* http::ClientContext::socketConnection protected
Definition at line 54 of file ClientContext.h.
The documentation for this class was generated from the following files:
http/ClientContext.h
http/ClientContext.cpp