snode.c: net::socket::ip::address::ipv6::InetAddress Class Reference
net::socket::ip::address::ipv6::InetAddress Class Reference
#include <InetAddress.h>
Public Member Functions
InetAddress ()
InetAddress (const InetAddress &ina)
InetAddress (const std::string &ipOrHostname)
InetAddress (const std::string &ipOrHostname, uint16_t port)
InetAddress (uint16_t port)
InetAddress (const struct sockaddr_in6 &addr)
uint16_t port () const
std::string host () const
std::string ip () const
std::string serv () const
InetAddress & operator= (const InetAddress &ina)
const struct sockaddr_in6 & getSockAddrIn6 () const
Public Member Functions inherited from net::socket::SocketAddress< struct sockaddr_in6 >
const struct sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from net::socket::SocketAddress< struct sockaddr_in6 >
using SockAddr = struct sockaddr_in6
Protected Attributes inherited from net::socket::SocketAddress< struct sockaddr_in6 >
SockAddr sockAddr
Detailed Description
Definition at line 50 of file InetAddress.h.
Constructor & Destructor Documentation
InetAddress() [1/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress ()
Definition at line 11 of file InetAddress.cpp.
{
         sockAddr.sin6_family = AF_INET6;
         sockAddr.sin6_addr = in6addr_any;
         sockAddr.sin6_port = 0;
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
InetAddress() [2/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress (const InetAddress & ina)
Definition at line 105 of file InetAddress.cpp.
{
         memcpy(&sockAddr, &ina.sockAddr, sizeof(struct sockaddr_in6));
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
InetAddress() [3/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress (const std::string & ipOrHostname) explicit
Definition at line 17 of file InetAddress.cpp.
{
         struct addrinfo hints {};
         struct addrinfo* res;
         struct addrinfo* resalloc;
         memset(&hints, 0, sizeof(hints));
         memset(&sockAddr, 0, sizeof(struct sockaddr_in6));
         /* We only care about IPV6 results */
         hints.ai_family = AF_INET6;
         hints.ai_socktype = 0;
         hints.ai_flags = AI_ADDRCONFIG | AI_V4MAPPED;
         int err = getaddrinfo(ipOrHostname.c_str(), NULL, &hints, &res);
         if (err != 0) {
             throw bad_hostname(ipOrHostname);
         }
         resalloc = res;
         while (res) {
             /* Check to make sure we have a valid AF_INET6 address */
             if (res->ai_family == AF_INET6) {
                 /* Use memcpy since we're going to free the res variable later */
                 memcpy(&sockAddr, res->ai_addr, res->ai_addrlen);
                 /* Here we convert the port to network byte order */
                 sockAddr.sin6_port = htons(0);
                 sockAddr.sin6_family = AF_INET6;
                 break;
             }
             res = res->ai_next;
         }
         freeaddrinfo(resalloc);
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
InetAddress() [4/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress (const std::string & ipOrHostname, uint16_t port) explicit
Definition at line 56 of file InetAddress.cpp.
{
         struct addrinfo hints {};
         struct addrinfo* res;
         struct addrinfo* resalloc;
         memset(&hints, 0, sizeof(hints));
         memset(&sockAddr, 0, sizeof(struct sockaddr_in6));
         /* We only care about IPV6 results */
         hints.ai_family = AF_INET6;
         hints.ai_socktype = 0;
         hints.ai_flags = AI_ADDRCONFIG | AI_V4MAPPED;
         int err = getaddrinfo(ipOrHostname.c_str(), NULL, &hints, &res);
         if (err != 0) {
             throw bad_hostname(ipOrHostname);
         }
         resalloc = res;
         while (res) {
             /* Check to make sure we have a valid AF_INET6 address */
             if (res->ai_family == AF_INET6) {
                 /* Use memcpy since we're going to free the res variable later */
                 memcpy(&sockAddr, res->ai_addr, res->ai_addrlen);
                 /* Here we convert the port to network byte order */
                 sockAddr.sin6_port = htons(port);
                 sockAddr.sin6_family = AF_INET6;
                 break;
             }
             res = res->ai_next;
         }
         freeaddrinfo(resalloc);
     }
References port(), and net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
InetAddress() [5/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress (uint16_t port) explicit
Definition at line 95 of file InetAddress.cpp.
{
         sockAddr.sin6_family = AF_INET6;
         sockAddr.sin6_addr = in6addr_any;
         sockAddr.sin6_port = htons(port);
     }
References port(), and net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
InetAddress() [6/6]
net::socket::ip::address::ipv6::InetAddress::InetAddress (const struct sockaddr_in6 & addr) explicit
Definition at line 101 of file InetAddress.cpp.
{
         memcpy(&this->sockAddr, &addr, sizeof(struct sockaddr_in6));
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
Member Function Documentation
getSockAddrIn6()
const struct sockaddr_in6 & net::socket::ip::address::ipv6::InetAddress::getSockAddrIn6 () const
Definition at line 142 of file InetAddress.cpp.
{
         return sockAddr;
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
host()
std::string net::socket::ip::address::ipv6::InetAddress::host () const
Definition at line 121 of file InetAddress.cpp.
{
         char host[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), host, 256, nullptr, 0, 0);
         return std::string(host);
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
ip()
std::string net::socket::ip::address::ipv6::InetAddress::ip () const
Definition at line 128 of file InetAddress.cpp.
{
         char ip[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), ip, 256, nullptr, 0, NI_NUMERICHOST);
         return std::string(ip);
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
operator=()
InetAddress & net::socket::ip::address::ipv6::InetAddress::operator= (const InetAddress & ina)
Definition at line 109 of file InetAddress.cpp.
{
         if (this != &ina) {
             memcpy(&sockAddr, &ina.sockAddr, sizeof(struct sockaddr_in6));
         }
         return *this;
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
port()
unsigned short net::socket::ip::address::ipv6::InetAddress::port () const
Definition at line 117 of file InetAddress.cpp.
{
         return (ntohs(sockAddr.sin6_port));
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
Referenced by InetAddress().
serv()
std::string net::socket::ip::address::ipv6::InetAddress::serv () const
Definition at line 135 of file InetAddress.cpp.
{
         char serv[256];
         getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), nullptr, 0, serv, 256, 0);
         return std::string(serv);
     }
References net::socket::SocketAddress< struct sockaddr_in6 >::sockAddr.
The documentation for this class was generated from the following files:
net/socket/ip/address/ipv6/InetAddress.h
net/socket/ip/address/ipv6/InetAddress.cpp