snode.c: web::http::client::SocketContextFactory< RequestT, ResponseT > Class Template Reference
web::http::client::SocketContextFactory< RequestT, ResponseT > Class Template Reference
#include <SocketContextFactory.h>
Public Types
using Request = RequestT
using Response = ResponseT
Public Member Functions
SocketContextFactory ()
~SocketContextFactory ()
void setOnResponse (const std::function< void(Request &, Response &)> &onResponse)
void setOnRequestError (const std::function< void(int, const std::string &)> onRequestError)
Private Member Functions
net::socket::stream::SocketContext * create (net::socket::stream::SocketConnection *socketConnection) const override
Private Attributes
std::function< void(Request &, Response &)> onResponse
std::function< void(int, const std::string &)> onRequestError
Static Private Attributes
static int useCount = 0
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::client::SocketContextFactory< RequestT, ResponseT >
Definition at line 37 of file SocketContextFactory.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::client::SocketContextFactory< RequestT, ResponseT >::Request = RequestT
Definition at line 39 of file SocketContextFactory.h.
Response
template<typename RequestT , typename ResponseT > using web::http::client::SocketContextFactory< RequestT, ResponseT >::Response = ResponseT
Definition at line 40 of file SocketContextFactory.h.
Constructor & Destructor Documentation
SocketContextFactory()
template<typename RequestT , typename ResponseT > web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory () inline
Definition at line 42 of file SocketContextFactory.h.
{
             if (useCount == 0) {
                 SocketContextUpgradeFactorySelector::instance()->loadSocketContexts();
             }
             useCount++;
         }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), web::http::client::SocketContextUpgradeFactorySelector::loadSocketContexts(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::useCount.
~SocketContextFactory()
template<typename RequestT , typename ResponseT > web::http::client::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory () inline virtual
Reimplemented from net::socket::stream::SocketContextFactory.
Definition at line 49 of file SocketContextFactory.h.
{
             useCount--;
             if (useCount == 0) {
                 SocketContextUpgradeFactorySelector::instance()->unloadSocketContexts();
             }
         }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), web::http::client::SocketContextUpgradeFactorySelector::unloadSocketContexts(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::useCount.
Member Function Documentation
create()
template<typename RequestT , typename ResponseT > net::socket::stream::SocketContext* web::http::client::SocketContextFactory< RequestT, ResponseT >::create (net::socket::stream::SocketConnection * socketConnection) const inline override private virtual
Implements net::socket::stream::SocketContextFactory.
Definition at line 57 of file SocketContextFactory.h.
{
             return new SocketContextT<Request, Response>(socketConnection, onResponse, onRequestError);
         }
References web::http::client::SocketContextFactory< RequestT, ResponseT >::onRequestError, and web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponse.
setOnRequestError()
template<typename RequestT , typename ResponseT > void web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnRequestError (const std::function< void(int, const std::string &)> onRequestError) inline
Definition at line 66 of file SocketContextFactory.h.
{
             this->onRequestError = onRequestError;
         }
References web::http::client::SocketContextFactory< RequestT, ResponseT >::onRequestError.
setOnResponse()
template<typename RequestT , typename ResponseT > void web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnResponse (const std::function< void(Request &, Response &)> & onResponse) inline
Definition at line 62 of file SocketContextFactory.h.
{
             this->onResponse = onResponse;
         }
References web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponse.
Member Data Documentation
onRequestError
template<typename RequestT , typename ResponseT > std::function<void(int, const std::string&)> web::http::client::SocketContextFactory< RequestT, ResponseT >::onRequestError private
Definition at line 72 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::create(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnRequestError().
onResponse
template<typename RequestT , typename ResponseT > std::function<void(Request&, Response&)> web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponse private
Definition at line 71 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::create(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnResponse().
useCount
template<typename RequestT , typename ResponseT > int web::http::client::SocketContextFactory< RequestT, ResponseT >::useCount = 0 static private
Definition at line 74 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
The documentation for this class was generated from the following file:
web/http/client/SocketContextFactory.h