snode.c: http::server::ServerContext Class Reference
http::server::ServerContext Class Reference abstract
#include <ServerContext.h>
Public Types
using SocketConnection = net::socket::stream::SocketConnectionBase
Public Member Functions
virtual ~ServerContext ()=default
void upgrade (ServerContext *newServerContext)
Public Member Functions inherited from net::socket::stream::SocketProtocol
virtual ~SocketProtocol ()=default
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
Protected Member Functions
void receiveData (const char *junk, std::size_t junkLen) override
virtual void parseReceivedData (const char *junk, std::size_t junkLen)=0
Protected Member Functions inherited from net::socket::stream::SocketProtocol
void setSocketConnection (SocketConnectionBase *socketConnection)
Private Attributes
bool markedForDelete = false
Additional Inherited Members
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
Detailed Description
Definition at line 37 of file ServerContext.h.
Member Typedef Documentation
SocketConnection
using http::server::ServerContext::SocketConnection = net::socket::stream::SocketConnectionBase
Definition at line 39 of file ServerContext.h.
Constructor & Destructor Documentation
~ServerContext()
virtual http::server::ServerContext::~ServerContext () virtual default
Member Function Documentation
parseReceivedData()
virtual void http::server::ServerContext::parseReceivedData (const char * junk, std::size_t junkLen) protected pure virtual
Implemented in http::websocket::WSServerContext, and http::server::HTTPServerContext< RequestT, ResponseT >.
Referenced by receiveData().
receiveData()
void http::server::ServerContext::receiveData (const char * junk, std::size_t junkLen) override protected virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 38 of file ServerContext.cpp.
{
         parseReceivedData(junk, junkLen);
         if (markedForDelete) {
             delete this;
         }
     }
References markedForDelete, and parseReceivedData().
upgrade()
void http::server::ServerContext::upgrade (ServerContext * newServerContext)
Definition at line 32 of file ServerContext.cpp.
{
         socketConnection->setSocketProtocol(newServerContext);
         markedForDelete = true;
     }
References markedForDelete, net::socket::stream::SocketConnectionBase::setSocketProtocol(), and net::socket::stream::SocketProtocol::socketConnection.
Referenced by http::server::Response::upgrade().
Member Data Documentation
markedForDelete
bool http::server::ServerContext::markedForDelete = false private
Definition at line 51 of file ServerContext.h.
Referenced by receiveData(), and upgrade().
The documentation for this class was generated from the following files:
http/server/ServerContext.h
http/server/ServerContext.cpp