snode.c: net::ReadEventReceiver Class Reference
net::ReadEventReceiver Class Reference abstract
#include <ReadEventReceiver.h>
Public Member Functions
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::EventReceiver
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
ReadEventReceiver ()
virtual void readEvent ()=0
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Friends
template<typename ReadEventReceiver >
class EventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::EventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 30 of file ReadEventReceiver.h.
Constructor & Destructor Documentation
ReadEventReceiver()
net::ReadEventReceiver::ReadEventReceiver () protected
Definition at line 26 of file ReadEventReceiver.cpp.
         : EventReceiver(EventLoop::instance().getReadEventDispatcher().getTimeout()) {
     }
Member Function Documentation
disable()
void net::ReadEventReceiver::disable () override virtual
Implements net::EventReceiver.
Definition at line 39 of file ReadEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().disable(this, fd);
     }
References net::EventDispatcher< EventReceiverT >::disable(), net::EventReceiver::fd, net::EventLoop::getReadEventDispatcher(), and net::EventLoop::instance().
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::close(), net::socket::stream::tls::SocketReader< SocketT >::read(), net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::readEvent(), net::socket::stream::SocketReader< SocketT >::readEvent(), and net::socket::stream::tls::TLSHandshake::readEvent().
dispatchEvent()
void net::ReadEventReceiver::dispatchEvent () inline override protected virtual
Implements net::EventReceiver.
Definition at line 36 of file ReadEventReceiver.h.
{
             readEvent();
         }
References readEvent().
enable()
void net::ReadEventReceiver::enable (int fd, long timeout = TIMEOUT::IGNORE) override virtual
Implements net::EventReceiver.
Definition at line 34 of file ReadEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().enable(this, fd);
         setTimeout(timeout);
     }
References net::EventDispatcher< EventReceiverT >::enable(), net::EventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), setTimeout(), and net::EventReceiver::timeout().
Referenced by net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::connectEvent(), net::socket::stream::tls::TLSHandshake::TLSHandshake(), and net::socket::stream::tls::TLSHandshake::writeEvent().
readEvent()
virtual void net::ReadEventReceiver::readEvent () protected pure virtual
Implemented in net::socket::stream::tls::TLSHandshake, net::socket::stream::SocketReader< SocketT >, net::socket::stream::SocketConnector< SocketConnectionT >, net::socket::stream::SocketConnector< stream::legacy::SocketConnection< SocketT > >, net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >, and FileReader.
Referenced by dispatchEvent().
resume()
void net::ReadEventReceiver::resume () override virtual
Implements net::EventReceiver.
Definition at line 47 of file ReadEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().resume(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::resume().
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read().
setTimeout()
void net::ReadEventReceiver::setTimeout (long timeout = TIMEOUT::DEFAULT)
Definition at line 30 of file ReadEventReceiver.cpp.
{
         EventReceiver::setTimeout(timeout, EventLoop::instance().getReadEventDispatcher().getTimeout());
     }
References net::EventReceiver::getTimeout(), net::EventLoop::instance(), net::EventReceiver::setTimeout(), and net::EventReceiver::timeout().
Referenced by enable(), and net::socket::stream::tls::TLSHandshake::TLSHandshake().
suspend()
void net::ReadEventReceiver::suspend () override virtual
Implements net::EventReceiver.
Definition at line 43 of file ReadEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().suspend(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::suspend().
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read(), and net::socket::stream::tls::TLSHandshake::timeout().
Friends And Related Function Documentation
EventDispatcher
template<typename ReadEventReceiver > friend class EventDispatcher friend
Definition at line 50 of file ReadEventReceiver.h.
The documentation for this class was generated from the following files:
net/ReadEventReceiver.h
net/ReadEventReceiver.cpp