snode.c: express::WebApp Class Reference
express::WebApp Class Reference abstract
#include <WebApp.h>
Static Public Member Functions
static void init (int argc, char *argv[])
static int start ()
static void stop ()
Protected Member Functions
WebApp ()
WebApp (const Router &router)
virtual void listen (unsigned short port, const std::function< void(int err)> &onError=nullptr)=0
virtual void listen (const std::string &host, unsigned short port, const std::function< void(int err)> &onError=nullptr)=0
Protected Member Functions inherited from express::Router
void dispatch (express::Request &req, express::Response &res)
void completed (const express::Request &req, const express::Response &res)
Static Private Attributes
static bool initialized {false}
Additional Inherited Members
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router & operator= (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::string &path, const Router &router)
Router & use (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::string &path, const Router &router)
Router & all (const Router &router)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::string &path, const Router &router)
Router & get (const Router &router)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::string &path, const Router &router)
Router & put (const Router &router)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::string &path, const Router &router)
Router & post (const Router &router)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::string &path, const Router &router)
Router & del (const Router &router)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::string &path, const Router &router)
Router & connect (const Router &router)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::string &path, const Router &router)
Router & options (const Router &router)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::string &path, const Router &router)
Router & trace (const Router &router)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::string &path, const Router &router)
Router & patch (const Router &router)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::string &path, const Router &router)
Router & head (const Router &router)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Detailed Description
Definition at line 34 of file WebApp.h.
Constructor & Destructor Documentation
WebApp() [1/2]
express::WebApp::WebApp () protected
Definition at line 32 of file WebApp.cpp.
                    {
         if (!initialized) {
             LOG(FATAL) << "ERROR: WebApp not initialized. Use WebApp::init(argc, argv) before creating a concrete WebApp object";
             exit(1);
         }
     }
References initialized.
WebApp() [2/2]
express::WebApp::WebApp (const Router & router) protected
Definition at line 39 of file WebApp.cpp.
         : Router(router) {
     }
Member Function Documentation
init()
void express::WebApp::init (int argc, char * argv[]) static
Definition at line 43 of file WebApp.cpp.
{
         net::EventLoop::init(argc, argv);
         WebApp::initialized = true;
     }
References net::EventLoop::init(), and initialized.
listen() [1/2]
virtual void express::WebApp::listen (const std::string & host, unsigned short port, const std::function< void(int err)> & onError = nullptr) protected pure virtual
Implemented in express::WebAppT< ServerT >, express::WebAppT< http::legacy::Server6< express::Request, express::Response > >, express::WebAppT< http::tls::Server6< express::Request, express::Response > >, express::WebAppT< http::legacy::Server< express::Request, express::Response > >, and express::WebAppT< http::tls::Server< express::Request, express::Response > >.
listen() [2/2]
virtual void express::WebApp::listen (unsigned short port, const std::function< void(int err)> & onError = nullptr) protected pure virtual
Implemented in express::WebAppT< ServerT >, express::WebAppT< http::legacy::Server6< express::Request, express::Response > >, express::WebAppT< http::tls::Server6< express::Request, express::Response > >, express::WebAppT< http::legacy::Server< express::Request, express::Response > >, and express::WebAppT< http::tls::Server< express::Request, express::Response > >.
start()
int express::WebApp::start () static
Definition at line 48 of file WebApp.cpp.
                       {
         return net::EventLoop::start();
     }
References net::EventLoop::start().
stop()
void express::WebApp::stop () static
Definition at line 52 of file WebApp.cpp.
                       {
         net::EventLoop::stop();
     }
References net::EventLoop::stop().
Member Data Documentation
initialized
bool express::WebApp::initialized {false} static private
Definition at line 48 of file WebApp.h.
Referenced by init(), and WebApp().
The documentation for this class was generated from the following files:
express/WebApp.h
express/WebApp.cpp