snode.c: net::EventLoop Class Reference
net::EventLoop Class Reference
#include <EventLoop.h>
Public Member Functions
ReadEventDispatcher & getReadEventDispatcher ()
AcceptEventDispatcher & getAcceptEventDispatcher ()
ConnectEventDispatcher & getConnectEventDispatcher ()
WriteEventDispatcher & getWriteEventDispatcher ()
OutOfBandEventDispatcher & getOutOfBandEventDispatcher ()
TimerEventDispatcher & getTimerEventDispatcher ()
unsigned long getEventCounter ()
unsigned long getTickCounter ()
Static Public Member Functions
static EventLoop & instance ()
static void init (int argc, char *argv[])
static int start ()
static void stop ()
Private Member Functions
EventLoop ()
void tick ()
Static Private Member Functions
static void stoponsig (int sig)
Private Attributes
FdSet readFdSet
FdSet writeFdSet
FdSet exceptFdSet
ReadEventDispatcher readEventDispatcher
AcceptEventDispatcher acceptEventDispatcher
WriteEventDispatcher writeEventDispatcher
OutOfBandEventDispatcher outOfBandEventDispatcher
ConnectEventDispatcher connectEventDispatcher
TimerEventDispatcher timerEventDispatcher
struct timeval nextInactivityTimeout = {LONG_MAX, 0}
unsigned long tickCounter = 0
Static Private Attributes
static EventLoop eventLoop
static bool running = false
static bool stopped = true
static int stopsig = 0
static bool initialized = false
Detailed Description
Definition at line 39 of file EventLoop.h.
Constructor & Destructor Documentation
EventLoop()
net::EventLoop::EventLoop () private
Definition at line 59 of file EventLoop.cpp.
         : readEventDispatcher(readFdSet, MAX_READ_INACTIVITY)
         , acceptEventDispatcher(readFdSet, MAX_ACCEPT_INACTIVITY)
         , writeEventDispatcher(writeFdSet, MAX_WRITE_INACTIVITY)
         , outOfBandEventDispatcher(exceptFdSet, MAX_OUTOFBAND_INACTIVITY)
         , connectEventDispatcher(writeFdSet, MAX_CONNECT_INACTIVITY) {
     }
Member Function Documentation
getAcceptEventDispatcher()
AcceptEventDispatcher& net::EventLoop::getAcceptEventDispatcher () inline
Definition at line 57 of file EventLoop.h.
{
             return acceptEventDispatcher;
         }
References acceptEventDispatcher.
Referenced by net::AcceptEventReceiver::disable(), net::AcceptEventReceiver::enable(), net::AcceptEventReceiver::resume(), and net::AcceptEventReceiver::suspend().
getConnectEventDispatcher()
ConnectEventDispatcher& net::EventLoop::getConnectEventDispatcher () inline
Definition at line 61 of file EventLoop.h.
{
             return connectEventDispatcher;
         }
References connectEventDispatcher.
Referenced by net::ConnectEventReceiver::disable(), net::ConnectEventReceiver::enable(), net::ConnectEventReceiver::resume(), and net::ConnectEventReceiver::suspend().
getEventCounter()
unsigned long net::EventLoop::getEventCounter () inline
Definition at line 77 of file EventLoop.h.
{
             return readEventDispatcher.getEventCounter() + writeEventDispatcher.getEventCounter() +
                    acceptEventDispatcher.getEventCounter() + outOfBandEventDispatcher.getEventCounter() +
                    connectEventDispatcher.getEventCounter();
         }
References acceptEventDispatcher, connectEventDispatcher, net::EventDispatcher< EventReceiverT >::getEventCounter(), outOfBandEventDispatcher, readEventDispatcher, and writeEventDispatcher.
getOutOfBandEventDispatcher()
OutOfBandEventDispatcher& net::EventLoop::getOutOfBandEventDispatcher () inline
Definition at line 69 of file EventLoop.h.
{
             return outOfBandEventDispatcher;
         }
References outOfBandEventDispatcher.
Referenced by net::OutOfBandEventReceiver::disable(), net::OutOfBandEventReceiver::enable(), net::OutOfBandEventReceiver::resume(), and net::OutOfBandEventReceiver::suspend().
getReadEventDispatcher()
ReadEventDispatcher& net::EventLoop::getReadEventDispatcher () inline
Definition at line 53 of file EventLoop.h.
{
             return readEventDispatcher;
         }
References readEventDispatcher.
Referenced by net::ReadEventReceiver::disable(), net::ReadEventReceiver::enable(), net::ReadEventReceiver::resume(), and net::ReadEventReceiver::suspend().
getTickCounter()
unsigned long net::EventLoop::getTickCounter () inline
Definition at line 83 of file EventLoop.h.
{
             return tickCounter;
         }
References tickCounter.
getTimerEventDispatcher()
TimerEventDispatcher& net::EventLoop::getTimerEventDispatcher () inline
Definition at line 73 of file EventLoop.h.
{
             return timerEventDispatcher;
         }
References timerEventDispatcher.
Referenced by net::timer::Timer::cancel(), net::timer::Timer::continousTimer(), and net::timer::Timer::singleshotTimer().
getWriteEventDispatcher()
WriteEventDispatcher& net::EventLoop::getWriteEventDispatcher () inline
Definition at line 65 of file EventLoop.h.
{
             return writeEventDispatcher;
         }
References writeEventDispatcher.
Referenced by net::WriteEventReceiver::disable(), net::WriteEventReceiver::enable(), net::WriteEventReceiver::resume(), and net::WriteEventReceiver::suspend().
init()
void net::EventLoop::init (int argc, char * argv[]) static
Definition at line 133 of file EventLoop.cpp.
{
         signal(SIGPIPE, SIG_IGN);
         signal(SIGQUIT, EventLoop::stoponsig);
         signal(SIGHUP, EventLoop::stoponsig);
         signal(SIGINT, EventLoop::stoponsig);
         signal(SIGTERM, EventLoop::stoponsig);
         signal(SIGABRT, EventLoop::stoponsig);
         Logger::init(argc, argv);
         Logger::setCustomFormatSpec("%tick", net::getTickCounterAsString);
         EventLoop::initialized = true;
     }
References net::getTickCounterAsString(), Logger::init(), initialized, Logger::setCustomFormatSpec(), and stoponsig().
Referenced by express::WebApp::init().
instance()
static EventLoop& net::EventLoop::instance () inline static
Definition at line 44 of file EventLoop.h.
{
             return eventLoop;
         }
References eventLoop.
Referenced by net::timer::Timer::cancel(), net::timer::Timer::continousTimer(), net::AcceptEventReceiver::disable(), net::ConnectEventReceiver::disable(), net::OutOfBandEventReceiver::disable(), net::ReadEventReceiver::disable(), net::WriteEventReceiver::disable(), net::AcceptEventReceiver::enable(), net::ConnectEventReceiver::enable(), net::OutOfBandEventReceiver::enable(), net::ReadEventReceiver::enable(), net::WriteEventReceiver::enable(), net::getTickCounterAsString(), net::AcceptEventReceiver::resume(), net::ConnectEventReceiver::resume(), net::OutOfBandEventReceiver::resume(), net::ReadEventReceiver::resume(), net::WriteEventReceiver::resume(), net::AcceptEventReceiver::setTimeout(), net::ConnectEventReceiver::setTimeout(), net::OutOfBandEventReceiver::setTimeout(), net::ReadEventReceiver::setTimeout(), net::WriteEventReceiver::setTimeout(), net::timer::Timer::singleshotTimer(), net::AcceptEventReceiver::suspend(), net::ConnectEventReceiver::suspend(), net::OutOfBandEventReceiver::suspend(), net::ReadEventReceiver::suspend(), and net::WriteEventReceiver::suspend().
start()
int net::EventLoop::start () static
Definition at line 148 of file EventLoop.cpp.
{
         if (!initialized) {
             PLOG(ERROR) << "snode.c not initialized. Use Multiplexer::init(argc, argv) before Multiplexer::start().";
             exit(1);
         }
         stopped = false;
         if (!running) {
             running = true;
             while (!stopped) {
                 eventLoop.tick();
             };
             eventLoop.readEventDispatcher.observeEnabledEvents();
             eventLoop.writeEventDispatcher.observeEnabledEvents();
             eventLoop.acceptEventDispatcher.observeEnabledEvents();
             eventLoop.outOfBandEventDispatcher.observeEnabledEvents();
             eventLoop.connectEventDispatcher.observeEnabledEvents();
             eventLoop.readEventDispatcher.disableObservedEvents();
             eventLoop.writeEventDispatcher.disableObservedEvents();
             eventLoop.acceptEventDispatcher.disableObservedEvents();
             eventLoop.outOfBandEventDispatcher.disableObservedEvents();
             eventLoop.connectEventDispatcher.disableObservedEvents();
             eventLoop.readEventDispatcher.unobserveDisabledEvents();
             eventLoop.writeEventDispatcher.unobserveDisabledEvents();
             eventLoop.acceptEventDispatcher.unobserveDisabledEvents();
             eventLoop.outOfBandEventDispatcher.unobserveDisabledEvents();
             eventLoop.connectEventDispatcher.unobserveDisabledEvents();
             eventLoop.readEventDispatcher.unobserveDisabledEventReceiver();
             eventLoop.writeEventDispatcher.unobserveDisabledEventReceiver();
             eventLoop.acceptEventDispatcher.unobserveDisabledEventReceiver();
             eventLoop.connectEventDispatcher.unobserveDisabledEventReceiver();
             eventLoop.outOfBandEventDispatcher.unobserveDisabledEventReceiver();
             eventLoop.timerEventDispatcher.cancelAll();
             running = false;
         }
         int returnReason = 0;
         if (stopsig != 0) {
             returnReason = -1;
         }
         return returnReason;
     }
References acceptEventDispatcher, net::TimerEventDispatcher::cancelAll(), connectEventDispatcher, net::EventDispatcher< EventReceiverT >::disableObservedEvents(), eventLoop, initialized, net::EventDispatcher< EventReceiverT >::observeEnabledEvents(), outOfBandEventDispatcher, readEventDispatcher, running, stopped, stopsig, tick(), timerEventDispatcher, net::EventDispatcher< EventReceiverT >::unobserveDisabledEventReceiver(), net::EventDispatcher< EventReceiverT >::unobserveDisabledEvents(), and writeEventDispatcher.
Referenced by express::WebApp::start().
stop()
void net::EventLoop::stop () static
Definition at line 201 of file EventLoop.cpp.
{
         stopped = true;
     }
References stopped.
Referenced by express::WebApp::stop(), stoponsig(), and tick().
stoponsig()
void net::EventLoop::stoponsig (int sig) static private
Definition at line 205 of file EventLoop.cpp.
{
         stopsig = sig;
         stop();
     }
References stop(), and stopsig.
Referenced by init().
tick()
void net::EventLoop::tick () inline private
Definition at line 67 of file EventLoop.cpp.
{
         struct timeval nextTimeout = readEventDispatcher.observeEnabledEvents();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         nextTimeout = writeEventDispatcher.observeEnabledEvents();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         nextTimeout = acceptEventDispatcher.observeEnabledEvents();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         nextTimeout = connectEventDispatcher.observeEnabledEvents();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         nextTimeout = outOfBandEventDispatcher.observeEnabledEvents();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         nextTimeout = timerEventDispatcher.getNextTimeout();
         nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
         int maxFd = readEventDispatcher.getMaxFd();
         maxFd = std::max(writeEventDispatcher.getMaxFd(), maxFd);
         maxFd = std::max(acceptEventDispatcher.getMaxFd(), maxFd);
         maxFd = std::max(connectEventDispatcher.getMaxFd(), maxFd);
         maxFd = std::max(outOfBandEventDispatcher.getMaxFd(), maxFd);
         if (maxFd >= 0 || !timerEventDispatcher.empty()) {
             if (nextInactivityTimeout < timeval({0, 0})) {
                 nextInactivityTimeout = {0, 0};
             }
             int counter = select(maxFd + 1, &readFdSet.get(), &writeFdSet.get(), &exceptFdSet.get(), &nextInactivityTimeout);
             if (counter >= 0) {
                 tickCounter++;
                 timerEventDispatcher.dispatch();
                 struct timeval currentTime = {time(nullptr), 0};
                 nextInactivityTimeout = {LONG_MAX, 0};
                 nextTimeout = readEventDispatcher.dispatchActiveEvents(currentTime);
                 nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
                 nextTimeout = writeEventDispatcher.dispatchActiveEvents(currentTime);
                 nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
                 nextTimeout = acceptEventDispatcher.dispatchActiveEvents(currentTime);
                 nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
                 nextTimeout = connectEventDispatcher.dispatchActiveEvents(currentTime);
                 nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
                 nextTimeout = outOfBandEventDispatcher.dispatchActiveEvents(currentTime);
                 nextInactivityTimeout = std::min(nextTimeout, nextInactivityTimeout);
             } else if (errno != EINTR) {
                 PLOG(ERROR) << "select";
                 stop();
             }
         } else {
             stop();
         }
         readEventDispatcher.unobserveDisabledEvents();
         writeEventDispatcher.unobserveDisabledEvents();
         acceptEventDispatcher.unobserveDisabledEvents();
         connectEventDispatcher.unobserveDisabledEvents();
         outOfBandEventDispatcher.unobserveDisabledEvents();
         readEventDispatcher.unobserveDisabledEventReceiver();
         writeEventDispatcher.unobserveDisabledEventReceiver();
         acceptEventDispatcher.unobserveDisabledEventReceiver();
         connectEventDispatcher.unobserveDisabledEventReceiver();
         outOfBandEventDispatcher.unobserveDisabledEventReceiver();
     }
References acceptEventDispatcher, connectEventDispatcher, net::TimerEventDispatcher::dispatch(), net::EventDispatcher< EventReceiverT >::dispatchActiveEvents(), net::TimerEventDispatcher::empty(), exceptFdSet, net::FdSet::get(), net::EventDispatcher< EventReceiverT >::getMaxFd(), net::TimerEventDispatcher::getNextTimeout(), nextInactivityTimeout, net::EventDispatcher< EventReceiverT >::observeEnabledEvents(), outOfBandEventDispatcher, readEventDispatcher, readFdSet, stop(), tickCounter, timerEventDispatcher, net::EventDispatcher< EventReceiverT >::unobserveDisabledEventReceiver(), net::EventDispatcher< EventReceiverT >::unobserveDisabledEvents(), writeEventDispatcher, and writeFdSet.
Referenced by start().
Member Data Documentation
acceptEventDispatcher
AcceptEventDispatcher net::EventLoop::acceptEventDispatcher private
Definition at line 99 of file EventLoop.h.
Referenced by getAcceptEventDispatcher(), getEventCounter(), start(), and tick().
connectEventDispatcher
ConnectEventDispatcher net::EventLoop::connectEventDispatcher private
Definition at line 102 of file EventLoop.h.
Referenced by getConnectEventDispatcher(), getEventCounter(), start(), and tick().
eventLoop
EventLoop net::EventLoop::eventLoop static private
Definition at line 92 of file EventLoop.h.
Referenced by instance(), and start().
exceptFdSet
FdSet net::EventLoop::exceptFdSet private
Definition at line 96 of file EventLoop.h.
Referenced by tick().
initialized
bool net::EventLoop::initialized = false static private
Definition at line 110 of file EventLoop.h.
Referenced by init(), and start().
nextInactivityTimeout
struct timeval net::EventLoop::nextInactivityTimeout = {LONG_MAX, 0} private
Definition at line 103 of file EventLoop.h.
Referenced by tick().
outOfBandEventDispatcher
OutOfBandEventDispatcher net::EventLoop::outOfBandEventDispatcher private
Definition at line 101 of file EventLoop.h.
Referenced by getEventCounter(), getOutOfBandEventDispatcher(), start(), and tick().
readEventDispatcher
ReadEventDispatcher net::EventLoop::readEventDispatcher private
Definition at line 98 of file EventLoop.h.
Referenced by getEventCounter(), getReadEventDispatcher(), start(), and tick().
readFdSet
FdSet net::EventLoop::readFdSet private
Definition at line 94 of file EventLoop.h.
Referenced by tick().
running
bool net::EventLoop::running = false static private
Definition at line 107 of file EventLoop.h.
Referenced by start().
stopped
bool net::EventLoop::stopped = true static private
Definition at line 108 of file EventLoop.h.
Referenced by start(), and stop().
stopsig
int net::EventLoop::stopsig = 0 static private
Definition at line 109 of file EventLoop.h.
Referenced by start(), and stoponsig().
tickCounter
unsigned long net::EventLoop::tickCounter = 0 private
Definition at line 112 of file EventLoop.h.
Referenced by getTickCounter(), and tick().
timerEventDispatcher
TimerEventDispatcher net::EventLoop::timerEventDispatcher private
Definition at line 103 of file EventLoop.h.
Referenced by getTimerEventDispatcher(), start(), and tick().
writeEventDispatcher
WriteEventDispatcher net::EventLoop::writeEventDispatcher private
Definition at line 100 of file EventLoop.h.
Referenced by getEventCounter(), getWriteEventDispatcher(), start(), and tick().
writeFdSet
FdSet net::EventLoop::writeFdSet private
Definition at line 95 of file EventLoop.h.
Referenced by tick().
The documentation for this class was generated from the following files:
net/EventLoop.h
net/EventLoop.cpp