snode.c: net::ExceptionalConditionEventReceiver Class Reference
net::ExceptionalConditionEventReceiver Class Reference abstract
#include <ExceptionalConditionEventReceiver.h>
Public Member Functions
void enable (int fd) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
ExceptionalConditionEventReceiver (long timeout=60)
virtual void outOfBandEvent ()=0
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
void dispatchEvent () override
Additional Inherited Members
Protected Attributes inherited from net::DescriptorEventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Detailed Description
Definition at line 32 of file ExceptionalConditionEventReceiver.h.
Constructor & Destructor Documentation
ExceptionalConditionEventReceiver()
net::ExceptionalConditionEventReceiver::ExceptionalConditionEventReceiver (long timeout = 60) protected
Definition at line 26 of file ExceptionalConditionEventReceiver.cpp.
         : DescriptorEventReceiver(timeout) {
     }
Member Function Documentation
disable()
void net::ExceptionalConditionEventReceiver::disable () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 38 of file ExceptionalConditionEventReceiver.cpp.
{
         EventLoop::instance().getExceptionalConditionEventDispatcher().disable(this, fd);
     }
References net::DescriptorEventDispatcher::disable(), net::DescriptorEventReceiver::fd, net::EventLoop::getExceptionalConditionEventDispatcher(), and net::EventLoop::instance().
dispatchEvent()
void net::ExceptionalConditionEventReceiver::dispatchEvent () override private virtual
Implements net::DescriptorEventReceiver.
Definition at line 30 of file ExceptionalConditionEventReceiver.cpp.
{
         outOfBandEvent();
     }
References outOfBandEvent().
enable()
void net::ExceptionalConditionEventReceiver::enable (int fd) override virtual
Implements net::DescriptorEventReceiver.
Definition at line 34 of file ExceptionalConditionEventReceiver.cpp.
{
         EventLoop::instance().getExceptionalConditionEventDispatcher().enable(this, fd);
     }
References net::DescriptorEventDispatcher::enable(), net::DescriptorEventReceiver::fd, net::EventLoop::getExceptionalConditionEventDispatcher(), and net::EventLoop::instance().
outOfBandEvent()
virtual void net::ExceptionalConditionEventReceiver::outOfBandEvent () protected pure virtual
Referenced by dispatchEvent().
resume()
void net::ExceptionalConditionEventReceiver::resume () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 46 of file ExceptionalConditionEventReceiver.cpp.
{
         EventLoop::instance().getExceptionalConditionEventDispatcher().resume(this, fd);
     }
References net::DescriptorEventReceiver::fd, net::EventLoop::getExceptionalConditionEventDispatcher(), net::EventLoop::instance(), and net::DescriptorEventDispatcher::resume().
suspend()
void net::ExceptionalConditionEventReceiver::suspend () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 42 of file ExceptionalConditionEventReceiver.cpp.
{
         EventLoop::instance().getExceptionalConditionEventDispatcher().suspend(this, fd);
     }
References net::DescriptorEventReceiver::fd, net::EventLoop::getExceptionalConditionEventDispatcher(), net::EventLoop::instance(), and net::DescriptorEventDispatcher::suspend().
The documentation for this class was generated from the following files:
net/ExceptionalConditionEventReceiver.h
net/ExceptionalConditionEventReceiver.cpp