snode.c: net::socket::stream::tls::SocketListener< SocketT > Class Template Reference
net::socket::stream::tls::SocketListener< SocketT > Class Template Reference
#include <SocketListener.h>
Public Types
using SocketConnection = stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Types inherited from net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >
using SocketConnection = stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
Protected Member Functions
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
~SocketListener () override
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(int err)> &onError) override
Protected Member Functions inherited from net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
SocketListener ()=delete
SocketListener (const SocketListener &)=delete
SocketListener & operator= (const SocketListener &)=delete
virtual void listen (const typename Socket::SocketAddress &localAddress, int backlog, const std::function< void(int err)> &onError)
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver ()
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Private Attributes
SSL_CTX * ctx = nullptr
Static Private Attributes
static int sslSessionCtxId = 1
Friends
template<typename SocketListener >
class stream::SocketServer
Additional Inherited Members
Public Member Functions inherited from net::AcceptEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::EventReceiver
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Attributes inherited from net::EventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketListener< SocketT >
Definition at line 40 of file SocketListener.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::tls::SocketListener< SocketT >::Socket = typename SocketConnection::Socket
Definition at line 43 of file SocketListener.h.
SocketAddress
template<typename SocketT > using net::socket::stream::tls::SocketListener< SocketT >::SocketAddress = typename Socket::SocketAddress
Definition at line 44 of file SocketListener.h.
SocketConnection
template<typename SocketT > using net::socket::stream::tls::SocketListener< SocketT >::SocketConnection = stream::tls::SocketConnection<SocketT>
Definition at line 42 of file SocketListener.h.
Constructor & Destructor Documentation
SocketListener()
template<typename SocketT > net::socket::stream::tls::SocketListener< SocketT >::SocketListener (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options) inline protected
Definition at line 47 of file SocketListener.h.
                 : stream::SocketListener<SocketConnection>(
                       [onConstruct](SocketConnection* socketConnection) -> void {
                           onConstruct(socketConnection);
                       },
                       [onDestruct](SocketConnection* socketConnection) -> void {
                           onDestruct(socketConnection);
                       },
                       [onConnect, &ctx = this->ctx](SocketConnection* socketConnection) -> void {
                           SSL* ssl = socketConnection->startSSL(ctx);
                           if (ssl != nullptr) {
                               socketConnection->ReadEventReceiver::suspend();
                               SSL_set_accept_state(ssl);
                               TLSHandshake::doHandshake(
                                   ssl,
                                   [&onConnect, socketConnection](void) -> void { // onSuccess
                                       socketConnection->ReadEventReceiver::resume();
                                       onConnect(socketConnection);
                                   },
                                   [socketConnection](void) -> void { // onTimeout
                                       PLOG(ERROR) << "SSL/TLS handshake timeout";
                                       socketConnection->ReadEventReceiver::disable();
                                   },
                                   [socketConnection](int sslErr) -> void { // onError
                                       ssl_log("SSL/TLS handshake failed", -sslErr);
                                       socketConnection->setSSLError(-sslErr);
                                       socketConnection->ReadEventReceiver::disable();
                                   });
                           } else {
                               socketConnection->ReadEventReceiver::disable();
                               ssl_log_error("SSL/TLS initialization failed");
                           }
                       },
                       [onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                           socketConnection->stopSSL();
                           onDisconnect(socketConnection);
                       },
                       onRead,
                       onReadError,
                       onWriteError,
                       options) {
                 ctx = ssl_ctx_new(options, true);
             }
References net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >::onConstruct.
~SocketListener()
template<typename SocketT > net::socket::stream::tls::SocketListener< SocketT >::~SocketListener () inline override protected virtual
Reimplemented from net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >.
Definition at line 101 of file SocketListener.h.
{
                 ssl_ctx_free(ctx);
             }
References net::socket::stream::tls::SocketListener< SocketT >::ctx, and net::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
listen()
template<typename SocketT > void net::socket::stream::tls::SocketListener< SocketT >::listen (const SocketAddress & localAddress, int backlog, const std::function< void(int err)> & onError) inline override protected
Definition at line 105 of file SocketListener.h.
{
                 if (ctx == nullptr) {
                     errno = EINVAL;
                     onError(EINVAL);
                 } else {
                     stream::SocketListener<SocketConnection>::listen(localAddress, backlog, onError);
                 }
             }
References net::socket::stream::tls::SocketListener< SocketT >::ctx, and net::socket::stream::SocketListener< SocketConnectionT >::listen().
Referenced by net::socket::stream::SocketServer< tls::SocketListener< rfcomm::Socket > >::listen().
Friends And Related Function Documentation
stream::SocketServer
template<typename SocketT > template<typename SocketListener > friend class stream::SocketServer friend
Definition at line 120 of file SocketListener.h.
Member Data Documentation
ctx
template<typename SocketT > SSL_CTX* net::socket::stream::tls::SocketListener< SocketT >::ctx = nullptr private
Definition at line 115 of file SocketListener.h.
Referenced by net::socket::stream::tls::SocketListener< SocketT >::listen(), and net::socket::stream::tls::SocketListener< SocketT >::~SocketListener().
sslSessionCtxId
template<typename Socket > int net::socket::stream::tls::SocketListener< Socket >::sslSessionCtxId = 1 static private
Definition at line 117 of file SocketListener.h.
The documentation for this class was generated from the following file:
net/socket/sock_stream/tls/SocketListener.h