snode.c: net::socket::stream::tls::TLSHandshake Class Reference
net::socket::stream::tls::TLSHandshake Class Reference
#include <TLSHandshake.h>
Public Member Functions
TLSHandshake (SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int err)> &onError)
void readEvent () override
void writeEvent () override
void timeout () override
void unobserved () override
Public Member Functions inherited from net::ReadEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::EventReceiver
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Public Member Functions inherited from net::WriteEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Static Public Member Functions
static void doHandshake (SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int err)> &onError)
Private Attributes
SSL * ssl = nullptr
std::function< void(void)> onSuccess
std::function< void(void)> onTimeout
std::function< void(int err)> onError
int fd = -1
Additional Inherited Members
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver ()
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from net::WriteEventReceiver
WriteEventReceiver ()
void dispatchEvent () override
Protected Attributes inherited from net::EventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 34 of file TLSHandshake.h.
Constructor & Destructor Documentation
TLSHandshake()
net::socket::stream::tls::TLSHandshake::TLSHandshake (SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int err)> & onError)
Definition at line 33 of file TLSHandshake.cpp.
         : ssl(ssl)
         , onSuccess(onSuccess)
         , onTimeout(onTimeout)
         , onError(onError) {
         ReadEventReceiver::setTimeout(TLSHANDSHAKE_TIMEOUT);
         WriteEventReceiver::setTimeout(TLSHANDSHAKE_TIMEOUT);
         fd = SSL_get_fd(ssl);
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_get_error(ssl, ret);
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 ReadEventReceiver::enable(fd);
                 break;
             case SSL_ERROR_WANT_WRITE:
                 WriteEventReceiver::enable(fd);
                 break;
             case SSL_ERROR_NONE:
                 onSuccess();
                 delete this;
                 break;
             default:
                 onError(-sslErr);
                 delete this;
                 break;
         }
     }
References net::ReadEventReceiver::enable(), net::WriteEventReceiver::enable(), fd, onError, onSuccess, net::ReadEventReceiver::setTimeout(), net::WriteEventReceiver::setTimeout(), ssl, and TLSHANDSHAKE_TIMEOUT.
Referenced by doHandshake().
Member Function Documentation
doHandshake()
void net::socket::stream::tls::TLSHandshake::doHandshake (SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int err)> & onError) static
Definition at line 121 of file TLSHandshake.cpp.
{
         new TLSHandshake(ssl, onSuccess, onTimeout, onError);
     }
References onError, onSuccess, onTimeout, ssl, and TLSHandshake().
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read(), and net::socket::stream::tls::SocketWriter< SocketT >::write().
readEvent()
void net::socket::stream::tls::TLSHandshake::readEvent () override virtual
Implements net::ReadEventReceiver.
Definition at line 67 of file TLSHandshake.cpp.
{
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_get_error(ssl, ret);
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 break;
             case SSL_ERROR_WANT_WRITE:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::enable(fd);
                 break;
             case SSL_ERROR_NONE:
                 ReadEventReceiver::disable();
                 onSuccess();
                 break;
             default:
                 ReadEventReceiver::disable();
                 onError(-sslErr);
                 break;
         }
     }
References net::ReadEventReceiver::disable(), net::WriteEventReceiver::enable(), fd, onError, onSuccess, and ssl.
timeout()
void net::socket::stream::tls::TLSHandshake::timeout () override virtual
Reimplemented from net::EventReceiver.
Definition at line 111 of file TLSHandshake.cpp.
{
         ReadEventReceiver::suspend();
         WriteEventReceiver::suspend();
         onTimeout();
     }
References onTimeout, net::ReadEventReceiver::suspend(), and net::WriteEventReceiver::suspend().
unobserved()
void net::socket::stream::tls::TLSHandshake::unobserved () override virtual
Implements net::EventReceiver.
Definition at line 117 of file TLSHandshake.cpp.
{
         delete this;
     }
writeEvent()
void net::socket::stream::tls::TLSHandshake::writeEvent () override virtual
Implements net::WriteEventReceiver.
Definition at line 89 of file TLSHandshake.cpp.
{
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_get_error(ssl, ret);
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 WriteEventReceiver::disable();
                 ReadEventReceiver::enable(fd);
                 break;
             case SSL_ERROR_WANT_WRITE:
                 break;
             case SSL_ERROR_NONE:
                 WriteEventReceiver::disable();
                 onSuccess();
                 break;
             default:
                 WriteEventReceiver::disable();
                 onError(-sslErr);
                 break;
         }
     }
References net::WriteEventReceiver::disable(), net::ReadEventReceiver::enable(), fd, onError, onSuccess, and ssl.
Member Data Documentation
fd
int net::socket::stream::tls::TLSHandshake::fd = -1 private
Definition at line 59 of file TLSHandshake.h.
Referenced by readEvent(), TLSHandshake(), and writeEvent().
onError
std::function<void(int err)> net::socket::stream::tls::TLSHandshake::onError private
Definition at line 57 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
onSuccess
std::function<void(void)> net::socket::stream::tls::TLSHandshake::onSuccess private
Definition at line 55 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
onTimeout
std::function<void(void)> net::socket::stream::tls::TLSHandshake::onTimeout private
Definition at line 56 of file TLSHandshake.h.
Referenced by doHandshake(), and timeout().
ssl
SSL* net::socket::stream::tls::TLSHandshake::ssl = nullptr private
Definition at line 54 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
The documentation for this class was generated from the following files:
net/socket/sock_stream/tls/TLSHandshake.h
net/socket/sock_stream/tls/TLSHandshake.cpp