snode.c: web::ws::WSContext Class Reference
web::ws::WSContext Class Reference
#include <WSContext.h>
Static Public Attributes
static web::ws::subprotocol::WSSubProtocolSelector selector
Protected Member Functions
WSContext (web::ws::WSSubProtocol *wSSubProtocol, web::ws::WSSubProtocol::Role role)
virtual ~WSContext ()=default
Protected Member Functions inherited from net::socket::stream::SocketProtocol
SocketProtocol ()=default
virtual ~SocketProtocol ()=default
Protected Member Functions inherited from web::ws::WSReceiver
void begin ()
uint64_t readOpcode (char *junk, uint64_t junkLen)
uint64_t readLength (char *junk, uint64_t junkLen)
uint64_t readELength (char *junk, uint64_t junkLen)
uint64_t readMaskingKey (char *junk, uint64_t junkLen)
uint64_t readPayload (char *junk, uint64_t junkLen)
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Protected Member Functions inherited from web::ws::WSTransmitter
WSTransmitter (bool masking)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
Protected Attributes
web::ws::WSSubProtocol * wSSubProtocol
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
Protected Attributes inherited from web::ws::WSReceiver
enum web::ws::WSReceiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
Private Member Functions
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void replyPong (const char *reason=nullptr, std::size_t reasonLength=0)
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
void close (const char *reason, std::size_t reasonLength)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void onMessageStart (int opCode) override
void onFrameReceived (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onPongReceived ()
void onMessageError (uint16_t errnum) override
void onProtocolConnected () override
void onProtocolDisconnected () override
void sendFrameData (uint8_t data) override
void sendFrameData (uint16_t data) override
void sendFrameData (uint32_t data) override
void sendFrameData (uint64_t data) override
void sendFrameData (const char *frame, uint64_t frameLength) override
void onReceiveFromPeer (const char *junk, std::size_t junkLen) override
void onReadError (int errnum) override
void onWriteError (int errnum) override
Private Attributes
bool closeReceived = false
bool closeSent = false
bool pingReceived = false
bool pongReceived = false
std::string pongCloseData
Friends
class web::ws::WSSubProtocol
Additional Inherited Members
Public Member Functions inherited from net::socket::stream::SocketProtocol
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void close ()
void switchSocketProtocol (SocketProtocol *socketProtocol)
void setTimeout (int timeout)
Public Member Functions inherited from web::ws::WSReceiver
void receive (char *junk, std::size_t junkLen)
Protected Types inherited from web::ws::WSReceiver
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Detailed Description
Definition at line 41 of file WSContext.h.
Constructor & Destructor Documentation
WSContext()
web::ws::WSContext::WSContext (web::ws::WSSubProtocol * wSSubProtocol, web::ws::WSSubProtocol::Role role) protected
Definition at line 39 of file WSContext.cpp.
         : WSTransmitter(role == web::ws::WSSubProtocol::Role::CLIENT)
         , wSSubProtocol(wSSubProtocol) {
         wSSubProtocol->setWSContext(this);
     }
References web::ws::WSSubProtocol::setWSContext(), and wSSubProtocol.
~WSContext()
virtual web::ws::WSContext::~WSContext () protected virtual default
Reimplemented in web::ws::server::WSContext.
Member Function Documentation
close() [1/2]
void web::ws::WSContext::close (const char * reason, std::size_t reasonLength) private
Definition at line 168 of file WSContext.cpp.
{
         sendMessage(8, message, messageLength);
     }
References sendMessage().
close() [2/2]
void web::ws::WSContext::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 144 of file WSContext.cpp.
{
         char* closePayload = const_cast<char*>(reason);
         std::size_t closePayloadLength = reasonLength;
         if (statusCode != 0) {
             closePayload = new char[reasonLength + 2];
             *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
             closePayloadLength += 2;
             if (reasonLength > 0) {
                 memcpy(closePayload + 2, reason, reasonLength);
             }
         }
         close(closePayload, closePayloadLength);
         if (statusCode != 0) {
             delete[] closePayload;
         }
         setTimeout(CLOSE_SOCKET_TIMEOUT);
         closeSent = true;
     }
References net::socket::stream::SocketProtocol::close(), CLOSE_SOCKET_TIMEOUT, closeSent, and net::socket::stream::SocketProtocol::setTimeout().
Referenced by web::ws::WSSubProtocol::sendClose().
getLocalAddressAsString()
std::string web::ws::WSContext::getLocalAddressAsString () const private
Definition at line 221 of file WSContext.cpp.
{
         return SocketProtocol::getLocalAddressAsString();
     }
Referenced by web::ws::WSSubProtocol::getLocalAddressAsString().
getRemoteAddressAsString()
std::string web::ws::WSContext::getRemoteAddressAsString () const private
Definition at line 225 of file WSContext.cpp.
{
         return SocketProtocol::getLocalAddressAsString();
     }
Referenced by web::ws::WSSubProtocol::getRemoteAddressAsString().
onFrameReceived()
void web::ws::WSContext::onFrameReceived (const char * junk, uint64_t junkLen) override private virtual
Implements web::ws::WSReceiver.
Definition at line 79 of file WSContext.cpp.
{
         if (!closeReceived && !pingReceived && !pongReceived) {
             std::size_t junkOffset = 0;
             do {
                 std::size_t sendJunkLen = (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                 wSSubProtocol->onMessageData(junk + junkOffset, sendJunkLen);
                 junkOffset += sendJunkLen;
             } while (junkLen - junkOffset > 0);
         } else {
             pongCloseData += std::string(junk, static_cast<std::size_t>(junkLen));
         }
     }
References closeReceived, web::ws::WSSubProtocol::onMessageData(), pingReceived, pongCloseData, pongReceived, and wSSubProtocol.
onMessageEnd()
void web::ws::WSContext::onMessageEnd () override private virtual
Implements web::ws::WSReceiver.
Definition at line 93 of file WSContext.cpp.
{
         if (closeReceived) {
             closeReceived = false;
             if (closeSent) { // active close
                 closeSent = false;
                 VLOG(0) << "Close confirmed from peer";
             } else { // passive close
                 VLOG(0) << "Close request received - replying with close";
                 close(pongCloseData.data(), pongCloseData.length());
                 pongCloseData.clear();
             }
             socketConnection->getSocketProtocol()->close();
         } else if (pingReceived) {
             pingReceived = false;
             replyPong(pongCloseData.data(), pongCloseData.length());
             pongCloseData.clear();
         } else if (pongReceived) {
             pongReceived = false;
             wSSubProtocol->onPongReceived();
         } else {
             wSSubProtocol->onMessageEnd();
         }
     }
References net::socket::stream::SocketProtocol::close(), closeReceived, closeSent, net::socket::stream::SocketConnectionBase::getSocketProtocol(), web::ws::WSSubProtocol::onMessageEnd(), web::ws::WSSubProtocol::onPongReceived(), pingReceived, pongCloseData, pongReceived, replyPong(), net::socket::stream::SocketProtocol::socketConnection, and wSSubProtocol.
onMessageError()
void web::ws::WSContext::onMessageError (uint16_t errnum) override private virtual
Implements web::ws::WSReceiver.
Definition at line 121 of file WSContext.cpp.
{
         VLOG(0) << "Message Error";
         wSSubProtocol->onMessageError(errnum);
         close(errnum, "hallo", std::string("hallo").length());
     }
References net::socket::stream::SocketProtocol::close(), web::ws::WSReceiver::length, web::ws::WSSubProtocol::onMessageError(), and wSSubProtocol.
onMessageStart()
void web::ws::WSContext::onMessageStart (int opCode) override private virtual
Implements web::ws::WSReceiver.
Definition at line 61 of file WSContext.cpp.
{
         switch (opCode) {
             case 0x08:
                 closeReceived = true;
                 break;
             case 0x09:
                 pingReceived = true;
                 VLOG(0) << "Ping received";
                 break;
             case 0x0A:
                 pongReceived = true;
                 break;
             default:
                 wSSubProtocol->onMessageStart(opCode);
                 break;
         }
     }
References closeReceived, web::ws::WSSubProtocol::onMessageStart(), web::ws::WSReceiver::opCode, pingReceived, pongReceived, and wSSubProtocol.
onPongReceived()
void web::ws::WSContext::onPongReceived () private
Definition at line 117 of file WSContext.cpp.
{
         wSSubProtocol->onPongReceived();
     }
References web::ws::WSSubProtocol::onPongReceived(), and wSSubProtocol.
onProtocolConnected()
void web::ws::WSContext::onProtocolConnected () override private virtual
Reimplemented from net::socket::stream::SocketProtocol.
Definition at line 128 of file WSContext.cpp.
{
         wSSubProtocol->onProtocolConnected();
     }
References web::ws::WSSubProtocol::onProtocolConnected(), and wSSubProtocol.
onProtocolDisconnected()
void web::ws::WSContext::onProtocolDisconnected () override private virtual
Reimplemented from net::socket::stream::SocketProtocol.
Definition at line 132 of file WSContext.cpp.
{
         wSSubProtocol->onProtocolDisconnected();
     }
References web::ws::WSSubProtocol::onProtocolDisconnected(), and wSSubProtocol.
onReadError()
void web::ws::WSContext::onReadError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 213 of file WSContext.cpp.
{
         VLOG(0) << "OnReadError: " << errnum;
     }
onReceiveFromPeer()
void web::ws::WSContext::onReceiveFromPeer (const char * junk, std::size_t junkLen) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 209 of file WSContext.cpp.
{
         WSReceiver::receive(const_cast<char*>(junk), junkLen);
     }
References web::ws::WSReceiver::receive().
onWriteError()
void web::ws::WSContext::onWriteError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 217 of file WSContext.cpp.
{
         VLOG(0) << "OnWriteError: " << errnum;
     }
replyPong()
void web::ws::WSContext::replyPong (const char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 140 of file WSContext.cpp.
{
         sendMessage(10, reason, reasonLength);
     }
References sendMessage().
Referenced by onMessageEnd().
sendFrameData() [1/5]
void web::ws::WSContext::sendFrameData (const char * frame, uint64_t frameLength) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 196 of file WSContext.cpp.
{
         if (!closeSent) {
             std::size_t frameOffset = 0;
             do {
                 std::size_t sendJunkLen =
                     (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                 sendToPeer(frame + frameOffset, sendJunkLen);
                 frameOffset += sendJunkLen;
             } while (frameLength - frameOffset > 0);
         }
     }
References closeSent, and net::socket::stream::SocketProtocol::sendToPeer().
sendFrameData() [2/5]
void web::ws::WSContext::sendFrameData (uint16_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 178 of file WSContext.cpp.
{
         if (!closeSent) {
             sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint16_t));
         }
     }
References closeSent, and net::socket::stream::SocketProtocol::sendToPeer().
sendFrameData() [3/5]
void web::ws::WSContext::sendFrameData (uint32_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 184 of file WSContext.cpp.
{
         if (!closeSent) {
             sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint32_t));
         }
     }
References closeSent, and net::socket::stream::SocketProtocol::sendToPeer().
sendFrameData() [4/5]
void web::ws::WSContext::sendFrameData (uint64_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 190 of file WSContext.cpp.
{
         if (!closeSent) {
             sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint64_t));
         }
     }
References closeSent, and net::socket::stream::SocketProtocol::sendToPeer().
sendFrameData() [5/5]
void web::ws::WSContext::sendFrameData (uint8_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 172 of file WSContext.cpp.
{
         if (!closeSent) {
             sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
         }
     }
References closeSent, and net::socket::stream::SocketProtocol::sendToPeer().
sendMessage()
void web::ws::WSContext::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 57 of file WSContext.cpp.
{
         WSTransmitter::sendMessage(opCode, message, messageLength);
     }
References web::ws::WSReceiver::opCode, and web::ws::WSTransmitter::sendMessage().
Referenced by close(), replyPong(), web::ws::WSSubProtocol::sendMessage(), and sendPing().
sendMessageEnd()
void web::ws::WSContext::sendMessageEnd (const char * message, std::size_t messageLength) private
Definition at line 53 of file WSContext.cpp.
{
         WSTransmitter::sendMessageEnd(message, messageLength);
     }
References web::ws::WSTransmitter::sendMessageEnd().
Referenced by web::ws::WSSubProtocol::sendMessageEnd().
sendMessageFrame()
void web::ws::WSContext::sendMessageFrame (const char * message, std::size_t messageLength) private
Definition at line 49 of file WSContext.cpp.
{
         WSTransmitter::sendMessageFrame(message, messageLength);
     }
References web::ws::WSTransmitter::sendMessageFrame().
Referenced by web::ws::WSSubProtocol::sendMessageFrame().
sendMessageStart()
void web::ws::WSContext::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 45 of file WSContext.cpp.
{
         WSTransmitter::sendMessageStart(opCode, message, messageLength);
     }
References web::ws::WSReceiver::opCode, and web::ws::WSTransmitter::sendMessageStart().
Referenced by web::ws::WSSubProtocol::sendMessageStart().
sendPing()
void web::ws::WSContext::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 136 of file WSContext.cpp.
{
         sendMessage(9, reason, reasonLength);
     }
References sendMessage().
Referenced by web::ws::WSSubProtocol::sendPing().
Friends And Related Function Documentation
web::ws::WSSubProtocol
friend class web::ws::WSSubProtocol friend
Definition at line 102 of file WSContext.h.
Member Data Documentation
closeReceived
bool web::ws::WSContext::closeReceived = false private
Definition at line 93 of file WSContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
closeSent
bool web::ws::WSContext::closeSent = false private
Definition at line 94 of file WSContext.h.
Referenced by close(), onMessageEnd(), and sendFrameData().
pingReceived
bool web::ws::WSContext::pingReceived = false private
Definition at line 96 of file WSContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
pongCloseData
std::string web::ws::WSContext::pongCloseData private
Definition at line 99 of file WSContext.h.
Referenced by onFrameReceived(), and onMessageEnd().
pongReceived
bool web::ws::WSContext::pongReceived = false private
Definition at line 97 of file WSContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
selector
web::ws::subprotocol::WSSubProtocolSelector web::ws::WSContext::selector static
Definition at line 51 of file WSContext.h.
Referenced by web::ws::server::WSContext::create().
wSSubProtocol
web::ws::WSSubProtocol* web::ws::WSContext::wSSubProtocol protected
Definition at line 54 of file WSContext.h.
Referenced by web::ws::server::WSContext::create(), onFrameReceived(), onMessageEnd(), onMessageError(), onMessageStart(), onPongReceived(), onProtocolConnected(), onProtocolDisconnected(), and WSContext().
The documentation for this class was generated from the following files:
web/ws/WSContext.h
web/ws/WSContext.cpp