snode.c: FileReader Class Reference
FileReader Class Reference
#include <FileReader.h>
Public Member Functions
void disable () override
void readEvent () override
Public Member Functions inherited from net::ReadEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
~Descriptor ()
void open (int fd, FLAGS flags=FLAGS::none)
int getFd () const
bool dontClose () const
Static Public Member Functions
static FileReader * read (const std::string &path, const std::function< void(char *junk, int junkLen)> &junkRead, const std::function< void(int err)> &onError)
Protected Member Functions
FileReader (int fd, const std::function< void(char *junk, int junkLen)> &junkRead, const std::function< void(int err)> &onError)
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
virtual void timeoutEvent ()
Protected Member Functions inherited from net::Descriptor
Descriptor ()=default
Private Member Functions
void unobserved () override
Private Attributes
std::function< void(char *data, int len)> junkRead
std::function< void(int errnum)> onError
bool stopped
Additional Inherited Members
Public Types inherited from net::Descriptor
enum FLAGS : unsigned short { FLAGS::none = 0, FLAGS::dontClose = 0x01 << 0 }
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 32 of file FileReader.h.
Constructor & Destructor Documentation
FileReader()
FileReader::FileReader (int fd, const std::function< void(char *junk, int junkLen)> & junkRead, const std::function< void(int err)> & onError) protected
Definition at line 31 of file FileReader.cpp.
     : junkRead(junkRead)
     , onError(onError)
     , stopped(false) {
     open(fd);
     ReadEventReceiver::enable();
 }
References net::Descriptor::fd, and net::Descriptor::open().
Referenced by read().
Member Function Documentation
disable()
void FileReader::disable () override virtual
Implements net::EventReceiver.
Definition at line 55 of file FileReader.cpp.
{
     if (!stopped) {
         ReadEventReceiver::disable();
         onError(0);
         stopped = true;
     }
 }
References onError, and stopped.
Referenced by express::Response::~Response().
read()
FileReader * FileReader::read (const std::string & path, const std::function< void(char *junk, int junkLen)> & junkRead, const std::function< void(int err)> & onError) static
Definition at line 39 of file FileReader.cpp.
{
     FileReader* fileReader = nullptr;
     int fd = ::open(path.c_str(), O_RDONLY);
     if (fd >= 0) {
         fileReader = new FileReader(fd, junkRead, onError);
     } else {
         onError(errno);
     }
     return fileReader;
 }
References net::Descriptor::fd, FileReader(), junkRead, onError, and net::Descriptor::open().
Referenced by readEvent(), and express::Response::sendFile().
readEvent()
void FileReader::readEvent () override virtual
Implements net::ReadEventReceiver.
Definition at line 67 of file FileReader.cpp.
{
     // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, hicpp-avoid-c-arrays, modernize-avoid-c-arrays)
     static char junk[MFREADSIZE];
     int ret = ::read(getFd(), junk, MFREADSIZE);
     if (!stopped) {
         if (ret > 0) {
             junkRead(junk, ret);
         } else {
             stopped = true;
             ReadEventReceiver::disable();
             onError(ret == 0 ? 0 : errno);
         }
     }
 }
References net::Descriptor::getFd(), junkRead, MFREADSIZE, onError, read(), and stopped.
unobserved()
void FileReader::unobserved () override private virtual
Implements net::EventReceiver.
Definition at line 63 of file FileReader.cpp.
{
     delete this;
 }
Member Data Documentation
junkRead
std::function<void(char* data, int len)> FileReader::junkRead private
Definition at line 50 of file FileReader.h.
Referenced by read(), and readEvent().
onError
std::function<void(int errnum)> FileReader::onError private
Definition at line 52 of file FileReader.h.
Referenced by disable(), read(), and readEvent().
stopped
bool FileReader::stopped private
Definition at line 54 of file FileReader.h.
Referenced by disable(), and readEvent().
The documentation for this class was generated from the following files:
net/file/FileReader.h
net/file/FileReader.cpp