snode.c: net::DescriptorEventDispatcher Class Reference
net::DescriptorEventDispatcher Class Reference
#include <DescriptorEventDispatcher.h>
Classes
class EventReceiverList
Public Member Functions
DescriptorEventDispatcher (FdSet &fdSet, long maxInactivity)
DescriptorEventDispatcher (const DescriptorEventDispatcher &)=delete
DescriptorEventDispatcher & operator= (const DescriptorEventDispatcher &)=delete
void enable (EventReceiver *eventReceiver, int fd)
void disable (EventReceiver *eventReceiver, int fd)
void suspend (EventReceiver *eventReceiver, int fd)
void resume (EventReceiver *eventReceiver, int fd)
unsigned long getEventCounter () const
long getTimeout () const
Private Member Functions
int getMaxFd () const
struct timeval dispatchActiveEvents (struct timeval currentTime)
struct timeval observeEnabledEvents ()
void unobserveDisabledEvents ()
void releaseUnobservedEvents ()
void disableObservedEvents ()
Private Attributes
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
EventReceiverList unobservedEventReceiver
FdSet & fdSet
long maxInactivity
unsigned long eventCounter = 0
Friends
class EventLoop
Detailed Description
Definition at line 41 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
DescriptorEventDispatcher() [1/2]
net::DescriptorEventDispatcher::DescriptorEventDispatcher (FdSet & fdSet, long maxInactivity) explicit
Definition at line 36 of file DescriptorEventDispatcher.cpp.
         : fdSet(fdSet)
         , maxInactivity(maxInactivity) {
     }
DescriptorEventDispatcher() [2/2]
net::DescriptorEventDispatcher::DescriptorEventDispatcher (const DescriptorEventDispatcher &) delete
Member Function Documentation
disable()
void net::DescriptorEventDispatcher::disable (EventReceiver * eventReceiver, int fd)
Definition at line 58 of file DescriptorEventDispatcher.cpp.
{
         if (enabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as enable
             enabledEventReceiver[fd].remove(eventReceiver);
             eventReceiver->disabled();
             if (eventReceiver->observationCounter == 0) {
                 unobservedEventReceiver.push_back(eventReceiver);
             }
         } else if (eventReceiver->isEnabled() &&
                    (!disabledEventReceiver.contains(fd) || !disabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as enable
             disabledEventReceiver[fd].push_back(eventReceiver);
         } else {
             LOG(WARNING) << "EventReceiver double disable";
         }
     }
References net::EventReceiver::disabled(), disabledEventReceiver, enabledEventReceiver, net::EventReceiver::isEnabled(), net::ObservationCounter::observationCounter, and unobservedEventReceiver.
Referenced by net::AcceptEventReceiver::disable(), net::ConnectEventReceiver::disable(), net::OutOfBandEventReceiver::disable(), net::ReadEventReceiver::disable(), and net::WriteEventReceiver::disable().
disableObservedEvents()
void net::DescriptorEventDispatcher::disableObservedEvents () private
Definition at line 193 of file DescriptorEventDispatcher.cpp.
{
         for (auto& [fd, eventReceivers] : observedEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 disabledEventReceiver[fd].push_back(eventReceiver);
             }
         }
     }
References disabledEventReceiver, and observedEventReceiver.
Referenced by net::EventLoop::start().
dispatchActiveEvents()
struct timeval net::DescriptorEventDispatcher::dispatchActiveEvents (struct timeval currentTime) private
Definition at line 105 of file DescriptorEventDispatcher.cpp.
{
         struct timeval nextInactivityTimeout {
             LONG_MAX, 0
         };
         for (const auto& [fd, eventReceivers] : observedEventReceiver) {
             EventReceiver* eventReceiver = eventReceivers.front();
             struct timeval maxInactivity = eventReceiver->getTimeout();
             if (fdSet.isSet(fd)) {
                 eventCounter++;
                 eventReceiver->dispatchEvent();
                 eventReceiver->triggered(currentTime);
                 nextInactivityTimeout = std::min(nextInactivityTimeout, maxInactivity);
             } else {
                 struct timeval inactivity = currentTime - eventReceiver->getLastTriggered();
                 if (inactivity >= maxInactivity) {
                     eventReceiver->timeout();
                     eventReceiver->disable();
                 } else {
                     nextInactivityTimeout = std::min(maxInactivity - inactivity, nextInactivityTimeout);
                 }
             }
         }
         return nextInactivityTimeout;
     }
References observedEventReceiver.
Referenced by net::EventLoop::tick().
enable()
void net::DescriptorEventDispatcher::enable (EventReceiver * eventReceiver, int fd)
Definition at line 41 of file DescriptorEventDispatcher.cpp.
{
         if (disabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as disable
             disabledEventReceiver[fd].remove(eventReceiver);
         } else if (!eventReceiver->isEnabled() &&
                    (!enabledEventReceiver.contains(fd) || !enabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as disable
             enabledEventReceiver[fd].push_back(eventReceiver);
             eventReceiver->enabled(fd);
             if (unobservedEventReceiver.contains(eventReceiver)) {
                 unobservedEventReceiver.remove(eventReceiver);
             }
         } else {
             LOG(WARNING) << "EventReceiver double enable";
         }
     }
References net::DescriptorEventDispatcher::EventReceiverList::contains(), disabledEventReceiver, net::EventReceiver::enabled(), enabledEventReceiver, net::EventReceiver::isEnabled(), and unobservedEventReceiver.
Referenced by net::AcceptEventReceiver::enable(), net::ConnectEventReceiver::enable(), net::OutOfBandEventReceiver::enable(), net::ReadEventReceiver::enable(), and net::WriteEventReceiver::enable().
getEventCounter()
unsigned long net::DescriptorEventDispatcher::getEventCounter () const
Definition at line 101 of file DescriptorEventDispatcher.cpp.
{
         return eventCounter;
     }
References eventCounter.
Referenced by net::EventLoop::getEventCounter().
getMaxFd()
int net::DescriptorEventDispatcher::getMaxFd () const private
Definition at line 105 of file DescriptorEventDispatcher.cpp.
{
         int maxFd = -1;
         if (!observedEventReceiver.empty()) {
             maxFd = observedEventReceiver.rbegin()->first;
         }
         return maxFd;
     }
Referenced by net::EventLoop::tick().
getTimeout()
long net::DescriptorEventDispatcher::getTimeout () const
Definition at line 97 of file DescriptorEventDispatcher.cpp.
{
         return maxInactivity;
     }
References maxInactivity.
observeEnabledEvents()
struct timeval net::DescriptorEventDispatcher::observeEnabledEvents () private
Definition at line 105 of file DescriptorEventDispatcher.cpp.
{
         struct timeval nextTimeout = {LONG_MAX, 0};
         for (auto [fd, eventReceivers] : enabledEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 observedEventReceiver[fd].push_front(eventReceiver);
                 if (!eventReceiver->isSuspended()) {
                     fdSet.set(fd);
                     nextTimeout = std::min(nextTimeout, eventReceiver->getTimeout());
                 } else {
                     fdSet.clr(fd, true);
                 }
             }
         }
         enabledEventReceiver.clear();
         fdSet.prepare();
         return nextTimeout;
     }
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
operator=()
DescriptorEventDispatcher& net::DescriptorEventDispatcher::operator= (const DescriptorEventDispatcher &) delete
releaseUnobservedEvents()
void net::DescriptorEventDispatcher::releaseUnobservedEvents () private
Definition at line 186 of file DescriptorEventDispatcher.cpp.
{
         for (EventReceiver* eventReceiver : unobservedEventReceiver) {
             eventReceiver->unobserved();
         }
         unobservedEventReceiver.clear();
     }
References unobservedEventReceiver.
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
resume()
void net::DescriptorEventDispatcher::resume (EventReceiver * eventReceiver, int fd)
Definition at line 86 of file DescriptorEventDispatcher.cpp.
{
         if (eventReceiver->isSuspended()) {
             eventReceiver->resumed();
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 fdSet.set(fd);
             }
         } else {
             LOG(WARNING) << "EventReceiver double resume";
         }
     }
References fdSet, net::EventReceiver::isSuspended(), observedEventReceiver, net::EventReceiver::resumed(), and net::FdSet::set().
Referenced by net::AcceptEventReceiver::resume(), net::ConnectEventReceiver::resume(), net::OutOfBandEventReceiver::resume(), net::ReadEventReceiver::resume(), and net::WriteEventReceiver::resume().
suspend()
void net::DescriptorEventDispatcher::suspend (EventReceiver * eventReceiver, int fd)
Definition at line 75 of file DescriptorEventDispatcher.cpp.
{
         if (!eventReceiver->isSuspended()) {
             eventReceiver->suspended();
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 fdSet.clr(fd, true);
             }
         } else {
             LOG(WARNING) << "EventReceiver double suspend";
         }
     }
References net::FdSet::clr(), fdSet, net::EventReceiver::isSuspended(), observedEventReceiver, and net::EventReceiver::suspended().
Referenced by net::AcceptEventReceiver::suspend(), net::ConnectEventReceiver::suspend(), net::OutOfBandEventReceiver::suspend(), net::ReadEventReceiver::suspend(), and net::WriteEventReceiver::suspend().
unobserveDisabledEvents()
void net::DescriptorEventDispatcher::unobserveDisabledEvents () private
Definition at line 163 of file DescriptorEventDispatcher.cpp.
{
         for (auto [fd, eventReceivers] : disabledEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 observedEventReceiver[fd].remove(eventReceiver);
                 if (observedEventReceiver[fd].empty() || observedEventReceiver[fd].front()->isSuspended()) {
                     if (observedEventReceiver[fd].empty()) {
                         observedEventReceiver.erase(fd);
                     }
                     fdSet.clr(fd, true);
                 } else {
                     fdSet.set(fd);
                     observedEventReceiver[fd].front()->triggered();
                 }
                 eventReceiver->disabled();
                 if (eventReceiver->observationCounter == 0) {
                     unobservedEventReceiver.push_back(eventReceiver);
                 }
                 eventReceiver->fd = -1;
             }
         }
         disabledEventReceiver.clear();
     }
References net::FdSet::clr(), disabledEventReceiver, fdSet, observedEventReceiver, net::FdSet::set(), and unobservedEventReceiver.
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
Friends And Related Function Documentation
EventLoop
friend class EventLoop friend
Definition at line 88 of file DescriptorEventDispatcher.h.
Member Data Documentation
disabledEventReceiver
std::map<int, EventReceiverList> net::DescriptorEventDispatcher::disabledEventReceiver private
Definition at line 79 of file DescriptorEventDispatcher.h.
Referenced by disable(), disableObservedEvents(), enable(), and unobserveDisabledEvents().
enabledEventReceiver
std::map<int, EventReceiverList> net::DescriptorEventDispatcher::enabledEventReceiver private
Definition at line 77 of file DescriptorEventDispatcher.h.
Referenced by disable(), and enable().
eventCounter
unsigned long net::DescriptorEventDispatcher::eventCounter = 0 private
Definition at line 86 of file DescriptorEventDispatcher.h.
Referenced by getEventCounter().
fdSet
FdSet& net::DescriptorEventDispatcher::fdSet private
Definition at line 82 of file DescriptorEventDispatcher.h.
Referenced by resume(), suspend(), and unobserveDisabledEvents().
maxInactivity
long net::DescriptorEventDispatcher::maxInactivity private
Definition at line 84 of file DescriptorEventDispatcher.h.
Referenced by getTimeout().
observedEventReceiver
std::map<int, EventReceiverList> net::DescriptorEventDispatcher::observedEventReceiver private
Definition at line 78 of file DescriptorEventDispatcher.h.
Referenced by disableObservedEvents(), dispatchActiveEvents(), resume(), suspend(), and unobserveDisabledEvents().
unobservedEventReceiver
EventReceiverList net::DescriptorEventDispatcher::unobservedEventReceiver private
Definition at line 80 of file DescriptorEventDispatcher.h.
Referenced by disable(), enable(), releaseUnobservedEvents(), and unobserveDisabledEvents().
The documentation for this class was generated from the following files:
net/DescriptorEventDispatcher.h
net/DescriptorEventDispatcher.cpp