snode.c: web::ws::server::SocketContextUpgradeFactory Class Reference
web::ws::server::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Member Functions
SocketContextUpgradeFactory ()
~SocketContextUpgradeFactory ()
std::string name () override
std::string type () override
Public Member Functions inherited from web::http::server::SocketContextUpgradeFactory
void prepare (web::http::server::Request &request, web::http::server::Response &response)
Private Member Functions
web::ws::server::SocketContext * create (net::socket::stream::SocketConnectionBase *socketConnection) const override
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Protected Attributes inherited from web::http::server::SocketContextUpgradeFactory
web::http::server::Request * request
web::http::server::Response * response
Detailed Description
Definition at line 16 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory()
web::ws::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory ()
Definition at line 39 of file SocketContextUpgradeFactory.cpp.
{
         web::ws::server::SubProtocolSelector::instance()->loadSubProtocols();
     }
References web::ws::server::SubProtocolSelector::instance().
~SocketContextUpgradeFactory()
web::ws::server::SocketContextUpgradeFactory::~SocketContextUpgradeFactory ()
Definition at line 43 of file SocketContextUpgradeFactory.cpp.
{
         web::ws::server::SubProtocolSelector::instance()->unloadSubProtocols();
     }
References web::ws::server::SubProtocolSelector::instance().
Member Function Documentation
create()
web::ws::server::SocketContext * web::ws::server::SocketContextUpgradeFactory::create (net::socket::stream::SocketConnectionBase * socketConnection) const override private virtual
Implements net::socket::stream::SocketContextFactory.
Definition at line 55 of file SocketContextUpgradeFactory.cpp.
{
         return web::ws::server::SocketContext::create(socketConnection, *request, *response);
     }
References web::ws::server::SocketContext::create(), web::http::server::SocketContextUpgradeFactory::request, and web::http::server::SocketContextUpgradeFactory::response.
name()
std::string web::ws::server::SocketContextUpgradeFactory::name () override virtual
Implements web::http::server::SocketContextUpgradeFactory.
Definition at line 47 of file SocketContextUpgradeFactory.cpp.
{
         return "websocket";
     }
type()
std::string web::ws::server::SocketContextUpgradeFactory::type () override virtual
Implements web::http::server::SocketContextUpgradeFactory.
Definition at line 51 of file SocketContextUpgradeFactory.cpp.
{
         return "server";
     }
The documentation for this class was generated from the following files:
web/ws/server/SocketContextUpgradeFactory.h
web/ws/server/SocketContextUpgradeFactory.cpp