snode.c: http::Response Class Reference
http::Response Class Reference
#include <Response.h>
Public Member Functions
void send (const char *buffer, std::size_t size)
void send (const std::string &text)
void end ()
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=false)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=false)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & type (const std::string &type)
Public Member Functions inherited from net::stream::Sink
Sink ()
virtual ~Sink ()
void connect (Source &source)
void disconnect (Source &source)
Protected Member Functions
Response (ServerContextBase *serverContext)
void enqueue (const char *buf, std::size_t len)
void enqueue (const std::string &str)
void sendHeader ()
void receive (const char *junk, std::size_t junkLen) override
void eof () override
void error (int errnum) override
virtual void reset ()
Protected Attributes
ServerContextBase * serverContext
ConnectionState connectionState = ConnectionState::Default
bool sendHeaderInProgress = false
bool headersSent = false
int responseStatus = 200
std::size_t contentSent = 0
std::size_t contentLength = 0
std::map< std::string, std::string > headers
std::map< std::string, CookieOptions > cookies
Protected Attributes inherited from net::stream::Sink
Source * source
Friends
template<typename Request , typename Response >
class ServerContext
Detailed Description
Definition at line 40 of file Response.h.
Constructor & Destructor Documentation
Response()
http::Response::Response (ServerContextBase * serverContext) explicit protected
Definition at line 35 of file Response.cpp.
         : serverContext(serverContext) {
     }
Member Function Documentation
append()
Response & http::Response::append (const std::string & field, const std::string & value)
Definition at line 69 of file Response.cpp.
{
         std::map<std::string, std::string>::iterator it = headers.find(field);
         if (it != headers.end()) {
             it->second += ", " + value;
         } else {
             set(field, value);
         }
         return *this;
     }
References headers, and set().
clearCookie()
Response & http::Response::clearCookie (const std::string & name, const std::map< std::string, std::string > & options = {})
Definition at line 119 of file Response.cpp.
{
         std::map<std::string, std::string> opts = options;
         opts.erase("Max-Age");
         time_t time = 0;
         opts["Expires"] = httputils::to_http_date(gmtime(&time));
         cookie(name, "", opts);
         return *this;
     }
References cookie(), and httputils::to_http_date().
cookie()
Response & http::Response::cookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 113 of file Response.cpp.
{
         cookies.insert({name, CookieOptions(value, options)});
         return *this;
     }
References cookies.
Referenced by clearCookie(), and sendHeader().
end()
void http::Response::end ()
Definition at line 177 of file Response.cpp.
{
         send("");
     }
References send().
Referenced by express::Response::redirect(), and express::Response::sendFile().
enqueue() [1/2]
void http::Response::enqueue (const char * buf, std::size_t len) protected
Definition at line 39 of file Response.cpp.
{
         if (!headersSent && !sendHeaderInProgress) {
             sendHeaderInProgress = true;
             sendHeader();
             sendHeaderInProgress = false;
             headersSent = true;
         }
         serverContext->sendResponseData(buf, len);
         if (headersSent) {
             contentSent += len;
             if (contentSent == contentLength) {
                 serverContext->responseCompleted();
             } else if (contentSent > contentLength) {
                 serverContext->terminateConnection();
             }
         }
     }
References contentLength, contentSent, headersSent, http::ServerContextBase::responseCompleted(), sendHeader(), sendHeaderInProgress, http::ServerContextBase::sendResponseData(), serverContext, and http::ServerContextBase::terminateConnection().
Referenced by enqueue(), receive(), send(), and sendHeader().
enqueue() [2/2]
void http::Response::enqueue (const std::string & str) protected
Definition at line 59 of file Response.cpp.
{
         enqueue(str.c_str(), str.size());
     }
References enqueue().
eof()
void http::Response::eof () override protected virtual
Implements net::stream::Sink.
Definition at line 185 of file Response.cpp.
{
         LOG(INFO) << "Stream EOF";
     }
error()
void http::Response::error (int errnum) override protected virtual
Implements net::stream::Sink.
Definition at line 189 of file Response.cpp.
{
         PLOG(ERROR) << "Stream error: ";
         serverContext->terminateConnection();
     }
References serverContext, and http::ServerContextBase::terminateConnection().
receive()
void http::Response::receive (const char * junk, std::size_t junkLen) override protected virtual
Implements net::stream::Sink.
Definition at line 181 of file Response.cpp.
{
         enqueue(junk, junkLen);
     }
References enqueue().
reset()
void http::Response::reset () protected virtual
Reimplemented in express::Response.
Definition at line 194 of file Response.cpp.
{
         headersSent = false;
         sendHeaderInProgress = false;
         contentSent = 0;
         responseStatus = 200;
         contentLength = 0;
         connectionState = ConnectionState::Default;
         headers.clear();
         cookies.clear();
     }
References connectionState, contentLength, contentSent, cookies, Default, headers, headersSent, responseStatus, and sendHeaderInProgress.
Referenced by express::Response::reset().
send() [1/2]
void http::Response::send (const char * buffer, std::size_t size)
Definition at line 131 of file Response.cpp.
{
         if (size > 0) {
             headers.insert({"Content-Type", "application/octet-stream"});
         }
         headers.insert_or_assign("Content-Length", std::to_string(size));
         enqueue(buffer, size);
     }
References enqueue(), and headers.
Referenced by end(), send(), and express::Response::sendStatus().
send() [2/2]
void http::Response::send (const std::string & text)
Definition at line 140 of file Response.cpp.
{
         if (text.size() > 0) {
             headers.insert({"Content-Type", "text/html; charset=utf-8"});
         }
         send(text.c_str(), text.size());
     }
References headers, and send().
sendHeader()
void http::Response::sendHeader () protected
Definition at line 147 of file Response.cpp.
{
         enqueue("HTTP/1.1 " + std::to_string(responseStatus) + " " + StatusCode::reason(responseStatus) + "\r\n");
         enqueue("Date: " + httputils::to_http_date() + "\r\n");
         headers.insert({{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}});
         for (auto& [field, value] : headers) {
             enqueue(field + ": " + value + "\r\n");
         }
         for (auto& [cookie, cookieValue] : cookies) {
             std::string cookieString =
                 std::accumulate(cookieValue.getOptions().begin(),
                                 cookieValue.getOptions().end(),
                                 cookie + "=" + cookieValue.getValue(),
                                 [](const std::string& str, const std::pair<const std::string&, const std::string&> option) -> std::string {
                                     return str + "; " + option.first + (!option.second.empty() ? "=" + option.second : "");
                                 });
             enqueue("Set-Cookie: " + cookieString + "\r\n");
         }
         enqueue("\r\n");
         if (headers.find("Content-Length") != headers.end()) {
             contentLength = std::stoi(headers.find("Content-Length")->second);
         } else {
             contentLength = 0;
         }
     }
References contentLength, cookie(), cookies, enqueue(), headers, StatusCode::reason(), responseStatus, and httputils::to_http_date().
Referenced by enqueue().
set() [1/2]
Response & http::Response::set (const std::map< std::string, std::string > & headers, bool overwrite = false)
Definition at line 81 of file Response.cpp.
{
         for (auto& [field, value] : headers) {
             set(field, value, overwrite);
         }
         return *this;
     }
References headers, and set().
set() [2/2]
Response & http::Response::set (const std::string & field, const std::string & value, bool overwrite = false)
Definition at line 89 of file Response.cpp.
{
         if (overwrite) {
             headers.insert_or_assign(field, value);
         } else {
             headers.insert({field, value});
         }
         if (field == "Content-Length") {
             contentLength = std::stol(value);
         } else if (field == "Connection" && httputils::ci_comp(value, "close")) {
             connectionState = ConnectionState::Close;
         } else if (field == "Connection" && httputils::ci_comp(value, "keep-alive")) {
             connectionState = ConnectionState::Keep;
         }
         return *this;
     }
References httputils::ci_comp(), Close, connectionState, contentLength, headers, and Keep.
Referenced by append(), express::Response::download(), express::Response::redirect(), set(), and type().
status()
Response & http::Response::status (int status)
Definition at line 63 of file Response.cpp.
{
         responseStatus = status;
         return *this;
     }
References responseStatus.
Referenced by express::Response::redirect(), and express::Response::sendStatus().
type()
Response & http::Response::type (const std::string & type)
Definition at line 107 of file Response.cpp.
{
         set({{"Content-Type", type}});
         return *this;
     }
References set().
Friends And Related Function Documentation
ServerContext
template<typename Request , typename Response > friend class ServerContext friend
Definition at line 85 of file Response.h.
Member Data Documentation
connectionState
ConnectionState http::Response::connectionState = ConnectionState::Default protected
Definition at line 61 of file Response.h.
Referenced by reset(), and set().
contentLength
std::size_t http::Response::contentLength = 0 protected
Definition at line 69 of file Response.h.
Referenced by enqueue(), reset(), sendHeader(), and set().
contentSent
std::size_t http::Response::contentSent = 0 protected
Definition at line 68 of file Response.h.
Referenced by enqueue(), and reset().
cookies
std::map<std::string, CookieOptions> http::Response::cookies protected
Definition at line 82 of file Response.h.
Referenced by cookie(), reset(), and sendHeader().
headers
std::map<std::string, std::string> http::Response::headers protected
Definition at line 81 of file Response.h.
Referenced by append(), reset(), send(), express::Response::sendFile(), sendHeader(), and set().
headersSent
bool http::Response::headersSent = false protected
Definition at line 64 of file Response.h.
Referenced by enqueue(), and reset().
responseStatus
int http::Response::responseStatus = 200 protected
Definition at line 66 of file Response.h.
Referenced by reset(), express::Response::sendFile(), sendHeader(), and status().
sendHeaderInProgress
bool http::Response::sendHeaderInProgress = false protected
Definition at line 63 of file Response.h.
Referenced by enqueue(), and reset().
serverContext
ServerContextBase* http::Response::serverContext protected
Definition at line 59 of file Response.h.
Referenced by enqueue(), error(), and express::Response::sendFile().
The documentation for this class was generated from the following files:
http/Response.h
http/Response.cpp