snode.c: web::ws::server::SubProtocol Class Reference
web::ws::server::SubProtocol Class Reference abstract
#include <SubProtocol.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Types inherited from web::ws::SubProtocol
enum class Role { SERVER , CLIENT }
Public Member Functions
virtual ~SubProtocol ()
void sendBroadcast (const char *message, std::size_t messageLength)
void sendBroadcast (const std::string &message)
void sendBroadcastStart (const char *message, std::size_t messageLength)
void sendBroadcastStart (const std::string &message)
void sendBroadcastFrame (const char *message, std::size_t messageLength)
void sendBroadcastFrame (const std::string &message)
void sendBroadcastEnd (const char *message, std::size_t messageLength)
void sendBroadcastEnd (const std::string &message)
void forEachClient (const std::function< void(SubProtocol *)> &forEachClient)
Public Member Functions inherited from web::ws::SubProtocol
void sendMessage (const char *message, std::size_t messageLength)
void sendMessage (const std::string &message)
void sendMessageStart (const char *message, std::size_t messageLength)
void sendMessageStart (const std::string &message)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageFrame (const std::string &message)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessageEnd (const std::string &message)
void sendPing (char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
const std::string & getName ()
void setWSContext (SocketContext *ServerContext)
Protected Member Functions
SubProtocol (const std::string &name)
SubProtocol ()=delete
SubProtocol (const SubProtocol &)=delete
SubProtocol & operator= (const SubProtocol &)=delete
Protected Member Functions inherited from web::ws::SubProtocol
SubProtocol (const std::string &name)
SubProtocol ()=delete
SubProtocol (const SubProtocol &)=delete
SubProtocol & operator= (const SubProtocol &)=delete
Private Member Functions
void onMessageStart (int opCode) override=0
void onMessageData (const char *junk, std::size_t junkLen) override=0
void onMessageEnd () override=0
void onPongReceived () override=0
void onMessageError (uint16_t errnum) override=0
void onProtocolConnected () override=0
void onProtocolDisconnected () override=0
void sendBroadcast (uint8_t opCode, const char *message, std::size_t messageLength)
void sendBroadcastStart (uint8_t opCode, const char *message, std::size_t messageLength)
void setClients (std::shared_ptr< std::list< web::ws::server::SubProtocol * >> clients)
Private Attributes
std::shared_ptr< std::list< web::ws::server::SubProtocol * > > clients
Friends
class web::ws::server::SocketContext
Additional Inherited Members
Protected Attributes inherited from web::ws::SubProtocol
SocketContext * context
const std::string name
Detailed Description
Definition at line 41 of file SubProtocol.h.
Member Enumeration Documentation
Role
enum web::ws::server::SubProtocol::Role strong
Enumerator
SERVER
CLIENT
Definition at line 43 of file SubProtocol.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
SubProtocol() [1/3]
web::ws::server::SubProtocol::SubProtocol (const std::string & name) protected
Definition at line 29 of file SubProtocol.cpp.
         : web::ws::SubProtocol(name) {
     }
SubProtocol() [2/3]
web::ws::server::SubProtocol::SubProtocol () protected delete
SubProtocol() [3/3]
web::ws::server::SubProtocol::SubProtocol (const SubProtocol &) protected delete
~SubProtocol()
web::ws::server::SubProtocol::~SubProtocol () virtual
Reimplemented from web::ws::SubProtocol.
Definition at line 33 of file SubProtocol.cpp.
{
         clients->remove(this);
     }
References clients.
Member Function Documentation
forEachClient()
void web::ws::server::SubProtocol::forEachClient (const std::function< void(SubProtocol *)> & forEachClient)
Definition at line 72 of file SubProtocol.cpp.
{
         for (SubProtocol* client : *clients) {
             forEachClient(client);
         }
     }
References clients.
onMessageData()
void web::ws::server::SubProtocol::onMessageData (const char * junk, std::size_t junkLen) override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onMessageEnd()
void web::ws::server::SubProtocol::onMessageEnd () override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onMessageError()
void web::ws::server::SubProtocol::onMessageError (uint16_t errnum) override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onMessageStart()
void web::ws::server::SubProtocol::onMessageStart (int opCode) override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onPongReceived()
void web::ws::server::SubProtocol::onPongReceived () override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onProtocolConnected()
void web::ws::server::SubProtocol::onProtocolConnected () override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
onProtocolDisconnected()
void web::ws::server::SubProtocol::onProtocolDisconnected () override private pure virtual
Implements web::ws::SubProtocol.
Implemented in web::ws::subprotocol::echo::server::Echo.
operator=()
SubProtocol& web::ws::server::SubProtocol::operator= (const SubProtocol &) protected delete
sendBroadcast() [1/3]
void web::ws::server::SubProtocol::sendBroadcast (const char * message, std::size_t messageLength)
Definition at line 41 of file SubProtocol.cpp.
{
         sendBroadcast(2, message, messageLength);
     }
Referenced by sendBroadcast().
sendBroadcast() [2/3]
void web::ws::server::SubProtocol::sendBroadcast (const std::string & message)
Definition at line 37 of file SubProtocol.cpp.
{
         sendBroadcast(1, message.data(), message.length());
     }
References sendBroadcast().
sendBroadcast() [3/3]
void web::ws::server::SubProtocol::sendBroadcast (uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 79 of file SubProtocol.cpp.
{
         for (SubProtocol* client : *clients) {
             client->context->sendMessage(opCode, message, messageLength);
         }
     }
References clients.
sendBroadcastEnd() [1/2]
void web::ws::server::SubProtocol::sendBroadcastEnd (const char * message, std::size_t messageLength)
Definition at line 62 of file SubProtocol.cpp.
{
         for (SubProtocol* client : *clients) {
             client->sendMessageEnd(message, messageLength);
         }
     }
References clients.
Referenced by sendBroadcastEnd().
sendBroadcastEnd() [2/2]
void web::ws::server::SubProtocol::sendBroadcastEnd (const std::string & message)
Definition at line 68 of file SubProtocol.cpp.
{
         sendBroadcastEnd(message.data(), message.length());
     }
References sendBroadcastEnd().
sendBroadcastFrame() [1/2]
void web::ws::server::SubProtocol::sendBroadcastFrame (const char * message, std::size_t messageLength)
Definition at line 52 of file SubProtocol.cpp.
{
         for (SubProtocol* client : *clients) {
             client->sendMessageFrame(message, messageLength);
         }
     }
References clients.
Referenced by sendBroadcastFrame().
sendBroadcastFrame() [2/2]
void web::ws::server::SubProtocol::sendBroadcastFrame (const std::string & message)
Definition at line 58 of file SubProtocol.cpp.
{
         sendBroadcastFrame(message.data(), message.length());
     }
References sendBroadcastFrame().
sendBroadcastStart() [1/3]
void web::ws::server::SubProtocol::sendBroadcastStart (const char * message, std::size_t messageLength)
Definition at line 45 of file SubProtocol.cpp.
{
         sendBroadcastStart(2, message, messageLength);
     }
Referenced by sendBroadcastStart().
sendBroadcastStart() [2/3]
void web::ws::server::SubProtocol::sendBroadcastStart (const std::string & message)
Definition at line 48 of file SubProtocol.cpp.
{
         sendBroadcastStart(1, message.data(), message.length());
     }
References sendBroadcastStart().
sendBroadcastStart() [3/3]
void web::ws::server::SubProtocol::sendBroadcastStart (uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 85 of file SubProtocol.cpp.
{
         for (SubProtocol* client : *clients) {
             client->context->sendMessageStart(opCode, message, messageLength);
         }
     }
References clients.
setClients()
void web::ws::server::SubProtocol::setClients (std::shared_ptr< std::list< web::ws::server::SubProtocol * >> clients) private
Definition at line 91 of file SubProtocol.cpp.
{
         this->clients = clients;
         clients->push_back(this);
     }
References clients.
Friends And Related Function Documentation
web::ws::server::SocketContext
friend class web::ws::server::SocketContext friend
Definition at line 100 of file SubProtocol.h.
Member Data Documentation
clients
std::shared_ptr<std::list<web::ws::server::SubProtocol*> > web::ws::server::SubProtocol::clients private
Definition at line 98 of file SubProtocol.h.
Referenced by forEachClient(), sendBroadcast(), sendBroadcastEnd(), sendBroadcastFrame(), sendBroadcastStart(), setClients(), and ~SubProtocol().
The documentation for this class was generated from the following files:
web/ws/server/SubProtocol.h
web/ws/server/SubProtocol.cpp