snode.c: net::socket::stream::tls::SocketWriter< SocketT > Class Template Reference
net::socket::stream::tls::SocketWriter< SocketT > Class Template Reference
#include <SocketWriter.h>
Protected Types
using Socket = SocketT
Protected Member Functions
ssize_t write (const char *junk, size_t junkLen) override
Protected Member Functions inherited from net::WriteEventReceiver
WriteEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
Protected Attributes
SSL * ssl = nullptr
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
time_t lastTriggered = 0
Additional Inherited Members
Public Types inherited from net::socket::stream::SocketWriter< SocketT >
using Socket = SocketT
Public Member Functions inherited from net::socket::stream::SocketWriter< SocketT >
SocketWriter ()=delete
SocketWriter (const std::function< void(int errnum)> &onError)
~SocketWriter () override
void writeEvent () override
void enqueue (const char *junk, size_t junkLen)
Public Member Functions inherited from net::WriteEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketWriter< SocketT >
Definition at line 40 of file SocketWriter.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::tls::SocketWriter< SocketT >::Socket = SocketT protected
Definition at line 42 of file SocketWriter.h.
Member Function Documentation
write()
template<typename SocketT > ssize_t net::socket::stream::tls::SocketWriter< SocketT >::write (const char * junk, size_t junkLen) inline override protected virtual
Implements net::socket::stream::SocketWriter< SocketT >.
Definition at line 46 of file SocketWriter.h.
{
             int ret = ::SSL_write(ssl, junk, junkLen);
             if (ret <= 0) {
                 int sslErr = SSL_get_error(ssl, ret);
                 switch (sslErr) {
                     case SSL_ERROR_WANT_WRITE:
                     case SSL_ERROR_WANT_READ:
                         class Renegotiator
                             : public ReadEventReceiver
                             , public WriteEventReceiver
                             , public Descriptor {
                         public:
                             Renegotiator(SocketWriter* socketWriter, SSL* ssl, int sslErr)
                                 : socketWriter(socketWriter)
                                 , ssl(ssl) {
                                 this->open(socketWriter->getFd(), FLAGS::dontClose);
                                 switch (sslErr) {
                                     case SSL_ERROR_WANT_READ:
                                         ReadEventReceiver::enable();
                                         break;
                                     case SSL_ERROR_WANT_WRITE:
                                         WriteEventReceiver::enable();
                                         break;
                                 }
                             }
                             void readEvent() override {
                                 int ret = SSL_write(ssl, nullptr, 0);
                                 int sslErr = SSL_get_error(ssl, ret);
                                 switch (sslErr) {
                                     case SSL_ERROR_WANT_WRITE:
                                         ReadEventReceiver::disable();
                                         WriteEventReceiver::enable();
                                         break;
                                     case SSL_ERROR_WANT_READ:
                                         break;
                                     default:
                                         ReadEventReceiver::disable();
                                         break;
                                 }
                             }
                             void writeEvent() override {
                                 int ret = SSL_write(ssl, nullptr, 0);
                                 int sslErr = SSL_get_error(ssl, ret);
                                 switch (sslErr) {
                                     case SSL_ERROR_WANT_READ:
                                         WriteEventReceiver::disable();
                                         ReadEventReceiver::enable();
                                         break;
                                     case SSL_ERROR_WANT_WRITE:
                                         break;
                                     default:
                                         WriteEventReceiver::disable();
                                         break;
                                 }
                             }
                             void unobserved() override {
                                 delete this;
                             }
                         private:
                             SocketWriter* socketWriter = nullptr;
                             SSL* ssl;
                         };
                         new Renegotiator(this, ssl, sslErr);
                         errno = EAGAIN;
                         [[fallthrough]];
                     case SSL_ERROR_NONE:
                     case SSL_ERROR_ZERO_RETURN:
                     case SSL_ERROR_SYSCALL:
                         ret = 0;
                         break;
                     default:
                         ret = -ERR_peek_error();
                         break;
                 }
             }
             return ret;
         }
References net::ReadEventReceiver::disable(), net::WriteEventReceiver::disable(), net::ReadEventReceiver::enable(), net::WriteEventReceiver::enable(), net::socket::stream::tls::SocketWriter< SocketT >::ssl, net::EventReceiver::unobserved(), and net::socket::stream::SocketWriter< SocketT >::writeEvent().
Member Data Documentation
ssl
template<typename SocketT > SSL* net::socket::stream::tls::SocketWriter< SocketT >::ssl = nullptr protected
Definition at line 137 of file SocketWriter.h.
Referenced by net::socket::stream::tls::SocketWriter< SocketT >::write().
The documentation for this class was generated from the following file:
net/socket/sock_stream/tls/SocketWriter.h