snode.c: net::socket::tcp::Socket Class Reference
net::socket::tcp::Socket Class Reference
#include <Socket.h>
Public Member Functions
Socket ()=default
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
virtual ~Socket ()
void open (const std::function< void(int errnum)> &onError, int flags=0)
void bind (const InetAddress &localAddress, const std::function< void(int errnum)> &onError)
const InetAddress & getLocalAddress () const
void setLocalAddress (const InetAddress &localAddress)
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
~Descriptor ()
void open (int fd, FLAGS flags=FLAGS::none)
int getFd () const
bool dontClose () const
Protected Attributes
InetAddress localAddress {}
Additional Inherited Members
Public Types inherited from net::Descriptor
enum FLAGS : unsigned short { FLAGS::none = 0, FLAGS::dontClose = 0x01 << 0 }
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Protected Member Functions inherited from net::Descriptor
Descriptor ()=default
Detailed Description
Definition at line 33 of file Socket.h.
Constructor & Destructor Documentation
Socket() [1/2]
net::socket::tcp::Socket::Socket () default
Socket() [2/2]
net::socket::tcp::Socket::Socket (const Socket &) delete
~Socket()
net::socket::tcp::Socket::~Socket () virtual
Reimplemented in net::socket::tcp::tls::Socket.
Definition at line 31 of file Socket.cpp.
                     {
         if (!dontClose()) {
             ::shutdown(getFd(), SHUT_RDWR);
         }
     }
References net::Descriptor::dontClose(), and net::Descriptor::getFd().
Member Function Documentation
bind()
void net::socket::tcp::Socket::bind (const InetAddress & localAddress, const std::function< void(int errnum)> & onError)
Definition at line 52 of file Socket.cpp.
{
         socklen_t addrlen = sizeof(struct sockaddr_in);
         int ret = ::bind(getFd(), reinterpret_cast<const struct sockaddr*>(&localAddress.getSockAddr()), addrlen);
         if (ret < 0) {
             onError(errno);
         } else {
             onError(0);
         }
     }
References net::Descriptor::getFd(), net::socket::InetAddress::getSockAddr(), and localAddress.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::listen().
getLocalAddress()
const InetAddress & net::socket::tcp::Socket::getLocalAddress () const
Definition at line 48 of file Socket.cpp.
{
         return localAddress;
     }
References localAddress.
open()
void net::socket::tcp::Socket::open (const std::function< void(int errnum)> & onError, int flags = 0)
Definition at line 37 of file Socket.cpp.
{
         int fd = ::socket(AF_INET, SOCK_STREAM | flags, 0);
         if (fd >= 0) {
             open(fd);
             onError(0);
         } else {
             onError(errno);
         }
     }
References net::Descriptor::fd.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::listen(), and net::socket::tcp::tls::SocketListener::SocketListener().
operator=()
Socket& net::socket::tcp::Socket::operator= (const Socket &) delete
setLocalAddress()
void net::socket::tcp::Socket::setLocalAddress (const InetAddress & localAddress)
Definition at line 64 of file Socket.cpp.
{
         this->localAddress = localAddress;
     }
References localAddress.
Member Data Documentation
localAddress
InetAddress net::socket::tcp::Socket::localAddress {} protected
Definition at line 50 of file Socket.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent(), bind(), getLocalAddress(), net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::listen(), net::socket::tcp::tls::SocketListener::listen(), and setLocalAddress().
The documentation for this class was generated from the following files:
net/socket/tcp/Socket.h
net/socket/tcp/Socket.cpp