snode.c: web::websocket::Receiver Class Reference
web::websocket::Receiver Class Reference abstract
#include <Receiver.h>
Classes
union MaskingKey
Public Member Functions
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Private Types
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Private Member Functions
std::size_t readOpcode ()
std::size_t readLength ()
std::size_t readELength ()
std::size_t readMaskingKey ()
std::size_t readPayload ()
virtual void onMessageStart (int opCode)=0
virtual void onFrameReceived (const char *junk, uint64_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual std::size_t readFrameData (char *junk, std::size_t junkLen)=0
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Private Attributes
enum web::websocket::Receiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
char elengthJunk [8]
char maskingKeyJunk [4]
char payloadJunk [16384]
Detailed Description
Definition at line 35 of file Receiver.h.
Member Enumeration Documentation
ParserState
enum web::websocket::Receiver::ParserState strong private
Enumerator
BEGIN
OPCODE
LENGTH
ELENGTH
MASKINGKEY
PAYLOAD
ERROR
Definition at line 68 of file Receiver.h.
 { BEGIN, OPCODE, LENGTH, ELENGTH, MASKINGKEY, PAYLOAD, ERROR } parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
Receiver() [1/2]
web::websocket::Receiver::Receiver () default
Receiver() [2/2]
web::websocket::Receiver::Receiver (const Receiver &) delete
Member Function Documentation
dumpFrame()
void web::websocket::Receiver::dumpFrame (char * frame, uint64_t frameLength) private
Definition at line 231 of file Receiver.cpp.
{
         unsigned long modul = 4;
         std::stringstream stringStream;
         for (std::size_t i = 0; i < frameLength; i++) {
             stringStream << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % modul == 0 || i == frameLength) {
                 VLOG(0) << "Frame: " << stringStream.str();
                 stringStream.str("");
             }
         }
     }
onFrameReceived()
virtual void web::websocket::Receiver::onFrameReceived (const char * junk, uint64_t junkLen) private pure virtual
Implemented in web::websocket::SocketContext.
Referenced by readPayload().
onMessageEnd()
virtual void web::websocket::Receiver::onMessageEnd () private pure virtual
Implemented in web::websocket::SocketContext.
Referenced by readLength(), readMaskingKey(), and readPayload().
onMessageError()
virtual void web::websocket::Receiver::onMessageError (uint16_t errnum) private pure virtual
Implemented in web::websocket::SocketContext.
Referenced by receive().
onMessageStart()
virtual void web::websocket::Receiver::onMessageStart (int opCode) private pure virtual
Implemented in web::websocket::SocketContext.
Referenced by readOpcode().
operator=()
Receiver& web::websocket::Receiver::operator= (const Receiver &) delete
readELength()
std::size_t web::websocket::Receiver::readELength () private
Definition at line 133 of file Receiver.cpp.
{
         std::size_t consumed = 0;
         elengthNumBytesLeft = (elengthNumBytesLeft == 0) ? elengthNumBytes : elengthNumBytesLeft;
         std::size_t elengthJunkLen = readFrameData(elengthJunk, elengthNumBytesLeft);
         while (elengthJunkLen - consumed > 0) {
             length |= static_cast<uint64_t>(*reinterpret_cast<unsigned char*>(elengthJunk + consumed))
                       << (elengthNumBytes - elengthNumBytesLeft) * 8;
             consumed++;
             elengthNumBytesLeft--;
         }
         if (elengthNumBytesLeft == 0) {
             switch (elengthNumBytes) {
                 case 2: {
                     length = be16toh(static_cast<uint16_t>(length));
                 } break;
                 case 8:
                     length = be64toh(length);
                     break;
             }
             if (length & static_cast<uint64_t>(0x01) << 63) {
                 parserState = ParserState::ERROR;
                 errorState = 1004;
             } else if (masked) {
                 parserState = ParserState::MASKINGKEY;
             } else {
                 parserState = ParserState::PAYLOAD;
             }
         }
         return consumed;
     }
References elengthJunk, elengthNumBytes, elengthNumBytesLeft, ERROR, errorState, length, masked, MASKINGKEY, parserState, PAYLOAD, and readFrameData().
Referenced by receive().
readFrameData()
virtual std::size_t web::websocket::Receiver::readFrameData (char * junk, std::size_t junkLen) private pure virtual
Implemented in web::websocket::SocketContext.
Referenced by readELength(), readLength(), readMaskingKey(), readOpcode(), and readPayload().
readLength()
std::size_t web::websocket::Receiver::readLength () private
Definition at line 95 of file Receiver.cpp.
{
         char byte = 0;
         std::size_t consumed = readFrameData(&byte, 1);
         if (consumed > 0) {
             uint8_t lengthByte = static_cast<uint8_t>(byte);
             masked = lengthByte & 0b10000000;
             length = lengthByte & 0b01111111;
             if (length > 125) {
                 switch (length) {
                     case 126:
                         elengthNumBytes = 2;
                         break;
                     case 127:
                         elengthNumBytes = 8;
                         break;
                 }
                 parserState = ParserState::ELENGTH;
                 length = 0;
             } else {
                 if (masked) {
                     parserState = ParserState::MASKINGKEY;
                 } else if (length > 0) {
                     parserState = ParserState::PAYLOAD;
                 } else {
                     if (fin) {
                         onMessageEnd();
                     }
                     reset();
                 }
             }
         }
         return consumed;
     }
References ELENGTH, elengthNumBytes, fin, length, masked, MASKINGKEY, onMessageEnd(), parserState, PAYLOAD, readFrameData(), and reset().
Referenced by receive().
readMaskingKey()
std::size_t web::websocket::Receiver::readMaskingKey () private
Definition at line 171 of file Receiver.cpp.
{
         std::size_t consumed = 0;
         maskingKeyNumBytesLeft = (maskingKeyNumBytesLeft == 0) ? maskingKeyNumBytes : maskingKeyNumBytesLeft;
         std::size_t maskingKeyJunkLen = readFrameData(maskingKeyJunk, maskingKeyNumBytesLeft);
         while (maskingKeyJunkLen - consumed > 0) {
             maskingKey |= static_cast<uint32_t>(*reinterpret_cast<unsigned char*>(maskingKeyJunk + consumed))
                           << (maskingKeyNumBytes - maskingKeyNumBytesLeft) * 8;
             consumed++;
             maskingKeyNumBytesLeft--;
         }
         if (maskingKeyNumBytesLeft == 0) {
             maskingKey = be32toh(maskingKey);
             if (length > 0) {
                 parserState = ParserState::PAYLOAD;
             } else {
                 if (fin) {
                     onMessageEnd();
                 }
                 reset();
             }
         }
         return consumed;
     }
References fin, length, maskingKey, maskingKeyJunk, maskingKeyNumBytes, maskingKeyNumBytesLeft, onMessageEnd(), parserState, PAYLOAD, readFrameData(), and reset().
Referenced by receive().
readOpcode()
std::size_t web::websocket::Receiver::readOpcode () private
Definition at line 69 of file Receiver.cpp.
{
         char byte = 0;
         std::size_t consumed = readFrameData(&byte, 1);
         if (consumed > 0) {
             uint8_t opCodeByte = static_cast<uint8_t>(byte);
             fin = opCodeByte & 0b10000000;
             opCode = opCodeByte & 0b00001111;
             if (!continuation) {
                 onMessageStart(opCode);
                 parserState = ParserState::LENGTH;
             } else if (opCode == 0) {
                 parserState = ParserState::LENGTH;
             } else {
                 parserState = ParserState::ERROR;
                 errorState = 1002;
                 VLOG(0) << "Error opcode in continuation frame";
             }
             continuation = !fin;
         }
         return consumed;
     }
References continuation, ERROR, errorState, fin, LENGTH, onMessageStart(), opCode, parserState, and readFrameData().
Referenced by receive().
readPayload()
std::size_t web::websocket::Receiver::readPayload () private
Definition at line 200 of file Receiver.cpp.
{
         std::size_t consumed = 0;
         std::size_t payloadJunkLen = (MAX_PAYLOAD_JUNK_LEN <= length - payloadRead) ? static_cast<std::size_t>(MAX_PAYLOAD_JUNK_LEN)
                                                                                     : static_cast<std::size_t>(length - payloadRead);
         payloadJunkLen = readFrameData(payloadJunk, payloadJunkLen);
         if (payloadJunkLen > 0) {
             MaskingKey maskingKeyAsArray = {.key = htobe32(maskingKey)};
             for (std::size_t i = 0; i < payloadJunkLen; i++) {
                 *(payloadJunk + i) = *(payloadJunk + i) ^ *(maskingKeyAsArray.keyAsArray + (i + payloadRead) % 4);
             }
             onFrameReceived(payloadJunk, payloadJunkLen);
             payloadRead += payloadJunkLen;
             consumed = payloadJunkLen;
         }
         if (payloadRead == length) {
             if (fin) {
                 onMessageEnd();
             }
             reset();
         }
         return consumed;
     }
References fin, web::websocket::Receiver::MaskingKey::key, web::websocket::Receiver::MaskingKey::keyAsArray, length, maskingKey, MAX_PAYLOAD_JUNK_LEN, onFrameReceived(), onMessageEnd(), payloadJunk, payloadRead, readFrameData(), and reset().
Referenced by receive().
receive()
void web::websocket::Receiver::receive ()
Definition at line 34 of file Receiver.cpp.
{
         std::size_t consumed = 0;
         bool parsingError = false;
         // dumpFrame(junk, junkLen);
         do {
             switch (parserState) {
                 case ParserState::BEGIN:
                     parserState = ParserState::OPCODE;
                     [[fallthrough]];
                 case ParserState::OPCODE:
                     consumed = readOpcode();
                     break;
                 case ParserState::LENGTH:
                     consumed = readLength();
                     break;
                 case ParserState::ELENGTH:
                     consumed = readELength();
                     break;
                 case ParserState::MASKINGKEY:
                     consumed = readMaskingKey();
                     break;
                 case ParserState::PAYLOAD:
                     consumed = readPayload();
                     break;
                 case ParserState::ERROR:
                     onMessageError(errorState);
                     parsingError = true;
                     reset();
                     break;
             };
         } while (consumed > 0 && !parsingError && parserState != ParserState::BEGIN);
     }
References BEGIN, ELENGTH, ERROR, errorState, LENGTH, MASKINGKEY, onMessageError(), OPCODE, parserState, PAYLOAD, readELength(), readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
Referenced by web::websocket::SocketContext::onReceiveFromPeer().
reset()
void web::websocket::Receiver::reset () private
Definition at line 246 of file Receiver.cpp.
{
         parserState = ParserState::BEGIN;
         fin = false;
         continuation = false;
         masked = false;
         opCode = 0;
         length = 0;
         maskingKey = 0;
         elengthNumBytes = 0;
         elengthNumBytesLeft = 0;
         maskingKeyNumBytes = 4;
         maskingKeyNumBytesLeft = 0;
         payloadRead = 0;
         errorState = 0;
     }
References BEGIN, continuation, elengthNumBytes, elengthNumBytesLeft, errorState, fin, length, masked, maskingKey, maskingKeyNumBytes, maskingKeyNumBytesLeft, opCode, parserState, and payloadRead.
Referenced by readLength(), readMaskingKey(), readPayload(), and receive().
Member Data Documentation
continuation
bool web::websocket::Receiver::continuation = false private
Definition at line 71 of file Receiver.h.
Referenced by readOpcode(), and reset().
elengthJunk
char web::websocket::Receiver::elengthJunk[8] private
Definition at line 88 of file Receiver.h.
Referenced by readELength().
elengthNumBytes
uint8_t web::websocket::Receiver::elengthNumBytes = 0 private
Definition at line 78 of file Receiver.h.
Referenced by readELength(), readLength(), and reset().
elengthNumBytesLeft
uint8_t web::websocket::Receiver::elengthNumBytesLeft = 0 private
Definition at line 79 of file Receiver.h.
Referenced by readELength(), and reset().
errorState
uint16_t web::websocket::Receiver::errorState = 0 private
Definition at line 86 of file Receiver.h.
Referenced by readELength(), readOpcode(), receive(), and reset().
fin
bool web::websocket::Receiver::fin = false private
Definition at line 70 of file Receiver.h.
Referenced by readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
length
uint64_t web::websocket::Receiver::length = 0 private
Definition at line 75 of file Receiver.h.
Referenced by readELength(), readLength(), readMaskingKey(), readPayload(), and reset().
masked
bool web::websocket::Receiver::masked = false private
Definition at line 72 of file Receiver.h.
Referenced by readELength(), readLength(), and reset().
maskingKey
uint32_t web::websocket::Receiver::maskingKey = 0 private
Definition at line 76 of file Receiver.h.
Referenced by readMaskingKey(), readPayload(), and reset().
maskingKeyJunk
char web::websocket::Receiver::maskingKeyJunk[4] private
Definition at line 89 of file Receiver.h.
Referenced by readMaskingKey().
maskingKeyNumBytes
uint8_t web::websocket::Receiver::maskingKeyNumBytes = 4 private
Definition at line 81 of file Receiver.h.
Referenced by readMaskingKey(), and reset().
maskingKeyNumBytesLeft
uint8_t web::websocket::Receiver::maskingKeyNumBytesLeft = 0 private
Definition at line 82 of file Receiver.h.
Referenced by readMaskingKey(), and reset().
opCode
uint8_t web::websocket::Receiver::opCode = 0 private
Definition at line 74 of file Receiver.h.
Referenced by web::websocket::SocketContext::onMessageStart(), readOpcode(), reset(), web::websocket::SocketContext::sendMessage(), and web::websocket::SocketContext::sendMessageStart().
parserState
enum web::websocket::Receiver::ParserState web::websocket::Receiver::parserState = ParserState::BEGIN private
Referenced by readELength(), readLength(), readMaskingKey(), readOpcode(), receive(), and reset().
payloadJunk
char web::websocket::Receiver::payloadJunk[16384] private
Definition at line 90 of file Receiver.h.
Referenced by readPayload().
payloadRead
uint64_t web::websocket::Receiver::payloadRead = 0 private
Definition at line 84 of file Receiver.h.
Referenced by readPayload(), and reset().
The documentation for this class was generated from the following files:
web/websocket/Receiver.h
web/websocket/Receiver.cpp