snode.c: net::stream::Source Class Reference
net::stream::Source Class Reference
#include <Source.h>
Public Member Functions
Source ()
virtual ~Source ()
void connect (Sink &sink)
void disconnect (Sink &sink)
void send (const char *junk, std::size_t junkLen)
void eof ()
void error (int errnum)
Protected Attributes
Sink * sink
Detailed Description
Definition at line 32 of file Source.h.
Constructor & Destructor Documentation
Source()
net::stream::Source::Source ()
Definition at line 25 of file Source.cpp.
         : sink(nullptr) {
     }
~Source()
net::stream::Source::~Source () virtual
Definition at line 29 of file Source.cpp.
                     {
         if (sink != nullptr) {
             sink->disconnect(*this);
         }
     }
References net::stream::Sink::disconnect(), and sink.
Member Function Documentation
connect()
void net::stream::Source::connect (Sink & sink)
Definition at line 35 of file Source.cpp.
{
         this->sink = &sink;
         if (this->sink != nullptr) {
             sink.connect(*this);
         }
     }
References net::stream::Sink::connect(), and sink.
disconnect()
void net::stream::Source::disconnect (Sink & sink)
Definition at line 42 of file Source.cpp.
{
         if (&sink == this->sink) {
             this->sink = nullptr;
         }
     }
References sink.
Referenced by net::stream::Sink::~Sink().
eof()
void net::stream::Source::eof ()
Definition at line 60 of file Source.cpp.
                      {
         if (this->sink != nullptr) {
             sink->eof();
         }
     }
References net::stream::Sink::eof(), and sink.
Referenced by FileReader::readEvent().
error()
void net::stream::Source::error (int errnum)
Definition at line 54 of file Source.cpp.
{
         if (this->sink != nullptr) {
             sink->error(errnum);
         }
     }
References net::stream::Sink::error(), and sink.
Referenced by FileReader::readEvent().
send()
void net::stream::Source::send (const char * junk, std::size_t junkLen)
Definition at line 48 of file Source.cpp.
{
         if (this->sink != nullptr) {
             sink->receive(junk, junkLen);
         }
     }
References net::stream::Sink::receive(), and sink.
Referenced by FileReader::readEvent().
Member Data Documentation
sink
Sink* net::stream::Source::sink protected
Definition at line 45 of file Source.h.
Referenced by connect(), disconnect(), eof(), error(), FileReader::FileReader(), send(), and ~Source().
The documentation for this class was generated from the following files:
net/stream/Source.h
net/stream/Source.cpp