snode.c: net::FdSet Class Reference
net::FdSet Class Reference
#include <FdSet.h>
Public Member Functions
FdSet ()
void set (int fd)
void clr (int fd, bool immediate=false)
int isSet (int fd) const
void zero ()
fd_set & get ()
Protected Attributes
fd_set registered {}
fd_set active {}
Detailed Description
Definition at line 30 of file FdSet.h.
Constructor & Destructor Documentation
FdSet()
net::FdSet::FdSet ()
Definition at line 27 of file FdSet.cpp.
                  {
         zero();
     }
References zero().
Member Function Documentation
clr()
void net::FdSet::clr (int fd, bool immediate = false)
Definition at line 35 of file FdSet.cpp.
{
         FD_CLR(fd, &registered);
         if (immediate) {
             FD_CLR(fd, &active);
         }
     }
References active, and registered.
Referenced by net::DescriptorEventDispatcher::suspend(), and net::DescriptorEventDispatcher::unobserveDisabledEvents().
get()
fd_set & net::FdSet::get ()
Definition at line 51 of file FdSet.cpp.
{
         active = registered;
         return active;
     }
References active, and registered.
Referenced by net::EventLoop::tick().
isSet()
int net::FdSet::isSet (int fd) const
Definition at line 42 of file FdSet.cpp.
{
         return FD_ISSET(fd, &active);
     }
References active.
set()
void net::FdSet::set (int fd)
Definition at line 31 of file FdSet.cpp.
{
         FD_SET(fd, &registered);
     }
References registered.
Referenced by net::DescriptorEventDispatcher::resume(), and net::DescriptorEventDispatcher::unobserveDisabledEvents().
zero()
void net::FdSet::zero ()
Definition at line 46 of file FdSet.cpp.
                      {
         FD_ZERO(&registered);
         FD_ZERO(&active);
     }
References active, and registered.
Referenced by FdSet().
Member Data Documentation
active
fd_set net::FdSet::active {} protected
Definition at line 42 of file FdSet.h.
Referenced by clr(), get(), isSet(), and zero().
registered
fd_set net::FdSet::registered {} protected
Definition at line 41 of file FdSet.h.
Referenced by clr(), get(), set(), and zero().
The documentation for this class was generated from the following files:
net/FdSet.h
net/FdSet.cpp