snode.c: web::ws::server::WSServerContextBase Class Reference
web::ws::server::WSServerContextBase Class Reference abstract
#include <WSServerContextBase.h>
Public Member Functions
virtual void messageStart (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)=0
virtual void sendFrame (char *message, std::size_t messageLength, uint32_t messageKey=0)=0
virtual void messageEnd (char *message, std::size_t messageLength, uint32_t messageKey=0)=0
virtual void message (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)=0
virtual void sendPing (char *reason=nullptr, std::size_t reasonLength=0)=0
virtual void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)=0
virtual std::string getLocalAddressAsString () const =0
virtual std::string getRemoteAddressAsString () const =0
Detailed Description
Definition at line 14 of file WSServerContextBase.h.
Member Function Documentation
close()
virtual void web::ws::server::WSServerContextBase::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::close().
getLocalAddressAsString()
virtual std::string web::ws::server::WSServerContextBase::getLocalAddressAsString () const pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::getLocalAddressAsString().
getRemoteAddressAsString()
virtual std::string web::ws::server::WSServerContextBase::getRemoteAddressAsString () const pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::getRemoteAddressAsString().
message()
virtual void web::ws::server::WSServerContextBase::message (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::message().
messageEnd()
virtual void web::ws::server::WSServerContextBase::messageEnd (char * message, std::size_t messageLength, uint32_t messageKey = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::messageEnd().
messageStart()
virtual void web::ws::server::WSServerContextBase::messageStart (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::messageStart().
sendFrame()
virtual void web::ws::server::WSServerContextBase::sendFrame (char * message, std::size_t messageLength, uint32_t messageKey = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::sendFrame().
sendPing()
virtual void web::ws::server::WSServerContextBase::sendPing (char * reason = nullptr, std::size_t reasonLength = 0) pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by web::ws::server::WSServerProtocol::sendPing().
The documentation for this class was generated from the following file:
web/ws/server/WSServerContextBase.h