snode.c: http::server::Response Class Reference
http::server::Response Class Reference
#include <Response.h>
Public Member Functions
void send (const char *junk, std::size_t junkLen)
void send (const std::string &junk)
void end ()
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=true)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & type (const std::string &type)
void upgrade (ServerContext *newServerContext)
Public Member Functions inherited from net::stream::Sink
Sink ()
virtual ~Sink ()
void connect (Source &source)
void disconnect (Source &source)
Protected Member Functions
Response (HTTPServerContextBase *serverContext)
void enqueue (const char *junk, std::size_t junkLen)
void enqueue (const std::string &junk)
void sendHeader ()
void receive (const char *junk, std::size_t junkLen) override
void eof () override
void error (int errnum) override
virtual void reset ()
Protected Attributes
HTTPServerContextBase * serverContext
ConnectionState connectionState = ConnectionState::Default
bool sendHeaderInProgress = false
bool headersSent = false
int responseStatus = 200
std::size_t contentSent = 0
std::size_t contentLength = 0
std::map< std::string, std::string > headers
std::map< std::string, CookieOptions > cookies
Protected Attributes inherited from net::stream::Sink
Source * source
Friends
template<typename Request , typename Response >
class HTTPServerContext
Detailed Description
Definition at line 41 of file Response.h.
Constructor & Destructor Documentation
Response()
http::server::Response::Response (HTTPServerContextBase * serverContext) explicit protected
Definition at line 35 of file Response.cpp.
         : serverContext(serverContext) {
     }
Member Function Documentation
append()
Response & http::server::Response::append (const std::string & field, const std::string & value)
Definition at line 69 of file Response.cpp.
{
         std::map<std::string, std::string>::iterator it = headers.find(field);
         if (it != headers.end()) {
             it->second += ", " + value;
         } else {
             set(field, value);
         }
         return *this;
     }
References headers, and set().
clearCookie()
Response & http::server::Response::clearCookie (const std::string & name, const std::map< std::string, std::string > & options = {})
Definition at line 120 of file Response.cpp.
{
         std::map<std::string, std::string> opts = options;
         opts.erase("Max-Age");
         time_t time = 0;
         opts["Expires"] = httputils::to_http_date(gmtime(&time));
         return cookie(name, "", opts);
     }
References cookie(), and httputils::to_http_date().
cookie()
Response & http::server::Response::cookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 114 of file Response.cpp.
{
         cookies.insert({name, CookieOptions(value, options)});
         return *this;
     }
References cookies.
Referenced by clearCookie(), and sendHeader().
end()
void http::server::Response::end ()
Definition at line 176 of file Response.cpp.
{
         send("");
     }
References send().
Referenced by express::Response::redirect(), express::Response::sendFile(), and upgrade().
enqueue() [1/2]
void http::server::Response::enqueue (const char * junk, std::size_t junkLen) protected
Definition at line 39 of file Response.cpp.
{
         if (!headersSent && !sendHeaderInProgress) {
             sendHeaderInProgress = true;
             sendHeader();
             sendHeaderInProgress = false;
             headersSent = true;
         }
         serverContext->sendResponseData(junk, junkLen);
         if (headersSent) {
             contentSent += junkLen;
             if (contentSent == contentLength) {
                 serverContext->responseCompleted();
             } else if (contentSent > contentLength) {
                 serverContext->terminateConnection();
             }
         }
     }
References contentLength, contentSent, headersSent, http::server::HTTPServerContextBase::responseCompleted(), sendHeader(), sendHeaderInProgress, http::server::HTTPServerContextBase::sendResponseData(), serverContext, and http::server::HTTPServerContextBase::terminateConnection().
Referenced by enqueue(), receive(), send(), and sendHeader().
enqueue() [2/2]
void http::server::Response::enqueue (const std::string & junk) protected
Definition at line 59 of file Response.cpp.
{
         enqueue(junk.data(), junk.size());
     }
References enqueue().
eof()
void http::server::Response::eof () override protected virtual
Implements net::stream::Sink.
Definition at line 184 of file Response.cpp.
{
         LOG(INFO) << "Stream EOF";
     }
error()
void http::server::Response::error (int errnum) override protected virtual
Implements net::stream::Sink.
Definition at line 188 of file Response.cpp.
{
         PLOG(ERROR) << "Stream error: ";
         serverContext->terminateConnection();
     }
References serverContext, and http::server::HTTPServerContextBase::terminateConnection().
receive()
void http::server::Response::receive (const char * junk, std::size_t junkLen) override protected virtual
Implements net::stream::Sink.
Definition at line 180 of file Response.cpp.
{
         enqueue(junk, junkLen);
     }
References enqueue().
reset()
void http::server::Response::reset () protected virtual
Reimplemented in express::Response.
Definition at line 193 of file Response.cpp.
{
         headersSent = false;
         sendHeaderInProgress = false;
         contentSent = 0;
         responseStatus = 200;
         contentLength = 0;
         connectionState = ConnectionState::Default;
         headers.clear();
         cookies.clear();
     }
References connectionState, contentLength, contentSent, cookies, Default, headers, headersSent, responseStatus, and sendHeaderInProgress.
Referenced by express::Response::reset().
send() [1/2]
void http::server::Response::send (const char * junk, std::size_t junkLen)
Definition at line 130 of file Response.cpp.
{
         if (junkLen > 0) {
             set("Content-Type", "application/octet-stream", false);
         }
         set("Content-Length", std::to_string(junkLen));
         enqueue(junk, junkLen);
     }
References enqueue(), and set().
Referenced by end(), send(), and express::Response::sendStatus().
send() [2/2]
void http::server::Response::send (const std::string & junk)
Definition at line 139 of file Response.cpp.
{
         if (junk.size() > 0) {
             set("Content-Type", "text/html; charset=utf-8");
         }
         send(junk.data(), junk.size());
     }
References send(), and set().
sendHeader()
void http::server::Response::sendHeader () protected
Definition at line 146 of file Response.cpp.
{
         enqueue("HTTP/1.1 " + std::to_string(responseStatus) + " " + StatusCode::reason(responseStatus) + "\r\n");
         enqueue("Date: " + httputils::to_http_date() + "\r\n");
         set({{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}});
         for (auto& [field, value] : headers) {
             enqueue(field + ": " + value + "\r\n");
         }
         for (auto& [cookie, cookieValue] : cookies) {
             std::string cookieString =
                 std::accumulate(cookieValue.getOptions().begin(),
                                 cookieValue.getOptions().end(),
                                 cookie + "=" + cookieValue.getValue(),
                                 [](const std::string& str, const std::pair<const std::string&, const std::string&> option) -> std::string {
                                     return str + "; " + option.first + (!option.second.empty() ? "=" + option.second : "");
                                 });
             enqueue("Set-Cookie: " + cookieString + "\r\n");
         }
         enqueue("\r\n");
         if (headers.find("Content-Length") != headers.end()) {
             contentLength = std::stoi(headers.find("Content-Length")->second);
         } else {
             contentLength = 0;
         }
     }
References contentLength, cookie(), cookies, enqueue(), headers, StatusCode::reason(), responseStatus, set(), and httputils::to_http_date().
Referenced by enqueue().
set() [1/2]
Response & http::server::Response::set (const std::map< std::string, std::string > & headers, bool overwrite = true)
Definition at line 81 of file Response.cpp.
{
         for (auto& [field, value] : headers) {
             set(field, value, overwrite);
         }
         return *this;
     }
References headers, and set().
set() [2/2]
Response & http::server::Response::set (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 89 of file Response.cpp.
{
         if (overwrite || headers.find(field) == headers.end()) {
             headers.insert_or_assign(field, value);
             if (field == "Content-Length") {
                 contentLength = std::stol(value);
             } else if (field == "Connection" && httputils::ci_comp(value, "close")) {
                 connectionState = ConnectionState::Close;
             } else if (field == "Connection" && httputils::ci_comp(value, "keep-alive")) {
                 connectionState = ConnectionState::Keep;
             }
         }
         return *this;
     }
References httputils::ci_comp(), Close, connectionState, contentLength, headers, and Keep.
Referenced by append(), express::Response::download(), express::Response::redirect(), send(), sendHeader(), set(), and type().
status()
Response & http::server::Response::status (int status)
Definition at line 63 of file Response.cpp.
{
         responseStatus = status;
         return *this;
     }
References responseStatus.
Referenced by express::Response::redirect(), and express::Response::sendStatus().
type()
Response & http::server::Response::type (const std::string & type)
Definition at line 105 of file Response.cpp.
{
         return set("Content-Type", type);
     }
References set().
upgrade()
void http::server::Response::upgrade (ServerContext * newServerContext)
Definition at line 109 of file Response.cpp.
{
         serverContext->upgrade(newServerContext);
         end();
     }
References end(), serverContext, and http::server::ServerContext::upgrade().
Friends And Related Function Documentation
HTTPServerContext
template<typename Request , typename Response > friend class HTTPServerContext friend
Definition at line 88 of file Response.h.
Member Data Documentation
connectionState
ConnectionState http::server::Response::connectionState = ConnectionState::Default protected
Definition at line 64 of file Response.h.
Referenced by reset(), and set().
contentLength
std::size_t http::server::Response::contentLength = 0 protected
Definition at line 72 of file Response.h.
Referenced by enqueue(), reset(), sendHeader(), and set().
contentSent
std::size_t http::server::Response::contentSent = 0 protected
Definition at line 71 of file Response.h.
Referenced by enqueue(), and reset().
cookies
std::map<std::string, CookieOptions> http::server::Response::cookies protected
Definition at line 85 of file Response.h.
Referenced by cookie(), reset(), and sendHeader().
headers
std::map<std::string, std::string> http::server::Response::headers protected
Definition at line 84 of file Response.h.
Referenced by append(), reset(), express::Response::sendFile(), sendHeader(), and set().
headersSent
bool http::server::Response::headersSent = false protected
Definition at line 67 of file Response.h.
Referenced by enqueue(), and reset().
responseStatus
int http::server::Response::responseStatus = 200 protected
Definition at line 69 of file Response.h.
Referenced by reset(), express::Response::sendFile(), sendHeader(), and status().
sendHeaderInProgress
bool http::server::Response::sendHeaderInProgress = false protected
Definition at line 66 of file Response.h.
Referenced by enqueue(), and reset().
serverContext
HTTPServerContextBase* http::server::Response::serverContext protected
Definition at line 62 of file Response.h.
Referenced by enqueue(), error(), express::Response::sendFile(), and upgrade().
The documentation for this class was generated from the following files:
http/server/http/Response.h
http/server/http/Response.cpp