snode.c: net::pipe::Source Class Reference
net::pipe::Source Class Reference
#include <Source.h>
Public Member Functions
Source ()
virtual ~Source ()
void connect (Sink &sink)
void disconnect (Sink &sink)
void send (const char *junk, std::size_t junkLen)
void eof ()
void error (int errnum)
Protected Attributes
Sink * sink
Detailed Description
Definition at line 32 of file Source.h.
Constructor & Destructor Documentation
Source()
net::pipe::Source::Source ()
Definition at line 29 of file Source.cpp.
         : sink(nullptr) {
     }
~Source()
net::pipe::Source::~Source () virtual
Definition at line 33 of file Source.cpp.
                     {
         if (sink != nullptr) {
             sink->disconnect(*this);
         }
     }
References net::pipe::Sink::disconnect(), and sink.
Member Function Documentation
connect()
void net::pipe::Source::connect (Sink & sink)
Definition at line 39 of file Source.cpp.
{
         this->sink = &sink;
         if (this->sink != nullptr) {
             sink.connect(*this);
         }
     }
References net::pipe::Sink::connect(), and sink.
disconnect()
void net::pipe::Source::disconnect (Sink & sink)
Definition at line 46 of file Source.cpp.
{
         if (&sink == this->sink) {
             this->sink = nullptr;
         }
     }
References sink.
Referenced by net::pipe::Sink::~Sink().
eof()
void net::pipe::Source::eof ()
Definition at line 64 of file Source.cpp.
                      {
         if (this->sink != nullptr) {
             sink->eof();
         }
     }
References net::pipe::Sink::eof(), and sink.
Referenced by FileReader::readEvent().
error()
void net::pipe::Source::error (int errnum)
Definition at line 58 of file Source.cpp.
{
         if (this->sink != nullptr) {
             sink->error(errnum);
         }
     }
References net::pipe::Sink::error(), and sink.
Referenced by FileReader::readEvent().
send()
void net::pipe::Source::send (const char * junk, std::size_t junkLen)
Definition at line 52 of file Source.cpp.
{
         if (this->sink != nullptr) {
             sink->receive(junk, junkLen);
         }
     }
References net::pipe::Sink::receive(), and sink.
Referenced by FileReader::readEvent().
Member Data Documentation
sink
Sink* net::pipe::Source::sink protected
Definition at line 45 of file Source.h.
Referenced by connect(), disconnect(), eof(), error(), FileReader::FileReader(), send(), and ~Source().
The documentation for this class was generated from the following files:
net/pipe/Source.h
net/pipe/Source.cpp