snode.c: net::Descriptor Class Reference
net::Descriptor Class Reference
#include <Descriptor.h>
Public Types
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Member Functions
void attach (int fd, enum Descriptor::FLAGS flags=FLAGS::none)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Public Attributes
enum net::Descriptor::FLAGS none
Protected Member Functions
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
Private Member Functions
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
Private Attributes
int fd = -1
Friends
enum FLAGS operator| (const enum FLAGS &f1, const enum FLAGS &f2)
enum FLAGS operator& (const enum FLAGS &f1, const enum FLAGS &f2)
Detailed Description
Definition at line 28 of file Descriptor.h.
Member Enumeration Documentation
FLAGS
enum net::Descriptor::FLAGS : unsigned short strong
Enumerator
none
dontClose
Definition at line 33 of file Descriptor.h.
                           : unsigned short {
             none = 0,
             dontClose = 0x01 << 0 // do not close sys-descriptor in case of desctruction
         } flags{FLAGS::none};
Constructor & Destructor Documentation
Descriptor() [1/2]
net::Descriptor::Descriptor (const Descriptor & d) private delete
Descriptor() [2/2]
net::Descriptor::Descriptor (int fd = -1, enum Descriptor::FLAGS flags = FLAGS::none) protected
Definition at line 29 of file Descriptor.cpp.
         : flags(flags)
         , fd(fd) {
     }
~Descriptor()
net::Descriptor::~Descriptor () protected
Definition at line 34 of file Descriptor.cpp.
{
         if (!dontClose()) {
             net::system::close(fd);
         }
     }
References net::system::close(), dontClose(), and fd.
Member Function Documentation
attach()
void net::Descriptor::attach (int fd, enum Descriptor::FLAGS flags = FLAGS::none)
Definition at line 40 of file Descriptor.cpp.
{
         this->fd = fd;
         this->flags = flags;
     }
References fd.
Referenced by FileReader::FileReader(), and net::socket::Socket< SocketAddressT >::open().
dontClose() [1/2]
bool net::Descriptor::dontClose () const
Definition at line 53 of file Descriptor.cpp.
{
         return (flags & FLAGS::dontClose) == FLAGS::dontClose;
     }
References dontClose.
Referenced by dontClose(), and ~Descriptor().
dontClose() [2/2]
void net::Descriptor::dontClose (bool dontClose)
Definition at line 49 of file Descriptor.cpp.
{
         this->flags = dontClose ? FLAGS::dontClose : FLAGS::none;
     }
References dontClose(), and none.
getFd()
int net::Descriptor::getFd () const
Definition at line 45 of file Descriptor.cpp.
{
         return fd;
     }
References fd.
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), net::socket::Socket< SocketAddressT >::bind(), net::socket::stream::SocketConnector< SocketConnectionT >::connectEvent(), net::socket::stream::SocketListener< SocketConnectionT >::end(), net::socket::stream::SocketListener< SocketConnectionT >::listen(), FileReader::readEvent(), net::pipe::PipeSink::readEvent(), net::socket::stream::SocketListener< SocketConnectionT >::reuseAddress(), net::socket::Socket< SocketAddressT >::shutdown(), net::socket::stream::tls::SocketConnection< SocketT >::startSSL(), and net::pipe::PipeSource::writeEvent().
operator=()
Descriptor& net::Descriptor::operator= (const Descriptor & descriptor) private delete
Friends And Related Function Documentation
operator&
enum FLAGS operator& (const enum FLAGS & f1, const enum FLAGS & f2) friend
Definition at line 53 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) & static_cast<unsigned short>(f2));
     }
operator|
enum FLAGS operator| (const enum FLAGS & f1, const enum FLAGS & f2) friend
Definition at line 53 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) | static_cast<unsigned short>(f2));
     }
Member Data Documentation
fd
int net::Descriptor::fd = -1 private
Definition at line 51 of file Descriptor.h.
Referenced by attach(), FileReader::connect(), FileReader::FileReader(), getFd(), net::socket::Socket< SocketAddressT >::open(), net::pipe::PipeSink::PipeSink(), net::pipe::PipeSource::PipeSource(), and ~Descriptor().
none
enum net::Descriptor::FLAGS net::Descriptor::none
The documentation for this class was generated from the following files:
net/Descriptor.h
net/Descriptor.cpp