snode.c: web::http::server::RequestParser Class Reference
web::http::server::RequestParser Class Reference
#include <RequestParser.h>
Public Member Functions
RequestParser (net::socket::stream::SocketContext *socketContext, const std::function< void(void)> &onStart, const std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> &onRequest, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> &onHeader, const std::function< void(char *, std::size_t)> &onContent, const std::function< void()> &onParsed, const std::function< void(int, const std::string &)> &onError)
RequestParser (const RequestParser &)=delete
RequestParser & operator= (const RequestParser &)=delete
void reset () override
Public Member Functions inherited from web::http::Parser
Parser (net::socket::stream::SocketContext *socketContext, const enum HTTPCompliance &compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()=default
void parse ()
Private Member Functions
virtual bool methodSupported (const std::string &method) const
void begin () override
enum Parser::ParserState parseStartLine (const std::string &line) override
enum Parser::ParserState parseHeader () override
enum Parser::ParserState parseContent (char *content, std::size_t size) override
void parsingFinished ()
enum Parser::ParserState parsingError (int code, const std::string &reason) override
Private Attributes
std::set< std::string > supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"}
std::string method
std::string url
std::string httpVersion
std::map< std::string, std::string > cookies
std::map< std::string, std::string > queries
int httpMajor = 0
int httpMinor = 0
std::function< void(void)> onStart
std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> onRequest
std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> onHeader
std::function< void(char *, std::size_t)> onContent
std::function< void()> onParsed
std::function< void(int, const std::string &)> onError
Additional Inherited Members
Protected Types inherited from web::http::Parser
enum class HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum class ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Protected Attributes inherited from web::http::Parser
enum web::http::Parser::HTTPCompliance hTTPCompliance
enum web::http::Parser::ParserState parserState = ParserState::BEGIN
char * content = nullptr
std::size_t contentLength = 0
std::map< std::string, std::string > headers
Static Protected Attributes inherited from web::http::Parser
static std::regex httpVersionRegex
Detailed Description
Definition at line 40 of file RequestParser.h.
Constructor & Destructor Documentation
RequestParser() [1/2]
web::http::server::RequestParser::RequestParser (net::socket::stream::SocketContext * socketContext, const std::function< void(void)> & onStart, const std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> & onRequest, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> & onHeader, const std::function< void(char *, std::size_t)> & onContent, const std::function< void()> & onParsed, const std::function< void(int, const std::string &)> & onError)
Definition at line 34 of file RequestParser.cpp.
         : Parser(socketContext)
         , onStart(onStart)
         , onRequest(onRequest)
         , onHeader(onHeader)
         , onContent(onContent)
         , onParsed(onParsed)
         , onError(onError) {
     }
RequestParser() [2/2]
web::http::server::RequestParser::RequestParser (const RequestParser &) delete
Member Function Documentation
begin()
void web::http::server::RequestParser::begin () override private virtual
Implements web::http::Parser.
Definition at line 67 of file RequestParser.cpp.
{
         onStart();
     }
References onStart.
methodSupported()
bool web::http::server::RequestParser::methodSupported (const std::string & method) const private virtual
Definition at line 63 of file RequestParser.cpp.
{
         return supportedMethods.contains(method);
     }
References method, and supportedMethods.
operator=()
RequestParser& web::http::server::RequestParser::operator= (const RequestParser &) delete
parseContent()
enum Parser::ParserState web::http::server::RequestParser::parseContent (char * content, std::size_t size) override private virtual
Implements web::http::Parser.
Definition at line 67 of file RequestParser.cpp.
{
         onContent(content, size);
         parsingFinished();
         return ParserState::BEGIN;
     }
parseHeader()
enum Parser::ParserState web::http::server::RequestParser::parseHeader () override private virtual
Implements web::http::Parser.
Definition at line 67 of file RequestParser.cpp.
{
         for (auto& [field, value] : Parser::headers) {
             if (field != "cookie") {
                 if (field == "content-length") {
                     Parser::contentLength = std::stoul(value);
                 }
             } else {
                 std::string cookiesLine = value;
                 while (!cookiesLine.empty()) {
                     std::string cookieLine;
                     std::tie(cookieLine, cookiesLine) = httputils::str_split(cookiesLine, ',');
                     while (!cookieLine.empty()) {
                         std::string cookie;
                         std::tie(cookie, cookieLine) = httputils::str_split(cookieLine, ';');
                         std::string name;
                         std::string value;
                         std::tie(name, value) = httputils::str_split(cookie, '=');
                         httputils::str_trimm(name);
                         httputils::str_trimm(value);
                         cookies.insert({name, value});
                     }
                 }
             }
         }
         Parser::headers.erase("cookie");
         onHeader(Parser::headers, cookies);
         enum Parser::ParserState parserState = Parser::ParserState::BODY;
         if (contentLength == 0) {
             parsingFinished();
             parserState = ParserState::BEGIN;
         }
         return parserState;
     }
parseStartLine()
enum Parser::ParserState web::http::server::RequestParser::parseStartLine (const std::string & line) override private virtual
Implements web::http::Parser.
Definition at line 67 of file RequestParser.cpp.
{
         enum Parser::ParserState parserState = Parser::ParserState::HEADER;
         if (!line.empty()) {
             std::string remaining;
             std::tie(method, remaining) = httputils::str_split(line, ' ');
             std::tie(url, httpVersion) = httputils::str_split(remaining, ' ');
             std::string queriesLine;
             std::tie(std::ignore, queriesLine) = httputils::str_split(url, '?');
             if (!methodSupported(method)) {
                 parserState = parsingError(400, "Bad request method");
             } else if (url.empty() || url.front() != '/') {
                 parserState = parsingError(400, "Malformed request");
             } else {
                 std::smatch httpVersionMatch;
                 if (!std::regex_match(httpVersion, httpVersionMatch, httpVersionRegex)) {
                     parserState = parsingError(400, "Wrong protocol-version");
                 } else {
                     httpMajor = std::stoi(httpVersionMatch.str(1));
                     httpMinor = std::stoi(httpVersionMatch.str(2));
                     while (!queriesLine.empty()) {
                         std::string query;
                         std::tie(query, queriesLine) = httputils::str_split(queriesLine, '&');
                         queries.insert(httputils::str_split(query, '='));
                     }
                     onRequest(method, url, httpVersion, httpMajor, httpMinor, queries);
                 }
             }
         } else {
             parserState = parsingError(400, "Request-line empty");
         }
         return parserState;
     }
parsingError()
enum Parser::ParserState web::http::server::RequestParser::parsingError (int code, const std::string & reason) override private virtual
Implements web::http::Parser.
Definition at line 161 of file RequestParser.cpp.
{
         onError(code, reason);
         return ParserState::ERROR;
     }
References onParsed, and reset().
parsingFinished()
void web::http::server::RequestParser::parsingFinished () private
Definition at line 161 of file RequestParser.cpp.
{
         onParsed();
         reset();
     }
reset()
void web::http::server::RequestParser::reset () override virtual
Reimplemented from web::http::Parser.
Definition at line 52 of file RequestParser.cpp.
{
         Parser::reset();
         method.clear();
         url.clear();
         httpVersion.clear();
         queries.clear();
         cookies.clear();
         httpMajor = 0;
         httpMinor = 0;
     }
References cookies, httpMajor, httpMinor, httpVersion, method, queries, web::http::Parser::reset(), and url.
Referenced by parsingError().
Member Data Documentation
cookies
std::map<std::string, std::string> web::http::server::RequestParser::cookies private
Definition at line 81 of file RequestParser.h.
Referenced by reset().
httpMajor
int web::http::server::RequestParser::httpMajor = 0 private
Definition at line 83 of file RequestParser.h.
Referenced by reset().
httpMinor
int web::http::server::RequestParser::httpMinor = 0 private
Definition at line 84 of file RequestParser.h.
Referenced by reset().
httpVersion
std::string web::http::server::RequestParser::httpVersion private
Definition at line 80 of file RequestParser.h.
Referenced by reset().
method
std::string web::http::server::RequestParser::method private
Definition at line 78 of file RequestParser.h.
Referenced by methodSupported(), and reset().
onContent
std::function<void(char*, std::size_t)> web::http::server::RequestParser::onContent private
Definition at line 91 of file RequestParser.h.
onError
std::function<void(int, const std::string&)> web::http::server::RequestParser::onError private
Definition at line 93 of file RequestParser.h.
onHeader
std::function<void(const std::map<std::string, std::string>&, const std::map<std::string, std::string>&)> web::http::server::RequestParser::onHeader private
Definition at line 90 of file RequestParser.h.
onParsed
std::function<void()> web::http::server::RequestParser::onParsed private
Definition at line 92 of file RequestParser.h.
Referenced by parsingError().
onRequest
std::function<void(const std::string&, const std::string&, const std::string&, int, int, const std::map<std::string, std::string>&)> web::http::server::RequestParser::onRequest private
Definition at line 89 of file RequestParser.h.
onStart
std::function<void(void)> web::http::server::RequestParser::onStart private
Definition at line 87 of file RequestParser.h.
Referenced by begin().
queries
std::map<std::string, std::string> web::http::server::RequestParser::queries private
Definition at line 82 of file RequestParser.h.
Referenced by reset().
supportedMethods
std::set<std::string> web::http::server::RequestParser::supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"} private
Definition at line 75 of file RequestParser.h.
Referenced by methodSupported().
url
std::string web::http::server::RequestParser::url private
Definition at line 79 of file RequestParser.h.
Referenced by reset().
The documentation for this class was generated from the following files:
web/http/server/RequestParser.h
web/http/server/RequestParser.cpp