snode.c: net::socket::tcp::SocketClient< SocketConnectionT > Class Template Reference
net::socket::tcp::SocketClient< SocketConnectionT > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketConnection = SocketConnectionT
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketClient_v)
SocketClient (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options={{}})
SocketClient ()=delete
virtual ~SocketClient ()=default
virtual void connect (const std::map< std::string, std::any > &options, const std::function< void(int err)> &onError, const typename SocketConnection::Socket::SocketAddress &localAddress=typename SocketConnection::Socket::SocketAddress())
Protected Attributes
std::map< std::string, std::any > options
bool isDynamic = false
Static Protected Attributes
static void * lastAllocAddress = nullptr
Private Attributes
std::function< void(SocketConnection *socketConnection)> onConstruct
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onConnect
std::function< void(SocketConnection *socketConnection)> onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
Detailed Description
template<typename SocketConnectionT>
class net::socket::tcp::SocketClient< SocketConnectionT >
Definition at line 43 of file SocketClient.h.
Member Typedef Documentation
SocketConnection
template<typename SocketConnectionT > using net::socket::tcp::SocketClient< SocketConnectionT >::SocketConnection = SocketConnectionT
Definition at line 45 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient() [1/2]
template<typename SocketConnectionT > net::socket::tcp::SocketClient< SocketConnectionT >::SocketClient (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 57 of file SocketClient.h.
                                                                 {{}})
             : onConstruct(onConstruct)
             , onDestruct(onDestruct)
             , onConnect(onConnect)
             , onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options)
             , isDynamic(this == SocketClient<SocketConnection>::lastAllocAddress) {
             SocketClient<SocketConnection>::lastAllocAddress = nullptr;
         }
SocketClient() [2/2]
template<typename SocketConnectionT > net::socket::tcp::SocketClient< SocketConnectionT >::SocketClient () delete
~SocketClient()
template<typename SocketConnectionT > virtual net::socket::tcp::SocketClient< SocketConnectionT >::~SocketClient () virtual default
Reimplemented in net::socket::tcp::tls::SocketClient< SocketT >.
Member Function Documentation
connect()
template<typename SocketConnectionT > virtual void net::socket::tcp::SocketClient< SocketConnectionT >::connect (const std::map< std::string, std::any > & options, const std::function< void(int err)> & onError, const typename SocketConnection::Socket::SocketAddress & localAddress = typename SocketConnection::Socket::SocketAddress()) inline virtual
Reimplemented in net::socket::tcp::tls::SocketClient< SocketT >.
Definition at line 84 of file SocketClient.h.
{
             std::string host = "";
             unsigned short port = 0;
             for (auto& [name, value] : options) {
                 if (name == "host") {
                     host = std::any_cast<const char*>(value);
                 } else if (name == "port") {
                     port = std::any_cast<int>(value);
                 }
             }
             SocketConnection* socketConnection =
                 new SocketConnection(onConstruct, onDestruct, onRead, onReadError, onWriteError, onDisconnect);
             socketConnection->open(
                 [socketConnection, &host, &port, &localAddress, &onConnect = this->onConnect, &onError](int err) -> void {
                     if (err) {
                         onError(err);
                         delete socketConnection;
                     } else {
                         socketConnection->bind(localAddress, [socketConnection, &host, &port, &onConnect, &onError](int err) -> void {
                             if (err) {
                                 onError(err);
                                 delete socketConnection;
                             } else {
                                 typename SocketConnection::Socket::SocketAddress server(host, port);
                                 class Connector
                                     : public WriteEventReceiver
                                     , public Descriptor {
                                 public:
                                     Connector(SocketConnection* socketConnection,
                                               const typename SocketConnection::Socket::SocketAddress& server,
                                               const std::function<void(SocketConnection* socketConnection)>& onConnect,
                                               const std::function<void(int err)>& onError)
                                         : socketConnection(socketConnection)
                                         , onConnect(onConnect)
                                         , onError(onError)
                                         , timeOut(net::timer::Timer::singleshotTimer(
                                               [this, socketConnection, onError](const void*) -> void {
                                                   onError(ETIMEDOUT);
                                                   WriteEventReceiver::disable();
                                                   delete socketConnection;
                                               },
                                               (struct timeval){CONNECT_TIMEOUT, 0},
                                               nullptr)) {
                                         open(socketConnection->getFd(), FLAGS::dontClose);
                                         errno = 0;
                                         int ret = ::connect(socketConnection->getFd(), &server.getSockAddr(), server.getSockAddrLen());
                                         if (ret == 0 || errno == EINPROGRESS) {
                                             typename SocketConnection::Socket::SocketAddress::SockAddr localAddress{};
                                             socklen_t addressLength = sizeof(localAddress);
                                             getsockname(
                                                 socketConnection->getFd(), reinterpret_cast<sockaddr*>(&localAddress), &addressLength);
                                             socketConnection->setLocalAddress(
                                                 typename SocketConnection::Socket::SocketAddress(localAddress));
                                             socketConnection->setRemoteAddress(server);
                                         }
                                         if (ret == 0) {
                                             timeOut.cancel();
                                             socketConnection->ReadEventReceiver::enable();
                                             onError(0);
                                             onConnect(socketConnection);
                                             delete this;
                                         } else if (errno == EINPROGRESS) {
                                             WriteEventReceiver::enable();
                                         } else {
                                             timeOut.cancel();
                                             onError(errno);
                                             delete socketConnection;
                                             delete this;
                                         }
                                     }
                                     void writeEvent() override {
                                         int cErrno = 0;
                                         socklen_t cErrnoLen = sizeof(cErrno);
                                         int err = getsockopt(socketConnection->getFd(), SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
                                         if (cErrno != EINPROGRESS) {
                                             timeOut.cancel();
                                             WriteEventReceiver::disable();
                                             if (err < 0) {
                                                 delete socketConnection;
                                                 onError(errno);
                                             } else if (cErrno != 0) {
                                                 delete socketConnection;
                                                 errno = cErrno;
                                                 onError(cErrno);
                                             } else {
                                                 socketConnection->ReadEventReceiver::enable();
                                                 onError(0);
                                                 onConnect(socketConnection);
                                             }
                                         }
                                     }
                                     void unobserved() override {
                                         delete this;
                                     }
                                 private:
                                     SocketConnection* socketConnection = nullptr;
                                     std::function<void(SocketConnection* socketConnection)> onConnect;
                                     std::function<void(int err)> onError;
                                     net::timer::Timer& timeOut;
                                 };
                                 errno = 0;
                                 new Connector(socketConnection, server, onConnect, onError);
                             }
                         });
                     }
                 },
                 SOCK_NONBLOCK);
         }
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect(), and net::socket::tcp::tls::SocketClient< SocketT >::connect().
operator delete()
template<typename SocketConnectionT > void net::socket::tcp::SocketClient< SocketConnectionT >::operator delete (void * socketClient_v) inline
Definition at line 53 of file SocketClient.h.
{
             free(socketClient_v);
         }
operator new()
template<typename SocketConnectionT > void* net::socket::tcp::SocketClient< SocketConnectionT >::operator new (size_t size) inline
Definition at line 47 of file SocketClient.h.
{
             SocketClient<SocketConnection>::lastAllocAddress = malloc(size);
             return SocketClient<SocketConnection>::lastAllocAddress;
         }
Member Data Documentation
isDynamic
template<typename SocketConnectionT > bool net::socket::tcp::SocketClient< SocketConnectionT >::isDynamic = false protected
Definition at line 226 of file SocketClient.h.
lastAllocAddress
template<typename SocketConnection > void * net::socket::tcp::SocketClient< SocketConnection >::lastAllocAddress = nullptr static protected
Definition at line 227 of file SocketClient.h.
onConnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketClient< SocketConnectionT >::onConnect private
Definition at line 217 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onConstruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketClient< SocketConnectionT >::onConstruct private
Definition at line 215 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onDestruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketClient< SocketConnectionT >::onDestruct private
Definition at line 216 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onDisconnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketClient< SocketConnectionT >::onDisconnect private
Definition at line 218 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onRead
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, const char* junk, ssize_t junkLen)> net::socket::tcp::SocketClient< SocketConnectionT >::onRead private
Definition at line 219 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onReadError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketClient< SocketConnectionT >::onReadError private
Definition at line 220 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
onWriteError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketClient< SocketConnectionT >::onWriteError private
Definition at line 221 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
options
template<typename SocketConnectionT > std::map<std::string, std::any> net::socket::tcp::SocketClient< SocketConnectionT >::options protected
Definition at line 224 of file SocketClient.h.
Referenced by net::socket::tcp::SocketClient< tls::SocketConnection< SocketT > >::connect().
The documentation for this class was generated from the following file:
net/socket/tcp/SocketClient.h