snode.c: web::websocket::server::SocketContext Class Reference
web::websocket::server::SocketContext Class Reference
#include <SocketContext.h>
Static Public Member Functions
static SocketContext * create (net::socket::stream::SocketConnection *socketConnection, web::http::server::Request &req, web::http::server::Response &res)
Protected Member Functions
SocketContext (net::socket::stream::SocketConnection *socketConnection, web::websocket::SubProtocol *subProtocol)
~SocketContext () override
Protected Member Functions inherited from web::websocket::SocketContext
SocketContext (net::socket::stream::SocketConnection *socketConnection, SubProtocol *subProtocol, Transmitter::Role role)
SocketContext ()=delete
SocketContext (const SocketContext &)=delete
SocketContext & operator= (const SocketContext &)=delete
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnection *socketConnection)
Protected Member Functions inherited from web::websocket::Receiver
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Protected Member Functions inherited from web::websocket::Transmitter
Transmitter (Role role)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Additional Inherited Members
Public Member Functions inherited from web::websocket::SocketContext
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketContext (const SocketContextFactory &socketContextFactory)
void setTimeout (int timeout)
Protected Types inherited from web::websocket::Transmitter
enum class Role { SERVER , CLIENT }
Protected Attributes inherited from web::websocket::SocketContext
web::websocket::SubProtocol * subProtocol
Detailed Description
Definition at line 43 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
web::websocket::server::SocketContext::SocketContext (net::socket::stream::SocketConnection * socketConnection, web::websocket::SubProtocol * subProtocol) protected
Definition at line 43 of file SocketContext.cpp.
         : web::websocket::SocketContext(socketConnection, subProtocol, Transmitter::Role::SERVER) {
     }
~SocketContext()
web::websocket::server::SocketContext::~SocketContext () override protected virtual
Reimplemented from web::websocket::SocketContext.
Definition at line 47 of file SocketContext.cpp.
{
         SubProtocolFactorySelector::instance()->destroy(subProtocol);
     }
References web::websocket::server::SubProtocolFactorySelector::instance(), and web::websocket::SocketContext::subProtocol.
Member Function Documentation
create()
SocketContext * web::websocket::server::SocketContext::create (net::socket::stream::SocketConnection * socketConnection, web::http::server::Request & req, web::http::server::Response & res) static
Definition at line 51 of file SocketContext.cpp.
{
         std::string subProtocolName = req.header("sec-websocket-protocol");
         SocketContext* context = nullptr;
         SubProtocolFactory* subProtocolFactory =
             dynamic_cast<SubProtocolFactory*>(SubProtocolFactorySelector::instance()->select(subProtocolName));
         if (subProtocolFactory != nullptr) {
             if (subProtocolFactory->role() == SubProtocolFactory::Role::SERVER) {
                 SubProtocol* subProtocol = dynamic_cast<SubProtocol*>(subProtocolFactory->create());
                 if (subProtocol != nullptr) {
                     subProtocol->setClients(subProtocolFactory->getClients());
                     context = new SocketContext(socketConnection, subProtocol);
                     if (context != nullptr) {
                         res.set("Upgrade", "websocket");
                         res.set("Connection", "Upgrade");
                         res.set("Sec-WebSocket-Protocol", subProtocolName);
                         web::websocket::serverWebSocketKey(req.header("sec-websocket-key"), [&res](char* key) -> void {
                             res.set("Sec-WebSocket-Accept", key);
                         });
                         res.status(101).end(); // Switch Protocol
                     } else {
                         subProtocolFactory->destroy(subProtocol);
                         res.status(500).end(); // Internal Server Error
                     }
                 } else {
                     res.status(404).end(); // Not Found
                 }
             } else {
                 res.status(500).end(); // Internal Server Error
             }
         } else {
             res.status(404).end(); // Not Found
         }
         return context;
     }
References web::websocket::SubProtocolFactory::create(), web::websocket::SubProtocolFactory::destroy(), web::http::server::Response::end(), web::websocket::server::SubProtocolFactory::getClients(), web::http::server::Request::header(), web::websocket::server::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactory::role(), web::websocket::SubProtocolFactory::SERVER, web::websocket::serverWebSocketKey(), web::http::server::Response::set(), net::socket::stream::SocketContext::socketConnection, web::websocket::SocketContext::SocketContext(), web::http::server::Response::status(), and web::websocket::SocketContext::subProtocol.
Referenced by web::websocket::server::SocketContextUpgradeFactory::create().
The documentation for this class was generated from the following files:
web/websocket/server/SocketContext.h
web/websocket/server/SocketContext.cpp