snode.c: net::stream::PipeSource Class Reference
net::stream::PipeSource Class Reference
#include <PipeSource.h>
Public Member Functions
PipeSource (int fd)
PipeSource (const PipeSource &)=delete
PipeSource & operator= (const PipeSource &)=delete
void send (const char *junk, std::size_t junkLen)
void send (const std::string &data)
void eof ()
void setOnError (const std::function< void(int errnum)> &onError)
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
void attach (int fd, enum Descriptor::FLAGS flags=FLAGS::none)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Public Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
void writeEvent () override
void unobserved () override
Protected Member Functions inherited from net::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
Protected Member Functions inherited from net::WriteEventReceiver
WriteEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
std::function< void(int errnum)> onError
std::vector< char > writeBuffer
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Additional Inherited Members
Public Types inherited from net::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Detailed Description
Definition at line 36 of file PipeSource.h.
Constructor & Destructor Documentation
PipeSource() [1/2]
net::stream::PipeSource::PipeSource (int fd)
Definition at line 35 of file PipeSource.cpp.
         : Descriptor(fd) {
         WriteEventReceiver::enable(fd);
         WriteEventReceiver::suspend();
     }
References net::DescriptorEventReceiver::enable(), net::Descriptor::fd, and net::DescriptorEventReceiver::suspend().
PipeSource() [2/2]
net::stream::PipeSource::PipeSource (const PipeSource &) delete
Member Function Documentation
eof()
void net::stream::PipeSource::eof ()
Definition at line 57 of file PipeSource.cpp.
{
         WriteEventReceiver::disable();
         WriteEventReceiver::suspend();
     }
References net::DescriptorEventReceiver::disable(), and net::DescriptorEventReceiver::suspend().
operator=()
PipeSource& net::stream::PipeSource::operator= (const PipeSource &) delete
send() [1/2]
void net::stream::PipeSource::send (const char * junk, std::size_t junkLen)
Definition at line 45 of file PipeSource.cpp.
{
         writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
         if (WriteEventReceiver::isSuspended()) {
             WriteEventReceiver::resume();
         }
     }
References net::DescriptorEventReceiver::isSuspended(), net::DescriptorEventReceiver::resume(), and writeBuffer.
Referenced by send().
send() [2/2]
void net::stream::PipeSource::send (const std::string & data)
Definition at line 53 of file PipeSource.cpp.
{
         send(data.data(), data.size());
     }
References send().
setOnError()
void net::stream::PipeSource::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 41 of file PipeSource.cpp.
{
         this->onError = onError;
     }
References onError.
unobserved()
void net::stream::PipeSource::unobserved () override protected virtual
Implements net::DescriptorEventReceiver.
Definition at line 84 of file PipeSource.cpp.
{
         delete this;
     }
writeEvent()
void net::stream::PipeSource::writeEvent () override protected virtual
Implements net::WriteEventReceiver.
Definition at line 62 of file PipeSource.cpp.
{
         errno = 0;
         ssize_t ret =
             ::write(getFd(), writeBuffer.data(), (writeBuffer.size() < MAX_SEND_JUNKSIZE) ? writeBuffer.size() : MAX_SEND_JUNKSIZE);
         if (ret > 0) {
             writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + ret);
             if (writeBuffer.empty()) {
                 WriteEventReceiver::suspend();
             }
         } else if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
             WriteEventReceiver::disable();
             WriteEventReceiver::suspend();
             if (onError) {
                 onError(errno);
             }
         }
     }
References net::DescriptorEventReceiver::disable(), net::Descriptor::getFd(), MAX_SEND_JUNKSIZE, onError, net::DescriptorEventReceiver::suspend(), and writeBuffer.
Member Data Documentation
onError
std::function<void(int errnum)> net::stream::PipeSource::onError protected
Definition at line 55 of file PipeSource.h.
Referenced by setOnError(), and writeEvent().
writeBuffer
std::vector<char> net::stream::PipeSource::writeBuffer protected
Definition at line 57 of file PipeSource.h.
Referenced by send(), and writeEvent().
The documentation for this class was generated from the following files:
net/stream/PipeSource.h
net/stream/PipeSource.cpp