snode.c: net::pipe::PipeSink Class Reference
net::pipe::PipeSink Class Reference
#include <PipeSink.h>
Public Member Functions
PipeSink (int fd)
void setOnData (const std::function< void(const char *junk, std::size_t junkLen)> &onData)
void setOnEof (const std::function< void()> &onEof)
void setOnError (const std::function< void(int errnum)> &onError)
Public Member Functions inherited from net::Descriptor
void attach (int fd, enum Descriptor::FLAGS flags=FLAGS::none)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Public Member Functions inherited from net::DescriptorEventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
void readEvent () override
void unobserved () override
Protected Member Functions inherited from net::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
std::function< void(const char *junk, std::size_t junkLen)> onData
std::function< void()> onEof
std::function< void(int errnum)> onError
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Private Member Functions
PipeSink (const PipeSink &)=delete
PipeSink & operator= (const PipeSink &)=delete
Additional Inherited Members
Public Types inherited from net::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Detailed Description
Definition at line 34 of file PipeSink.h.
Constructor & Destructor Documentation
PipeSink() [1/2]
net::pipe::PipeSink::PipeSink (const PipeSink &) private delete
PipeSink() [2/2]
net::pipe::PipeSink::PipeSink (int fd)
Definition at line 35 of file PipeSink.cpp.
         : Descriptor(fd) {
         ReadEventReceiver::enable(fd);
     }
References net::DescriptorEventReceiver::enable(), and net::Descriptor::fd.
Member Function Documentation
operator=()
PipeSink& net::pipe::PipeSink::operator= (const PipeSink &) private delete
readEvent()
void net::pipe::PipeSink::readEvent () override protected virtual
Implements net::ReadEventReceiver.
Definition at line 40 of file PipeSink.cpp.
{
         // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, hicpp-avoid-c-arrays, modernize-avoid-c-arrays)
         static char junk[MAX_READ_JUNKSIZE];
         ssize_t ret = net::system::read(getFd(), junk, MAX_READ_JUNKSIZE);
         if (ret > 0) {
             if (onData) {
                 onData(junk, static_cast<std::size_t>(ret));
             }
         } else {
             ReadEventReceiver::disable();
             ReadEventReceiver::suspend();
             if (ret == 0) {
                 if (onEof) {
                     onEof();
                 }
             } else {
                 if (onError) {
                     onError(errno);
                 }
             }
         }
     }
References net::DescriptorEventReceiver::disable(), net::Descriptor::getFd(), MAX_READ_JUNKSIZE, onData, onEof, onError, net::system::read(), and net::DescriptorEventReceiver::suspend().
setOnData()
void net::pipe::PipeSink::setOnData (const std::function< void(const char *junk, std::size_t junkLen)> & onData)
Definition at line 66 of file PipeSink.cpp.
{
         this->onData = onData;
     }
References onData.
setOnEof()
void net::pipe::PipeSink::setOnEof (const std::function< void()> & onEof)
Definition at line 70 of file PipeSink.cpp.
{
         this->onEof = onEof;
     }
References onEof.
setOnError()
void net::pipe::PipeSink::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 74 of file PipeSink.cpp.
{
         this->onError = onError;
     }
References onError.
unobserved()
void net::pipe::PipeSink::unobserved () override protected virtual
Implements net::DescriptorEventReceiver.
Definition at line 78 of file PipeSink.cpp.
{
         delete this;
     }
Member Data Documentation
onData
std::function<void(const char* junk, std::size_t junkLen)> net::pipe::PipeSink::onData protected
Definition at line 51 of file PipeSink.h.
Referenced by readEvent(), and setOnData().
onEof
std::function<void()> net::pipe::PipeSink::onEof protected
Definition at line 52 of file PipeSink.h.
Referenced by readEvent(), and setOnEof().
onError
std::function<void(int errnum)> net::pipe::PipeSink::onError protected
Definition at line 53 of file PipeSink.h.
Referenced by readEvent(), and setOnError().
The documentation for this class was generated from the following files:
net/pipe/PipeSink.h
net/pipe/PipeSink.cpp