snode.c: express::RouterDispatcher Class Reference
express::RouterDispatcher Class Reference
#include <Router.h>
Public Member Functions
void dispatch (Request &req, Response &res) const
Public Member Functions inherited from express::Dispatcher
Dispatcher ()=default
virtual ~Dispatcher ()=default
Private Member Functions
void dispatch (const RouterDispatcher *parentRouter, const std::string &parentMountPath, const MountPoint &mountPoint, Request &req, Response &res) const override
void terminate () const
State & getState () const
bool proceed () const
void returnTo (const RouterDispatcher *parentRouter) const
Private Attributes
std::list< Route > routes
State state
Friends
class Router
class ApplicationDispatcher
class MiddlewareDispatcher
Detailed Description
Definition at line 80 of file Router.h.
Member Function Documentation
dispatch() [1/2]
void express::RouterDispatcher::dispatch (const RouterDispatcher * parentRouter, const std::string & parentMountPath, const MountPoint & mountPoint, Request & req, Response & res) const override private virtual
Implements express::Dispatcher.
Definition at line 219 of file Router.cpp.
{
         std::string absoluteMountPath = path_concat(parentMountPath, mountPoint.relativeMountPath);
         // TODO: Fix regex-match
         if ((req.path.rfind(absoluteMountPath, 0) == 0 &&
              (mountPoint.method == "use" || req.method == mountPoint.method || mountPoint.method == "all"))) {
             for (const Route& route : routes) {
                 route.dispatch(this, absoluteMountPath, req, res);
                 if (!proceed()) {
                     break;
                 }
             }
         }
         returnTo(parentRouter);
     }
References express::MountPoint::method, web::http::server::Request::method, express::Request::path, express::path_concat(), proceed(), express::MountPoint::relativeMountPath, returnTo(), and routes.
dispatch() [2/2]
void express::RouterDispatcher::dispatch (Request & req, Response & res) const
Definition at line 241 of file Router.cpp.
{
         dispatch(nullptr, "/", MountPoint("use", "/"), req, res);
     }
getState()
State& express::RouterDispatcher::getState () const inline private
Definition at line 95 of file Router.h.
{
             return state;
         }
References state.
Referenced by express::MiddlewareDispatcher::dispatch().
proceed()
bool express::RouterDispatcher::proceed () const inline private
Definition at line 99 of file Router.h.
{
             return state.proceed;
         }
References express::State::proceed, and state.
Referenced by dispatch().
returnTo()
void express::RouterDispatcher::returnTo (const RouterDispatcher * parentRouter) const private
Definition at line 245 of file Router.cpp.
{
         if (parentRouter) {
             parentRouter->state.proceed = state.proceed | state.parentProceed;
         }
         state.proceed = true;
         state.parentProceed = false;
     }
References express::State::parentProceed, express::State::proceed, and state.
Referenced by dispatch().
terminate()
void express::RouterDispatcher::terminate () const inline private
Definition at line 91 of file Router.h.
{
             state.proceed = false;
         }
References express::State::proceed, and state.
Referenced by express::MiddlewareDispatcher::dispatch(), and express::ApplicationDispatcher::dispatch().
Friends And Related Function Documentation
ApplicationDispatcher
friend class ApplicationDispatcher friend
Definition at line 109 of file Router.h.
MiddlewareDispatcher
friend class MiddlewareDispatcher friend
Definition at line 110 of file Router.h.
Router
friend class Router friend
Definition at line 108 of file Router.h.
Member Data Documentation
routes
std::list<Route> express::RouterDispatcher::routes private
Definition at line 105 of file Router.h.
Referenced by dispatch().
state
State express::RouterDispatcher::state mutable private
Definition at line 106 of file Router.h.
Referenced by getState(), proceed(), returnTo(), and terminate().
The documentation for this class was generated from the following files:
express/Router.h
express/Router.cpp