snode.c: Logger Class Reference
Logger Class Reference
#include <Logger.h>
Public Types
enum Level {
INFO , DEBUG , WARNING , ERROR ,
FATAL
}
Static Public Member Functions
static void init (int argc, char *argv[])
static void setLogLevel (int level)
static void setVerboseLevel (unsigned short level)
static void logToFile (const std::string &logFile="")
static void quiet ()
static void setCustomFormatSpec (const char *format, const el::FormatSpecifierValueResolver &resolver)
Static Protected Attributes
static el::Configurations conf
Private Member Functions
Logger ()=delete
~Logger ()=delete
Detailed Description
Definition at line 29 of file Logger.h.
Member Enumeration Documentation
Level
enum Logger::Level
Enumerator
INFO
DEBUG
WARNING
ERROR
FATAL
Definition at line 34 of file Logger.h.
 { INFO, DEBUG, WARNING, ERROR, FATAL };
Constructor & Destructor Documentation
Logger()
Logger::Logger () private delete
~Logger()
Logger::~Logger () private delete
Member Function Documentation
init()
void Logger::init (int argc, char * argv[]) static
Definition at line 31 of file Logger.cpp.
{
     START_EASYLOGGINGPP(argc, argv);
     conf.setGlobally(el::ConfigurationType::Enabled, "true");
     conf.setGlobally(el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %level %msg");
     conf.setGlobally(el::ConfigurationType::ToFile, "false");
     conf.setGlobally(el::ConfigurationType::ToStandardOutput, "true");
     conf.setGlobally(el::ConfigurationType::SubsecondPrecision, "2");
     conf.setGlobally(el::ConfigurationType::PerformanceTracking, "false");
     conf.setGlobally(el::ConfigurationType::MaxLogFileSize, "2097152");
     conf.setGlobally(el::ConfigurationType::LogFlushThreshold, "100");
     conf.set(el::Level::Verbose, el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %msg");
     el::Loggers::addFlag(el::LoggingFlag::DisableApplicationAbortOnFatalLog);
     el::Loggers::addFlag(el::LoggingFlag::DisablePerformanceTrackingCheckpointComparison);
     el::Loggers::addFlag(el::LoggingFlag::ColoredTerminalOutput);
     el::Loggers::reconfigureLogger("default", conf);
     el::Logger* logger = el::Loggers::getLogger("default");
     std::string logFilename = logger->typedConfigurations()->filename(el::Level::Verbose).c_str();
     if (logFilename != "/dev/null") {
         conf.setGlobally(el::ConfigurationType::ToFile, "true");
         el::Loggers::reconfigureLogger("default", conf);
     }
     setLogLevel(6);
 }
References conf, and setLogLevel().
Referenced by net::EventLoop::init().
logToFile()
void Logger::logToFile (const std::string & logFile = "") static
Definition at line 106 of file Logger.cpp.
{
     conf.setGlobally(el::ConfigurationType::Filename, logFile);
     conf.setGlobally(el::ConfigurationType::ToFile, "true");
     el::Loggers::reconfigureLogger("default", conf);
 }
References conf.
quiet()
void Logger::quiet () static
Definition at line 113 of file Logger.cpp.
                    {
     conf.setGlobally(el::ConfigurationType::ToStandardOutput, "false");
     el::Loggers::reconfigureLogger("default", conf);
 }
References conf.
setCustomFormatSpec()
void Logger::setCustomFormatSpec (const char * format, const el::FormatSpecifierValueResolver & resolver) static
Definition at line 61 of file Logger.cpp.
{
     el::Helpers::installCustomFormatSpecifier(el::CustomFormatSpecifier(format, resolver));
 }
Referenced by net::EventLoop::init().
setLogLevel()
void Logger::setLogLevel (int level) static
Definition at line 67 of file Logger.cpp.
{
     conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "false");   // trace method/function calling
     conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "false");   // typical assert messages - but we can go on
     conf.set(el::Level::Info, el::ConfigurationType::Enabled, "false");    // additional infos - what 's going on
     conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "false"); // not that serious but mentioning
     conf.set(el::Level::Error, el::ConfigurationType::Enabled, "false");   // serious errors - but we can go on
     conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "false");   // asserts - stop - we can not go on
     switch (level) {
         case 6:
             conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 5:
             conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 4:
             conf.set(el::Level::Info, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 3:
             conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 2:
             conf.set(el::Level::Error, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 1:
             conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "true");
             [[fallthrough]];
         case 0:
             [[fallthrough]];
         default:;
     };
     el::Loggers::reconfigureLogger("default", conf);
 }
References conf.
Referenced by init().
setVerboseLevel()
void Logger::setVerboseLevel (unsigned short level) static
Definition at line 102 of file Logger.cpp.
{
     el::Loggers::setVerboseLevel(level);
 }
Member Data Documentation
conf
INITIALIZE_EASYLOGGINGPP el::Configurations Logger::conf static protected
Definition at line 50 of file Logger.h.
Referenced by init(), logToFile(), quiet(), and setLogLevel().
The documentation for this class was generated from the following files:
log/Logger.h
log/Logger.cpp