snode.c: net::EventDispatcher::FdSet Class Reference
net::EventDispatcher::FdSet Class Reference
Public Member Functions
FdSet ()
void set (int fd)
void clr (int fd)
int isSet (int fd) const
void zero ()
fd_set & get ()
Protected Attributes
fd_set registered
fd_set active
Detailed Description
Definition at line 41 of file EventDispatcher.h.
Constructor & Destructor Documentation
FdSet()
net::EventDispatcher::FdSet::FdSet ()
Definition at line 40 of file EventDispatcher.cpp.
{
         zero();
     }
References zero().
Member Function Documentation
clr()
void net::EventDispatcher::FdSet::clr (int fd)
Definition at line 48 of file EventDispatcher.cpp.
{
         FD_CLR(fd, &registered);
         FD_CLR(fd, &active);
     }
Referenced by net::EventDispatcher::suspend(), and net::EventDispatcher::unobserveDisabledEvents().
get()
fd_set & net::EventDispatcher::FdSet::get ()
Definition at line 62 of file EventDispatcher.cpp.
{
         active = registered;
         return active;
     }
Referenced by net::EventDispatcher::dispatchActiveEvents().
isSet()
int net::EventDispatcher::FdSet::isSet (int fd) const
Definition at line 53 of file EventDispatcher.cpp.
{
         return FD_ISSET(fd, &active);
     }
set()
void net::EventDispatcher::FdSet::set (int fd)
Definition at line 44 of file EventDispatcher.cpp.
{
         FD_SET(fd, &registered);
     }
Referenced by net::EventDispatcher::resume(), and net::EventDispatcher::unobserveDisabledEvents().
zero()
void net::EventDispatcher::FdSet::zero ()
Definition at line 57 of file EventDispatcher.cpp.
{
         FD_ZERO(&registered);
         FD_ZERO(&active);
     }
Referenced by FdSet().
Member Data Documentation
active
fd_set net::EventDispatcher::FdSet::active protected
Definition at line 53 of file EventDispatcher.h.
registered
fd_set net::EventDispatcher::FdSet::registered protected
Definition at line 52 of file EventDispatcher.h.
The documentation for this class was generated from the following files:
net/EventDispatcher.h
net/EventDispatcher.cpp