snode.c: net::socket::tcp::SocketConnectionBase Class Reference
net::socket::tcp::SocketConnectionBase Class Reference abstract
#include <SocketConnectionBase.h>
Public Member Functions
SocketConnectionBase ()=default
SocketConnectionBase (const SocketConnectionBase &)=delete
SocketConnectionBase & operator= (const SocketConnectionBase &)=delete
virtual ~SocketConnectionBase ()=default
virtual void enqueue (const char *junk, size_t junkLen)=0
virtual void enqueue (const std::string &data)=0
virtual void end (bool instantly=false)=0
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &attribute) const
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &&attribute) const
template<utils::InjectableAttribute Attribute>
constexpr bool getContext (std::function< void(Attribute &)> onFound) const
template<utils::InjectableAttribute Attribute>
constexpr void getContext (std::function< void(Attribute &)> onFound, std::function< void(const std::string &)> onNotFound) const
Private Attributes
utils::SingleAttributeInjector protocol
Detailed Description
Definition at line 30 of file SocketConnectionBase.h.
Constructor & Destructor Documentation
SocketConnectionBase() [1/2]
net::socket::tcp::SocketConnectionBase::SocketConnectionBase () default
SocketConnectionBase() [2/2]
net::socket::tcp::SocketConnectionBase::SocketConnectionBase (const SocketConnectionBase &) delete
~SocketConnectionBase()
virtual net::socket::tcp::SocketConnectionBase::~SocketConnectionBase () virtual default
Member Function Documentation
end()
virtual void net::socket::tcp::SocketConnectionBase::end (bool instantly = false) pure virtual
Implemented in net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >.
Referenced by http::ServerContext::terminateConnection().
enqueue() [1/2]
virtual void net::socket::tcp::SocketConnectionBase::enqueue (const char * junk, size_t junkLen) pure virtual
Implemented in net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >.
Referenced by http::ServerContext::sendResponseData().
enqueue() [2/2]
virtual void net::socket::tcp::SocketConnectionBase::enqueue (const std::string & data) pure virtual
Implemented in net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >.
getContext() [1/2]
template<utils::InjectableAttribute Attribute> constexpr bool net::socket::tcp::SocketConnectionBase::getContext (std::function< void(Attribute &)> onFound) const inline constexpr
Definition at line 54 of file SocketConnectionBase.h.
{
             return protocol.getAttribute<Attribute>([&onFound](Attribute& attribute) -> void {
                 onFound(attribute);
             });
         }
References utils::SingleAttributeInjector::getAttribute(), and protocol.
getContext() [2/2]
template<utils::InjectableAttribute Attribute> constexpr void net::socket::tcp::SocketConnectionBase::getContext (std::function< void(Attribute &)> onFound, std::function< void(const std::string &)> onNotFound) const inline constexpr
Definition at line 61 of file SocketConnectionBase.h.
{
             return protocol.getAttribute<Attribute>(
                 [&onFound](Attribute& attribute) -> void {
                     onFound(attribute);
                 },
                 [&onNotFound](const std::string& msg) -> void {
                     onNotFound(msg);
                 });
         }
References utils::SingleAttributeInjector::getAttribute(), and protocol.
operator=()
SocketConnectionBase& net::socket::tcp::SocketConnectionBase::operator= (const SocketConnectionBase &) delete
setContext() [1/2]
template<utils::InjectableAttribute Attribute> constexpr void net::socket::tcp::SocketConnectionBase::setContext (Attribute && attribute) const inline constexpr
Definition at line 49 of file SocketConnectionBase.h.
{
             protocol.setAttribute<Attribute>(attribute);
         }
References protocol, and utils::SingleAttributeInjector::setAttribute().
setContext() [2/2]
template<utils::InjectableAttribute Attribute> constexpr void net::socket::tcp::SocketConnectionBase::setContext (Attribute & attribute) const inline constexpr
Definition at line 44 of file SocketConnectionBase.h.
{
             protocol.setAttribute<Attribute>(attribute);
         }
References protocol, and utils::SingleAttributeInjector::setAttribute().
Member Data Documentation
protocol
utils::SingleAttributeInjector net::socket::tcp::SocketConnectionBase::protocol private
Definition at line 72 of file SocketConnectionBase.h.
Referenced by getContext(), and setContext().
The documentation for this class was generated from the following file:
net/socket/tcp/SocketConnectionBase.h