snode.c: http::websocket::WSServerContext Class Reference
http::websocket::WSServerContext Class Reference
#include <WSServerContext.h>
Public Member Functions
WSServerContext (const std::function< void(WSServerContext *wSServerContext, int opCode)> &_onMessageStart, const std::function< void(WSServerContext *wSServerContext, const char *junk, std::size_t junkLen)> &_onFrameData, const std::function< void(WSServerContext *wSServerContext)> &_onMessageEnd)
void messageStart (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0) override
void sendFrame (const char *message, std::size_t messageLength, uint32_t messageKey=0) override
void messageEnd (const char *message, std::size_t messageLength, uint32_t messageKey=0) override
void message (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0) override
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
Public Member Functions inherited from net::socket::stream::SocketProtocol
virtual ~SocketProtocol ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
void close ()
void switchSocketProtocol (SocketProtocol *socketProtocol)
Public Member Functions inherited from http::websocket::WSReceiver
void receive (char *junk, std::size_t junkLen)
Private Member Functions
void receiveFromPeer (const char *junk, std::size_t junkLen) override
void onReadError (int errnum) override
void onWriteError (int errnum) override
void onMessageStart (int opCode) override
void onFrameData (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onError (uint16_t errnum) override
void onFrameReady (char *frame, uint64_t frameLength) override
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0)
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
Private Attributes
bool closeReceived = false
bool closeSent = false
bool pingReceived = false
bool pongReceived = false
std::function< void(WSServerContext *wSServerContext, int opCode)> _onMessageStart = nullptr
std::function< void(WSServerContext *wSServerContext, const char *junk, std::size_t junkLen)> _onFrameData = nullptr
std::function< void(WSServerContext *wSServerContext)> _onMessageEnd = nullptr
Additional Inherited Members
Protected Types inherited from http::websocket::WSReceiver
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Protected Member Functions inherited from net::socket::stream::SocketProtocol
void take (const char *junk, std::size_t junkLen)
void setSocketConnection (SocketConnectionBase *socketConnection)
Protected Member Functions inherited from http::websocket::WSReceiver
void begin ()
uint64_t readOpcode (char *junk, uint64_t junkLen)
uint64_t readLength (char *junk, uint64_t junkLen)
uint64_t readELength (char *junk, uint64_t junkLen)
uint64_t readMaskingKey (char *junk, uint64_t junkLen)
uint64_t readPayload (char *junk, uint64_t junkLen)
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
bool markedForDelete = false
Protected Attributes inherited from http::websocket::WSReceiver
enum http::websocket::WSReceiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
Detailed Description
Definition at line 36 of file WSServerContext.h.
Constructor & Destructor Documentation
WSServerContext()
http::websocket::WSServerContext::WSServerContext (const std::function< void(WSServerContext *wSServerContext, int opCode)> & _onMessageStart, const std::function< void(WSServerContext *wSServerContext, const char *junk, std::size_t junkLen)> & _onFrameData, const std::function< void(WSServerContext *wSServerContext)> & _onMessageEnd)
Definition at line 34 of file WSServerContext.cpp.
         : _onMessageStart(_onMessageStart)
         , _onFrameData(_onFrameData)
         , _onMessageEnd(_onMessageEnd) {
     }
Member Function Documentation
close()
void http::websocket::WSServerContext::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 148 of file WSServerContext.cpp.
{
         char* closePayload = const_cast<char*>(reason);
         std::size_t closePayloadLength = reasonLength;
         if (statusCode != 0) {
             closePayload = new char[reasonLength + 2];
             *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
             closePayloadLength += 2;
             if (reasonLength > 0) {
                 memcpy(closePayload + 2, reason, reasonLength);
             }
         }
         message(8, closePayload, closePayloadLength);
         if (statusCode != 0) {
             delete[] closePayload;
         }
         closeSent = true;
     }
References closeSent, and message().
message()
void http::websocket::WSServerContext::message (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0) override virtual
Reimplemented from http::websocket::WSTransmitter.
Definition at line 61 of file WSServerContext.cpp.
{
         if (!closeSent) {
             WSTransmitter::message(opCode, message, messageLength, messageKey);
         }
     }
References closeSent, http::websocket::WSTransmitter::message(), and http::websocket::WSReceiver::opCode.
Referenced by close(), messageEnd(), messageStart(), sendFrame(), sendPing(), and sendPong().
messageEnd()
void http::websocket::WSServerContext::messageEnd (const char * message, std::size_t messageLength, uint32_t messageKey = 0) override virtual
Reimplemented from http::websocket::WSTransmitter.
Definition at line 55 of file WSServerContext.cpp.
{
         if (!closeSent) {
             WSTransmitter::messageEnd(message, messageLength, messageKey);
         }
     }
References closeSent, message(), and http::websocket::WSTransmitter::messageEnd().
messageStart()
void http::websocket::WSServerContext::messageStart (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0) override virtual
Reimplemented from http::websocket::WSTransmitter.
Definition at line 43 of file WSServerContext.cpp.
{
         if (!closeSent) {
             WSTransmitter::messageStart(opCode, message, messageLength, messageKey);
         }
     }
References closeSent, message(), http::websocket::WSTransmitter::messageStart(), and http::websocket::WSReceiver::opCode.
onError()
void http::websocket::WSServerContext::onError (uint16_t errnum) override private virtual
Implements http::websocket::WSReceiver.
Definition at line 139 of file WSServerContext.cpp.
{
         VLOG(0) << std::endl << "Message Error";
         close(errnum);
     }
References net::socket::stream::SocketProtocol::close().
onFrameData()
void http::websocket::WSServerContext::onFrameData (const char * junk, uint64_t junkLen) override private virtual
Implements http::websocket::WSReceiver.
Definition at line 103 of file WSServerContext.cpp.
{
         if (!closeReceived && !pingReceived && !pongReceived) {
             std::size_t junkOffset = 0;
             do {
                 std::size_t sendJunkLen = (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                 _onFrameData(this, junk + junkOffset, sendJunkLen);
                 junkOffset += sendJunkLen;
             } while (junkLen - junkOffset > 0);
         } else {
             // collect data for close and pong
         }
     }
References _onFrameData, closeReceived, pingReceived, and pongReceived.
onFrameReady()
void http::websocket::WSServerContext::onFrameReady (char * frame, uint64_t frameLength) override private virtual
Implements http::websocket::WSTransmitter.
Definition at line 144 of file WSServerContext.cpp.
{
         sendToPeer(frame, static_cast<std::size_t>(frameLength));
     }
References net::socket::stream::SocketProtocol::sendToPeer().
onMessageEnd()
void http::websocket::WSServerContext::onMessageEnd () override private virtual
Implements http::websocket::WSReceiver.
Definition at line 117 of file WSServerContext.cpp.
{
         if (closeReceived) {
             closeReceived = false;
             if (closeSent) { // active close
                 closeSent = false;
                 VLOG(0) << "Request close";
             } else { // passive close
                 VLOG(0) << "Closed";
                 close();
             }
             socketConnection->getSocketProtocol()->close();
         } else if (pingReceived) {
             pingReceived = false;
             sendPong();
         } else if (pongReceived) {
             pongReceived = false;
             /* Propagate connection alive to application? */
         } else {
             _onMessageEnd(this);
         }
     }
References _onMessageEnd, net::socket::stream::SocketProtocol::close(), closeReceived, closeSent, net::socket::stream::SocketConnectionBase::getSocketProtocol(), pingReceived, pongReceived, sendPong(), and net::socket::stream::SocketProtocol::socketConnection.
onMessageStart()
void http::websocket::WSServerContext::onMessageStart (int opCode) override private virtual
Implements http::websocket::WSReceiver.
Definition at line 79 of file WSServerContext.cpp.
{
         closeReceived = (opCode == 0x08);
         pingReceived = (opCode == 0x09);
         pongReceived = (opCode == 0x0A);
         switch (opCode) {
             case 0x08:
                 closeReceived = true;
                 VLOG(0) << "Close requested";
                 break;
             case 0x09:
                 pingReceived = true;
                 VLOG(0) << "Ping received";
                 break;
             case 0x0A:
                 pongReceived = true;
                 VLOG(0) << "Pong received";
                 break;
             default:
                 _onMessageStart(this, opCode);
                 break;
         }
     }
References _onMessageStart, closeReceived, http::websocket::WSReceiver::opCode, pingReceived, and pongReceived.
onReadError()
void http::websocket::WSServerContext::onReadError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 71 of file WSServerContext.cpp.
{
         VLOG(0) << "OnReadError: " << errnum;
     }
onWriteError()
void http::websocket::WSServerContext::onWriteError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 75 of file WSServerContext.cpp.
{
         VLOG(0) << "OnWriteError: " << errnum;
     }
receiveFromPeer()
void http::websocket::WSServerContext::receiveFromPeer (const char * junk, std::size_t junkLen) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 67 of file WSServerContext.cpp.
{
         WSReceiver::receive(const_cast<char*>(junk), junkLen);
     }
References http::websocket::WSReceiver::receive().
sendFrame()
void http::websocket::WSServerContext::sendFrame (const char * message, std::size_t messageLength, uint32_t messageKey = 0) override virtual
Reimplemented from http::websocket::WSTransmitter.
Definition at line 49 of file WSServerContext.cpp.
{
         if (!closeSent) {
             WSTransmitter::sendFrame(message, messageLength, messageKey);
         }
     }
References closeSent, message(), and http::websocket::WSTransmitter::sendFrame().
sendPing()
void http::websocket::WSServerContext::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 170 of file WSServerContext.cpp.
{
         message(9, reason, reasonLength);
     }
References message().
sendPong()
void http::websocket::WSServerContext::sendPong (const char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 174 of file WSServerContext.cpp.
{
         message(10, reason, reasonLength);
     }
References message().
Referenced by onMessageEnd().
Member Data Documentation
_onFrameData
std::function<void(WSServerContext* wSServerContext, const char* junk, std::size_t junkLen)> http::websocket::WSServerContext::_onFrameData = nullptr private
Definition at line 77 of file WSServerContext.h.
Referenced by onFrameData().
_onMessageEnd
std::function<void(WSServerContext* wSServerContext)> http::websocket::WSServerContext::_onMessageEnd = nullptr private
Definition at line 78 of file WSServerContext.h.
Referenced by onMessageEnd().
_onMessageStart
std::function<void(WSServerContext* wSServerContext, int opCode)> http::websocket::WSServerContext::_onMessageStart = nullptr private
Definition at line 76 of file WSServerContext.h.
Referenced by onMessageStart().
closeReceived
bool http::websocket::WSServerContext::closeReceived = false private
Definition at line 70 of file WSServerContext.h.
Referenced by onFrameData(), onMessageEnd(), and onMessageStart().
closeSent
bool http::websocket::WSServerContext::closeSent = false private
Definition at line 71 of file WSServerContext.h.
Referenced by close(), message(), messageEnd(), messageStart(), onMessageEnd(), and sendFrame().
pingReceived
bool http::websocket::WSServerContext::pingReceived = false private
Definition at line 73 of file WSServerContext.h.
Referenced by onFrameData(), onMessageEnd(), and onMessageStart().
pongReceived
bool http::websocket::WSServerContext::pongReceived = false private
Definition at line 74 of file WSServerContext.h.
Referenced by onFrameData(), onMessageEnd(), and onMessageStart().
The documentation for this class was generated from the following files:
http/server/ws/WSServerContext.h
http/server/ws/WSServerContext.cpp