snode.c: net::timer::IntervalTimer Class Reference
net::timer::IntervalTimer Class Reference
#include <IntervalTimer.h>
Public Member Functions
IntervalTimer (const std::function< void(const void *arg, const std::function< void()> &stop)> &dispatcher, const struct timeval &timeout, const void *arg)
IntervalTimer (const std::function< void(const void *arg)> &dispatcher, const struct timeval &timeout, const void *arg)
~IntervalTimer () override=default
IntervalTimer & operator= (const IntervalTimer &timer)=delete
bool dispatch () override
Public Member Functions inherited from net::timer::Timer
Timer (const Timer &)=delete
Timer & operator= (const Timer &timer)=delete
void cancel ()
Private Attributes
std::function< void(const void *arg, const std::function< void()> &stop)> dispatcherS = nullptr
std::function< void(const void *arg)> dispatcherC = nullptr
Additional Inherited Members
Static Public Member Functions inherited from net::timer::Timer
static IntervalTimer & continousTimer (const std::function< void(const void *arg, const std::function< void()> &stop)> &dispatcher, const struct timeval &timeout, const void *arg)
static IntervalTimer & continousTimer (const std::function< void(const void *arg)> &dispatcher, const struct timeval &timeout, const void *arg)
static SingleshotTimer & singleshotTimer (const std::function< void(const void *arg)> &dispatcher, const struct timeval &timeout, const void *arg)
Protected Member Functions inherited from net::timer::Timer
Timer (const struct timeval &timeout, const void *arg)
virtual ~Timer ()=default
void update ()
void destroy () override
struct timeval & timeout () override
operator struct timeval () const override
Protected Attributes inherited from net::timer::Timer
const void * arg
Detailed Description
Definition at line 30 of file IntervalTimer.h.
Constructor & Destructor Documentation
IntervalTimer() [1/2]
net::timer::IntervalTimer::IntervalTimer (const std::function< void(const void *arg, const std::function< void()> &stop)> & dispatcher, const struct timeval & timeout, const void * arg) inline
Definition at line 32 of file IntervalTimer.h.
             : Timer(timeout, arg)
             , dispatcherS(dispatcher) {
         }
IntervalTimer() [2/2]
net::timer::IntervalTimer::IntervalTimer (const std::function< void(const void *arg)> & dispatcher, const struct timeval & timeout, const void * arg) inline
Definition at line 39 of file IntervalTimer.h.
             : Timer(timeout, arg)
             , dispatcherC(dispatcher) {
         }
~IntervalTimer()
net::timer::IntervalTimer::~IntervalTimer () override default
Member Function Documentation
dispatch()
bool net::timer::IntervalTimer::dispatch () inline override virtual
Implements net::TimerEventReceiver.
Definition at line 48 of file IntervalTimer.h.
{
             bool stop = false;
             if (dispatcherS) {
                 dispatcherS(arg, [&stop]() -> void {
                     stop = true;
                 });
                 if (stop) {
                     cancel();
                 } else {
                     update();
                 }
             } else if (dispatcherC) {
                 dispatcherC(arg);
                 update();
             }
             return !stop;
         }
References net::timer::Timer::arg, net::timer::Timer::cancel(), dispatcherC, dispatcherS, and net::timer::Timer::update().
operator=()
IntervalTimer& net::timer::IntervalTimer::operator= (const IntervalTimer & timer) delete
Member Data Documentation
dispatcherC
std::function<void(const void* arg)> net::timer::IntervalTimer::dispatcherC = nullptr private
Definition at line 70 of file IntervalTimer.h.
Referenced by dispatch().
dispatcherS
std::function<void(const void* arg, const std::function<void()>& stop)> net::timer::IntervalTimer::dispatcherS = nullptr private
Definition at line 69 of file IntervalTimer.h.
Referenced by dispatch().
The documentation for this class was generated from the following file:
net/timer/IntervalTimer.h