snode.c: express::Response Class Reference
express::Response Class Reference
#include <Response.h>
Public Member Functions
Response ()=delete
Response (const http::Response &res)
void sendFile (const std::string &file, const std::function< void(int err)> &onError=nullptr)
void download (const std::string &file, const std::function< void(int err)> &onError=nullptr)
void download (const std::string &file, const std::string &name, const std::function< void(int err)> &onError=nullptr)
void redirect (const std::string &name)
void redirect (int status, const std::string &name)
void sendStatus (int status)
Public Member Functions inherited from http::Response
void send (const char *buffer, size_t size)
void send (const std::string &text)
void end ()
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=false)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=false)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & type (const std::string &type)
Protected Member Functions
void disable () override
Protected Member Functions inherited from http::Response
Response (ServerContext *serverContext)
virtual ~Response ()=default
void enqueue (const char *buf, size_t len)
void enqueue (const std::string &str)
void sendHeader ()
virtual void reset ()
Protected Attributes
FileReader * fileReader = nullptr
Protected Attributes inherited from http::Response
ServerContext * serverContext
bool keepAlive = true
bool sendHeaderInProgress = false
bool headersSent = false
int responseStatus = 0
size_t contentSent = 0
size_t contentLength = 0
std::map< std::string, std::string > headers
std::map< std::string, CookieOptions > cookies
Detailed Description
Definition at line 33 of file Response.h.
Constructor & Destructor Documentation
Response() [1/2]
express::Response::Response () delete
Response() [2/2]
express::Response::Response (const http::Response & res)
Definition at line 34 of file Response.cpp.
         : http::Response(res) {
     }
Member Function Documentation
disable()
void express::Response::disable () override protected virtual
Reimplemented from http::Response.
Definition at line 111 of file Response.cpp.
{
         http::Response::disable();
         if (fileReader != nullptr) {
             fileReader->disable();
             fileReader = nullptr;
         }
     }
References http::Response::disable(), FileReader::disable(), and fileReader.
download() [1/2]
void express::Response::download (const std::string & file, const std::function< void(int err)> & onError = nullptr)
Definition at line 83 of file Response.cpp.
{
         std::string name = file;
         if (name[0] == '/') {
             name.erase(0, 1);
         }
         download(file, name, onError);
     }
download() [2/2]
void express::Response::download (const std::string & file, const std::string & name, const std::function< void(int err)> & onError = nullptr)
Definition at line 93 of file Response.cpp.
{
         set({{"Content-Disposition", "attachment; filename=\"" + name + "\""}});
         sendFile(file, onError);
     }
References sendFile(), and http::Response::set().
redirect() [1/2]
void express::Response::redirect (const std::string & name)
Definition at line 98 of file Response.cpp.
{
         redirect(302, name);
     }
redirect() [2/2]
void express::Response::redirect (int status, const std::string & name)
Definition at line 102 of file Response.cpp.
{
         this->status(status).set({{"Location", name}});
         end();
     }
References http::Response::end(), http::Response::set(), and http::Response::status().
sendFile()
void express::Response::sendFile (const std::string & file, const std::function< void(int err)> & onError = nullptr)
Definition at line 38 of file Response.cpp.
{
         std::string absolutFileName = file;
         if (std::filesystem::exists(absolutFileName)) {
             std::error_code ec;
             absolutFileName = std::filesystem::canonical(absolutFileName);
             if (std::filesystem::is_regular_file(absolutFileName, ec) && !ec) {
                 headers.insert({{"Content-Type", MimeTypes::contentType(absolutFileName)},
                                 {"Last-Modified", httputils::file_mod_http_date(absolutFileName)}});
                 headers.insert_or_assign("Content-Length", std::to_string(std::filesystem::file_size(absolutFileName)));
                 fileReader = FileReader::read(
                     absolutFileName,
                     [this](char* data, int length) -> void {
                         enqueue(data, length);
                     },
                     [this, onError](int err) -> void {
                         if (onError) {
                             onError(err);
                         }
                         if (err != 0) {
                             serverContext->terminateConnection();
                         }
                     });
             } else {
                 responseStatus = 403;
                 errno = EACCES;
                 serverContext->terminateConnection();
                 if (onError) {
                     onError(EACCES);
                 }
                 end();
             }
         } else {
             responseStatus = 404;
             errno = ENOENT;
             serverContext->terminateConnection();
             if (onError) {
                 onError(ENOENT);
             }
             end();
         }
     }
References MimeTypes::contentType(), http::Response::end(), http::Response::enqueue(), httputils::file_mod_http_date(), fileReader, http::Response::headers, FileReader::read(), http::Response::responseStatus, http::Response::serverContext, and http::ServerContext::terminateConnection().
Referenced by download().
sendStatus()
void express::Response::sendStatus (int status)
Definition at line 107 of file Response.cpp.
{
         this->status(status).send(StatusCode::reason(status));
     }
References StatusCode::reason(), http::Response::send(), and http::Response::status().
Member Data Documentation
fileReader
FileReader* express::Response::fileReader = nullptr protected
Definition at line 51 of file Response.h.
Referenced by disable(), and sendFile().
The documentation for this class was generated from the following files:
express/Response.h
express/Response.cpp