snode.c: express::middleware::StaticMiddleware Class Reference
express::middleware::StaticMiddleware Class Reference
#include <StaticMiddleware.h>
Public Member Functions
StaticMiddleware (const StaticMiddleware &)=delete
StaticMiddleware & operator= (const StaticMiddleware &)=delete
StaticMiddleware & clearStdHeaders ()
StaticMiddleware & setStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::string &field, const std::string &value)
StaticMiddleware & appendStdCookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
StaticMiddleware & alwaysClose ()
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router & operator= (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::string &path, const Router &router)
Router & use (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::string &path, const Router &router)
Router & all (const Router &router)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::string &path, const Router &router)
Router & get (const Router &router)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::string &path, const Router &router)
Router & put (const Router &router)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::string &path, const Router &router)
Router & post (const Router &router)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::string &path, const Router &router)
Router & del (const Router &router)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::string &path, const Router &router)
Router & connect (const Router &router)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::string &path, const Router &router)
Router & options (const Router &router)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::string &path, const Router &router)
Router & trace (const Router &router)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::string &path, const Router &router)
Router & patch (const Router &router)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::string &path, const Router &router)
Router & head (const Router &router)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Protected Member Functions
StaticMiddleware (const std::string &root)
Protected Member Functions inherited from express::Router
void dispatch (express::Request &req, express::Response &res)
void completed (const express::Request &req, const express::Response &res)
Static Protected Member Functions
static class StaticMiddleware & instance (const std::string &root)
Protected Attributes
std::string root
std::map< std::string, std::string > stdHeaders
std::map< std::string, http::CookieOptions > stdCookies = {}
bool forceClose = false
Friends
class StaticMiddleware & StaticMiddleware (const std::string &root)
Detailed Description
Definition at line 29 of file StaticMiddleware.h.
Constructor & Destructor Documentation
StaticMiddleware() [1/2]
express::middleware::StaticMiddleware::StaticMiddleware (const std::string & root) protected
Definition at line 32 of file StaticMiddleware.cpp.
         : root(root) {
         use([&stdHeaders = this->stdHeaders, &stdCookies = this->stdCookies, &forceClose = this->forceClose] MIDDLEWARE(req, res, next) {
             if (req.method == "GET") {
                 if (forceClose || ((req.connectionState == ConnectionState::Close) || (req.httpMajor == 0 && req.httpMinor == 9) ||
                                    (req.httpMajor == 1 && req.httpMinor == 0 && req.connectionState != ConnectionState::Keep) ||
                                    (req.httpMajor == 1 && req.httpMinor == 1 && req.connectionState == ConnectionState::Close))) {
                     res.set("Connection", "Close");
                 } else {
                     res.set("Connection", "Keep-Alive");
                 }
                 res.set(stdHeaders);
                 for (const auto& [value, options] : stdCookies) {
                     res.cookie(value, options.getValue(), options.getOptions());
                 }
                 next();
             } else {
                 LOG(DEBUG) << "Wrong method " << req.method;
                 res.set("Connection", "Close");
                 res.sendStatus(400);
             }
         });
         use([] MIDDLEWARE(req, res, next) {
             if (req.url == "/") {
                 LOG(INFO) << "REDIRECT " + req.url + " -> " + "/index.html";
                 res.redirect(308, "/index.html");
             } else {
                 next();
             }
         });
         use([this] APPLICATION(req, res) {
             LOG(INFO) << "GET " + req.url + " -> " + this->root + req.url;
             res.sendFile(this->root + req.url, [&req](int ret) -> void {
                 if (ret != 0) {
                     PLOG(ERROR) << req.url;
                 }
             });
         });
     }
References for(), forceClose, MIDDLEWARE, express::Router::options(), stdCookies, stdHeaders, and express::Router::use().
StaticMiddleware() [2/2]
express::middleware::StaticMiddleware::StaticMiddleware (const StaticMiddleware &) delete
Member Function Documentation
alwaysClose()
class StaticMiddleware & express::middleware::StaticMiddleware::alwaysClose ()
Definition at line 106 of file StaticMiddleware.cpp.
{
         this->forceClose = true;
         return *this;
     }
appendStdCookie()
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdCookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 98 of file StaticMiddleware.cpp.
{
         this->stdCookies.insert({name, http::CookieOptions(value, options)});
         return *this;
     }
appendStdHeaders() [1/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 86 of file StaticMiddleware.cpp.
{
         this->stdHeaders.insert(stdHeaders.begin(), stdHeaders.end());
         return *this;
     }
appendStdHeaders() [2/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::string & field, const std::string & value)
Definition at line 92 of file StaticMiddleware.cpp.
{
         this->stdHeaders[field] = value;
         return *this;
     }
clearStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::clearStdHeaders ()
Definition at line 74 of file StaticMiddleware.cpp.
{
         this->stdHeaders.clear();
         return *this;
     }
instance()
class StaticMiddleware & express::middleware::StaticMiddleware::instance (const std::string & root) static protected
Definition at line 115 of file StaticMiddleware.cpp.
{
         if (!staticMiddlewares.contains(root)) {
             staticMiddlewares[root] = std::shared_ptr<StaticMiddleware>(new StaticMiddleware(root));
         }
         return *staticMiddlewares[root];
     }
References express::middleware::StaticMiddleware(), and express::middleware::staticMiddlewares.
operator=()
StaticMiddleware& express::middleware::StaticMiddleware::operator= (const StaticMiddleware &) delete
setStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::setStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 80 of file StaticMiddleware.cpp.
{
         this->stdHeaders = stdHeaders;
         return *this;
     }
Friends And Related Function Documentation
StaticMiddleware
class StaticMiddleware& StaticMiddleware (const std::string & root) friend
Definition at line 124 of file StaticMiddleware.cpp.
{
         return StaticMiddleware::instance(root);
     }
Member Data Documentation
forceClose
bool express::middleware::StaticMiddleware::forceClose = false protected
Definition at line 53 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
root
std::string express::middleware::StaticMiddleware::root protected
Definition at line 49 of file StaticMiddleware.h.
stdCookies
std::map<std::string, http::CookieOptions> express::middleware::StaticMiddleware::stdCookies = {} protected
Definition at line 52 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
stdHeaders
std::map<std::string, std::string> express::middleware::StaticMiddleware::stdHeaders protected
Initial value:
= {
            {"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}}
Definition at line 50 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
The documentation for this class was generated from the following files:
express/middleware/StaticMiddleware.h
express/middleware/StaticMiddleware.cpp