snode.c: net::DynamicLoader Class Reference
net::DynamicLoader Class Reference
#include <DynamicLoader.h>
Static Public Member Functions
static void * dlOpen (const std::string &libFile, int flags)
static void dlCloseDelayed (void *handle)
static int dlClose (void *handle)
template<typename Symbol >
static Symbol dlSym (void *handle, const std::string &symbol)
static char * dlError ()
Private Member Functions
DynamicLoader ()=delete
~DynamicLoader ()=delete
Static Private Member Functions
static int execDlClose (void *handle)
static void execDlCloseDeleyed ()
static void execDlCloseAll ()
Static Private Attributes
static std::map< void *, std::string > dlOpenedLibraries
static std::set< void * > registeredForDlClose
Friends
class EventLoop
Detailed Description
Definition at line 34 of file DynamicLoader.h.
Constructor & Destructor Documentation
DynamicLoader()
net::DynamicLoader::DynamicLoader () private delete
~DynamicLoader()
net::DynamicLoader::~DynamicLoader () private delete
Member Function Documentation
dlClose()
int net::DynamicLoader::dlClose (void * handle) static
Definition at line 60 of file DynamicLoader.cpp.
{
         int ret = 0;
         if (handle != nullptr) {
             if (dlOpenedLibraries.contains(handle) && !registeredForDlClose.contains(handle)) {
                 VLOG(0) << "dlCloseSync: " << dlOpenedLibraries[handle];
                 ret = execDlClose(handle);
             } else {
                 VLOG(0) << "dlCloseSync: Handle" << handle << " opened using dlOpen.";
             }
         } else {
             VLOG(0) << "dlCloseSync: Handle is nullptr";
         }
         return ret;
     }
References dlOpenedLibraries, execDlClose(), and registeredForDlClose.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::add(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
dlCloseDelayed()
void net::DynamicLoader::dlCloseDelayed (void * handle) static
Definition at line 46 of file DynamicLoader.cpp.
{
         if (handle != nullptr) {
             if (dlOpenedLibraries.contains(handle) && !registeredForDlClose.contains(handle)) {
                 VLOG(0) << "dlCloseDelayed: " << dlOpenedLibraries[handle];
                 registeredForDlClose.insert(handle);
             } else {
                 VLOG(0) << "dlCloseDelayed: Handle" << handle << " opened using dlOpen.";
             }
         } else {
             VLOG(0) << "dlCloseDelayed: Handle is nullptr";
         }
     }
References dlOpenedLibraries, and registeredForDlClose.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
dlError()
char * net::DynamicLoader::dlError () static
Definition at line 77 of file DynamicLoader.cpp.
{
         return net::system::dlerror();
     }
References net::system::dlerror().
Referenced by execDlCloseAll(), execDlCloseDeleyed(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load().
dlOpen()
void * net::DynamicLoader::dlOpen (const std::string & libFile, int flags) static
Definition at line 34 of file DynamicLoader.cpp.
{
         VLOG(0) << "dlOpen: " << libFile;
         void* handle = net::system::dlopen(libFile.c_str(), flags);
         if (handle != nullptr) {
             dlOpenedLibraries[handle] = libFile;
         }
         return handle;
     }
References net::system::dlopen(), and dlOpenedLibraries.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load().
dlSym()
template<typename Symbol > static Symbol net::DynamicLoader::dlSym (void * handle, const std::string & symbol) inline static
Definition at line 46 of file DynamicLoader.h.
{
             return reinterpret_cast<Symbol>(net::system::dlsym(handle, symbol.c_str()));
         }
References net::system::dlsym().
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load().
execDlClose()
int net::DynamicLoader::execDlClose (void * handle) static private
Definition at line 81 of file DynamicLoader.cpp.
{
         int ret = -1;
         if (handle != nullptr) {
             if (dlOpenedLibraries.contains(handle)) {
                 VLOG(0) << "execDLClose: " << dlOpenedLibraries[handle];
                 ret = net::system::dlclose(handle);
                 dlOpenedLibraries.erase(handle);
             }
         }
         return ret;
     }
References net::system::dlclose(), and dlOpenedLibraries.
Referenced by dlClose(), execDlCloseAll(), and execDlCloseDeleyed().
execDlCloseAll()
void net::DynamicLoader::execDlCloseAll () static private
Definition at line 109 of file DynamicLoader.cpp.
{
         execDlCloseDeleyed();
         std::map<void*, std::string>::iterator it = dlOpenedLibraries.begin();
         while (it != dlOpenedLibraries.end()) {
             std::map<void*, std::string>::iterator tmpIt = it;
             ++it;
             int ret = execDlClose(tmpIt->first);
             if (ret != 0) {
                 VLOG(0) << "Error execDlCloseAll: " << net::DynamicLoader::dlError();
             }
         }
     }
References dlError(), dlOpenedLibraries, execDlClose(), and execDlCloseDeleyed().
Referenced by net::EventLoop::_free().
execDlCloseDeleyed()
void net::DynamicLoader::execDlCloseDeleyed () static private
Definition at line 97 of file DynamicLoader.cpp.
{
         for (void* handle : registeredForDlClose) {
             int ret = execDlClose(handle);
             if (ret != 0) {
                 VLOG(0) << "Error execDeleyedDlClose: " << net::DynamicLoader::dlError();
             }
         }
         registeredForDlClose.clear();
     }
References dlError(), execDlClose(), and registeredForDlClose.
Referenced by net::EventLoop::_tick(), and execDlCloseAll().
Friends And Related Function Documentation
EventLoop
friend class EventLoop friend
Definition at line 60 of file DynamicLoader.h.
Member Data Documentation
dlOpenedLibraries
std::map< void *, std::string > net::DynamicLoader::dlOpenedLibraries static private
Definition at line 57 of file DynamicLoader.h.
Referenced by dlClose(), dlCloseDelayed(), dlOpen(), execDlClose(), and execDlCloseAll().
registeredForDlClose
std::set< void * > net::DynamicLoader::registeredForDlClose static private
Definition at line 58 of file DynamicLoader.h.
Referenced by dlClose(), dlCloseDelayed(), and execDlCloseDeleyed().
The documentation for this class was generated from the following files:
net/DynamicLoader.h
net/DynamicLoader.cpp