snode.c: http::server::RequestParser Class Reference
http::server::RequestParser Class Reference
#include <RequestParser.h>
Public Member Functions
RequestParser (const std::function< void(void)> &onStart, const std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> &onRequest, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> &onHeader, const std::function< void(char *, std::size_t)> &onContent, const std::function< void()> &onParsed, const std::function< void(int status, const std::string &reason)> &onError)
void reset () override
Public Member Functions inherited from http::Parser
Parser (enum HTTPCompliance compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()=default
void parse (const char *junk, std::size_t junkLen)
Protected Member Functions
virtual bool methodSupported (const std::string &method)
void begin () override
enum Parser::ParserState parseStartLine (const std::string &line) override
enum Parser::ParserState parseHeader () override
enum Parser::ParserState parseContent (char *content, std::size_t size) override
void parsingFinished ()
enum Parser::ParserState parsingError (int code, const std::string &reason) override
Protected Attributes
std::set< std::string > supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"}
std::string method
std::string url
std::string httpVersion
std::map< std::string, std::string > cookies
std::map< std::string, std::string > queries
int httpMajor = 0
int httpMinor = 0
std::function< void(void)> onStart
std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> onRequest
std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> onHeader
std::function< void(char *, std::size_t)> onContent
std::function< void()> onParsed
std::function< void(int status, const std::string &reason)> onError
Protected Attributes inherited from http::Parser
enum http::Parser::HTTPCompliance HTTPCompliance
enum http::Parser::ParserState parserState = ParserState::BEGIN
char * content = nullptr
std::size_t contentLength = 0
std::map< std::string, std::string > headers
Additional Inherited Members
Protected Types inherited from http::Parser
enum class HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum class ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Static Protected Attributes inherited from http::Parser
static std::regex httpVersionRegex
Detailed Description
Definition at line 36 of file RequestParser.h.
Constructor & Destructor Documentation
RequestParser()
http::server::RequestParser::RequestParser (const std::function< void(void)> & onStart, const std::function< void(const std::string &, const std::string &, const std::string &, int, int, const std::map< std::string, std::string > &)> & onRequest, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, std::string > &)> & onHeader, const std::function< void(char *, std::size_t)> & onContent, const std::function< void()> & onParsed, const std::function< void(int status, const std::string &reason)> & onError)
Definition at line 34 of file RequestParser.cpp.
         : onStart(onStart)
         , onRequest(onRequest)
         , onHeader(onHeader)
         , onContent(onContent)
         , onParsed(onParsed)
         , onError(onError) {
     }
Member Function Documentation
begin()
void http::server::RequestParser::begin () override protected virtual
Implements http::Parser.
Definition at line 61 of file RequestParser.cpp.
{
         onStart();
     }
References onStart.
methodSupported()
virtual bool http::server::RequestParser::methodSupported (const std::string & method) inline protected virtual
Definition at line 52 of file RequestParser.h.
{
             return supportedMethods.contains(method);
         }
References method, and supportedMethods.
parseContent()
enum Parser::ParserState http::server::RequestParser::parseContent (char * content, std::size_t size) override protected virtual
Implements http::Parser.
Definition at line 61 of file RequestParser.cpp.
{
         onContent(content, size);
         parsingFinished();
         return ParserState::BEGIN;
     }
parseHeader()
enum Parser::ParserState http::server::RequestParser::parseHeader () override protected virtual
Implements http::Parser.
Definition at line 61 of file RequestParser.cpp.
{
         for (auto& [field, value] : Parser::headers) {
             if (field != "cookie") {
                 if (field == "content-length") {
                     Parser::contentLength = std::stoi(value);
                 }
             } else {
                 std::string cookiesLine = value;
                 while (!cookiesLine.empty()) {
                     std::string cookieLine;
                     std::tie(cookieLine, cookiesLine) = httputils::str_split(cookiesLine, ',');
                     while (!cookieLine.empty()) {
                         std::string cookie;
                         std::tie(cookie, cookieLine) = httputils::str_split(cookieLine, ';');
                         std::string name;
                         std::string value;
                         std::tie(name, value) = httputils::str_split(cookie, '=');
                         httputils::str_trimm(name);
                         httputils::str_trimm(value);
                         cookies.insert({name, value});
                     }
                 }
             }
         }
         Parser::headers.erase("cookie");
         onHeader(Parser::headers, cookies);
         enum Parser::ParserState parserState = Parser::ParserState::BODY;
         if (contentLength == 0) {
             parsingFinished();
             parserState = ParserState::BEGIN;
         }
         return parserState;
     }
parseStartLine()
enum Parser::ParserState http::server::RequestParser::parseStartLine (const std::string & line) override protected virtual
Implements http::Parser.
Definition at line 61 of file RequestParser.cpp.
{
         enum Parser::ParserState parserState = Parser::ParserState::HEADER;
         if (!line.empty()) {
             std::string remaining;
             std::tie(method, remaining) = httputils::str_split(line, ' ');
             std::tie(url, httpVersion) = httputils::str_split(remaining, ' ');
             std::string queriesLine;
             std::tie(std::ignore, queriesLine) = httputils::str_split(url, '?');
             if (!methodSupported(method)) {
                 parserState = parsingError(400, "Bad request method");
             } else if (url.empty() || url.front() != '/') {
                 parserState = parsingError(400, "Malformed request");
             } else {
                 std::smatch httpVersionMatch;
                 if (!std::regex_match(httpVersion, httpVersionMatch, httpVersionRegex)) {
                     parserState = parsingError(400, "Wrong protocol-version");
                 } else {
                     httpMajor = std::stoi(httpVersionMatch.str(1));
                     httpMinor = std::stoi(httpVersionMatch.str(2));
                     while (!queriesLine.empty()) {
                         std::string query;
                         std::tie(query, queriesLine) = httputils::str_split(queriesLine, '&');
                         queries.insert(httputils::str_split(query, '='));
                     }
                     onRequest(method, url, httpVersion, httpMajor, httpMinor, queries);
                 }
             }
         } else {
             parserState = parsingError(400, "Request-line empty");
         }
         return parserState;
     }
parsingError()
enum Parser::ParserState http::server::RequestParser::parsingError (int code, const std::string & reason) override protected virtual
Implements http::Parser.
Definition at line 155 of file RequestParser.cpp.
{
         onError(code, reason);
         return ParserState::ERROR;
     }
References onParsed, and reset().
parsingFinished()
void http::server::RequestParser::parsingFinished () protected
Definition at line 155 of file RequestParser.cpp.
{
         onParsed();
         reset();
     }
reset()
void http::server::RequestParser::reset () override virtual
Reimplemented from http::Parser.
Definition at line 50 of file RequestParser.cpp.
{
         Parser::reset();
         method.clear();
         url.clear();
         httpVersion.clear();
         queries.clear();
         cookies.clear();
         httpMajor = 0;
         httpMinor = 0;
     }
References cookies, httpMajor, httpMinor, httpVersion, method, queries, http::Parser::reset(), and url.
Referenced by parsingError().
Member Data Documentation
cookies
std::map<std::string, std::string> http::server::RequestParser::cookies protected
Definition at line 75 of file RequestParser.h.
Referenced by reset().
httpMajor
int http::server::RequestParser::httpMajor = 0 protected
Definition at line 77 of file RequestParser.h.
Referenced by reset().
httpMinor
int http::server::RequestParser::httpMinor = 0 protected
Definition at line 78 of file RequestParser.h.
Referenced by reset().
httpVersion
std::string http::server::RequestParser::httpVersion protected
Definition at line 74 of file RequestParser.h.
Referenced by reset().
method
std::string http::server::RequestParser::method protected
Definition at line 72 of file RequestParser.h.
Referenced by methodSupported(), and reset().
onContent
std::function<void(char*, std::size_t)> http::server::RequestParser::onContent protected
Definition at line 85 of file RequestParser.h.
onError
std::function<void(int status, const std::string& reason)> http::server::RequestParser::onError protected
Definition at line 87 of file RequestParser.h.
onHeader
std::function<void(const std::map<std::string, std::string>&, const std::map<std::string, std::string>&)> http::server::RequestParser::onHeader protected
Definition at line 84 of file RequestParser.h.
onParsed
std::function<void()> http::server::RequestParser::onParsed protected
Definition at line 86 of file RequestParser.h.
Referenced by parsingError().
onRequest
std::function<void(const std::string&, const std::string&, const std::string&, int, int, const std::map<std::string, std::string>&)> http::server::RequestParser::onRequest protected
Definition at line 83 of file RequestParser.h.
onStart
std::function<void(void)> http::server::RequestParser::onStart protected
Definition at line 81 of file RequestParser.h.
Referenced by begin().
queries
std::map<std::string, std::string> http::server::RequestParser::queries protected
Definition at line 76 of file RequestParser.h.
Referenced by reset().
supportedMethods
std::set<std::string> http::server::RequestParser::supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"} protected
Definition at line 69 of file RequestParser.h.
Referenced by methodSupported().
url
std::string http::server::RequestParser::url protected
Definition at line 73 of file RequestParser.h.
Referenced by reset().
The documentation for this class was generated from the following files:
http/server/RequestParser.h
http/server/RequestParser.cpp