snode.c: net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
#include <SocketConnection.h>
Public Types
using SocketReader = SocketReaderT
using SocketWriter = SocketWriterT
using SocketAddress = SocketAddressT
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketConnection_v)
SocketConnection ()=delete
SocketConnection (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::function< void(SocketConnection *socketConnection)> &onDisconnect)
~SocketConnection () override
void enqueue (const char *junk, size_t junkLen) override
void enqueue (const std::string &data) override
void end (bool instantly=false) override
const SocketAddress & getRemoteAddress () const
void setRemoteAddress (const SocketAddress &remoteAddress)
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress)
Public Member Functions inherited from net::socket::stream::SocketConnectionBase
SocketConnectionBase ()=default
SocketConnectionBase (const SocketConnectionBase &)=delete
SocketConnectionBase & operator= (const SocketConnectionBase &)=delete
virtual ~SocketConnectionBase ()=default
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &attribute) const
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &&attribute) const
template<utils::InjectableAttribute Attribute>
constexpr bool getContext (std::function< void(Attribute &)> onFound) const
template<utils::InjectableAttribute Attribute>
constexpr void getContext (std::function< void(Attribute &)> onFound, std::function< void(const std::string &)> onNotFound) const
Private Member Functions
void unobserved () override
Private Attributes
SocketAddress remoteAddress {}
SocketAddress localAddress {}
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onDisconnect
bool isDynamic
Static Private Attributes
static void * lastAllocAddress = nullptr
Detailed Description
template<typename SocketReaderT, typename SocketWriterT, typename SocketAddressT>
class net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >
Definition at line 33 of file SocketConnection.h.
Member Typedef Documentation
SocketAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 40 of file SocketConnection.h.
SocketReader
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::SocketReader = SocketReaderT
Definition at line 38 of file SocketConnection.h.
SocketWriter
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::SocketWriter = SocketWriterT
Definition at line 39 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnection () delete
SocketConnection() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnection (const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection)> & onConstruct, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection)> & onDestruct, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection, int errnum)> & onWriteError, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT > *socketConnection)> & onDisconnect) inline
Definition at line 54 of file SocketConnection.h.
             : SocketReader(
                   [this, onRead](const char* junk, ssize_t junkLen) -> void {
                       onRead(this, junk, junkLen);
                   },
                   [this, onReadError](int errnum) -> void {
                       onReadError(this, errnum);
                   })
             , SocketWriter([this, onWriteError](int errnum) -> void {
                 onWriteError(this, errnum);
             })
             , onDestruct(onDestruct)
             , onDisconnect(onDisconnect)
             , isDynamic(this == lastAllocAddress) {
             onConstruct(this);
         }
~SocketConnection()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::~SocketConnection () inline override
Definition at line 76 of file SocketConnection.h.
{
             onDestruct(this);
         }
Member Function Documentation
end()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::end (bool instantly = false) inline override virtual
Implements net::socket::stream::SocketConnectionBase.
Definition at line 98 of file SocketConnection.h.
{
             SocketReader::disable();
             if (instantly) {
                 SocketWriter::disable();
             }
         }
enqueue() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::enqueue (const char * junk, size_t junkLen) inline override virtual
Implements net::socket::stream::SocketConnectionBase.
Definition at line 90 of file SocketConnection.h.
{
             SocketWriter::enqueue(junk, junkLen);
         }
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::enqueue().
enqueue() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::enqueue (const std::string & data) inline override virtual
Implements net::socket::stream::SocketConnectionBase.
Definition at line 94 of file SocketConnection.h.
{
             enqueue(data.c_str(), data.size());
         }
getLocalAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::getLocalAddress () const inline
Definition at line 113 of file SocketConnection.h.
{
             return localAddress;
         }
getRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::getRemoteAddress () const inline
Definition at line 105 of file SocketConnection.h.
{
             return remoteAddress;
         }
operator delete()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::operator delete (void * socketConnection_v) inline
Definition at line 48 of file SocketConnection.h.
{
             free(socketConnection_v);
         }
operator new()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void* net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::operator new (size_t size) inline
Definition at line 42 of file SocketConnection.h.
{
             SocketConnection<SocketReader, SocketWriter, SocketAddress>::lastAllocAddress = malloc(size);
             return SocketConnection<SocketReader, SocketWriter, SocketAddress>::lastAllocAddress;
         }
setLocalAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::setLocalAddress (const SocketAddress & localAddress) inline
Definition at line 117 of file SocketConnection.h.
{
             this->localAddress = localAddress;
         }
Referenced by net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >::acceptEvent().
setRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::setRemoteAddress (const SocketAddress & remoteAddress) inline
Definition at line 109 of file SocketConnection.h.
{
             this->remoteAddress = remoteAddress;
         }
Referenced by net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >::acceptEvent().
unobserved()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::unobserved () inline override private
Definition at line 81 of file SocketConnection.h.
{
             onDisconnect(this);
             if (isDynamic) {
                 delete this;
             }
         }
Member Data Documentation
isDynamic
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > bool net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::isDynamic private
Definition at line 128 of file SocketConnection.h.
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::unobserved().
lastAllocAddress
template<typename SocketReader , typename SocketWriter , typename SocketAddress > void * net::socket::stream::SocketConnection< SocketReader, SocketWriter, SocketAddress >::lastAllocAddress = nullptr static private
Definition at line 129 of file SocketConnection.h.
localAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::localAddress {} private
Definition at line 123 of file SocketConnection.h.
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::getLocalAddress(), and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::setLocalAddress().
onDestruct
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::onDestruct private
Definition at line 125 of file SocketConnection.h.
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::~SocketConnection().
onDisconnect
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::onDisconnect private
Definition at line 126 of file SocketConnection.h.
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::unobserved().
remoteAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::remoteAddress {} private
Definition at line 122 of file SocketConnection.h.
Referenced by net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::getRemoteAddress(), and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >::setRemoteAddress().
The documentation for this class was generated from the following file:
net/socket/sock_stream/SocketConnection.h