snode.c: net::socket::stream::SocketConnector< SocketConnectionT > Class Template Reference
net::socket::stream::SocketConnector< SocketConnectionT > Class Template Reference
#include <SocketConnector.h>
Protected Types
using SocketConnection = SocketConnectionT
using Socket = typename SocketConnection::Socket
Protected Member Functions
void * operator new (size_t size)
void operator delete (void *socketListener_v)
SocketConnector (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
SocketConnector ()=delete
SocketConnector (const SocketConnector &)=delete
SocketConnector & operator= (const SocketConnector &)=delete
virtual ~SocketConnector ()=default
virtual void connect (const std::map< std::string, std::any > &options, const std::function< void(int err)> &onError, const typename SocketConnection::Socket::SocketAddress &bindAddress=typename SocketConnection::Socket::SocketAddress())
void connectEvent () override
void readEvent () override
void unobserved () override
Protected Member Functions inherited from net::ConnectEventReceiver
ConnectEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver ()
Protected Attributes
std::function< void(SocketConnection *socketConnection)> onConstruct
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onConnect
std::function< void(SocketConnection *socketConnection)> onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
std::function< void(int err)> onError
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
time_t lastTriggered = 0
Private Attributes
SocketConnection * socketConnection = nullptr
bool connected = false
std::map< std::string, std::any > options
bool isDynamic
Static Private Attributes
static void * lastAllocAddress = nullptr
Friends
template<typename SocketConnectorT >
class SocketClient
Additional Inherited Members
Public Member Functions inherited from net::ConnectEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Public Member Functions inherited from net::ReadEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Detailed Description
template<typename SocketConnectionT>
class net::socket::stream::SocketConnector< SocketConnectionT >
Definition at line 40 of file SocketConnector.h.
Member Typedef Documentation
Socket
template<typename SocketConnectionT > using net::socket::stream::SocketConnector< SocketConnectionT >::Socket = typename SocketConnection::Socket protected
Definition at line 46 of file SocketConnector.h.
SocketConnection
template<typename SocketConnectionT > using net::socket::stream::SocketConnector< SocketConnectionT >::SocketConnection = SocketConnectionT protected
Definition at line 45 of file SocketConnector.h.
Constructor & Destructor Documentation
SocketConnector() [1/3]
template<typename SocketConnectionT > net::socket::stream::SocketConnector< SocketConnectionT >::SocketConnector (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options) inline protected
Definition at line 58 of file SocketConnector.h.
             : ConnectEventReceiver()
             , ReadEventReceiver()
             , SocketConnection::Socket()
             , onConstruct(onConstruct)
             , onDestruct(onDestruct)
             , onConnect(onConnect)
             , onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options)
             , isDynamic(this == SocketConnector::lastAllocAddress) {
         }
SocketConnector() [2/3]
template<typename SocketConnectionT > net::socket::stream::SocketConnector< SocketConnectionT >::SocketConnector () protected delete
SocketConnector() [3/3]
template<typename SocketConnectionT > net::socket::stream::SocketConnector< SocketConnectionT >::SocketConnector (const SocketConnector< SocketConnectionT > &) protected delete
~SocketConnector()
template<typename SocketConnectionT > virtual net::socket::stream::SocketConnector< SocketConnectionT >::~SocketConnector () protected virtual default
Reimplemented in net::socket::stream::tls::SocketConnector< SocketT >.
Member Function Documentation
connect()
template<typename SocketConnectionT > virtual void net::socket::stream::SocketConnector< SocketConnectionT >::connect (const std::map< std::string, std::any > & options, const std::function< void(int err)> & onError, const typename SocketConnection::Socket::SocketAddress & bindAddress = typename SocketConnection::Socket::SocketAddress()) inline protected virtual
Reimplemented in net::socket::stream::tls::SocketConnector< SocketT >.
Definition at line 88 of file SocketConnector.h.
{
             this->onError = onError;
             std::string host = "";
             unsigned short port = 0;
             for (auto& [name, value] : options) {
                 if (name == "host") {
                     host = std::any_cast<const char*>(value);
                 } else if (name == "port") {
                     port = std::any_cast<int>(value);
                 }
             }
             typename SocketConnection::Socket::SocketAddress server(host, port);
             errno = 0;
             Socket::open(
                 [this, &bindAddress, &server, &onError](int errnum) -> void {
                     if (errnum > 0) {
                         onError(errnum);
                         delete this;
                     } else {
                         Socket::bind(bindAddress, [this, &server, &onError](int errnum) -> void {
                             if (errnum > 0) {
                                 onError(errnum);
                                 delete this;
                             } else {
                                 int ret = ::connect(Socket::getFd(), &server.getSockAddr(), server.getSockAddrLen());
                                 if (ret == 0 || errno == EINPROGRESS) {
                                     ConnectEventReceiver::enable();
                                     socketConnection =
                                         new SocketConnection(onConstruct, onDestruct, onRead, onReadError, onWriteError, onDisconnect);
                                 } else {
                                     onError(errno);
                                     delete this;
                                 }
                             }
                         });
                     }
                 },
                 SOCK_NONBLOCK);
         }
Referenced by net::socket::stream::SocketClient< legacy::SocketConnector< net::socket::ipv6::tcp::Socket > >::connect(), net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect(), and net::socket::stream::tls::SocketConnector< SocketT >::connect().
connectEvent()
template<typename SocketConnectionT > void net::socket::stream::SocketConnector< SocketConnectionT >::connectEvent () inline override protected virtual
Implements net::ConnectEventReceiver.
Definition at line 137 of file SocketConnector.h.
{
             errno = 0;
             int cErrno = 0;
             socklen_t cErrnoLen = sizeof(cErrno);
             int err = getsockopt(Socket::getFd(), SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
             if (err == 0) {
                 if (cErrno != EINPROGRESS) {
                     ConnectEventReceiver::disable();
                     if (cErrno == 0) {
                         typename Socket::SocketAddress::SockAddr localAddress{};
                         socklen_t localAddressLength = sizeof(localAddress);
                         typename Socket::SocketAddress::SockAddr remoteAddress{};
                         socklen_t remoteAddressLength = sizeof(remoteAddress);
                         if (getsockname(Socket::getFd(), reinterpret_cast<sockaddr*>(&localAddress), &localAddressLength) == 0) {
                             if (getpeername(Socket::getFd(), reinterpret_cast<sockaddr*>(&remoteAddress), &remoteAddressLength) == 0) {
                                 ReadEventReceiver::enable();
                                 socketConnection->open(Socket::getFd(), Descriptor::FLAGS::dontClose);
                                 socketConnection->setRemoteAddress(typename Socket::SocketAddress(remoteAddress));
                                 socketConnection->setLocalAddress(typename Socket::SocketAddress(localAddress));
                                 socketConnection->ReadEventReceiver::enable();
                                 onError(0);
                                 onConnect(socketConnection);
                                 connected = true;
                             } else {
                                 onError(errno);
                             }
                         } else {
                             onError(errno);
                         }
                     } else {
                         errno = cErrno;
                         onError(cErrno);
                     }
                 }
             } else {
                 onError(errno);
             }
         }
operator delete()
template<typename SocketConnectionT > void net::socket::stream::SocketConnector< SocketConnectionT >::operator delete (void * socketListener_v) inline protected
Definition at line 54 of file SocketConnector.h.
{
             free(socketListener_v);
         }
operator new()
template<typename SocketConnectionT > void* net::socket::stream::SocketConnector< SocketConnectionT >::operator new (size_t size) inline protected
Definition at line 48 of file SocketConnector.h.
{
             SocketConnector<SocketConnection>::lastAllocAddress = malloc(size);
             return SocketConnector<SocketConnection>::lastAllocAddress;
         }
operator=()
template<typename SocketConnectionT > SocketConnector& net::socket::stream::SocketConnector< SocketConnectionT >::operator= (const SocketConnector< SocketConnectionT > &) protected delete
readEvent()
template<typename SocketConnectionT > void net::socket::stream::SocketConnector< SocketConnectionT >::readEvent () inline override protected virtual
Implements net::ReadEventReceiver.
Definition at line 186 of file SocketConnector.h.
{
             ReadEventReceiver::disable();
         }
unobserved()
template<typename SocketConnectionT > void net::socket::stream::SocketConnector< SocketConnectionT >::unobserved () inline override protected virtual
Implements net::EventReceiver.
Definition at line 190 of file SocketConnector.h.
{
             if (!connected) {
                 delete socketConnection;
             }
             if (isDynamic) {
                 delete this;
             }
         }
Friends And Related Function Documentation
SocketClient
template<typename SocketConnectionT > template<typename SocketConnectorT > friend class SocketClient friend
Definition at line 220 of file SocketConnector.h.
Member Data Documentation
connected
template<typename SocketConnectionT > bool net::socket::stream::SocketConnector< SocketConnectionT >::connected = false private
Definition at line 212 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connectEvent(), and net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::unobserved().
isDynamic
template<typename SocketConnectionT > bool net::socket::stream::SocketConnector< SocketConnectionT >::isDynamic private
Definition at line 216 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::unobserved().
lastAllocAddress
template<typename SocketConnectionT > void * net::socket::stream::SocketConnector< SocketConnectionT >::lastAllocAddress = nullptr static private
Definition at line 217 of file SocketConnector.h.
onConnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnector< SocketConnectionT >::onConnect protected
Definition at line 202 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connectEvent().
onConstruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnector< SocketConnectionT >::onConstruct protected
Definition at line 200 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
onDestruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnector< SocketConnectionT >::onDestruct protected
Definition at line 201 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
onDisconnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketConnector< SocketConnectionT >::onDisconnect protected
Definition at line 203 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
onError
template<typename SocketConnectionT > std::function<void(int err)> net::socket::stream::SocketConnector< SocketConnectionT >::onError protected
Definition at line 208 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect(), and net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connectEvent().
onRead
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, const char* junk, ssize_t junkLen)> net::socket::stream::SocketConnector< SocketConnectionT >::onRead protected
Definition at line 204 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
onReadError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketConnector< SocketConnectionT >::onReadError protected
Definition at line 205 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
onWriteError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketConnector< SocketConnectionT >::onWriteError protected
Definition at line 206 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
options
template<typename SocketConnectionT > std::map<std::string, std::any> net::socket::stream::SocketConnector< SocketConnectionT >::options private
Definition at line 214 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect().
socketConnection
template<typename SocketConnectionT > SocketConnection* net::socket::stream::SocketConnector< SocketConnectionT >::socketConnection = nullptr private
Definition at line 211 of file SocketConnector.h.
Referenced by net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connect(), net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::connectEvent(), and net::socket::stream::SocketConnector< net::socket::stream::tls::SocketConnection< SocketT > >::unobserved().
The documentation for this class was generated from the following file:
net/socket/sock_stream/SocketConnector.h