snode.c: web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT > Class Template Reference
web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT > Class Template Reference abstract
#include <SubProtocolFactorySelector.h>
Public Types
enum class Role { SERVER , CLIENT }
using SubProtocolFactory = SubProtocolFactoryT
Public Member Functions
SubProtocolFactory * select (const std::string &subProtocolName)
void unload (SubProtocolFactory *subProtocolFactory)
Protected Member Functions
SubProtocolFactorySelector ()=default
SubProtocolFactorySelector (const SubProtocolFactorySelector &)=delete
SubProtocolFactorySelector & operator= (const SubProtocolFactorySelector &)=delete
virtual ~SubProtocolFactorySelector ()=default
virtual SubProtocolFactory * load (const std::string &subProtocolName)=0
SubProtocolFactory * load (const std::string &subProtocolName, Role role)
void addSubProtocolSearchPath (const std::string &searchPath)
void allowDlOpen ()
void linkSubProtocol (const std::string &subProtocolName, SubProtocolFactory *(*linkedPlugin)())
Private Member Functions
void add (SubProtocolFactory *subProtocolFactory, void *handle=nullptr)
Private Attributes
std::map< std::string, SubProtocolPlugin< SubProtocolFactory > > subProtocolPlugins
std::map< std::string, SubProtocolFactory *(*)()> linkedSubProtocolFactories
std::list< std::string > searchPaths
bool onlyLinked = false
Detailed Description
template<typename SubProtocolFactoryT>
class web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >
Definition at line 42 of file SubProtocolFactorySelector.h.
Member Typedef Documentation
SubProtocolFactory
template<typename SubProtocolFactoryT > using web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::SubProtocolFactory = SubProtocolFactoryT
Definition at line 44 of file SubProtocolFactorySelector.h.
Member Enumeration Documentation
Role
template<typename SubProtocolFactoryT > enum web::websocket::SubProtocolFactorySelector::Role strong
Enumerator
SERVER
CLIENT
Definition at line 46 of file SubProtocolFactorySelector.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
SubProtocolFactorySelector() [1/2]
template<typename SubProtocolFactoryT > web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::SubProtocolFactorySelector () protected default
SubProtocolFactorySelector() [2/2]
template<typename SubProtocolFactoryT > web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::SubProtocolFactorySelector (const SubProtocolFactorySelector< SubProtocolFactoryT > &) protected delete
~SubProtocolFactorySelector()
template<typename SubProtocolFactoryT > virtual web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::~SubProtocolFactorySelector () protected virtual default
Member Function Documentation
add()
template<typename SubProtocolFactoryT > void web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::add (SubProtocolFactory * subProtocolFactory, void * handle = nullptr) inline private
Definition at line 57 of file SubProtocolFactorySelector.h.
{
             SubProtocolPlugin<SubProtocolFactory> subProtocolPlugin = {.subProtocolFactory = subProtocolFactory, .handle = handle};
             if (subProtocolFactory != nullptr) {
                 const auto [it, success] = subProtocolPlugins.insert({subProtocolFactory->name(), subProtocolPlugin});
                 if (!success) {
                     VLOG(0) << "Subprotocol already existing: not using " << subProtocolFactory->name();
                     subProtocolFactory->destroy();
                     if (handle != nullptr) {
                         net::DynamicLoader::dlClose(handle);
                     }
                 }
             } else if (handle != nullptr) {
                 net::DynamicLoader::dlClose(handle);
             }
         }
References net::DynamicLoader::dlClose(), web::websocket::SubProtocolPlugin< SubProtocolFactory >::subProtocolFactory, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::subProtocolPlugins.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select().
addSubProtocolSearchPath()
template<typename SubProtocolFactoryT > void web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::addSubProtocolSearchPath (const std::string & searchPath) inline protected
Definition at line 106 of file SubProtocolFactorySelector.h.
{
             searchPaths.push_back(searchPath);
         }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::searchPaths.
allowDlOpen()
template<typename SubProtocolFactoryT > void web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::allowDlOpen () inline protected
Definition at line 146 of file SubProtocolFactorySelector.h.
{
             onlyLinked = false;
         }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::onlyLinked.
linkSubProtocol()
template<typename SubProtocolFactoryT > void web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkSubProtocol (const std::string & subProtocolName, SubProtocolFactory *(*)() linkedPlugin) inline protected
Definition at line 150 of file SubProtocolFactorySelector.h.
{
             onlyLinked = true;
             linkedSubProtocolFactories[subProtocolName] = linkedPlugin;
         }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkedSubProtocolFactories, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::onlyLinked.
Referenced by web::websocket::client::SubProtocolFactorySelector::link(), and web::websocket::server::SubProtocolFactorySelector::link().
load() [1/2]
template<typename SubProtocolFactoryT > virtual SubProtocolFactory* web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load (const std::string & subProtocolName) protected pure virtual
Implemented in web::websocket::server::SubProtocolFactorySelector, and web::websocket::client::SubProtocolFactorySelector.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select().
load() [2/2]
template<typename SubProtocolFactoryT > SubProtocolFactory* web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load (const std::string & subProtocolName, Role role) inline protected
Definition at line 77 of file SubProtocolFactorySelector.h.
{
             SubProtocolFactory* subProtocolFactory = nullptr;
             for (const std::string& searchPath : searchPaths) {
                 void* handle =
                     net::DynamicLoader::dlOpen(searchPath + "/libsnodec-websocket-" + subProtocolName + ".so", RTLD_LAZY | RTLD_LOCAL);
                 if (handle != nullptr) {
                     SubProtocolFactory* (*getSubProtocolFactory)() = net::DynamicLoader::dlSym<SubProtocolFactory* (*) ()>(
                         handle, subProtocolName + (role == Role::SERVER ? "Server" : "Client") + "SubProtocolFactory");
                     if (getSubProtocolFactory != nullptr) {
                         subProtocolFactory = getSubProtocolFactory();
                         if (subProtocolFactory != nullptr) {
                             add(subProtocolFactory, handle);
                             break;
                         } else {
                             net::DynamicLoader::dlClose(handle);
                         }
                     } else {
                         VLOG(0) << "Optaining function \"plugin()\" in plugin failed: " << net::DynamicLoader::dlError();
                     }
                 } else {
                     VLOG(0) << "Error dlopen: " << net::DynamicLoader::dlError();
                 }
             }
             return subProtocolFactory;
         }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::add(), net::DynamicLoader::dlClose(), net::DynamicLoader::dlError(), net::DynamicLoader::dlOpen(), net::DynamicLoader::dlSym(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::searchPaths, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::SERVER.
operator=()
template<typename SubProtocolFactoryT > SubProtocolFactorySelector& web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::operator= (const SubProtocolFactorySelector< SubProtocolFactoryT > &) protected delete
select()
template<typename SubProtocolFactoryT > SubProtocolFactory* web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select (const std::string & subProtocolName) inline
Definition at line 111 of file SubProtocolFactorySelector.h.
{
             SubProtocolFactory* subProtocolFactory = nullptr;
             if (subProtocolPlugins.contains(subProtocolName)) {
                 subProtocolFactory = subProtocolPlugins[subProtocolName].subProtocolFactory;
             } else if (linkedSubProtocolFactories.contains(subProtocolName)) {
                 SubProtocolFactory* (*plugin)() = linkedSubProtocolFactories[subProtocolName];
                 subProtocolFactory = plugin();
                 if (subProtocolFactory != nullptr) {
                     add(subProtocolFactory, nullptr);
                 }
             } else if (!onlyLinked) {
                 subProtocolFactory = load(subProtocolName);
             }
             return subProtocolFactory;
         }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::add(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkedSubProtocolFactories, web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::onlyLinked, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::subProtocolPlugins.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create(), and web::websocket::server::SocketContextUpgradeFactory::create().
unload()
template<typename SubProtocolFactoryT > void web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload (SubProtocolFactory * subProtocolFactory) inline
Definition at line 129 of file SubProtocolFactorySelector.h.
{
             std::string name = subProtocolFactory->name();
             if (subProtocolPlugins.contains(name)) {
                 subProtocolFactory->destroy();
                 SubProtocolPlugin<SubProtocolFactory>& subProtocolPlugin = subProtocolPlugins[name];
                 if (subProtocolPlugin.handle != nullptr) {
                     net::DynamicLoader::dlClose(subProtocolPlugin.handle);
                 }
                 subProtocolPlugins.erase(name);
             }
         }
References net::DynamicLoader::dlClose(), web::websocket::SubProtocolPlugin< SubProtocolFactory >::handle, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::subProtocolPlugins.
Referenced by web::websocket::client::SubProtocolFactory::deleteSubProtocol(), and web::websocket::server::SubProtocolFactory::deleteSubProtocol().
Member Data Documentation
linkedSubProtocolFactories
template<typename SubProtocolFactoryT > std::map<std::string, SubProtocolFactory* (*) ()> web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkedSubProtocolFactories private
Definition at line 157 of file SubProtocolFactorySelector.h.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkSubProtocol(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select().
onlyLinked
template<typename SubProtocolFactoryT > bool web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::onlyLinked = false private
Definition at line 160 of file SubProtocolFactorySelector.h.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::allowDlOpen(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkSubProtocol(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select().
searchPaths
template<typename SubProtocolFactoryT > std::list<std::string> web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::searchPaths private
Definition at line 158 of file SubProtocolFactorySelector.h.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::addSubProtocolSearchPath(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
subProtocolPlugins
template<typename SubProtocolFactoryT > std::map<std::string, SubProtocolPlugin<SubProtocolFactory> > web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::subProtocolPlugins private
Definition at line 156 of file SubProtocolFactorySelector.h.
Referenced by web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::add(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
The documentation for this class was generated from the following file:
web/websocket/SubProtocolFactorySelector.h