snode.c: net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT > Class Template Reference
net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketContextFactory = SocketContextFactoryT
using SocketConnector = SocketConnectorT
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
SocketClient (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketClient ()=default
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(int)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Protected Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory
Private Member Functions
SocketClient ()=delete
Private Attributes
std::function< void(const SocketAddress &, const SocketAddress &)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename SocketContextFactoryT, typename SocketConnectorT>
class net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >
Definition at line 36 of file SocketClient.h.
Member Typedef Documentation
SocketAddress
template<typename SocketContextFactoryT , typename SocketConnectorT > using net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketAddress = typename SocketConnection::Socket::SocketAddress
Definition at line 43 of file SocketClient.h.
SocketConnection
template<typename SocketContextFactoryT , typename SocketConnectorT > using net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketConnection = typename SocketConnector::SocketConnection
Definition at line 42 of file SocketClient.h.
SocketConnector
template<typename SocketContextFactoryT , typename SocketConnectorT > using net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketConnector = SocketConnectorT
Definition at line 41 of file SocketClient.h.
SocketContextFactory
template<typename SocketContextFactoryT , typename SocketConnectorT > using net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketContextFactory = SocketContextFactoryT
Definition at line 40 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient() [1/2]
template<typename SocketContextFactoryT , typename SocketConnectorT > net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketClient () private delete
SocketClient() [2/2]
template<typename SocketContextFactoryT , typename SocketConnectorT > net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::SocketClient (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 45 of file SocketClient.h.
                                                                 {{}})
             : socketContextFactory(std::make_shared<SocketContextFactory>())
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketClient()
template<typename SocketContextFactoryT , typename SocketConnectorT > virtual net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::~SocketClient () virtual default
Member Function Documentation
connect() [1/2]
template<typename SocketContextFactoryT , typename SocketConnectorT > void net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect (const SocketAddress & remoteAddress, const SocketAddress & bindAddress, const std::function< void(int)> & onError) const inline
Definition at line 58 of file SocketClient.h.
{
             SocketConnector* socketConnector = new SocketConnector(socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketConnector->connect(remoteAddress, bindAddress, onError);
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnect, net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnected, net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onDisconnect, net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::options, and net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::socketContextFactory.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect().
connect() [2/2]
template<typename SocketContextFactoryT , typename SocketConnectorT > void net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect (const SocketAddress & remoteAddress, const std::function< void(int)> & onError) const inline
Definition at line 64 of file SocketClient.h.
{
             connect(remoteAddress, SocketAddress(), onError);
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect().
getSocketContextFactory()
template<typename SocketContextFactoryT , typename SocketConnectorT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::getSocketContextFactory () inline
Definition at line 80 of file SocketClient.h.
{
             return socketContextFactory;
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::socketContextFactory.
onConnect()
template<typename SocketContextFactoryT , typename SocketConnectorT > void net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect) inline
Definition at line 68 of file SocketClient.h.
{
             _onConnect = onConnect;
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnect.
onConnected()
template<typename SocketContextFactoryT , typename SocketConnectorT > void net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 72 of file SocketClient.h.
{
             _onConnected = onConnected;
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnected.
onDisconnect()
template<typename SocketContextFactoryT , typename SocketConnectorT > void net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 76 of file SocketClient.h.
{
             _onDisconnect = onDisconnect;
         }
References net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename SocketContextFactoryT , typename SocketConnectorT > std::function<void(const SocketAddress&, const SocketAddress&)> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnect private
Definition at line 88 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect(), and net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onConnect().
_onConnected
template<typename SocketContextFactoryT , typename SocketConnectorT > std::function<void(SocketConnection*)> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onConnected private
Definition at line 89 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect(), and net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onConnected().
_onDisconnect
template<typename SocketContextFactoryT , typename SocketConnectorT > std::function<void(SocketConnection*)> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::_onDisconnect private
Definition at line 90 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect(), and net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::onDisconnect().
options
template<typename SocketContextFactoryT , typename SocketConnectorT > std::map<std::string, std::any> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::options private
Definition at line 92 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect().
socketContextFactory
template<typename SocketContextFactoryT , typename SocketConnectorT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::socketContextFactory protected
Definition at line 85 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::connect(), and net::socket::stream::SocketClient< SocketContextFactoryT, SocketConnectorT >::getSocketContextFactory().
The documentation for this class was generated from the following file:
net/socket/stream/SocketClient.h