snode.c: web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT > Class Template Reference
web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT > Class Template Reference abstract
#include <SubProtocol.h>
Public Types
using SocketContext = SocketContextT
using SubProtocolFactory = SubProtocolFactoryT
Public Member Functions
virtual ~SubProtocol ()=default
void sendMessage (const char *message, std::size_t messageLength)
void sendMessage (const std::string &message)
void sendMessageStart (const char *message, std::size_t messageLength)
void sendMessageStart (const std::string &message)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageFrame (const std::string &message)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessageEnd (const std::string &message)
void sendPing (char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
const std::string & getName ()
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *junk, std::size_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onPongReceived ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onConnected ()=0
virtual void onDisconnected ()=0
void setSocketContext (SocketContext *serverContext)
SocketContext * getSocketContext ()
void setSubProtocolFactory (SubProtocolFactory *subProtocolFactory)
SubProtocolFactory * getSubProtocolFactory ()
Protected Types
enum class Role { SERVER , CLIENT }
Protected Member Functions
SubProtocol (const std::string &name)
SubProtocol ()=delete
SubProtocol (const SubProtocol &)=delete
SubProtocol & operator= (const SubProtocol &)=delete
Protected Attributes
SocketContext * context
SubProtocolFactory * subProtocolFactory
const std::string name
Detailed Description
template<typename SocketContextT, typename SubProtocolFactoryT>
class web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >
Definition at line 33 of file SubProtocol.h.
Member Typedef Documentation
SocketContext
template<typename SocketContextT , typename SubProtocolFactoryT > using web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::SocketContext = SocketContextT
Definition at line 35 of file SubProtocol.h.
SubProtocolFactory
template<typename SocketContextT , typename SubProtocolFactoryT > using web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::SubProtocolFactory = SubProtocolFactoryT
Definition at line 36 of file SubProtocol.h.
Member Enumeration Documentation
Role
template<typename SocketContextT , typename SubProtocolFactoryT > enum web::websocket::SubProtocol::Role strong protected
Enumerator
SERVER
CLIENT
Definition at line 39 of file SubProtocol.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
SubProtocol() [1/3]
template<typename SocketContextT , typename SubProtocolFactoryT > web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::SubProtocol (const std::string & name) inline protected
Definition at line 41 of file SubProtocol.h.
             : name(name) {
         }
SubProtocol() [2/3]
template<typename SocketContextT , typename SubProtocolFactoryT > web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::SubProtocol () protected delete
SubProtocol() [3/3]
template<typename SocketContextT , typename SubProtocolFactoryT > web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::SubProtocol (const SubProtocol< SocketContextT, SubProtocolFactoryT > &) protected delete
~SubProtocol()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::~SubProtocol () virtual default
Reimplemented in web::websocket::server::SubProtocol, and web::websocket::client::SubProtocol.
Member Function Documentation
getLocalAddressAsString()
template<typename SocketContextT , typename SubProtocolFactoryT > std::string web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getLocalAddressAsString () const inline
Definition at line 93 of file SubProtocol.h.
{
             return context->getLocalAddressAsString();
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
getName()
template<typename SocketContextT , typename SubProtocolFactoryT > const std::string& web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getName () inline
Definition at line 100 of file SubProtocol.h.
{
             return name;
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::name.
Referenced by web::websocket::server::ChannelManager::subscribe().
getRemoteAddressAsString()
template<typename SocketContextT , typename SubProtocolFactoryT > std::string web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getRemoteAddressAsString () const inline
Definition at line 96 of file SubProtocol.h.
{
             return context->getRemoteAddressAsString();
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
getSocketContext()
template<typename SocketContextT , typename SubProtocolFactoryT > SocketContext* web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSocketContext () inline
Definition at line 119 of file SubProtocol.h.
{
             return context;
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
getSubProtocolFactory()
template<typename SocketContextT , typename SubProtocolFactoryT > SubProtocolFactory* web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSubProtocolFactory () inline
Definition at line 127 of file SubProtocol.h.
{
             return subProtocolFactory;
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::subProtocolFactory.
Referenced by web::websocket::client::SocketContextUpgradeFactory::destroy(), and web::websocket::server::SocketContextUpgradeFactory::destroy().
onConnected()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onConnected () pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onDisconnected()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onDisconnected () pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onMessageData()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onMessageData (const char * junk, std::size_t junkLen) pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onMessageEnd()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onMessageEnd () pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onMessageError()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onMessageError (uint16_t errnum) pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onMessageStart()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onMessageStart (int opCode) pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
onPongReceived()
template<typename SocketContextT , typename SubProtocolFactoryT > virtual void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::onPongReceived () pure virtual
Implemented in web::websocket::server::SubProtocol, web::websocket::client::SubProtocol, web::websocket::subprotocol::echo::server::Echo, and web::websocket::subprotocol::echo::client::Echo.
operator=()
template<typename SocketContextT , typename SubProtocolFactoryT > SubProtocol& web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::operator= (const SubProtocol< SocketContextT, SubProtocolFactoryT > &) protected delete
sendClose()
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) inline
Definition at line 89 of file SubProtocol.h.
{
             context->sendClose(statusCode, reason, reasonLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
sendMessage() [1/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessage (const char * message, std::size_t messageLength) inline
Definition at line 53 of file SubProtocol.h.
{
             context->sendMessage(2, message, messageLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
sendMessage() [2/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessage (const std::string & message) inline
Definition at line 57 of file SubProtocol.h.
{
             context->sendMessage(1, message.data(), message.length());
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
sendMessageEnd() [1/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageEnd (const char * message, std::size_t messageLength) inline
Definition at line 77 of file SubProtocol.h.
{
             context->sendMessageEnd(message, messageLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
Referenced by web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageEnd().
sendMessageEnd() [2/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageEnd (const std::string & message) inline
Definition at line 81 of file SubProtocol.h.
{
             sendMessageEnd(message.data(), message.length());
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageEnd().
sendMessageFrame() [1/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageFrame (const char * message, std::size_t messageLength) inline
Definition at line 69 of file SubProtocol.h.
{
             context->sendMessageFrame(message, messageLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
Referenced by web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageFrame().
sendMessageFrame() [2/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageFrame (const std::string & message) inline
Definition at line 73 of file SubProtocol.h.
{
             sendMessageFrame(message.data(), message.length());
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageFrame().
sendMessageStart() [1/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageStart (const char * message, std::size_t messageLength) inline
Definition at line 61 of file SubProtocol.h.
{
             context->sendMessageStart(2, message, messageLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
sendMessageStart() [2/2]
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageStart (const std::string & message) inline
Definition at line 65 of file SubProtocol.h.
{
             context->sendMessageStart(1, message.data(), message.length());
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
sendPing()
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendPing (char * reason = nullptr, std::size_t reasonLength = 0) inline
Definition at line 85 of file SubProtocol.h.
{
             context->sendPing(reason, reasonLength);
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
setSocketContext()
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSocketContext (SocketContext * serverContext) inline
Definition at line 115 of file SubProtocol.h.
{
             context = serverContext;
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create(), and web::websocket::server::SocketContextUpgradeFactory::create().
setSubProtocolFactory()
template<typename SocketContextT , typename SubProtocolFactoryT > void web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSubProtocolFactory (SubProtocolFactory * subProtocolFactory) inline
Definition at line 123 of file SubProtocol.h.
{
             this->subProtocolFactory = subProtocolFactory;
         }
References web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::subProtocolFactory.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create(), and web::websocket::server::SocketContextUpgradeFactory::create().
Member Data Documentation
context
template<typename SocketContextT , typename SubProtocolFactoryT > SocketContext* web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::context protected
Definition at line 132 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getLocalAddressAsString(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getRemoteAddressAsString(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSocketContext(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendClose(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessage(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageEnd(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageFrame(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendMessageStart(), web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::sendPing(), and web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSocketContext().
name
template<typename SocketContextT , typename SubProtocolFactoryT > const std::string web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::name protected
Definition at line 135 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getName().
subProtocolFactory
template<typename SocketContextT , typename SubProtocolFactoryT > SubProtocolFactory* web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::subProtocolFactory protected
Definition at line 133 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::getSubProtocolFactory(), and web::websocket::SubProtocol< SocketContextT, SubProtocolFactoryT >::setSubProtocolFactory().
The documentation for this class was generated from the following file:
web/websocket/SubProtocol.h