snode.c: net::stream::Sink Class Reference
net::stream::Sink Class Reference abstract
#include <Sink.h>
Public Member Functions
Sink ()
virtual ~Sink ()
virtual void receive (const char *junk, std::size_t junkLen)=0
virtual void eof ()=0
virtual void error (int errnum)=0
void connect (Source &source)
void disconnect (Source &source)
Protected Attributes
Source * source
Detailed Description
Definition at line 32 of file Sink.h.
Constructor & Destructor Documentation
Sink()
net::stream::Sink::Sink ()
Definition at line 25 of file Sink.cpp.
         : source(nullptr) {
     }
~Sink()
net::stream::Sink::~Sink () virtual
Definition at line 29 of file Sink.cpp.
                 {
         if (source != nullptr) {
             source->disconnect(*this);
         }
     }
References net::stream::Source::disconnect(), and source.
Member Function Documentation
connect()
void net::stream::Sink::connect (Source & source)
Definition at line 35 of file Sink.cpp.
{
         this->source = &source;
     }
References source.
Referenced by net::stream::Source::connect().
disconnect()
void net::stream::Sink::disconnect (Source & source)
Definition at line 39 of file Sink.cpp.
{
         if (&source == this->source) {
             this->source = nullptr;
         }
     }
References source.
Referenced by net::stream::Source::~Source().
eof()
virtual void net::stream::Sink::eof () pure virtual
Implemented in http::server::Response, and http::client::Request.
Referenced by net::stream::Source::eof().
error()
virtual void net::stream::Sink::error (int errnum) pure virtual
Implemented in http::server::Response, and http::client::Request.
Referenced by net::stream::Source::error().
receive()
virtual void net::stream::Sink::receive (const char * junk, std::size_t junkLen) pure virtual
Implemented in http::server::Response, and http::client::Request.
Referenced by net::stream::Source::send().
Member Data Documentation
source
Source* net::stream::Sink::source protected
Definition at line 45 of file Sink.h.
Referenced by connect(), disconnect(), and ~Sink().
The documentation for this class was generated from the following files:
net/stream/Sink.h
net/stream/Sink.cpp