snode.c: web::ws::SubProtocolSelector Class Reference
web::ws::SubProtocolSelector Class Reference abstract
#include <SubProtocolSelector.h>
Public Member Functions
void loadSubProtocols ()
void loadSubProtocol (const std::string &filePath)
void loadSubProtocols (const std::string &directoryPath)
void registerSubProtocol (SubProtocolInterface *subProtocolPluginInterface, void *handle=nullptr)
void unloadSubProtocols ()
Protected Member Functions
SubProtocolSelector ()=default
virtual ~SubProtocolSelector ()=default
SubProtocolSelector (const SubProtocolSelector &)=delete
SubProtocolSelector & operator= (const SubProtocolSelector &)=delete
virtual SubProtocolInterface * select (const std::string &subProtocolName)=0
Protected Attributes
std::map< std::string, SubProtocolPlugin > serverSubprotocols
std::map< std::string, SubProtocolPlugin > clientSubprotocols
Detailed Description
Definition at line 38 of file SubProtocolSelector.h.
Constructor & Destructor Documentation
SubProtocolSelector() [1/2]
web::ws::SubProtocolSelector::SubProtocolSelector () protected default
~SubProtocolSelector()
virtual web::ws::SubProtocolSelector::~SubProtocolSelector () protected virtual default
SubProtocolSelector() [2/2]
web::ws::SubProtocolSelector::SubProtocolSelector (const SubProtocolSelector &) protected delete
Member Function Documentation
loadSubProtocol()
void web::ws::SubProtocolSelector::loadSubProtocol (const std::string & filePath)
Definition at line 91 of file SubProtocolSelector.cpp.
{
         void* handle = dlopen(filePath.c_str(), RTLD_LAZY | RTLD_GLOBAL);
         if (handle != nullptr) {
             VLOG(0) << "DLOpen: success: " << filePath;
             SubProtocolInterface* (*plugin)() = reinterpret_cast<SubProtocolInterface* (*) ()>(dlsym(handle, "plugin"));
             if (plugin != nullptr) {
                 SubProtocolInterface* subProtocolInterface = plugin();
                 if (subProtocolInterface != nullptr) {
                     registerSubProtocol(subProtocolInterface, handle);
                 } else {
                     dlclose(handle);
                 }
             } else {
                 VLOG(0) << "Optaining function \"plugin()\" in plugin failed: " << dlerror();
             }
         } else {
             VLOG(0) << "DLOpen: error: " << dlerror() << " - " << filePath;
         }
     }
References web::ws::server::plugin(), and registerSubProtocol().
Referenced by loadSubProtocols().
loadSubProtocols() [1/2]
void web::ws::SubProtocolSelector::loadSubProtocols ()
Definition at line 37 of file SubProtocolSelector.cpp.
{
 #ifndef NDEBUG
 #ifdef SUBPROTOCOL_PATH
         loadSubProtocols(SUBPROTOCOL_PATH);
 #endif
 #endif
         loadSubProtocols("/usr/lib/snodec/web/ws/subprotocol");
         loadSubProtocols("/usr/local/lib/snodec/web/ws/subprotocol");
     }
loadSubProtocols() [2/2]
void web::ws::SubProtocolSelector::loadSubProtocols (const std::string & directoryPath)
Definition at line 114 of file SubProtocolSelector.cpp.
{
         if (std::filesystem::exists(directoryPath) && std::filesystem::is_directory(directoryPath)) {
             for (const std::filesystem::directory_entry& directoryEntry : std::filesystem::recursive_directory_iterator(directoryPath)) {
                 if (std::filesystem::is_regular_file(directoryEntry) && directoryEntry.path().extension() == ".so") {
                     loadSubProtocol(directoryEntry.path());
                 } else {
                     VLOG(1) << "Not a library: Ignoring " << directoryEntry;
                 }
             }
         } else {
             VLOG(1) << "Not a directory: Ignoring path: " << directoryPath;
         }
     }
References loadSubProtocol().
operator=()
SubProtocolSelector& web::ws::SubProtocolSelector::operator= (const SubProtocolSelector &) protected delete
registerSubProtocol()
void web::ws::SubProtocolSelector::registerSubProtocol (SubProtocolInterface * subProtocolPluginInterface, void * handle = nullptr)
Definition at line 47 of file SubProtocolSelector.cpp.
{
         SubProtocolPlugin subProtocolPlugin = {.subprotocolPluginInterface = subProtocolInterface, .handle = handle};
         if (subProtocolInterface != nullptr) {
             if (subProtocolInterface->role() == web::ws::SubProtocol::Role::SERVER) {
                 const auto [it, success] = serverSubprotocols.insert({subProtocolInterface->name(), subProtocolPlugin});
                 if (!success) {
                     VLOG(0) << "Subprotocol already existing: not using " << subProtocolInterface->name();
                     delete subProtocolInterface;
                     if (handle != nullptr) {
                         dlclose(handle);
                     }
                 }
             } else {
                 const auto [it, success] = clientSubprotocols.insert({subProtocolInterface->name(), subProtocolPlugin});
                 if (!success) {
                     VLOG(0) << "Subprotocol already existing: not using " << subProtocolInterface->name();
                     delete subProtocolInterface;
                     if (handle != nullptr) {
                         dlclose(handle);
                     }
                 }
             }
         } else if (handle != nullptr) {
             dlclose(handle);
         }
     }
References clientSubprotocols, web::ws::SubProtocolInterface::name(), web::ws::SubProtocolInterface::role(), web::ws::SubProtocol::SERVER, serverSubprotocols, and web::ws::SubProtocolPlugin::subprotocolPluginInterface.
Referenced by loadSubProtocol().
select()
virtual SubProtocolInterface* web::ws::SubProtocolSelector::select (const std::string & subProtocolName) protected pure virtual
Implemented in web::ws::server::SubProtocolSelector.
unloadSubProtocols()
void web::ws::SubProtocolSelector::unloadSubProtocols ()
Definition at line 75 of file SubProtocolSelector.cpp.
{
         for (const auto& [name, subProtocolPlugin] : serverSubprotocols) {
             delete subProtocolPlugin.subprotocolPluginInterface;
             if (subProtocolPlugin.handle != nullptr) {
                 dlclose(subProtocolPlugin.handle);
             }
         }
         for (const auto& [name, subProtocolPlugin] : clientSubprotocols) {
             delete subProtocolPlugin.subprotocolPluginInterface;
             if (subProtocolPlugin.handle != nullptr) {
                 dlclose(subProtocolPlugin.handle);
             }
         }
     }
References clientSubprotocols, and serverSubprotocols.
Member Data Documentation
clientSubprotocols
std::map<std::string, SubProtocolPlugin> web::ws::SubProtocolSelector::clientSubprotocols protected
Definition at line 58 of file SubProtocolSelector.h.
Referenced by registerSubProtocol(), and unloadSubProtocols().
serverSubprotocols
std::map<std::string, SubProtocolPlugin> web::ws::SubProtocolSelector::serverSubprotocols protected
Definition at line 57 of file SubProtocolSelector.h.
Referenced by registerSubProtocol(), web::ws::server::SubProtocolSelector::select(), and unloadSubProtocols().
The documentation for this class was generated from the following files:
web/ws/SubProtocolSelector.h
web/ws/SubProtocolSelector.cpp