snode.c: web::http::client::ClientContextFactory< RequestT, ResponseT > Class Template Reference
web::http::client::ClientContextFactory< RequestT, ResponseT > Class Template Reference
#include <ClientContextFactory.h>
Public Types
using Request = RequestT
using Response = ResponseT
Public Member Functions
ClientContextFactory ()=default
void setOnResponse (const std::function< void(Response &)> &onResponse)
void setOnRequestError (const std::function< void(int, const std::string &)> onRequestError)
Public Member Functions inherited from net::socket::stream::SocketProtocolFactory
virtual ~SocketProtocolFactory ()=default
Protected Attributes
std::function< void(Response &)> onResponse
std::function< void(int, const std::string &)> onRequestError
Private Member Functions
net::socket::stream::SocketProtocol * create () const override
Additional Inherited Members
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::client::ClientContextFactory< RequestT, ResponseT >
Definition at line 33 of file ClientContextFactory.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::client::ClientContextFactory< RequestT, ResponseT >::Request = RequestT
Definition at line 35 of file ClientContextFactory.h.
Response
template<typename RequestT , typename ResponseT > using web::http::client::ClientContextFactory< RequestT, ResponseT >::Response = ResponseT
Definition at line 36 of file ClientContextFactory.h.
Constructor & Destructor Documentation
ClientContextFactory()
template<typename RequestT , typename ResponseT > web::http::client::ClientContextFactory< RequestT, ResponseT >::ClientContextFactory () default
Member Function Documentation
create()
template<typename RequestT , typename ResponseT > net::socket::stream::SocketProtocol* web::http::client::ClientContextFactory< RequestT, ResponseT >::create () const inline override private virtual
Implements net::socket::stream::SocketProtocolFactory.
Definition at line 41 of file ClientContextFactory.h.
{
             return new ClientContext<Request, Response>(onResponse, onRequestError);
         }
References web::http::client::ClientContextFactory< RequestT, ResponseT >::onRequestError, and web::http::client::ClientContextFactory< RequestT, ResponseT >::onResponse.
setOnRequestError()
template<typename RequestT , typename ResponseT > void web::http::client::ClientContextFactory< RequestT, ResponseT >::setOnRequestError (const std::function< void(int, const std::string &)> onRequestError) inline
Definition at line 50 of file ClientContextFactory.h.
{
             this->onRequestError = onRequestError;
         }
References web::http::client::ClientContextFactory< RequestT, ResponseT >::onRequestError.
setOnResponse()
template<typename RequestT , typename ResponseT > void web::http::client::ClientContextFactory< RequestT, ResponseT >::setOnResponse (const std::function< void(Response &)> & onResponse) inline
Definition at line 46 of file ClientContextFactory.h.
{
             this->onResponse = onResponse;
         }
References web::http::client::ClientContextFactory< RequestT, ResponseT >::onResponse.
Member Data Documentation
onRequestError
template<typename RequestT , typename ResponseT > std::function<void(int, const std::string&)> web::http::client::ClientContextFactory< RequestT, ResponseT >::onRequestError protected
Definition at line 56 of file ClientContextFactory.h.
Referenced by web::http::client::ClientContextFactory< RequestT, ResponseT >::create(), and web::http::client::ClientContextFactory< RequestT, ResponseT >::setOnRequestError().
onResponse
template<typename RequestT , typename ResponseT > std::function<void(Response&)> web::http::client::ClientContextFactory< RequestT, ResponseT >::onResponse protected
Definition at line 55 of file ClientContextFactory.h.
Referenced by web::http::client::ClientContextFactory< RequestT, ResponseT >::create(), and web::http::client::ClientContextFactory< RequestT, ResponseT >::setOnResponse().
The documentation for this class was generated from the following file:
web/http/client/ClientContextFactory.h