snode.c: net::socket::tcp::SocketListener< SocketConnectionT > Class Template Reference
net::socket::tcp::SocketListener< SocketConnectionT > Class Template Reference
#include <SocketListener.h>
Public Types
using SocketConnection = SocketConnectionT
Public Types inherited from net::Descriptor
enum FLAGS : unsigned short { FLAGS::none = 0, FLAGS::dontClose = 0x01 << 0 }
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketListener_v)
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
SocketListener ()=delete
SocketListener (const SocketListener &)=delete
SocketListener & operator= (const SocketListener &)=delete
virtual ~SocketListener ()=default
virtual void listen (const InetAddress &localAddress, int backlog, const std::function< void(int err)> &onError)
void reuseAddress (const std::function< void(int errnum)> &onError)
void acceptEvent () override
void end ()
Public Member Functions inherited from net::AcceptEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Public Member Functions inherited from net::socket::tcp::Socket
Socket ()=default
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
virtual ~Socket ()
void open (const std::function< void(int errnum)> &onError, int flags=0)
void bind (const InetAddress &localAddress, const std::function< void(int errnum)> &onError)
const InetAddress & getLocalAddress () const
void setLocalAddress (const InetAddress &localAddress)
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
~Descriptor ()
void open (int fd, FLAGS flags=FLAGS::none)
int getFd () const
bool dontClose () const
Protected Attributes
std::map< std::string, std::any > options
bool isDynamic
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Protected Attributes inherited from net::socket::tcp::Socket
InetAddress localAddress {}
Static Protected Attributes
static void * lastAllocAddress = nullptr
Private Member Functions
void unobserved () override
Private Attributes
std::function< void(SocketConnection *socketConnection)> onConstruct
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onConnect
std::function< void(SocketConnection *socketConnection)> onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
Additional Inherited Members
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
Protected Member Functions inherited from net::Descriptor
Descriptor ()=default
Detailed Description
template<typename SocketConnectionT>
class net::socket::tcp::SocketListener< SocketConnectionT >
Definition at line 39 of file SocketListener.h.
Member Typedef Documentation
SocketConnection
template<typename SocketConnectionT > using net::socket::tcp::SocketListener< SocketConnectionT >::SocketConnection = SocketConnectionT
Definition at line 43 of file SocketListener.h.
Constructor & Destructor Documentation
SocketListener() [1/3]
template<typename SocketConnectionT > net::socket::tcp::SocketListener< SocketConnectionT >::SocketListener (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options) inline
Definition at line 55 of file SocketListener.h.
             : AcceptEventReceiver()
             , Socket()
             , onConstruct(onConstruct)
             , onDestruct(onDestruct)
             , onConnect(onConnect)
             , onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options)
             , isDynamic(this == SocketListener::lastAllocAddress) {
         }
SocketListener() [2/3]
template<typename SocketConnectionT > net::socket::tcp::SocketListener< SocketConnectionT >::SocketListener () delete
SocketListener() [3/3]
template<typename SocketConnectionT > net::socket::tcp::SocketListener< SocketConnectionT >::SocketListener (const SocketListener< SocketConnectionT > &) delete
~SocketListener()
template<typename SocketConnectionT > virtual net::socket::tcp::SocketListener< SocketConnectionT >::~SocketListener () virtual default
Reimplemented in net::socket::tcp::tls::SocketListener.
Member Function Documentation
acceptEvent()
template<typename SocketConnectionT > void net::socket::tcp::SocketListener< SocketConnectionT >::acceptEvent () inline override virtual
Implements net::AcceptEventReceiver.
Definition at line 122 of file SocketListener.h.
{
             errno = 0;
             struct sockaddr_in remoteAddress {};
             socklen_t addrlen = sizeof(remoteAddress);
             int scFd = -1;
             scFd = ::accept4(getFd(), reinterpret_cast<struct sockaddr*>(&remoteAddress), &addrlen, SOCK_NONBLOCK);
             if (scFd >= 0) {
                 struct sockaddr_in localAddress {};
                 socklen_t addressLength = sizeof(localAddress);
                 if (getsockname(scFd, reinterpret_cast<sockaddr*>(&localAddress), &addressLength) == 0) {
                     SocketConnection* socketConnection =
                         new SocketConnection(onConstruct, onDestruct, onRead, onReadError, onWriteError, onDisconnect);
                     socketConnection->open(scFd);
                     socketConnection->setRemoteAddress(InetAddress(remoteAddress));
                     socketConnection->setLocalAddress(InetAddress(localAddress));
                     socketConnection->ReadEventReceiver::enable();
                     onConnect(socketConnection);
                 } else {
                     PLOG(ERROR) << "getsockname";
                     shutdown(scFd, SHUT_RDWR);
                     ::close(scFd);
                 }
             } else if (errno != EINTR) {
                 PLOG(ERROR) << "accept";
             }
         }
end()
template<typename SocketConnectionT > void net::socket::tcp::SocketListener< SocketConnectionT >::end () inline
Definition at line 158 of file SocketListener.h.
                    {
             AcceptEventReceiver::disable();
         }
listen()
template<typename SocketConnectionT > virtual void net::socket::tcp::SocketListener< SocketConnectionT >::listen (const InetAddress & localAddress, int backlog, const std::function< void(int err)> & onError) inline virtual
Reimplemented in net::socket::tcp::tls::SocketListener.
Definition at line 83 of file SocketListener.h.
{
             open([this, &localAddress, &backlog, &onError](int errnum) -> void {
                 if (errnum > 0) {
                     onError(errnum);
                 } else {
                     reuseAddress([this, &localAddress, &backlog, &onError](int errnum) -> void {
                         if (errnum != 0) {
                             onError(errnum);
                         } else {
                             bind(localAddress, [this, &backlog, &onError](int errnum) -> void {
                                 if (errnum > 0) {
                                     onError(errnum);
                                 } else {
                                     int ret = ::listen(getFd(), backlog);
                                     if (ret < 0) {
                                         onError(errno);
                                     } else {
                                         AcceptEventReceiver::enable();
                                         onError(0);
                                     }
                                 }
                             });
                         }
                     });
                 }
             });
         }
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::listen(), net::socket::tcp::SocketServer< legacy::SocketListener >::listen(), and net::socket::tcp::tls::SocketListener::listen().
operator delete()
template<typename SocketConnectionT > void net::socket::tcp::SocketListener< SocketConnectionT >::operator delete (void * socketListener_v) inline
Definition at line 51 of file SocketListener.h.
{
             free(socketListener_v);
         }
operator new()
template<typename SocketConnectionT > void* net::socket::tcp::SocketListener< SocketConnectionT >::operator new (size_t size) inline
Definition at line 45 of file SocketListener.h.
{
             SocketListener<SocketConnection>::lastAllocAddress = malloc(size);
             return SocketListener<SocketConnection>::lastAllocAddress;
         }
operator=()
template<typename SocketConnectionT > SocketListener& net::socket::tcp::SocketListener< SocketConnectionT >::operator= (const SocketListener< SocketConnectionT > &) delete
reuseAddress()
template<typename SocketConnectionT > void net::socket::tcp::SocketListener< SocketConnectionT >::reuseAddress (const std::function< void(int errnum)> & onError) inline
Definition at line 112 of file SocketListener.h.
{
             int sockopt = 1;
             if (setsockopt(getFd(), SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt)) < 0) {
                 onError(errno);
             } else {
                 onError(0);
             }
         }
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::listen().
unobserved()
template<typename SocketConnectionT > void net::socket::tcp::SocketListener< SocketConnectionT >::unobserved () inline override private virtual
Implements net::EventReceiver.
Definition at line 163 of file SocketListener.h.
{
             if (isDynamic) {
                 delete this;
             }
         }
Member Data Documentation
isDynamic
template<typename SocketConnectionT > bool net::socket::tcp::SocketListener< SocketConnectionT >::isDynamic protected
Definition at line 180 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::unobserved().
lastAllocAddress
template<typename SocketConnection > void * net::socket::tcp::SocketListener< SocketConnection >::lastAllocAddress = nullptr static protected
Definition at line 181 of file SocketListener.h.
onConnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketListener< SocketConnectionT >::onConnect private
Definition at line 171 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onConstruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketListener< SocketConnectionT >::onConstruct private
Definition at line 169 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onDestruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketListener< SocketConnectionT >::onDestruct private
Definition at line 170 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onDisconnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketListener< SocketConnectionT >::onDisconnect private
Definition at line 172 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onRead
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, const char* junk, ssize_t junkLen)> net::socket::tcp::SocketListener< SocketConnectionT >::onRead private
Definition at line 173 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onReadError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketListener< SocketConnectionT >::onReadError private
Definition at line 174 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
onWriteError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketListener< SocketConnectionT >::onWriteError private
Definition at line 175 of file SocketListener.h.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent().
options
template<typename SocketConnectionT > std::map<std::string, std::any> net::socket::tcp::SocketListener< SocketConnectionT >::options protected
Definition at line 178 of file SocketListener.h.
The documentation for this class was generated from the following file:
net/socket/tcp/SocketListener.h