snode.c: net::socket::stream::SocketContext Class Reference
net::socket::stream::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketContext (const SocketContextFactory &socketContextFactory)
void setTimeout (int timeout)
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
virtual void onConnected ()
virtual void onDisconnected ()
Protected Member Functions
SocketContext (SocketConnection *socketConnection)
virtual ~SocketContext ()=default
Private Member Functions
void receiveFromPeer ()
Private Attributes
SocketConnection * socketConnection
Friends
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT >
class SocketConnectionT
Detailed Description
Definition at line 37 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
net::socket::stream::SocketContext::SocketContext (SocketConnection * socketConnection) explicit protected
Definition at line 30 of file SocketContext.cpp.
         : socketConnection(socketConnection) {
     }
~SocketContext()
virtual net::socket::stream::SocketContext::~SocketContext () protected virtual default
Reimplemented in web::websocket::SocketContext, web::http::client::SocketContext, web::websocket::server::SocketContext, and web::websocket::client::SocketContext.
Member Function Documentation
close()
void net::socket::stream::SocketContext::close ()
Definition at line 54 of file SocketContext.cpp.
{
         socketConnection->close();
     }
References net::socket::stream::SocketConnection::close(), and socketConnection.
Referenced by web::websocket::SocketContext::sendClose().
getLocalAddressAsString()
std::string net::socket::stream::SocketContext::getLocalAddressAsString () const
Definition at line 46 of file SocketContext.cpp.
{
         return socketConnection->getLocalAddressAsString();
     }
References net::socket::stream::SocketConnection::getLocalAddressAsString(), and socketConnection.
Referenced by web::websocket::SocketContext::getLocalAddressAsString().
getRemoteAddressAsString()
std::string net::socket::stream::SocketContext::getRemoteAddressAsString () const
Definition at line 50 of file SocketContext.cpp.
{
         return socketConnection->getRemoteAddressAsString();
     }
References net::socket::stream::SocketConnection::getRemoteAddressAsString(), and socketConnection.
Referenced by web::websocket::SocketContext::getRemoteAddressAsString().
onConnected()
void net::socket::stream::SocketContext::onConnected () virtual
Reimplemented in web::websocket::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
         VLOG(0) << "Protocol connected";
     }
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::switchSocketContext().
onDisconnected()
void net::socket::stream::SocketContext::onDisconnected () virtual
Reimplemented in web::websocket::SocketContext.
Definition at line 78 of file SocketContext.cpp.
{
         VLOG(0) << "Protocol disconnecteded";
     }
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::switchSocketContext().
onReadError()
virtual void net::socket::stream::SocketContext::onReadError (int errnum) pure virtual
Implemented in web::websocket::SocketContext, web::http::server::SocketContextT< RequestT, ResponseT >, and web::http::client::SocketContextT< RequestT, ResponseT >.
onReceiveFromPeer()
virtual void net::socket::stream::SocketContext::onReceiveFromPeer () pure virtual
Implemented in web::websocket::SocketContext, web::http::server::SocketContextT< RequestT, ResponseT >, and web::http::client::SocketContextT< RequestT, ResponseT >.
Referenced by receiveFromPeer().
onWriteError()
virtual void net::socket::stream::SocketContext::onWriteError (int errnum) pure virtual
Implemented in web::websocket::SocketContext, web::http::server::SocketContextT< RequestT, ResponseT >, and web::http::client::SocketContextT< RequestT, ResponseT >.
readFromPeer()
std::size_t net::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen)
Definition at line 42 of file SocketContext.cpp.
{
         return socketConnection->readFromPeer(junk, junklen);
     }
References net::socket::stream::SocketConnection::readFromPeer(), and socketConnection.
Referenced by web::websocket::SocketContext::readFrameData(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
receiveFromPeer()
void net::socket::stream::SocketContext::receiveFromPeer () private
Definition at line 62 of file SocketContext.cpp.
{
         onReceiveFromPeer();
         if (this != socketConnection->getSocketContext()) {
             delete this; // we were replaced by a different context.
         }
     }
References net::socket::stream::SocketConnection::getSocketContext(), onReceiveFromPeer(), and socketConnection.
sendToPeer() [1/2]
void net::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen)
Definition at line 34 of file SocketContext.cpp.
{
         socketConnection->sendToPeer(junk, junkLen);
     }
References net::socket::stream::SocketConnection::sendToPeer(), and socketConnection.
Referenced by web::http::client::Request::enqueue(), web::http::server::Response::enqueue(), web::websocket::SocketContext::sendFrameData(), and sendToPeer().
sendToPeer() [2/2]
void net::socket::stream::SocketContext::sendToPeer (const std::string & data)
Definition at line 38 of file SocketContext.cpp.
{
         sendToPeer(data.data(), data.length());
     }
References sendToPeer().
setTimeout()
void net::socket::stream::SocketContext::setTimeout (int timeout)
Definition at line 70 of file SocketContext.cpp.
{
         socketConnection->setTimeout(timeout);
     }
References net::socket::stream::SocketConnection::setTimeout(), and socketConnection.
Referenced by web::websocket::SocketContext::sendClose().
switchSocketContext()
void net::socket::stream::SocketContext::switchSocketContext (const SocketContextFactory & socketContextFactory)
Definition at line 58 of file SocketContext.cpp.
{
         socketConnection->switchSocketContext(socketContextFactory);
     }
References socketConnection, and net::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::upgrade().
Friends And Related Function Documentation
SocketConnectionT
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > friend class SocketConnectionT friend
Definition at line 68 of file SocketContext.h.
Member Data Documentation
socketConnection
SocketConnection* net::socket::stream::SocketContext::socketConnection private
Definition at line 65 of file SocketContext.h.
Referenced by close(), web::websocket::server::SocketContext::create(), getLocalAddressAsString(), getRemoteAddressAsString(), readFromPeer(), receiveFromPeer(), sendToPeer(), setTimeout(), and switchSocketContext().
The documentation for this class was generated from the following files:
net/socket/stream/SocketContext.h
net/socket/stream/SocketContext.cpp