snode.c: net::ConnectEventReceiver Class Reference
net::ConnectEventReceiver Class Reference abstract
#include <ConnectEventReceiver.h>
Public Member Functions
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::EventReceiver
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
ConnectEventReceiver ()
virtual void connectEvent ()=0
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Friends
template<typename ConnectEventReceiver >
class EventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::EventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 30 of file ConnectEventReceiver.h.
Constructor & Destructor Documentation
ConnectEventReceiver()
net::ConnectEventReceiver::ConnectEventReceiver () protected
Definition at line 26 of file ConnectEventReceiver.cpp.
         : EventReceiver(EventLoop::instance().getConnectEventDispatcher().getTimeout()) {
     }
Member Function Documentation
connectEvent()
virtual void net::ConnectEventReceiver::connectEvent () protected pure virtual
Implemented in net::socket::stream::SocketConnector< SocketConnectionT >, net::socket::stream::SocketConnector< stream::legacy::SocketConnection< SocketT > >, and net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >.
Referenced by dispatchEvent().
disable()
void net::ConnectEventReceiver::disable () override virtual
Implements net::EventReceiver.
Definition at line 39 of file ConnectEventReceiver.cpp.
{
         EventLoop::instance().getConnectEventDispatcher().disable(this, fd);
     }
References net::EventDispatcher< EventReceiverT >::disable(), net::EventReceiver::fd, net::EventLoop::getConnectEventDispatcher(), and net::EventLoop::instance().
Referenced by net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::connectEvent().
dispatchEvent()
void net::ConnectEventReceiver::dispatchEvent () inline override protected virtual
Implements net::EventReceiver.
Definition at line 36 of file ConnectEventReceiver.h.
{
             connectEvent();
         }
References connectEvent().
enable()
void net::ConnectEventReceiver::enable (int fd, long timeout = TIMEOUT::IGNORE) override virtual
Implements net::EventReceiver.
Definition at line 34 of file ConnectEventReceiver.cpp.
{
         EventLoop::instance().getConnectEventDispatcher().enable(this, fd);
         setTimeout(timeout);
     }
References net::EventDispatcher< EventReceiverT >::enable(), net::EventReceiver::fd, net::EventLoop::getConnectEventDispatcher(), net::EventLoop::instance(), setTimeout(), and net::EventReceiver::timeout().
Referenced by net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >::connect().
resume()
void net::ConnectEventReceiver::resume () override virtual
Implements net::EventReceiver.
Definition at line 47 of file ConnectEventReceiver.cpp.
{
         EventLoop::instance().getConnectEventDispatcher().resume(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getConnectEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::resume().
setTimeout()
void net::ConnectEventReceiver::setTimeout (long timeout = TIMEOUT::DEFAULT)
Definition at line 30 of file ConnectEventReceiver.cpp.
{
         EventReceiver::setTimeout(timeout, EventLoop::instance().getConnectEventDispatcher().getTimeout());
     }
References net::EventReceiver::getTimeout(), net::EventLoop::instance(), net::EventReceiver::setTimeout(), and net::EventReceiver::timeout().
Referenced by enable().
suspend()
void net::ConnectEventReceiver::suspend () override virtual
Implements net::EventReceiver.
Definition at line 43 of file ConnectEventReceiver.cpp.
{
         EventLoop::instance().getConnectEventDispatcher().suspend(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getConnectEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::suspend().
Friends And Related Function Documentation
EventDispatcher
template<typename ConnectEventReceiver > friend class EventDispatcher friend
Definition at line 50 of file ConnectEventReceiver.h.
The documentation for this class was generated from the following files:
net/ConnectEventReceiver.h
net/ConnectEventReceiver.cpp