snode.c: net::timer::Timer Class Reference
net::timer::Timer Class Reference abstract
#include <Timer.h>
Classes
struct absoluteTimeout
Public Member Functions
Timer (const Timer &)=delete
Timer & operator= (const Timer &timer)=delete
void cancel ()
Static Public Member Functions
static IntervalTimer & continousTimer (const std::function< void(const void *arg, const std::function< void()> &stop)> &dispatcher, const struct timeval &timeout, const void *arg)
static IntervalTimer & continousTimer (const std::function< void(const void *arg)> &dispatcher, const struct timeval &timeout, const void *arg)
static SingleshotTimer & singleshotTimer (const std::function< void(const void *arg)> &dispatcher, const struct timeval &timeout, const void *arg)
Protected Member Functions
Timer (const struct timeval &timeout, const void *arg)
virtual ~Timer ()=default
void update ()
void destroy ()
virtual bool dispatch ()=0
struct timeval & timeout ()
operator struct timeval () const
Protected Attributes
const void * arg
Private Attributes
struct timeval delay
Friends
class net::TimerEventDispatcher
Detailed Description
Definition at line 38 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
net::timer::Timer::Timer (const struct timeval & timeout, const void * arg) protected
Definition at line 32 of file Timer.cpp.
         : arg(arg)
         , delay(timeout) {
         gettimeofday(&absoluteTimeout, nullptr);
         update();
     }
References update().
~Timer()
virtual net::timer::Timer::~Timer () protected virtual default
Timer() [2/2]
net::timer::Timer::Timer (const Timer &) delete
Member Function Documentation
cancel()
void net::timer::Timer::cancel ()
Definition at line 67 of file Timer.cpp.
{
         EventLoop::instance().getTimerEventDispatcher().remove(this);
     }
References net::EventLoop::getTimerEventDispatcher(), net::EventLoop::instance(), and net::TimerEventDispatcher::remove().
Referenced by net::timer::IntervalTimer::dispatch(), and net::timer::SingleshotTimer::dispatch().
continousTimer() [1/2]
IntervalTimer & net::timer::Timer::continousTimer (const std::function< void(const void *arg)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 59 of file Timer.cpp.
{
         IntervalTimer* ct = new IntervalTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(ct);
         return *ct;
     }
References net::TimerEventDispatcher::add(), arg, net::EventLoop::getTimerEventDispatcher(), net::EventLoop::instance(), and timeout().
continousTimer() [2/2]
IntervalTimer & net::timer::Timer::continousTimer (const std::function< void(const void *arg, const std::function< void()> &stop)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 48 of file Timer.cpp.
{
         IntervalTimer* ct = new IntervalTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(ct);
         return *ct;
     }
References net::TimerEventDispatcher::add(), arg, net::EventLoop::getTimerEventDispatcher(), net::EventLoop::instance(), and timeout().
destroy()
void net::timer::Timer::destroy () protected
Definition at line 75 of file Timer.cpp.
{
         delete this;
     }
dispatch()
virtual bool net::timer::Timer::dispatch () protected pure virtual
Implemented in net::timer::SingleshotTimer, and net::timer::IntervalTimer.
operator struct timeval()
net::timer::Timer::operator struct timeval () const explicit protected
Definition at line 83 of file Timer.cpp.
{
         return absoluteTimeout;
     }
operator=()
Timer& net::timer::Timer::operator= (const Timer & timer) delete
singleshotTimer()
SingleshotTimer & net::timer::Timer::singleshotTimer (const std::function< void(const void *arg)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 40 of file Timer.cpp.
{
         SingleshotTimer* st = new SingleshotTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(st);
         return *st;
     }
References net::TimerEventDispatcher::add(), arg, net::EventLoop::getTimerEventDispatcher(), net::EventLoop::instance(), and timeout().
Referenced by net::socket::tcp::SocketClient< legacy::SocketConnection >::connect(), and net::socket::tcp::tls::SocketListener::SocketListener().
timeout()
struct timeval & net::timer::Timer::timeout () protected
Definition at line 79 of file Timer.cpp.
{
         return absoluteTimeout;
     }
Referenced by continousTimer(), and singleshotTimer().
update()
void net::timer::Timer::update () protected
Definition at line 71 of file Timer.cpp.
{
         absoluteTimeout = absoluteTimeout + delay;
     }
References delay.
Referenced by net::timer::IntervalTimer::dispatch(), and Timer().
Friends And Related Function Documentation
net::TimerEventDispatcher
friend class net::TimerEventDispatcher friend
Definition at line 76 of file Timer.h.
Member Data Documentation
arg
const void* net::timer::Timer::arg protected
Definition at line 61 of file Timer.h.
Referenced by continousTimer(), net::timer::IntervalTimer::dispatch(), net::timer::SingleshotTimer::dispatch(), and singleshotTimer().
delay
struct timeval net::timer::Timer::delay private
Definition at line 70 of file Timer.h.
Referenced by update().
The documentation for this class was generated from the following files:
net/timer/Timer.h
net/timer/Timer.cpp