snode.c: net::socket::stream::SocketProtocol Class Reference
net::socket::stream::SocketProtocol Class Reference abstract
#include <SocketProtocol.h>
Public Member Functions
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void close ()
void switchSocketProtocol (SocketProtocol *socketProtocol)
void setTimeout (int timeout)
Protected Member Functions
SocketProtocol ()=default
virtual ~SocketProtocol ()=default
Protected Attributes
SocketConnectionBase * socketConnection
Private Member Functions
virtual void onReceiveFromPeer (const char *junk, std::size_t junkLen)=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
void receiveFromPeer (const char *junk, std::size_t junkLen)
void setSocketConnection (SocketConnectionBase *socketConnection)
virtual void onProtocolConnected ()
virtual void onProtocolDisconnected ()
Private Attributes
bool markedForDelete = false
Friends
class SocketConnectionBase
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT >
class SocketConnection
Detailed Description
Definition at line 33 of file SocketProtocol.h.
Constructor & Destructor Documentation
SocketProtocol()
net::socket::stream::SocketProtocol::SocketProtocol () protected default
~SocketProtocol()
virtual net::socket::stream::SocketProtocol::~SocketProtocol () protected virtual default
Member Function Documentation
close()
void net::socket::stream::SocketProtocol::close ()
Definition at line 46 of file SocketProtocol.cpp.
{
         socketConnection->close();
     }
References net::socket::stream::SocketConnectionBase::close(), and socketConnection.
Referenced by web::ws::WSContext::close(), web::ws::WSContext::onMessageEnd(), web::ws::WSContext::onMessageError(), web::http::client::ClientContext< RequestT, ResponseT >::terminateConnection(), and web::http::server::HTTPServerContext< RequestT, ResponseT >::terminateConnection().
getLocalAddressAsString()
std::string net::socket::stream::SocketProtocol::getLocalAddressAsString () const
Definition at line 38 of file SocketProtocol.cpp.
{
         return socketConnection->getLocalAddressAsString();
     }
References net::socket::stream::SocketConnectionBase::getLocalAddressAsString(), and socketConnection.
getRemoteAddressAsString()
std::string net::socket::stream::SocketProtocol::getRemoteAddressAsString () const
Definition at line 42 of file SocketProtocol.cpp.
{
         return socketConnection->getRemoteAddressAsString();
     }
References net::socket::stream::SocketConnectionBase::getRemoteAddressAsString(), and socketConnection.
onProtocolConnected()
void net::socket::stream::SocketProtocol::onProtocolConnected () private virtual
Reimplemented in web::ws::WSContext.
Definition at line 72 of file SocketProtocol.cpp.
{
         VLOG(0) << "Protocol connected";
     }
Referenced by net::socket::stream::SocketConnectionBase::switchSocketProtocol().
onProtocolDisconnected()
void net::socket::stream::SocketProtocol::onProtocolDisconnected () private virtual
Reimplemented in web::ws::WSContext.
Definition at line 76 of file SocketProtocol.cpp.
{
         VLOG(0) << "Protocol disconnecteded";
     }
Referenced by net::socket::stream::SocketConnectionBase::switchSocketProtocol().
onReadError()
virtual void net::socket::stream::SocketProtocol::onReadError (int errnum) private pure virtual
Implemented in web::ws::WSContext, web::http::server::HTTPServerContext< RequestT, ResponseT >, and web::http::client::ClientContext< RequestT, ResponseT >.
onReceiveFromPeer()
virtual void net::socket::stream::SocketProtocol::onReceiveFromPeer (const char * junk, std::size_t junkLen) private pure virtual
Implemented in web::ws::WSContext, web::http::server::HTTPServerContext< RequestT, ResponseT >, and web::http::client::ClientContext< RequestT, ResponseT >.
Referenced by receiveFromPeer().
onWriteError()
virtual void net::socket::stream::SocketProtocol::onWriteError (int errnum) private pure virtual
Implemented in web::ws::WSContext, web::http::server::HTTPServerContext< RequestT, ResponseT >, and web::http::client::ClientContext< RequestT, ResponseT >.
receiveFromPeer()
void net::socket::stream::SocketProtocol::receiveFromPeer (const char * junk, std::size_t junkLen) private
Definition at line 56 of file SocketProtocol.cpp.
{
         onReceiveFromPeer(junk, junkLen);
         if (markedForDelete) {
             delete this;
         }
     }
References markedForDelete, and onReceiveFromPeer().
sendToPeer() [1/2]
void net::socket::stream::SocketProtocol::sendToPeer (const char * junk, std::size_t junkLen)
Definition at line 30 of file SocketProtocol.cpp.
{
         socketConnection->enqueue(junk, junkLen);
     }
References net::socket::stream::SocketConnectionBase::enqueue(), and socketConnection.
Referenced by web::ws::WSContext::sendFrameData(), and sendToPeer().
sendToPeer() [2/2]
void net::socket::stream::SocketProtocol::sendToPeer (const std::string & data)
Definition at line 34 of file SocketProtocol.cpp.
{
         sendToPeer(data.data(), data.length());
     }
References sendToPeer().
setSocketConnection()
void net::socket::stream::SocketProtocol::setSocketConnection (SocketConnectionBase * socketConnection) private
Definition at line 68 of file SocketProtocol.cpp.
{
         this->socketConnection = socketConnection;
     }
References socketConnection.
Referenced by net::socket::stream::SocketConnectionBase::SocketConnectionBase().
setTimeout()
void net::socket::stream::SocketProtocol::setTimeout (int timeout)
Definition at line 64 of file SocketProtocol.cpp.
{
         socketConnection->setTimeout(timeout);
     }
References net::socket::stream::SocketConnectionBase::setTimeout(), and socketConnection.
Referenced by web::ws::WSContext::close().
switchSocketProtocol()
void net::socket::stream::SocketProtocol::switchSocketProtocol (SocketProtocol * socketProtocol)
Definition at line 50 of file SocketProtocol.cpp.
{
         socketConnection->switchSocketProtocol(socketProtocol);
         markedForDelete = true;
     }
References markedForDelete, socketConnection, and net::socket::stream::SocketConnectionBase::switchSocketProtocol().
Referenced by web::http::server::Response::upgrade().
Friends And Related Function Documentation
SocketConnection
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > friend class SocketConnection friend
Definition at line 71 of file SocketProtocol.h.
SocketConnectionBase
friend class SocketConnectionBase friend
Definition at line 68 of file SocketProtocol.h.
Member Data Documentation
markedForDelete
bool net::socket::stream::SocketProtocol::markedForDelete = false private
Definition at line 66 of file SocketProtocol.h.
Referenced by receiveFromPeer(), and switchSocketProtocol().
socketConnection
SocketConnectionBase* net::socket::stream::SocketProtocol::socketConnection protected
Definition at line 52 of file SocketProtocol.h.
Referenced by close(), getLocalAddressAsString(), getRemoteAddressAsString(), web::ws::WSContext::onMessageEnd(), sendToPeer(), setSocketConnection(), setTimeout(), net::socket::stream::SocketConnectionBase::switchSocketProtocol(), and switchSocketProtocol().
The documentation for this class was generated from the following files:
net/socket/stream/SocketProtocol.h
net/socket/stream/SocketProtocol.cpp