snode.c: web::http::server::SocketContextUpgradeFactorySelector Class Reference
web::http::server::SocketContextUpgradeFactorySelector Class Reference
#include <SocketContextUpgradeFactorySelector.h>
Public Member Functions
void destroy ()
SocketContextUpgradeFactory * select (Request &req, Response &res)
bool add (web::http::server::SocketContextUpgradeFactory *socketContextUpgradeFactory)
Static Public Member Functions
static SocketContextUpgradeFactorySelector * instance ()
Protected Member Functions
web::http::server::SocketContextUpgradeFactory * load (const std::string &socketContextName)
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory, void *handler)
Protected Attributes
std::map< std::string, SocketContextPlugin > socketContextUpgradePlugins
std::list< std::string > searchPaths
Private Member Functions
SocketContextUpgradeFactorySelector ()
~SocketContextUpgradeFactorySelector ()=default
Static Private Attributes
static SocketContextUpgradeFactorySelector * socketContextUpgradeFactorySelector = nullptr
Detailed Description
Definition at line 43 of file SocketContextUpgradeFactorySelector.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactorySelector()
web::http::server::SocketContextUpgradeFactorySelector::SocketContextUpgradeFactorySelector () private
Definition at line 39 of file SocketContextUpgradeFactorySelector.cpp.
{
 #ifndef NDEBUG
 #ifdef UPGRADECONTEXT_SERVER_COMPILE_PATH
         searchPaths.push_back(UPGRADECONTEXT_SERVER_COMPILE_PATH);
 #endif // UPGRADECONTEXT_SERVER_COMPILE_PATH
 #endif // NDEBUG
         searchPaths.push_back(UPGRADECONTEXT_SERVER_INSTALL_PATH);
     }
References searchPaths.
Referenced by instance().
~SocketContextUpgradeFactorySelector()
web::http::server::SocketContextUpgradeFactorySelector::~SocketContextUpgradeFactorySelector () private default
Member Function Documentation
add() [1/2]
bool web::http::server::SocketContextUpgradeFactorySelector::add (SocketContextUpgradeFactory * socketContextUpgradeFactory, void * handler) protected
Definition at line 149 of file SocketContextUpgradeFactorySelector.cpp.
{
         bool success = false;
         if (socketContextUpgradeFactory != nullptr) {
             SocketContextPlugin socketContextPlugin = {.socketContextUpgradeFactory = socketContextUpgradeFactory, .handle = handle};
             if (socketContextUpgradeFactory->role() == SocketContextUpgradeFactory::Role::SERVER) {
                 std::tie(std::ignore, success) =
                     socketContextUpgradePlugins.insert({socketContextUpgradeFactory->name(), socketContextPlugin});
             }
         }
         return success;
     }
References web::http::server::SocketContextUpgradeFactory::name(), web::http::server::SocketContextUpgradeFactory::role(), web::http::server::SocketContextUpgradeFactory::SERVER, web::http::server::SocketContextPlugin::socketContextUpgradeFactory, and socketContextUpgradePlugins.
add() [2/2]
bool web::http::server::SocketContextUpgradeFactorySelector::add (web::http::server::SocketContextUpgradeFactory * socketContextUpgradeFactory)
Definition at line 145 of file SocketContextUpgradeFactorySelector.cpp.
{
         return add(socketContextUpgradeFactory, nullptr);
     }
Referenced by load().
destroy()
void web::http::server::SocketContextUpgradeFactorySelector::destroy ()
Definition at line 59 of file SocketContextUpgradeFactorySelector.cpp.
{
         for (const auto& [name, socketContextPlugin] : socketContextUpgradePlugins) {
             socketContextPlugin.socketContextUpgradeFactory->destroy();
             if (socketContextPlugin.handle != nullptr) {
                 dlclose(socketContextPlugin.handle);
             }
         }
         delete this;
     }
References socketContextUpgradePlugins.
Referenced by web::http::server::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
instance()
SocketContextUpgradeFactorySelector * web::http::server::SocketContextUpgradeFactorySelector::instance () static
Definition at line 51 of file SocketContextUpgradeFactorySelector.cpp.
{
         if (socketContextUpgradeFactorySelector == nullptr) {
             socketContextUpgradeFactorySelector = new SocketContextUpgradeFactorySelector();
         }
         return socketContextUpgradeFactorySelector;
     }
References SocketContextUpgradeFactorySelector(), and socketContextUpgradeFactorySelector.
Referenced by load(), web::http::server::Response::upgrade(), and web::http::server::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
load()
SocketContextUpgradeFactory * web::http::server::SocketContextUpgradeFactorySelector::load (const std::string & socketContextName) protected
Definition at line 110 of file SocketContextUpgradeFactorySelector.cpp.
{
         SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
         void* handle = dlopen(filePath.c_str(), RTLD_LAZY | RTLD_LOCAL);
         if (handle != nullptr) {
             SocketContextUpgradeFactory* (*plugin)() = reinterpret_cast<SocketContextUpgradeFactory* (*) ()>(dlsym(handle, "plugin"));
             if (plugin != nullptr) {
                 socketContextUpgradeFactory = plugin();
                 if (socketContextUpgradeFactory != nullptr) {
                     if (SocketContextUpgradeFactorySelector::instance()->add(socketContextUpgradeFactory, handle)) {
                         VLOG(0) << "UpgradeSocketContext loaded successfully: " << filePath;
                     } else {
                         socketContextUpgradeFactory->destroy();
                         socketContextUpgradeFactory = nullptr;
                         dlclose(handle);
                         VLOG(0) << "UpgradeSocketContext already existing. Not using: " << filePath;
                     }
                 } else {
                     dlclose(handle);
                     VLOG(0) << "SocketContextUpgradeFactory not created: " << filePath;
                 }
             } else {
                 dlclose(handle);
                 VLOG(0) << "Not a Plugin \"" << filePath;
             }
         } else {
             VLOG(0) << "Error dlopen: " << dlerror();
         }
         return socketContextUpgradeFactory;
     }
References add(), web::http::server::SocketContextUpgradeFactory::destroy(), instance(), and web::ws::client::plugin().
Referenced by select().
select()
SocketContextUpgradeFactory * web::http::server::SocketContextUpgradeFactorySelector::select (Request & req, Response & res)
Definition at line 70 of file SocketContextUpgradeFactorySelector.cpp.
{
         SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
         std::string upgradeContextNames = req.header("upgrade");
         if (!upgradeContextNames.empty()) {
             std::string upgradeContextName;
             std::string upgradeContextPriority;
             std::tie(upgradeContextName, upgradeContextNames) = httputils::str_split(upgradeContextNames, ',');
             std::tie(upgradeContextName, upgradeContextPriority) = httputils::str_split(upgradeContextName, '/');
             httputils::to_lower(upgradeContextName);
             if (socketContextUpgradePlugins.contains(upgradeContextName)) {
                 socketContextUpgradeFactory = socketContextUpgradePlugins[upgradeContextName].socketContextUpgradeFactory;
             } else {
                 for (const std::string& searchPath : searchPaths) {
                     socketContextUpgradeFactory = load(searchPath + "/lib" + upgradeContextName + ".so");
                     if (socketContextUpgradeFactory != nullptr) {
                         break;
                     }
                 }
             }
         }
         if (socketContextUpgradeFactory != nullptr) {
             socketContextUpgradeFactory->prepare(req, res);
         }
         return socketContextUpgradeFactory;
     }
References web::http::server::Request::header(), load(), web::http::server::SocketContextUpgradeFactory::prepare(), searchPaths, socketContextUpgradePlugins, httputils::str_split(), and httputils::to_lower().
Referenced by web::http::server::Response::upgrade().
Member Data Documentation
searchPaths
std::list<std::string> web::http::server::SocketContextUpgradeFactorySelector::searchPaths protected
Definition at line 62 of file SocketContextUpgradeFactorySelector.h.
Referenced by select(), and SocketContextUpgradeFactorySelector().
socketContextUpgradeFactorySelector
SocketContextUpgradeFactorySelector * web::http::server::SocketContextUpgradeFactorySelector::socketContextUpgradeFactorySelector = nullptr static private
Definition at line 65 of file SocketContextUpgradeFactorySelector.h.
Referenced by instance().
socketContextUpgradePlugins
std::map<std::string, SocketContextPlugin> web::http::server::SocketContextUpgradeFactorySelector::socketContextUpgradePlugins protected
Definition at line 61 of file SocketContextUpgradeFactorySelector.h.
Referenced by add(), destroy(), and select().
The documentation for this class was generated from the following files:
web/http/server/SocketContextUpgradeFactorySelector.h
web/http/server/SocketContextUpgradeFactorySelector.cpp