snode.c: net::socket::ip::address::ipv4::InetAddress Class Reference
net::socket::ip::address::ipv4::InetAddress Class Reference
#include <InetAddress.h>
Public Member Functions
InetAddress ()
InetAddress (const std::string &ipOrHostname)
InetAddress (const std::string &ipOrHostname, uint16_t port)
InetAddress (uint16_t port)
uint16_t port () const
std::string host () const
std::string ip () const
std::string serv () const
std::string toString () const override
Public Member Functions inherited from net::socket::SocketAddress< struct sockaddr_in >
SocketAddress ()
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr)
SocketAddress & operator= (const SocketAddress &socketAddress)
SocketAddress & operator= (const SockAddr &sockAddr)
const sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from net::socket::SocketAddress< struct sockaddr_in >
using SockAddr = struct sockaddr_in
Protected Attributes inherited from net::socket::SocketAddress< struct sockaddr_in >
SockAddr sockAddr
Detailed Description
Definition at line 50 of file InetAddress.h.
Constructor & Destructor Documentation
InetAddress() [1/4]
net::socket::ip::address::ipv4::InetAddress::InetAddress ()
Definition at line 33 of file InetAddress.cpp.
{
         sockAddr.sin_family = AF_INET;
         sockAddr.sin_addr.s_addr = htonl(INADDR_ANY);
         sockAddr.sin_port = 0;
     }
References net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
InetAddress() [2/4]
net::socket::ip::address::ipv4::InetAddress::InetAddress (const std::string & ipOrHostname) explicit
Definition at line 39 of file InetAddress.cpp.
         : InetAddress(ipOrHostname, 0) {
     }
InetAddress() [3/4]
net::socket::ip::address::ipv4::InetAddress::InetAddress (const std::string & ipOrHostname, uint16_t port)
Definition at line 43 of file InetAddress.cpp.
{
         struct addrinfo hints {};
         struct addrinfo* res;
         struct addrinfo* resalloc;
         memset(&hints, 0, sizeof(hints));
         memset(&sockAddr, 0, sizeof(sockAddr));
         /* We only care about IPV6 results */
         hints.ai_family = AF_INET;
         hints.ai_socktype = 0;
         hints.ai_flags = AI_ADDRCONFIG;
         int err = net::system::getaddrinfo(ipOrHostname.c_str(), nullptr, &hints, &res);
         if (err != 0) {
             throw bad_hostname(ipOrHostname);
         }
         resalloc = res;
         while (res) {
             /* Check to make sure we have a valid AF_INET6 address */
             if (res->ai_family == AF_INET) {
                 /* Use memcpy since we're going to free the res variable later */
                 memcpy(&sockAddr, res->ai_addr, res->ai_addrlen);
                 /* Here we convert the port to network byte order */
                 sockAddr.sin_port = htons(port);
                 sockAddr.sin_family = AF_INET;
                 break;
             }
             res = res->ai_next;
         }
         net::system::freeaddrinfo(resalloc);
     }
References net::system::freeaddrinfo(), net::system::getaddrinfo(), port(), and net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
InetAddress() [4/4]
net::socket::ip::address::ipv4::InetAddress::InetAddress (uint16_t port) explicit
Definition at line 82 of file InetAddress.cpp.
{
         sockAddr.sin_family = AF_INET;
         sockAddr.sin_port = htons(port);
         sockAddr.sin_addr.s_addr = htonl(INADDR_ANY);
     }
References port(), and net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Member Function Documentation
host()
std::string net::socket::ip::address::ipv4::InetAddress::host () const
Definition at line 92 of file InetAddress.cpp.
{
         char host[NI_MAXHOST];
         net::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), host, 256, nullptr, 0, 0);
         return host;
     }
References net::system::getnameinfo(), and net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Referenced by toString().
ip()
std::string net::socket::ip::address::ipv4::InetAddress::ip () const
Definition at line 99 of file InetAddress.cpp.
{
         char ip[NI_MAXHOST];
         net::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), ip, 256, nullptr, 0, NI_NUMERICHOST);
         return ip;
     }
References net::system::getnameinfo(), and net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Referenced by toString().
port()
uint16_t net::socket::ip::address::ipv4::InetAddress::port () const
Definition at line 88 of file InetAddress.cpp.
{
         return (ntohs(sockAddr.sin_port));
     }
References net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Referenced by InetAddress(), and toString().
serv()
std::string net::socket::ip::address::ipv4::InetAddress::serv () const
Definition at line 106 of file InetAddress.cpp.
{
         char serv[NI_MAXSERV];
         net::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), nullptr, 0, serv, 256, 0);
         return serv;
     }
References net::system::getnameinfo(), and net::socket::SocketAddress< struct sockaddr_in >::sockAddr.
toString()
std::string net::socket::ip::address::ipv4::InetAddress::toString () const override virtual
Implements net::socket::SocketAddress< struct sockaddr_in >.
Definition at line 113 of file InetAddress.cpp.
{
         return host() + "(" + ip() + "):" + std::to_string(port());
     }
References host(), ip(), and port().
The documentation for this class was generated from the following files:
net/socket/ip/address/ipv4/InetAddress.h
net/socket/ip/address/ipv4/InetAddress.cpp