snode.c: http::ServerContext< RequestT, ResponseT > Class Template Reference
http::ServerContext< RequestT, ResponseT > Class Template Reference
#include <ServerContext.h>
Classes
struct RequestContext
Public Types
using SocketConnection = net::socket::stream::SocketConnectionBase
using Request = RequestT
using Response = ResponseT
Public Member Functions
ServerContext (SocketConnection *socketConnection, const std::function< void(Request &req, Response &res)> &onRequestReady, const std::function< void(Request &req, Response &res)> &onRequestCompleted)
~ServerContext ()
void receiveRequestData (const char *junk, size_t junkLen) override
void onReadError (int errnum)
void sendResponseData (const char *buf, size_t len) override
void onWriteError (int errnum) override
void responseCompleted () override
void terminateConnection () override
Public Member Functions inherited from http::ServerContextBase
virtual ~ServerContextBase ()=default
Private Member Functions
void requestParsed ()
void reset ()
Private Attributes
SocketConnection * socketConnection
std::function< void(Request &req, Response &res)> onRequestReady
std::function< void(Request &req, Response &res)> onRequestCompleted
RequestParser parser
std::list< RequestContext > requestContexts
bool requestInProgress = false
bool connectionTerminated = false
Detailed Description
template<typename RequestT, typename ResponseT>
class http::ServerContext< RequestT, ResponseT >
Definition at line 52 of file ServerContext.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using http::ServerContext< RequestT, ResponseT >::Request = RequestT
Definition at line 55 of file ServerContext.h.
Response
template<typename RequestT , typename ResponseT > using http::ServerContext< RequestT, ResponseT >::Response = ResponseT
Definition at line 56 of file ServerContext.h.
SocketConnection
template<typename RequestT , typename ResponseT > using http::ServerContext< RequestT, ResponseT >::SocketConnection = net::socket::stream::SocketConnectionBase
Definition at line 54 of file ServerContext.h.
Constructor & Destructor Documentation
ServerContext()
template<typename Request , typename Response > http::ServerContext< Request, Response >::ServerContext (SocketConnection * socketConnection, const std::function< void(Request &req, Response &res)> & onRequestReady, const std::function< void(Request &req, Response &res)> & onRequestCompleted)
Definition at line 34 of file ServerContext.hpp.
         : socketConnection(socketConnection)
         , onRequestReady(onRequestReady)
         , onRequestCompleted(onRequestCompleted)
         , parser(
               [this](void) -> void {
                   VLOG(3) << "++ BEGIN:";
                   requestContexts.emplace_back(RequestContext(this));
               },
               [this](const std::string& method,
                      const std::string& url,
                      const std::string& httpVersion,
                      int httpMajor,
                      int httpMinor,
                      const std::map<std::string, std::string>& queries) -> void {
                   VLOG(3) << "++ Request: " << method << " " << url << " " << httpVersion;
                   Request& request = requestContexts.back().request;
                   request.method = method;
                   request.url = url;
                   request.queries = &queries;
                   request.httpVersion = httpVersion;
                   request.httpMajor = httpMajor;
                   request.httpMinor = httpMinor;
               },
               [this](const std::map<std::string, std::string>& header, const std::map<std::string, std::string>& cookies) -> void {
                   Request& request = requestContexts.back().request;
                   VLOG(3) << "++ Header:";
                   request.headers = &header;
                   for (auto [field, value] : header) {
                       if (field == "connection" && value == "close") {
                           request.connectionState = ConnectionState::Close;
                       } else if (field == "connection" && value == "keep-alive") {
                           request.connectionState = ConnectionState::Keep;
                       }
                       VLOG(3) << "     " << field << ": " << value;
                   }
                   VLOG(3) << "++ Cookies";
                   request.cookies = &cookies;
                   for (auto [cookie, value] : cookies) {
                       VLOG(3) << "     " << cookie << ": " << value;
                   }
               },
               [this](char* content, size_t contentLength) -> void {
                   VLOG(3) << "++ Content: " << contentLength;
                   Request& request = requestContexts.back().request;
                   request.body = content;
                   request.contentLength = contentLength;
               },
               [this, onRequestReady]() -> void {
                   VLOG(3) << "++ Parsed ++";
                   RequestContext& requestContext = requestContexts.back();
                   requestContext.request.extend();
                   requestContext.ready = true;
                   requestParsed();
               },
               [this](int status, const std::string& reason) -> void {
                   VLOG(3) << "++ Error: " << status << " : " << reason;
                   RequestContext& requestContext = requestContexts.back();
                   requestContext.status = status;
                   requestContext.reason = reason;
                   requestContext.ready = true;
                   requestParsed();
               }) {
     }
References http::ServerContext< RequestT, ResponseT >::requestContexts.
~ServerContext()
template<typename Request , typename Response > http::ServerContext< Request, Response >::~ServerContext
Definition at line 117 of file ServerContext.hpp.
{
         if (requestInProgress) {
             RequestContext& requestContext = requestContexts.front();
             onRequestCompleted(requestContext.request, requestContext.response);
         }
     }
References http::ServerContext< RequestT, ResponseT >::RequestContext::request, and http::ServerContext< RequestT, ResponseT >::RequestContext::response.
Member Function Documentation
onReadError()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::onReadError (int errnum) virtual
Implements http::ServerContextBase.
Definition at line 131 of file ServerContext.hpp.
{
         if (errnum != 0 && errnum != ECONNRESET) {
             PLOG(ERROR) << "Connection read: " << errnum;
             reset();
         }
     }
onWriteError()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::onWriteError (int errnum) override virtual
Implements http::ServerContextBase.
Definition at line 144 of file ServerContext.hpp.
{
         if (errnum != 0 && errnum != ECONNRESET) {
             PLOG(ERROR) << "Connection write: " << errnum;
             reset();
         }
     }
receiveRequestData()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::receiveRequestData (const char * junk, size_t junkLen) override virtual
Implements http::ServerContextBase.
Definition at line 126 of file ServerContext.hpp.
{
         parser.parse(junk, junkLen);
     }
requestParsed()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::requestParsed private
Definition at line 152 of file ServerContext.hpp.
{
         if (!requestInProgress) {
             RequestContext& requestContext = requestContexts.front();
             requestInProgress = true;
             if (requestContext.status == 0) {
                 onRequestReady(requestContext.request, requestContext.response);
             } else {
                 requestContext.response.status(requestContext.status).send(requestContext.reason);
                 terminateConnection();
             }
         }
     }
References http::ServerContext< RequestT, ResponseT >::RequestContext::reason, http::ServerContext< RequestT, ResponseT >::RequestContext::request, http::ServerContext< RequestT, ResponseT >::RequestContext::response, http::Response::send(), http::Response::status(), and http::ServerContext< RequestT, ResponseT >::RequestContext::status.
reset()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::reset private
Definition at line 203 of file ServerContext.hpp.
{
         if (!requestContexts.empty()) {
             RequestContext& requestContext = requestContexts.front();
             requestContext.request.reset();
             requestContext.response.reset();
         }
         requestInProgress = false;
     }
References http::ServerContext< RequestT, ResponseT >::RequestContext::request, http::Request::reset(), http::Response::reset(), and http::ServerContext< RequestT, ResponseT >::RequestContext::response.
responseCompleted()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::responseCompleted override virtual
Implements http::ServerContextBase.
Definition at line 167 of file ServerContext.hpp.
{
         RequestContext& requestContext = requestContexts.front();
         onRequestCompleted(requestContext.request, requestContext.response);
         // if 0.9 => terminate
         // if 1.0 && (request != Keep || contentLength = -1) => terminate
         // if 1.1 && (request == Close || contentLength = -1) => terminate
         if ((requestContext.request.httpMajor == 0 && requestContext.request.httpMinor == 9) ||
             (requestContext.request.httpMajor == 1 && requestContext.request.httpMinor == 0 &&
              requestContext.request.connectionState != ConnectionState::Keep) ||
             (requestContext.request.httpMajor == 1 && requestContext.request.httpMinor == 1 &&
              requestContext.request.connectionState == ConnectionState::Close) ||
             (requestContext.response.connectionState == ConnectionState::Close)) {
             terminateConnection();
         } else {
             reset();
             requestContexts.pop_front();
             if (!requestContexts.empty() && requestContexts.front().ready) {
                 RequestContext& requestContext = requestContexts.front();
                 requestInProgress = true;
                 if (requestContext.status == 0) {
                     onRequestReady(requestContext.request, requestContext.response);
                 } else {
                     requestContext.response.status(requestContext.status).send(requestContext.reason);
                     terminateConnection();
                 }
             }
         }
     }
References Close, http::Request::connectionState, http::Response::connectionState, http::Request::httpMajor, http::Request::httpMinor, Keep, http::ServerContext< RequestT, ResponseT >::RequestContext::reason, http::ServerContext< RequestT, ResponseT >::RequestContext::request, http::ServerContext< RequestT, ResponseT >::RequestContext::response, http::Response::send(), http::Response::status(), and http::ServerContext< RequestT, ResponseT >::RequestContext::status.
sendResponseData()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::sendResponseData (const char * buf, size_t len) override virtual
Implements http::ServerContextBase.
Definition at line 139 of file ServerContext.hpp.
{
         socketConnection->enqueue(buf, len);
     }
References net::socket::stream::SocketConnectionBase::enqueue().
terminateConnection()
template<typename Request , typename Response > void http::ServerContext< Request, Response >::terminateConnection override virtual
Implements http::ServerContextBase.
Definition at line 214 of file ServerContext.hpp.
{
         if (!connectionTerminated) {
             socketConnection->close();
             requestContexts.clear();
             connectionTerminated = true;
         }
         reset();
     }
References net::socket::stream::SocketConnectionBase::close().
Member Data Documentation
connectionTerminated
template<typename RequestT , typename ResponseT > bool http::ServerContext< RequestT, ResponseT >::connectionTerminated = false private
Definition at line 100 of file ServerContext.h.
onRequestCompleted
template<typename RequestT , typename ResponseT > std::function<void(Request& req, Response& res)> http::ServerContext< RequestT, ResponseT >::onRequestCompleted private
Definition at line 93 of file ServerContext.h.
onRequestReady
template<typename RequestT , typename ResponseT > std::function<void(Request& req, Response& res)> http::ServerContext< RequestT, ResponseT >::onRequestReady private
Definition at line 92 of file ServerContext.h.
parser
template<typename RequestT , typename ResponseT > RequestParser http::ServerContext< RequestT, ResponseT >::parser private
Definition at line 95 of file ServerContext.h.
requestContexts
template<typename RequestT , typename ResponseT > std::list<RequestContext> http::ServerContext< RequestT, ResponseT >::requestContexts private
Definition at line 97 of file ServerContext.h.
Referenced by http::ServerContext< RequestT, ResponseT >::ServerContext().
requestInProgress
template<typename RequestT , typename ResponseT > bool http::ServerContext< RequestT, ResponseT >::requestInProgress = false private
Definition at line 99 of file ServerContext.h.
socketConnection
template<typename RequestT , typename ResponseT > SocketConnection* http::ServerContext< RequestT, ResponseT >::socketConnection private
Definition at line 90 of file ServerContext.h.
The documentation for this class was generated from the following files:
http/ServerContext.h
http/ServerContext.hpp