snode.c: web::http::client::Response Class Reference
web::http::client::Response Class Reference
#include <Response.h>
Public Member Functions
const std::string & header (const std::string &key, int i=0) const
const std::string & cookie (const std::string &key) const
std::size_t bodyLength () const
void upgrade (Request &request)
Public Attributes
std::string httpVersion
std::string statusCode
std::string reason
char * body = nullptr
std::size_t contentLength = 0
const std::map< std::string, std::string > * headers = nullptr
const std::map< std::string, CookieOptions > * cookies = nullptr
Protected Member Functions
Response (SocketContext *clientContext)
void reset ()
Protected Attributes
SocketContext * socketContext
Private Attributes
std::string nullstr = ""
Friends
template<typename Request , typename Response >
class SocketContext
Detailed Description
Definition at line 41 of file Response.h.
Constructor & Destructor Documentation
Response()
web::http::client::Response::Response (SocketContext * clientContext) protected
Definition at line 36 of file Response.cpp.
         : socketContext(clientContext) {
     }
Member Function Documentation
bodyLength()
std::size_t web::http::client::Response::bodyLength () const
Definition at line 72 of file Response.cpp.
{
         return contentLength;
     }
References contentLength.
cookie()
const std::string & web::http::client::Response::cookie (const std::string & key) const
Definition at line 59 of file Response.cpp.
{
         std::map<std::string, CookieOptions>::const_iterator it;
         std::string tmpKey = key;
         httputils::to_lower(tmpKey);
         if ((it = cookies->find(tmpKey)) != cookies->end()) {
             return it->second.getValue();
         } else {
             return nullstr;
         }
     }
References cookies, nullstr, and httputils::to_lower().
header()
const std::string & web::http::client::Response::header (const std::string & key, int i = 0) const
Definition at line 40 of file Response.cpp.
{
         std::string tmpKey = key;
         httputils::to_lower(tmpKey);
         if (headers->find(tmpKey) != headers->end()) {
             std::pair<std::multimap<std::string, std::string>::const_iterator, std::multimap<std::string, std::string>::const_iterator>
                 range = headers->equal_range(tmpKey);
             if (std::distance(range.first, range.second) >= i) {
                 std::advance(range.first, i);
                 return (*(range.first)).second;
             } else {
                 return nullstr;
             }
         } else {
             return nullstr;
         }
     }
References headers, nullstr, and httputils::to_lower().
Referenced by web::http::client::SocketContextUpgradeFactorySelector::select(), and upgrade().
reset()
void web::http::client::Response::reset () protected
Definition at line 95 of file Response.cpp.
{
     }
upgrade()
void web::http::client::Response::upgrade (Request & request)
Definition at line 76 of file Response.cpp.
{
         if (httputils::ci_contains(this->header("connection"), "Upgrade")) {
             web::http::client::SocketContextUpgradeFactory* socketContextUpgradeFactory =
                 web::http::client::SocketContextUpgradeFactorySelector::instance()->select(request, *this);
             if (socketContextUpgradeFactory != nullptr) {
                 if (socketContext->switchSocketContext(socketContextUpgradeFactory) == nullptr) {
                     socketContext->terminateConnection();
                 }
             } else {
                 VLOG(0) << "SocketContextUpgradeFactory not existing";
                 socketContext->terminateConnection();
             }
         } else {
             VLOG(0) << "Response did not contain upgrade";
             socketContext->terminateConnection();
         }
     }
References httputils::ci_contains(), header(), web::http::client::SocketContextUpgradeFactorySelector::instance(), web::http::client::SocketContextUpgradeFactorySelector::select(), socketContext, net::socket::stream::SocketContext::switchSocketContext(), and web::http::client::SocketContext< RequestT, ResponseT >::terminateConnection().
Friends And Related Function Documentation
SocketContext
template<typename Request , typename Response > friend class SocketContext friend
Definition at line 70 of file Response.h.
Member Data Documentation
body
char* web::http::client::Response::body = nullptr
Definition at line 58 of file Response.h.
contentLength
std::size_t web::http::client::Response::contentLength = 0
Definition at line 59 of file Response.h.
Referenced by bodyLength().
cookies
const std::map<std::string, CookieOptions>* web::http::client::Response::cookies = nullptr
Definition at line 65 of file Response.h.
Referenced by cookie().
headers
const std::map<std::string, std::string>* web::http::client::Response::headers = nullptr
Definition at line 64 of file Response.h.
Referenced by header().
httpVersion
std::string web::http::client::Response::httpVersion
Definition at line 55 of file Response.h.
nullstr
std::string web::http::client::Response::nullstr = "" private
Definition at line 73 of file Response.h.
Referenced by cookie(), and header().
reason
std::string web::http::client::Response::reason
Definition at line 57 of file Response.h.
socketContext
SocketContext* web::http::client::Response::socketContext protected
Definition at line 45 of file Response.h.
Referenced by upgrade().
statusCode
std::string web::http::client::Response::statusCode
Definition at line 56 of file Response.h.
The documentation for this class was generated from the following files:
web/http/client/Response.h
web/http/client/Response.cpp