snode.c: web::ws::Transmitter Class Reference
web::ws::Transmitter Class Reference abstract
#include <Transmitter.h>
Public Member Functions
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Protected Member Functions
Transmitter (bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Private Member Functions
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength)
void sendFrame (bool fin, uint8_t opCode, const char *payload, uint64_t payloadLength)
void dumpFrame (char *frame, uint64_t frameLength)
virtual void sendFrameData (uint8_t data)=0
virtual void sendFrameData (uint16_t data)=0
virtual void sendFrameData (uint32_t data)=0
virtual void sendFrameData (uint64_t data)=0
virtual void sendFrameData (const char *frame, uint64_t frameLength)=0
Private Attributes
std::default_random_engine generator
std::uniform_int_distribution< uint32_t > distribution {1, UINT32_MAX}
bool masking = false
Detailed Description
Definition at line 32 of file Transmitter.h.
Constructor & Destructor Documentation
Transmitter() [1/3]
web::ws::Transmitter::Transmitter () default
Transmitter() [2/3]
web::ws::Transmitter::Transmitter (const Transmitter &) delete
Transmitter() [3/3]
web::ws::Transmitter::Transmitter (bool masking) protected
Definition at line 35 of file Transmitter.cpp.
         : masking(masking) {
     }
Member Function Documentation
dumpFrame()
void web::ws::Transmitter::dumpFrame (char * frame, uint64_t frameLength) private
Definition at line 183 of file Transmitter.cpp.
{
         unsigned int modul = 4;
         std::stringstream stringStream;
         for (std::size_t i = 0; i < frameLength; i++) {
             stringStream << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % modul == 0 || i == frameLength) {
                 VLOG(0) << "Frame: " << stringStream.str();
                 stringStream.str("");
             }
         }
     }
operator=()
Transmitter& web::ws::Transmitter::operator= (const Transmitter &) delete
send()
void web::ws::Transmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 55 of file Transmitter.cpp.
{
         std::size_t messageOffset = 0;
         do {
             std::size_t sendFrameLength =
                 (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
             bool fin = (sendFrameLength == messageLength - messageOffset) && end;
             sendFrame(fin, opCode, message + messageOffset, sendFrameLength);
             messageOffset += sendFrameLength;
             opCode = 0; // continuation
         } while (messageLength - messageOffset > 0);
     }
References sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by sendMessage(), sendMessageEnd(), sendMessageFrame(), and sendMessageStart().
sendFrame()
void web::ws::Transmitter::sendFrame (bool fin, uint8_t opCode, const char * payload, uint64_t payloadLength) private
Definition at line 132 of file Transmitter.cpp.
{
         uint64_t length = 0;
         if (payloadLength < 126) {
             length = payloadLength;
         } else if (payloadLength < 0x10000) {
             length = 126;
         } else {
             length = 127;
         }
         char header[2];
         header[0] = static_cast<char>((fin ? 0b10000000 : 0) | opCode);
         header[1] = static_cast<char>((masking ? 0b10000000 : 0) | length);
         sendFrameData(header, 2);
         switch (length) {
             case 126:
                 sendFrameData(static_cast<uint16_t>(payloadLength));
                 break;
             case 127:
                 sendFrameData(payloadLength);
                 break;
         }
         union MaskingKey {
             uint32_t keyAsValue;
             char keyAsBytes[4];
         };
         MaskingKey maskingKeyAsArray = {.keyAsValue = distribution(generator)};
         if (masking) {
             sendFrameData(maskingKeyAsArray.keyAsValue);
             for (uint64_t i = 0; i < payloadLength; i++) {
                 *(const_cast<char*>(payload) + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4);
             }
         }
         sendFrameData(payload, payloadLength);
         if (masking) {
             for (uint64_t i = 0; i < payloadLength; i++) {
                 *(const_cast<char*>(payload) + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4);
             }
         }
     }
References distribution, generator, masking, and sendFrameData().
Referenced by send().
sendFrameData() [1/5]
virtual void web::ws::Transmitter::sendFrameData (const char * frame, uint64_t frameLength) private pure virtual
Implemented in web::ws::SocketContext.
sendFrameData() [2/5]
virtual void web::ws::Transmitter::sendFrameData (uint16_t data) private pure virtual
Implemented in web::ws::SocketContext.
sendFrameData() [3/5]
virtual void web::ws::Transmitter::sendFrameData (uint32_t data) private pure virtual
Implemented in web::ws::SocketContext.
sendFrameData() [4/5]
virtual void web::ws::Transmitter::sendFrameData (uint64_t data) private pure virtual
Implemented in web::ws::SocketContext.
sendFrameData() [5/5]
virtual void web::ws::Transmitter::sendFrameData (uint8_t data) private pure virtual
Implemented in web::ws::SocketContext.
Referenced by sendFrame().
sendMessage()
void web::ws::Transmitter::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) protected
Definition at line 39 of file Transmitter.cpp.
{
         send(true, opCode, message, messageLength);
     }
References send().
Referenced by web::ws::SocketContext::sendMessage().
sendMessageEnd()
void web::ws::Transmitter::sendMessageEnd (const char * message, std::size_t messageLength) protected
Definition at line 51 of file Transmitter.cpp.
{
         send(true, 0, message, messageLength);
     }
References send().
Referenced by web::ws::SocketContext::sendMessageEnd().
sendMessageFrame()
void web::ws::Transmitter::sendMessageFrame (const char * message, std::size_t messageLength) protected
Definition at line 47 of file Transmitter.cpp.
{
         send(false, 0, message, messageLength);
     }
References send().
Referenced by web::ws::SocketContext::sendMessageFrame().
sendMessageStart()
void web::ws::Transmitter::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) protected
Definition at line 43 of file Transmitter.cpp.
{
         send(false, opCode, message, messageLength);
     }
References send().
Referenced by web::ws::SocketContext::sendMessageStart().
Member Data Documentation
distribution
std::uniform_int_distribution<uint32_t> web::ws::Transmitter::distribution {1, UINT32_MAX} private
Definition at line 61 of file Transmitter.h.
Referenced by sendFrame().
generator
std::default_random_engine web::ws::Transmitter::generator private
Definition at line 60 of file Transmitter.h.
Referenced by sendFrame().
masking
bool web::ws::Transmitter::masking = false private
Definition at line 63 of file Transmitter.h.
Referenced by sendFrame().
The documentation for this class was generated from the following files:
web/ws/Transmitter.h
web/ws/Transmitter.cpp