snode.c: web::http::server::SocketContextUpgradeFactory Class Reference
web::http::server::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Types
using Resquest = web::http::server::Request
using Reponse = web::http::server::Response
Public Types inherited from web::http::SocketContextUpgradeFactory< Request, Response >
enum class Role
using Request = Request
using Response = Response
Protected Member Functions
SocketContextUpgradeFactory ()
void checkRefCount () final
Protected Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
SocketContextUpgradeFactory (Role role)
~SocketContextUpgradeFactory () override=default
void incRefCount ()
void decRefCount ()
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Static Protected Member Functions
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Additional Inherited Members
Public Member Functions inherited from web::http::SocketContextUpgradeFactory< Request, Response >
virtual std::string name ()=0
void prepare (Request &request, Response &response)
SocketContextUpgradeFactory< Request, Response >::Role getRole () const
void destroy ()
Public Member Functions inherited from net::socket::stream::SocketContextFactory
virtual SocketContext * create (SocketConnection *socketConnection)=0
Protected Attributes inherited from web::http::SocketContextUpgradeFactory< Request, Response >
Request * request
Response * response
std::size_t refCount
Detailed Description
Definition at line 37 of file SocketContextUpgradeFactory.h.
Member Typedef Documentation
Reponse
using web::http::server::SocketContextUpgradeFactory::Reponse = web::http::server::Response
Definition at line 40 of file SocketContextUpgradeFactory.h.
Resquest
using web::http::server::SocketContextUpgradeFactory::Resquest = web::http::server::Request
Definition at line 39 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory()
web::http::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory () protected
Definition at line 30 of file SocketContextUpgradeFactory.cpp.
         : web::http::SocketContextUpgradeFactory<Request, Response>(http::SocketContextUpgradeFactory<Request, Response>::Role::SERVER) {
     }
Member Function Documentation
checkRefCount()
void web::http::server::SocketContextUpgradeFactory::checkRefCount () final protected virtual
Implements web::http::SocketContextUpgradeFactory< Request, Response >.
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
         if (refCount == 0) {
             web::http::server::SocketContextUpgradeFactorySelector::instance()->unload(this);
         }
     }
References web::http::server::SocketContextUpgradeFactorySelector::instance(), web::http::SocketContextUpgradeFactory< Request, Response >::refCount, and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
Referenced by web::websocket::server::SocketContextUpgradeFactory::create().
link()
void web::http::server::SocketContextUpgradeFactory::link (const std::string & upgradeContextName, SocketContextUpgradeFactory *(*)() linkedPlugin) static protected
Definition at line 40 of file SocketContextUpgradeFactory.cpp.
{
         web::http::server::SocketContextUpgradeFactorySelector::instance()->link(upgradeContextName, linkedPlugin);
     }
References web::http::server::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link().
Referenced by web::websocket::server::SocketContextUpgradeFactory::link().
The documentation for this class was generated from the following files:
web/http/server/SocketContextUpgradeFactory.h
web/http/server/SocketContextUpgradeFactory.cpp