snode.c: http::websocket::WSTransmitter Class Reference
http::websocket::WSTransmitter Class Reference abstract
#include <WSTransmitter.h>
Classes
union MaskingKey
Public Member Functions
void messageStart (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (const char *message, std::size_t messageLength, uint32_t messageKey=0)
void messageEnd (const char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0)
Private Member Functions
void sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, const char *payload, uint64_t payloadLength)
void dumpFrame (char *frame, uint64_t frameLength)
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey)
virtual void onFrameReady (char *frame, uint64_t frameLength)=0
Detailed Description
Definition at line 31 of file WSTransmitter.h.
Member Function Documentation
dumpFrame()
void http::websocket::WSTransmitter::dumpFrame (char * frame, uint64_t frameLength) private
Definition at line 121 of file WSTransmitter.cpp.
{
         for (std::size_t i = 0; i < frameLength; i++) {
             std::cout << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % 4 == 0) {
                 std::cout << std::endl;
             }
         }
         std::cout << std::endl;
     }
message() [1/2]
void http::websocket::WSTransmitter::message (const char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 37 of file WSTransmitter.cpp.
{
         send(false, 0, message, messageLength, messageKey);
     }
References send().
Referenced by http::websocket::WSServerContext::close(), message(), messageEnd(), messageStart(), http::websocket::WSServerContext::onMessageEnd(), http::websocket::WSServerContext::ping(), http::websocket::WSServerContext::pong(), and send().
message() [2/2]
void http::websocket::WSTransmitter::message (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 45 of file WSTransmitter.cpp.
{
         send(true, opCode, message, messageLength, messageKey);
     }
References message(), and send().
messageEnd()
void http::websocket::WSTransmitter::messageEnd (const char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 41 of file WSTransmitter.cpp.
{
         send(true, 0, message, messageLength, messageKey);
     }
References message(), and send().
messageStart()
void http::websocket::WSTransmitter::messageStart (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 33 of file WSTransmitter.cpp.
{
         send(false, opCode, message, messageLength, messageKey);
     }
References message(), and send().
onFrameReady()
virtual void http::websocket::WSTransmitter::onFrameReady (char * frame, uint64_t frameLength) private pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by sendFrame().
send()
void http::websocket::WSTransmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey) private
Definition at line 49 of file WSTransmitter.cpp.
{
         std::size_t messageOffset = 0;
         do {
             std::size_t sendMessageLength =
                 (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
             bool fin = sendMessageLength == messageLength - messageOffset;
             sendFrame(fin && end, opCode, messageKey, message + messageOffset, sendMessageLength);
             messageOffset += sendMessageLength;
             opCode = 0; // continuation
         } while (messageLength - messageOffset > 0);
     }
References message(), sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by message(), messageEnd(), and messageStart().
sendFrame()
void http::websocket::WSTransmitter::sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, const char * payload, uint64_t payloadLength) private
Definition at line 66 of file WSTransmitter.cpp.
{
         uint64_t frameLength = 2 + payloadLength;
         uint8_t opCodeOffset = 0;
         uint8_t lengthOffset = 1;
         uint8_t eLengthOffset = 2;
         uint8_t maskingKeyOffset = 2;
         uint8_t payloadOffset = 2;
         if (maskingKey > 0) {
             frameLength += 4;
             payloadOffset += 4;
         }
         char* frame = nullptr;
         uint64_t length = 0;
         if (payloadLength < 126) {
             frame = new char[frameLength];
             length = payloadLength;
         } else if (payloadLength < 0x10000) {
             frameLength += 2;
             maskingKeyOffset += 2;
             payloadOffset += 2;
             frame = new char[frameLength];
             *reinterpret_cast<uint16_t*>(frame + eLengthOffset) = htobe16(static_cast<uint16_t>(payloadLength));
             length = 126;
         } else {
             frameLength += 8;
             maskingKeyOffset += 8;
             payloadOffset += 8;
             frame = new char[frameLength];
             *reinterpret_cast<uint64_t*>(frame + eLengthOffset) = htobe64(payloadLength);
             length = 127;
         }
         if (maskingKey > 0) {
             *reinterpret_cast<uint32_t*>(frame + maskingKeyOffset) = htobe32(maskingKey);
         }
         *reinterpret_cast<uint8_t*>(frame + opCodeOffset) = static_cast<uint8_t>((fin ? 0b10000000 : 0) | opCode);
         *reinterpret_cast<uint8_t*>(frame + lengthOffset) = static_cast<uint8_t>(((maskingKey > 0) ? 0b10000000 : 0) | length);
         MaskingKey maskingKeyAsArray = {.key = htobe32(maskingKey)};
         for (uint64_t i = 0; i < payloadLength; i++) {
             *(frame + payloadOffset + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsArray + i % 4);
         }
         //        dumpFrame(frame, frameLength);
         onFrameReady(frame, frameLength);
         delete[] frame;
     }
References http::websocket::WSTransmitter::MaskingKey::key, http::websocket::WSTransmitter::MaskingKey::keyAsArray, and onFrameReady().
Referenced by send().
The documentation for this class was generated from the following files:
http/WSTransmitter.h
http/WSTransmitter.cpp