snode.c: net::EventDispatcher< EventReceiverT > Class Template Reference
net::EventDispatcher< EventReceiverT > Class Template Reference
#include <EventDispatcher.h>
Classes
class EventReceiverList
Public Types
using EventReceiver = EventReceiverT
Public Member Functions
EventDispatcher (FdSet &fdSet, long maxInactivity)
EventDispatcher (const EventDispatcher &)=delete
EventDispatcher & operator= (const EventDispatcher &)=delete
void enable (EventReceiver *eventReceiver, int fd)
void disable (EventReceiver *eventReceiver, int fd)
void suspend (EventReceiver *eventReceiver, int fd)
void resume (EventReceiver *eventReceiver, int fd)
long getTimeout () const
unsigned long getEventCounter ()
Private Member Functions
int getMaxFd ()
struct timeval observeEnabledEvents ()
struct timeval dispatchActiveEvents (struct timeval currentTime)
void unobserveDisabledEvents ()
void unobserveDisabledEventReceiver ()
void disableObservedEvents ()
Private Attributes
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
EventReceiverList unobservedEventReceiver
FdSet & fdSet
long maxInactivity
unsigned long eventCounter = 0
Friends
class EventLoop
Detailed Description
template<typename EventReceiverT>
class net::EventDispatcher< EventReceiverT >
Definition at line 43 of file EventDispatcher.h.
Member Typedef Documentation
EventReceiver
template<typename EventReceiverT > using net::EventDispatcher< EventReceiverT >::EventReceiver = EventReceiverT
Definition at line 45 of file EventDispatcher.h.
Constructor & Destructor Documentation
EventDispatcher() [1/2]
template<typename EventReceiverT > net::EventDispatcher< EventReceiverT >::EventDispatcher (FdSet & fdSet, long maxInactivity) inline explicit
Definition at line 60 of file EventDispatcher.h.
             : fdSet(fdSet)
             , maxInactivity(maxInactivity) {
         }
EventDispatcher() [2/2]
template<typename EventReceiverT > net::EventDispatcher< EventReceiverT >::EventDispatcher (const EventDispatcher< EventReceiverT > &) delete
Member Function Documentation
disable()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::disable (EventReceiver * eventReceiver, int fd) inline
Definition at line 86 of file EventDispatcher.h.
{
             if (enabledEventReceiver[fd].contains(eventReceiver)) {
                 // same tick
                 enabledEventReceiver[fd].remove(eventReceiver);
                 eventReceiver->disabled();
                 if (eventReceiver->observationCounter == 0) {
                     unobservedEventReceiver.push_back(eventReceiver);
                 }
             } else if (eventReceiver->isEnabled() &&
                        (!disabledEventReceiver.contains(fd) || !disabledEventReceiver[fd].contains(eventReceiver))) {
                 // normal
                 disabledEventReceiver[fd].push_back(eventReceiver);
             } else {
                 LOG(WARNING) << "EventReceiver double disable";
             }
         }
Referenced by net::AcceptEventReceiver::disable(), net::ConnectEventReceiver::disable(), net::OutOfBandEventReceiver::disable(), net::ReadEventReceiver::disable(), and net::WriteEventReceiver::disable().
disableObservedEvents()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::disableObservedEvents () inline private
Definition at line 222 of file EventDispatcher.h.
{
             for (auto& [fd, eventReceivers] : observedEventReceiver) {
                 for (EventReceiver* eventReceiver : eventReceivers) {
                     disabledEventReceiver[fd].push_back(eventReceiver);
                 }
             }
         }
Referenced by net::EventLoop::start().
dispatchActiveEvents()
template<typename EventReceiverT > struct timeval net::EventDispatcher< EventReceiverT >::dispatchActiveEvents (struct timeval currentTime) inline private
Definition at line 134 of file EventDispatcher.h.
{
             struct timeval nextInactivityTimeout {
                 LONG_MAX, 0
             };
             for (const auto& [fd, eventReceivers] : observedEventReceiver) {
                 EventReceiver* eventReceiver = eventReceivers.front();
                 struct timeval maxInactivity = eventReceiver->getTimeout();
                 if (fdSet.isSet(fd)) {
                     eventCounter++;
                     eventReceiver->dispatchEvent();
                     eventReceiver->triggered(currentTime);
                     nextInactivityTimeout = std::min(nextInactivityTimeout, maxInactivity);
                 } else {
                     struct timeval inactivity = currentTime - eventReceiver->getLastTriggered();
                     if (inactivity >= maxInactivity) {
                         eventReceiver->timeout();
                         eventReceiver->disable();
                     } else {
                         nextInactivityTimeout = std::min(maxInactivity - inactivity, nextInactivityTimeout);
                     }
                 }
             }
             return nextInactivityTimeout;
         }
Referenced by net::EventLoop::tick().
enable()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::enable (EventReceiver * eventReceiver, int fd) inline
Definition at line 69 of file EventDispatcher.h.
{
             if (disabledEventReceiver[fd].contains(eventReceiver)) {
                 // same tick
                 disabledEventReceiver[fd].remove(eventReceiver);
             } else if (!eventReceiver->isEnabled() &&
                        (!enabledEventReceiver.contains(fd) || !enabledEventReceiver[fd].contains(eventReceiver))) {
                 // normal
                 enabledEventReceiver[fd].push_back(eventReceiver);
                 eventReceiver->enabled(fd);
                 if (unobservedEventReceiver.contains(eventReceiver)) {
                     unobservedEventReceiver.remove(eventReceiver);
                 }
             } else {
                 LOG(WARNING) << "EventReceiver double enable";
             }
         }
Referenced by net::AcceptEventReceiver::enable(), net::ConnectEventReceiver::enable(), net::OutOfBandEventReceiver::enable(), net::ReadEventReceiver::enable(), and net::WriteEventReceiver::enable().
getEventCounter()
template<typename EventReceiverT > unsigned long net::EventDispatcher< EventReceiverT >::getEventCounter () inline
Definition at line 129 of file EventDispatcher.h.
{
             return eventCounter;
         }
Referenced by net::EventLoop::getEventCounter().
getMaxFd()
template<typename EventReceiverT > int net::EventDispatcher< EventReceiverT >::getMaxFd () inline private
Definition at line 134 of file EventDispatcher.h.
{
             int maxFd = -1;
             if (!observedEventReceiver.empty()) {
                 maxFd = observedEventReceiver.rbegin()->first;
             }
             return maxFd;
         }
Referenced by net::EventLoop::tick().
getTimeout()
template<typename EventReceiverT > long net::EventDispatcher< EventReceiverT >::getTimeout () const inline
Definition at line 125 of file EventDispatcher.h.
{
             return maxInactivity;
         }
observeEnabledEvents()
template<typename EventReceiverT > struct timeval net::EventDispatcher< EventReceiverT >::observeEnabledEvents () inline private
Definition at line 134 of file EventDispatcher.h.
{
             struct timeval nextTimeout = {LONG_MAX, 0};
             for (auto [fd, eventReceivers] : enabledEventReceiver) {
                 for (EventReceiver* eventReceiver : eventReceivers) {
                     observedEventReceiver[fd].push_front(eventReceiver);
                     if (!eventReceiver->isSuspended()) {
                         fdSet.set(fd);
                         nextTimeout = std::min(nextTimeout, eventReceiver->getTimeout());
                     } else {
                         fdSet.clr(fd, true);
                     }
                 }
             }
             enabledEventReceiver.clear();
             fdSet.prepare();
             return nextTimeout;
         }
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
operator=()
template<typename EventReceiverT > EventDispatcher& net::EventDispatcher< EventReceiverT >::operator= (const EventDispatcher< EventReceiverT > &) delete
resume()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::resume (EventReceiver * eventReceiver, int fd) inline
Definition at line 114 of file EventDispatcher.h.
{
             if (eventReceiver->isSuspended()) {
                 eventReceiver->resumed();
                 if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                     fdSet.set(fd);
                 }
             } else {
                 LOG(WARNING) << "EventReceiver double resume";
             }
         }
Referenced by net::AcceptEventReceiver::resume(), net::ConnectEventReceiver::resume(), net::OutOfBandEventReceiver::resume(), net::ReadEventReceiver::resume(), and net::WriteEventReceiver::resume().
suspend()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::suspend (EventReceiver * eventReceiver, int fd) inline
Definition at line 103 of file EventDispatcher.h.
{
             if (!eventReceiver->isSuspended()) {
                 eventReceiver->suspended();
                 if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                     fdSet.clr(fd, true);
                 }
             } else {
                 LOG(WARNING) << "EventReceiver double suspend";
             }
         }
Referenced by net::AcceptEventReceiver::suspend(), net::ConnectEventReceiver::suspend(), net::OutOfBandEventReceiver::suspend(), net::ReadEventReceiver::suspend(), and net::WriteEventReceiver::suspend().
unobserveDisabledEventReceiver()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::unobserveDisabledEventReceiver () inline private
Definition at line 215 of file EventDispatcher.h.
{
             for (EventReceiver* eventReceiver : unobservedEventReceiver) {
                 eventReceiver->unobserved();
             }
             unobservedEventReceiver.clear();
         }
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
unobserveDisabledEvents()
template<typename EventReceiverT > void net::EventDispatcher< EventReceiverT >::unobserveDisabledEvents () inline private
Definition at line 192 of file EventDispatcher.h.
{
             for (auto [fd, eventReceivers] : disabledEventReceiver) {
                 for (EventReceiver* eventReceiver : eventReceivers) {
                     observedEventReceiver[fd].remove(eventReceiver);
                     if (observedEventReceiver[fd].empty() || observedEventReceiver[fd].front()->isSuspended()) {
                         if (observedEventReceiver[fd].empty()) {
                             observedEventReceiver.erase(fd);
                         }
                         fdSet.clr(fd, true);
                     } else {
                         fdSet.set(fd);
                         observedEventReceiver[fd].front()->triggered();
                     }
                     eventReceiver->disabled();
                     if (eventReceiver->observationCounter == 0) {
                         unobservedEventReceiver.push_back(eventReceiver);
                     }
                     eventReceiver->fd = -1;
                 }
             }
             disabledEventReceiver.clear();
         }
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
Friends And Related Function Documentation
EventLoop
template<typename EventReceiverT > friend class EventLoop friend
Definition at line 241 of file EventDispatcher.h.
Member Data Documentation
disabledEventReceiver
template<typename EventReceiverT > std::map<int, EventReceiverList> net::EventDispatcher< EventReceiverT >::disabledEventReceiver private
Definition at line 232 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::disable(), net::EventDispatcher< ReadEventReceiver >::disableObservedEvents(), net::EventDispatcher< ReadEventReceiver >::enable(), and net::EventDispatcher< ReadEventReceiver >::unobserveDisabledEvents().
enabledEventReceiver
template<typename EventReceiverT > std::map<int, EventReceiverList> net::EventDispatcher< EventReceiverT >::enabledEventReceiver private
Definition at line 230 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::disable(), and net::EventDispatcher< ReadEventReceiver >::enable().
eventCounter
template<typename EventReceiverT > unsigned long net::EventDispatcher< EventReceiverT >::eventCounter = 0 private
Definition at line 239 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::getEventCounter().
fdSet
template<typename EventReceiverT > FdSet& net::EventDispatcher< EventReceiverT >::fdSet private
Definition at line 235 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::resume(), net::EventDispatcher< ReadEventReceiver >::suspend(), and net::EventDispatcher< ReadEventReceiver >::unobserveDisabledEvents().
maxInactivity
template<typename EventReceiverT > long net::EventDispatcher< EventReceiverT >::maxInactivity private
Definition at line 237 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::getTimeout().
observedEventReceiver
template<typename EventReceiverT > std::map<int, EventReceiverList> net::EventDispatcher< EventReceiverT >::observedEventReceiver private
Definition at line 231 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::disableObservedEvents(), net::EventDispatcher< ReadEventReceiver >::observeEnabledEvents(), net::EventDispatcher< ReadEventReceiver >::resume(), net::EventDispatcher< ReadEventReceiver >::suspend(), and net::EventDispatcher< ReadEventReceiver >::unobserveDisabledEvents().
unobservedEventReceiver
template<typename EventReceiverT > EventReceiverList net::EventDispatcher< EventReceiverT >::unobservedEventReceiver private
Definition at line 233 of file EventDispatcher.h.
Referenced by net::EventDispatcher< ReadEventReceiver >::disable(), net::EventDispatcher< ReadEventReceiver >::enable(), net::EventDispatcher< ReadEventReceiver >::unobserveDisabledEventReceiver(), and net::EventDispatcher< ReadEventReceiver >::unobserveDisabledEvents().
The documentation for this class was generated from the following file:
net/EventDispatcher.h