snode.c: express::ApplicationDispatcher Class Reference
express::ApplicationDispatcher Class Reference
Public Member Functions
ApplicationDispatcher (const std::function< void(Request &req, Response &res)> &lambda)
Public Member Functions inherited from express::Dispatcher
Dispatcher ()=default
virtual ~Dispatcher ()=default
Private Member Functions
void dispatch (const RouterDispatcher *parentRouter, const std::string &parentMountPath, const MountPoint &mountPoint, Request &req, Response &res) const override
Private Attributes
const std::function< void(Request &req, Response &res)> lambda
Detailed Description
Definition at line 199 of file Router.cpp.
Constructor & Destructor Documentation
ApplicationDispatcher()
express::ApplicationDispatcher::ApplicationDispatcher (const std::function< void(Request &req, Response &res)> & lambda) inline explicit
Definition at line 201 of file Router.cpp.
             : lambda(lambda) {
         }
Member Function Documentation
dispatch()
void express::ApplicationDispatcher::dispatch (const RouterDispatcher * parentRouter, const std::string & parentMountPath, const MountPoint & mountPoint, Request & req, Response & res) const override private virtual
Implements express::Dispatcher.
Definition at line 275 of file Router.cpp.
{
         std::string absoluteMountPath = path_concat(parentMountPath, mountPoint.relativeMountPath);
         // TODO: Fix regex-match
         if ((req.path.rfind(absoluteMountPath, 0) == 0 && mountPoint.method == "use") ||
             ((absoluteMountPath == req.path || checkForUrlMatch(absoluteMountPath, req.url)) &&
              (req.method == mountPoint.method || mountPoint.method == "all"))) {
             parentRouter->terminate();
             if (hasResult(absoluteMountPath)) {
                 setParams(absoluteMountPath, req);
             }
             lambda(req, res);
         }
     }
References express::checkForUrlMatch(), express::hasResult(), lambda, express::MountPoint::method, web::http::server::Request::method, express::Request::path, express::path_concat(), express::MountPoint::relativeMountPath, express::setParams(), express::RouterDispatcher::terminate(), and web::http::server::Request::url.
Member Data Documentation
lambda
const std::function<void(Request& req, Response& res)> express::ApplicationDispatcher::lambda private
Definition at line 212 of file Router.cpp.
Referenced by dispatch().
The documentation for this class was generated from the following file:
express/Router.cpp