snode.c: web::ws::SubProtocol Class Reference
web::ws::SubProtocol Class Reference abstract
#include <SubProtocol.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
virtual ~SubProtocol ()
void sendMessage (const char *message, std::size_t messageLength)
void sendMessage (const std::string &message)
void sendMessageStart (const char *message, std::size_t messageLength)
void sendMessageStart (const std::string &message)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageFrame (const std::string &message)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessageEnd (const std::string &message)
void sendPing (char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
const std::string & getName ()
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *junk, std::size_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onPongReceived ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onProtocolConnected ()=0
virtual void onProtocolDisconnected ()=0
void setWSContext (SocketContext *ServerContext)
Protected Member Functions
SubProtocol (const std::string &name)
SubProtocol ()=delete
SubProtocol (const SubProtocol &)=delete
SubProtocol & operator= (const SubProtocol &)=delete
Protected Attributes
SocketContext * context
const std::string name
Detailed Description
Definition at line 36 of file SubProtocol.h.
Member Enumeration Documentation
Role
enum web::ws::SubProtocol::Role strong
Enumerator
SERVER
CLIENT
Definition at line 38 of file SubProtocol.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
SubProtocol() [1/3]
web::ws::SubProtocol::SubProtocol (const std::string & name) protected
Definition at line 29 of file SubProtocol.cpp.
         : name(name) {
     }
SubProtocol() [2/3]
web::ws::SubProtocol::SubProtocol () protected delete
SubProtocol() [3/3]
web::ws::SubProtocol::SubProtocol (const SubProtocol &) protected delete
~SubProtocol()
web::ws::SubProtocol::~SubProtocol () virtual
Reimplemented in web::ws::server::SubProtocol.
Definition at line 33 of file SubProtocol.cpp.
{
     }
Member Function Documentation
getLocalAddressAsString()
std::string web::ws::SubProtocol::getLocalAddressAsString () const
Definition at line 76 of file SubProtocol.cpp.
{
         return context->getLocalAddressAsString();
     }
References context, and web::ws::SocketContext::getLocalAddressAsString().
getName()
const std::string & web::ws::SubProtocol::getName ()
Definition at line 89 of file SubProtocol.cpp.
{
         return name;
     }
References name.
Referenced by web::ws::server::SubProtocolSelector::destroy().
getRemoteAddressAsString()
std::string web::ws::SubProtocol::getRemoteAddressAsString () const
Definition at line 80 of file SubProtocol.cpp.
{
         return context->getRemoteAddressAsString();
     }
References context, and web::ws::SocketContext::getRemoteAddressAsString().
onMessageData()
virtual void web::ws::SubProtocol::onMessageData (const char * junk, std::size_t junkLen) pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onFrameReceived().
onMessageEnd()
virtual void web::ws::SubProtocol::onMessageEnd () pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onMessageEnd().
onMessageError()
virtual void web::ws::SubProtocol::onMessageError (uint16_t errnum) pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onMessageError().
onMessageStart()
virtual void web::ws::SubProtocol::onMessageStart (int opCode) pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onMessageStart().
onPongReceived()
virtual void web::ws::SubProtocol::onPongReceived () pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onMessageEnd(), and web::ws::SocketContext::onPongReceived().
onProtocolConnected()
virtual void web::ws::SubProtocol::onProtocolConnected () pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onProtocolConnected().
onProtocolDisconnected()
virtual void web::ws::SubProtocol::onProtocolDisconnected () pure virtual
Implemented in web::ws::server::SubProtocol, and web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::SocketContext::onProtocolDisconnected().
operator=()
SubProtocol& web::ws::SubProtocol::operator= (const SubProtocol &) protected delete
sendClose()
void web::ws::SubProtocol::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 72 of file SubProtocol.cpp.
{
         context->close(statusCode, reason, reasonLength);
     }
References web::ws::SocketContext::close(), and context.
sendMessage() [1/2]
void web::ws::SubProtocol::sendMessage (const char * message, std::size_t messageLength)
Definition at line 36 of file SubProtocol.cpp.
{
         context->sendMessage(2, msg, messageLength);
     }
References context, and web::ws::SocketContext::sendMessage().
sendMessage() [2/2]
void web::ws::SubProtocol::sendMessage (const std::string & message)
Definition at line 40 of file SubProtocol.cpp.
{
         context->sendMessage(1, msg.data(), msg.length());
     }
References context, and web::ws::SocketContext::sendMessage().
sendMessageEnd() [1/2]
void web::ws::SubProtocol::sendMessageEnd (const char * message, std::size_t messageLength)
Definition at line 60 of file SubProtocol.cpp.
{
         context->sendMessageEnd(message, messageLength);
     }
References context, and web::ws::SocketContext::sendMessageEnd().
Referenced by sendMessageEnd().
sendMessageEnd() [2/2]
void web::ws::SubProtocol::sendMessageEnd (const std::string & message)
Definition at line 64 of file SubProtocol.cpp.
{
         sendMessageEnd(message.data(), message.length());
     }
References sendMessageEnd().
sendMessageFrame() [1/2]
void web::ws::SubProtocol::sendMessageFrame (const char * message, std::size_t messageLength)
Definition at line 52 of file SubProtocol.cpp.
{
         context->sendMessageFrame(message, messageLength);
     }
References context, and web::ws::SocketContext::sendMessageFrame().
Referenced by sendMessageFrame().
sendMessageFrame() [2/2]
void web::ws::SubProtocol::sendMessageFrame (const std::string & message)
Definition at line 56 of file SubProtocol.cpp.
{
         sendMessageFrame(message.data(), message.length());
     }
References sendMessageFrame().
sendMessageStart() [1/2]
void web::ws::SubProtocol::sendMessageStart (const char * message, std::size_t messageLength)
Definition at line 44 of file SubProtocol.cpp.
{
         context->sendMessageStart(2, message, messageLength);
     }
References context, and web::ws::SocketContext::sendMessageStart().
sendMessageStart() [2/2]
void web::ws::SubProtocol::sendMessageStart (const std::string & message)
Definition at line 48 of file SubProtocol.cpp.
                                                                { // 1
         context->sendMessageStart(1, message.data(), message.length());
     }
References context, and web::ws::SocketContext::sendMessageStart().
sendPing()
void web::ws::SubProtocol::sendPing (char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 68 of file SubProtocol.cpp.
{
         context->sendPing(reason, reasonLength);
     }
References context, and web::ws::SocketContext::sendPing().
setWSContext()
void web::ws::SubProtocol::setWSContext (SocketContext * ServerContext)
Definition at line 85 of file SubProtocol.cpp.
{
         context = ServerContext;
     }
References context.
Referenced by web::ws::SocketContext::SocketContext().
Member Data Documentation
context
SocketContext* web::ws::SubProtocol::context protected
Definition at line 85 of file SubProtocol.h.
Referenced by getLocalAddressAsString(), getRemoteAddressAsString(), sendClose(), sendMessage(), sendMessageEnd(), sendMessageFrame(), sendMessageStart(), sendPing(), and setWSContext().
name
const std::string web::ws::SubProtocol::name protected
Definition at line 87 of file SubProtocol.h.
Referenced by getName().
The documentation for this class was generated from the following files:
web/ws/SubProtocol.h
web/ws/SubProtocol.cpp