snode.c: web::ws::server::SocketContext Class Reference
web::ws::server::SocketContext Class Reference
#include <SocketContext.h>
Static Public Member Functions
static SocketContext * create (net::socket::stream::SocketConnectionBase *socketConnection, web::http::server::Request &req, web::http::server::Response &res)
Protected Member Functions
SocketContext (net::socket::stream::SocketConnectionBase *socketConnection, web::ws::server::SubProtocol *subProtocol, web::ws::SubProtocol::Role role)
~SocketContext () override
Protected Member Functions inherited from web::ws::SocketContext
SocketContext (net::socket::stream::SocketConnectionBase *socketConnection, web::ws::SubProtocol *subProtocol, web::ws::SubProtocol::Role role)
SocketContext ()=delete
SocketContext (const SocketContext &)=delete
SocketContext & operator= (const SocketContext &)=delete
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnectionBase *socketConnection)
Protected Member Functions inherited from web::ws::Transmitter
Transmitter (bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Additional Inherited Members
Public Member Functions inherited from web::ws::SocketContext
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void replyPong (const char *reason=nullptr, std::size_t reasonLength=0)
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketProtocol (const SocketContextFactory &socketProtocolFactory)
void setTimeout (int timeout)
Public Member Functions inherited from web::ws::Receiver
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Public Member Functions inherited from web::ws::Transmitter
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Protected Attributes inherited from web::ws::SocketContext
web::ws::SubProtocol * subProtocol
Detailed Description
Definition at line 33 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
web::ws::server::SocketContext::SocketContext (net::socket::stream::SocketConnectionBase * socketConnection, web::ws::server::SubProtocol * subProtocol, web::ws::SubProtocol::Role role) protected
Definition at line 35 of file SocketContext.cpp.
         : web::ws::SocketContext(socketConnection, subProtocol, role) {
     }
~SocketContext()
web::ws::server::SocketContext::~SocketContext () override protected virtual
Reimplemented from web::ws::SocketContext.
Member Function Documentation
create()
SocketContext * web::ws::server::SocketContext::create (net::socket::stream::SocketConnectionBase * socketConnection, web::http::server::Request & req, web::http::server::Response & res) static
Definition at line 50 of file SocketContext.cpp.
{
         std::string subProtocolName = req.header("sec-websocket-protocol");
         web::ws::server::SubProtocolInterface* subProtocolInterface =
             web::ws::server::SubProtocolSelector::instance()->select(subProtocolName);
         web::ws::server::SocketContext* context = nullptr;
         if (subProtocolInterface != nullptr) {
             web::ws::server::SubProtocol* subProtocol = static_cast<web::ws::server::SubProtocol*>(subProtocolInterface->create(req, res));
             if (subProtocol != nullptr) {
                 subProtocol->setClients(subProtocolInterface->getClients());
                 context = new web::ws::server::SocketContext(socketConnection, subProtocol, web::ws::SubProtocol::Role::SERVER);
                 if (context != nullptr) {
                     res.set("Upgrade", "websocket");
                     res.set("Connection", "Upgrade");
                     res.set("Sec-WebSocket-Protocol", subProtocolName);
                     web::ws::serverWebSocketKey(req.header("sec-websocket-key"), [&res](char* key) -> void {
                         res.set("Sec-WebSocket-Accept", key);
                     });
                     res.status(101).end(); // Switch Protocol
                 } else {
                     delete subProtocol;
                     res.status(500).end();
                 }
             } else {
                 res.status(500).end(); // Internal Server Error
             }
         } else {
             res.status(404).end(); // Not found
         }
         return context;
     }
References web::ws::SubProtocolInterface::create(), web::http::server::Response::end(), web::ws::server::SubProtocolInterface::getClients(), web::http::server::Request::header(), web::ws::server::SubProtocolSelector::instance(), web::ws::SubProtocol::SERVER, web::ws::serverWebSocketKey(), web::http::server::Response::set(), net::socket::stream::SocketContext::socketConnection, web::http::server::Response::status(), and web::ws::SocketContext::subProtocol.
Referenced by web::ws::server::SocketContextUpgradeFactory::create().
The documentation for this class was generated from the following files:
web/ws/server/SocketContext.h
web/ws/server/SocketContext.cpp