snode.c: net::socket::stream::SocketServer< SocketListenerT > Class Template Reference
net::socket::stream::SocketServer< SocketListenerT > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketListener = SocketListenerT
using SocketConnection = typename SocketListener::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
SocketServer (const std::shared_ptr< const SocketProtocolFactory > socketProtocolFactory, const std::function< void(const SocketAddress &localAddress, const SocketAddress &remoteAddress)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onConnected, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, std::size_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options={{}})
SocketServer ()=delete
virtual ~SocketServer ()=default
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int err)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
Private Attributes
std::shared_ptr< const SocketProtocolFactory > socketProtocolFactory = nullptr
std::function< void(const SocketAddress &localAddress, const SocketAddress &remoteAddress)> _onConnect
std::function< void(SocketConnection *socketConnection)> _onConnected
std::function< void(SocketConnection *socketConnection)> _onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, std::size_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
std::map< std::string, std::any > options
Detailed Description
template<typename SocketListenerT>
class net::socket::stream::SocketServer< SocketListenerT >
Definition at line 39 of file SocketServer.h.
Member Typedef Documentation
SocketAddress
template<typename SocketListenerT > using net::socket::stream::SocketServer< SocketListenerT >::SocketAddress = typename SocketConnection::Socket::SocketAddress
Definition at line 43 of file SocketServer.h.
SocketConnection
template<typename SocketListenerT > using net::socket::stream::SocketServer< SocketListenerT >::SocketConnection = typename SocketListener::SocketConnection
Definition at line 42 of file SocketServer.h.
SocketListener
template<typename SocketListenerT > using net::socket::stream::SocketServer< SocketListenerT >::SocketListener = SocketListenerT
Definition at line 41 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer() [1/2]
template<typename SocketListenerT > net::socket::stream::SocketServer< SocketListenerT >::SocketServer (const std::shared_ptr< const SocketProtocolFactory > socketProtocolFactory, const std::function< void(const SocketAddress &localAddress, const SocketAddress &remoteAddress)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onConnected, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, std::size_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 45 of file SocketServer.h.
                                                                 {{}})
             : socketProtocolFactory(socketProtocolFactory)
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options) {
         }
SocketServer() [2/2]
template<typename SocketListenerT > net::socket::stream::SocketServer< SocketListenerT >::SocketServer () delete
~SocketServer()
template<typename SocketListenerT > virtual net::socket::stream::SocketServer< SocketListenerT >::~SocketServer () virtual default
Member Function Documentation
listen()
template<typename SocketListenerT > void net::socket::stream::SocketServer< SocketListenerT >::listen (const SocketAddress & bindAddress, int backlog, const std::function< void(int err)> & onError) const inline
Definition at line 67 of file SocketServer.h.
{
             errno = 0;
             SocketListener* socketListener = new SocketListener(
                 socketProtocolFactory, _onConnect, _onConnected, _onDisconnect, onRead, onReadError, onWriteError, options);
             socketListener->listen(bindAddress, backlog, onError);
         }
References net::socket::stream::SocketServer< SocketListenerT >::_onConnect, net::socket::stream::SocketServer< SocketListenerT >::_onConnected, net::socket::stream::SocketServer< SocketListenerT >::_onDisconnect, net::socket::stream::SocketServer< SocketListenerT >::onRead, net::socket::stream::SocketServer< SocketListenerT >::onReadError, net::socket::stream::SocketServer< SocketListenerT >::onWriteError, net::socket::stream::SocketServer< SocketListenerT >::options, and net::socket::stream::SocketServer< SocketListenerT >::socketProtocolFactory.
onConnect()
template<typename SocketListenerT > void net::socket::stream::SocketServer< SocketListenerT >::onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect) inline
Definition at line 76 of file SocketServer.h.
{
             _onConnect = onConnect;
         }
References net::socket::stream::SocketServer< SocketListenerT >::_onConnect.
onConnected()
template<typename SocketListenerT > void net::socket::stream::SocketServer< SocketListenerT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 80 of file SocketServer.h.
{
             _onConnected = onConnected;
         }
References net::socket::stream::SocketServer< SocketListenerT >::_onConnected.
onDisconnect()
template<typename SocketListenerT > void net::socket::stream::SocketServer< SocketListenerT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 84 of file SocketServer.h.
{
             _onDisconnect = onDisconnect;
         }
References net::socket::stream::SocketServer< SocketListenerT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename SocketListenerT > std::function<void(const SocketAddress& localAddress, const SocketAddress& remoteAddress)> net::socket::stream::SocketServer< SocketListenerT >::_onConnect private
Definition at line 91 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen(), and net::socket::stream::SocketServer< SocketListenerT >::onConnect().
_onConnected
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketServer< SocketListenerT >::_onConnected private
Definition at line 92 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen(), and net::socket::stream::SocketServer< SocketListenerT >::onConnected().
_onDisconnect
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketServer< SocketListenerT >::_onDisconnect private
Definition at line 93 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen(), and net::socket::stream::SocketServer< SocketListenerT >::onDisconnect().
onRead
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, const char* junk, std::size_t junkLen)> net::socket::stream::SocketServer< SocketListenerT >::onRead private
Definition at line 94 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen().
onReadError
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketServer< SocketListenerT >::onReadError private
Definition at line 95 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen().
onWriteError
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketServer< SocketListenerT >::onWriteError private
Definition at line 96 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen().
options
template<typename SocketListenerT > std::map<std::string, std::any> net::socket::stream::SocketServer< SocketListenerT >::options private
Definition at line 98 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen().
socketProtocolFactory
template<typename SocketListenerT > std::shared_ptr<const SocketProtocolFactory> net::socket::stream::SocketServer< SocketListenerT >::socketProtocolFactory = nullptr private
Definition at line 89 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketListenerT >::listen().
The documentation for this class was generated from the following file:
net/socket/stream/SocketServer.h