snode.c: web::ws::subprotocol::WSSubProtocolSelector Class Reference
web::ws::subprotocol::WSSubProtocolSelector Class Reference
#include <WSSubProtocolSelector.h>
Public Member Functions
WSSubProtocolSelector ()
~WSSubProtocolSelector ()
void loadSubProtocols (const std::string &path)
void loadSubProtocol (const WSSubProtocolPluginInterface &wSProtocolPlugin)
WSSubProtocolPluginInterface * select (const std::string &subProtocol, web::ws::WSSubProtocol::Role role)
Protected Member Functions
void loadSubProtocols ()
Private Attributes
std::map< std::string, WSSubProtocolPluginInterface > serverSubprotocols
std::map< std::string, WSSubProtocolPluginInterface > clientSubprotocols
Detailed Description
Definition at line 34 of file WSSubProtocolSelector.h.
Constructor & Destructor Documentation
WSSubProtocolSelector()
web::ws::subprotocol::WSSubProtocolSelector::WSSubProtocolSelector ()
Definition at line 36 of file WSSubProtocolSelector.cpp.
{
         loadSubProtocols();
     }
References loadSubProtocols().
~WSSubProtocolSelector()
web::ws::subprotocol::WSSubProtocolSelector::~WSSubProtocolSelector ()
Definition at line 84 of file WSSubProtocolSelector.cpp.
{
         for (auto& [name, subProtocol] : serverSubprotocols) {
             if (subProtocol.handle != nullptr) {
                 dlclose(subProtocol.handle);
             }
         }
         for (auto& [name, subProtocol] : clientSubprotocols) {
             if (subProtocol.handle != nullptr) {
                 dlclose(subProtocol.handle);
             }
         }
     }
References clientSubprotocols, web::ws::subprotocol::echo::server::name(), and serverSubprotocols.
Member Function Documentation
loadSubProtocol()
void web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocol (const WSSubProtocolPluginInterface & wSProtocolPlugin)
Definition at line 46 of file WSSubProtocolSelector.cpp.
{
         if (subProtocol.role() == web::ws::WSSubProtocol::Role::SERVER) {
             const auto [it, success] = serverSubprotocols.insert({subProtocol.name(), subProtocol});
             if (!success && subProtocol.handle) {
                 dlclose(subProtocol.handle);
             }
         } else {
             const auto [it, success] = clientSubprotocols.insert({subProtocol.name(), subProtocol});
             if (!success && subProtocol.handle) {
                 dlclose(subProtocol.handle);
             }
         }
     }
References clientSubprotocols, web::ws::subprotocol::WSSubProtocolPluginInterface::handle, web::ws::subprotocol::WSSubProtocolPluginInterface::name, web::ws::subprotocol::WSSubProtocolPluginInterface::role, web::ws::WSSubProtocol::SERVER, and serverSubprotocols.
Referenced by loadSubProtocols().
loadSubProtocols() [1/2]
void web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocols () protected
Definition at line 40 of file WSSubProtocolSelector.cpp.
{
         loadSubProtocols(SUBPROTOCOL_PATH);
         loadSubProtocols("/usr/lib/snodec/web/ws/subprotocol");
         loadSubProtocols("/usr/local/lib/snodec/web/ws/subprotocol");
     }
Referenced by WSSubProtocolSelector().
loadSubProtocols() [2/2]
void web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocols (const std::string & path)
Definition at line 60 of file WSSubProtocolSelector.cpp.
{
         if (std::filesystem::exists(path) && std::filesystem::is_directory(path)) {
             for (const std::filesystem::directory_entry& directoryEntry : std::filesystem::recursive_directory_iterator(path)) {
                 if (std::filesystem::is_regular_file(directoryEntry) && directoryEntry.path().extension() == ".so") {
                     void* handle = dlopen(directoryEntry.path().c_str(), RTLD_NOW | RTLD_LOCAL);
                     if (handle != nullptr) {
                         WSSubProtocolPluginInterface (*wSSubProtocolPluginInterface)(void*) =
                             reinterpret_cast<WSSubProtocolPluginInterface (*)(void*)>(dlsym(handle, "plugin"));
                         loadSubProtocol(wSSubProtocolPluginInterface(handle));
                         VLOG(1) << "DLOpen: success: " << directoryEntry.path().c_str();
                     } else {
                         VLOG(1) << "DLOpen: error: " << dlerror() << " - " << directoryEntry.path().c_str();
                     }
                 } else {
                     VLOG(1) << "Not a library: Ignoring direntry " << directoryEntry;
                 }
             }
         } else {
             VLOG(1) << "Not a directory: Ignoring path: " << path;
         }
     }
References loadSubProtocol().
select()
WSSubProtocolPluginInterface * web::ws::subprotocol::WSSubProtocolSelector::select (const std::string & subProtocol, web::ws::WSSubProtocol::Role role)
Definition at line 98 of file WSSubProtocolSelector.cpp.
{
         WSSubProtocolPluginInterface* subProtocol = nullptr;
         if (role == web::ws::WSSubProtocol::Role::SERVER) { // server
             if (serverSubprotocols.contains(subProtocolName)) {
                 subProtocol = &serverSubprotocols[subProtocolName];
             }
         } else if (role == web::ws::WSSubProtocol::Role::CLIENT) { // client
             if (clientSubprotocols.contains(subProtocolName)) {
                 subProtocol = &clientSubprotocols[subProtocolName];
             }
         }
         return subProtocol;
     }
References web::ws::WSSubProtocol::CLIENT, clientSubprotocols, web::ws::subprotocol::echo::server::role(), web::ws::WSSubProtocol::SERVER, and serverSubprotocols.
Referenced by web::ws::server::WSContext::create().
Member Data Documentation
clientSubprotocols
std::map<std::string, WSSubProtocolPluginInterface> web::ws::subprotocol::WSSubProtocolSelector::clientSubprotocols private
Definition at line 49 of file WSSubProtocolSelector.h.
Referenced by loadSubProtocol(), select(), and ~WSSubProtocolSelector().
serverSubprotocols
std::map<std::string, WSSubProtocolPluginInterface> web::ws::subprotocol::WSSubProtocolSelector::serverSubprotocols private
Definition at line 48 of file WSSubProtocolSelector.h.
Referenced by loadSubProtocol(), select(), and ~WSSubProtocolSelector().
The documentation for this class was generated from the following files:
web/ws/subprotocol/WSSubProtocolSelector.h
web/ws/subprotocol/WSSubProtocolSelector.cpp