snode.c: http::client::ClientContextBase Class Reference
http::client::ClientContextBase Class Reference abstract
#include <ClientContext.h>
Public Member Functions
virtual ~ClientContextBase ()=default
virtual void sendRequestData (const char *buf, std::size_t len)=0
virtual Request & getRequest ()=0
virtual void terminateConnection ()=0
virtual void requestCompleted ()=0
Public Member Functions inherited from net::socket::stream::SocketProtocol
virtual ~SocketProtocol ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
void close ()
virtual void receiveFromPeer (const char *junk, std::size_t junkLen)=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
void switchSocketProtocol (SocketProtocol *socketProtocol)
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketProtocol
void take (const char *junk, std::size_t junkLen)
void setSocketConnection (SocketConnectionBase *socketConnection)
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
bool markedForDelete = false
Detailed Description
Definition at line 41 of file ClientContext.h.
Constructor & Destructor Documentation
~ClientContextBase()
virtual http::client::ClientContextBase::~ClientContextBase () virtual default
Member Function Documentation
getRequest()
virtual Request& http::client::ClientContextBase::getRequest () pure virtual
Implemented in http::client::ClientContext< RequestT, ResponseT >.
requestCompleted()
virtual void http::client::ClientContextBase::requestCompleted () pure virtual
Implemented in http::client::ClientContext< RequestT, ResponseT >.
Referenced by http::client::Request::enqueue().
sendRequestData()
virtual void http::client::ClientContextBase::sendRequestData (const char * buf, std::size_t len) pure virtual
Implemented in http::client::ClientContext< RequestT, ResponseT >.
Referenced by http::client::Request::enqueue().
terminateConnection()
virtual void http::client::ClientContextBase::terminateConnection () pure virtual
Implemented in http::client::ClientContext< RequestT, ResponseT >.
Referenced by http::client::Request::enqueue(), and http::client::Request::error().
The documentation for this class was generated from the following file:
http/client/ClientContext.h