snode.c: web::websocket::server::SubProtocolFactory Class Reference
web::websocket::server::SubProtocolFactory Class Reference
#include <SubProtocolFactory.h>
Public Member Functions
void deleteSubProtocol (SubProtocol *subProtocol) override
Public Member Functions inherited from web::websocket::SubProtocolFactory< web::websocket::server::SubProtocol >
SubProtocolFactory ()=default
virtual ~SubProtocolFactory ()=default
SubProtocol * createSubProtocol ()
virtual std::string name ()=0
virtual void destroy ()=0
virtual SubProtocol * create ()=0
Static Public Member Functions
static void link (const std::string &subProtocolName, SubProtocolFactory *(*getSubProtocolFactory)())
Additional Inherited Members
Public Types inherited from web::websocket::SubProtocolFactory< web::websocket::server::SubProtocol >
using SubProtocol = web::websocket::server::SubProtocol
Protected Attributes inherited from web::websocket::SubProtocolFactory< web::websocket::server::SubProtocol >
std::size_t refCount
Detailed Description
Definition at line 33 of file SubProtocolFactory.h.
Member Function Documentation
deleteSubProtocol()
void web::websocket::server::SubProtocolFactory::deleteSubProtocol (SubProtocol * subProtocol) override virtual
Reimplemented from web::websocket::SubProtocolFactory< web::websocket::server::SubProtocol >.
Definition at line 33 of file SubProtocolFactory.cpp.
{
         web::websocket::SubProtocolFactory<SubProtocol>::deleteSubProtocol(subProtocol);
         if (refCount == 0) {
             SubProtocolFactorySelector::instance()->unload(this);
         }
     }
References web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::server::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactory< web::websocket::server::SubProtocol >::refCount, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Referenced by web::websocket::server::SocketContextUpgradeFactory::create(), and web::websocket::server::SocketContextUpgradeFactory::destroy().
link()
void web::websocket::server::SubProtocolFactory::link (const std::string & subProtocolName, SubProtocolFactory *(*)() getSubProtocolFactory) static
Definition at line 29 of file SubProtocolFactory.cpp.
{
         SubProtocolFactorySelector::link(subProtocolName, getSubProtocolFactory);
     }
References web::websocket::server::SubProtocolFactorySelector::link().
The documentation for this class was generated from the following files:
web/websocket/server/SubProtocolFactory.h
web/websocket/server/SubProtocolFactory.cpp