snode.c: net::socket::stream::SocketListener< SocketConnectionT > Class Template Reference
net::socket::stream::SocketListener< SocketConnectionT > Class Template Reference
#include <SocketListener.h>
Public Types
using SocketConnection = SocketConnectionT
using Socket = typename SocketConnection::Socket
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketListener_v)
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
SocketListener ()=delete
SocketListener (const SocketListener &)=delete
SocketListener & operator= (const SocketListener &)=delete
virtual ~SocketListener ()=default
virtual void listen (const typename SocketConnection::Socket::SocketAddress &localAddress, int backlog, const std::function< void(int err)> &onError)
void reuseAddress (const std::function< void(int errnum)> &onError)
void acceptEvent () override
void end ()
Public Member Functions inherited from net::AcceptEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Attributes
std::map< std::string, std::any > options
bool isDynamic
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Static Protected Attributes
static void * lastAllocAddress = nullptr
Private Member Functions
void unobserved () override
Private Attributes
std::function< void(SocketConnection *socketConnection)> onConstruct
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onConnect
std::function< void(SocketConnection *socketConnection)> onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
Additional Inherited Members
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
Detailed Description
template<typename SocketConnectionT>
class net::socket::stream::SocketListener< SocketConnectionT >
Definition at line 38 of file SocketListener.h.
Member Typedef Documentation
Socket
template<typename SocketConnectionT > using net::socket::stream::SocketListener< SocketConnectionT >::Socket = typename SocketConnection::Socket
Definition at line 43 of file SocketListener.h.
SocketConnection
template<typename SocketConnectionT > using net::socket::stream::SocketListener< SocketConnectionT >::SocketConnection = SocketConnectionT
Definition at line 42 of file SocketListener.h.
Constructor & Destructor Documentation
SocketListener() [1/3]
template<typename SocketConnectionT > net::socket::stream::SocketListener< SocketConnectionT >::SocketListener (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options) inline
Definition at line 55 of file SocketListener.h.
             : AcceptEventReceiver()
             , Socket()
             , onConstruct(onConstruct)
             , onDestruct(onDestruct)
             , onConnect(onConnect)
             , onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options)
             , isDynamic(this == SocketListener::lastAllocAddress) {
         }
SocketListener() [2/3]
template<typename SocketConnectionT > net::socket::stream::SocketListener< SocketConnectionT >::SocketListener () delete
SocketListener() [3/3]
template<typename SocketConnectionT > net::socket::stream::SocketListener< SocketConnectionT >::SocketListener (const SocketListener< SocketConnectionT > &) delete
~SocketListener()
template<typename SocketConnectionT > virtual net::socket::stream::SocketListener< SocketConnectionT >::~SocketListener () virtual default
Reimplemented in net::socket::stream::tls::SocketListener< SocketT >.
Member Function Documentation
acceptEvent()
template<typename SocketConnectionT > void net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent () inline override virtual
Implements net::AcceptEventReceiver.
Definition at line 124 of file SocketListener.h.
{
             errno = 0;
             typename SocketConnection::Socket::SocketAddress::SockAddr remoteAddress{};
             socklen_t addrlen = sizeof(remoteAddress);
             int scFd = -1;
             scFd = ::accept4(Socket::getFd(), reinterpret_cast<struct sockaddr*>(&remoteAddress), &addrlen, SOCK_NONBLOCK);
             if (scFd >= 0) {
                 typename Socket::SocketAddress::SockAddr localAddress{};
                 socklen_t addressLength = sizeof(localAddress);
                 if (getsockname(scFd, reinterpret_cast<sockaddr*>(&localAddress), &addressLength) == 0) {
                     SocketConnection* socketConnection =
                         new SocketConnection(onConstruct, onDestruct, onRead, onReadError, onWriteError, onDisconnect);
                     socketConnection->open(scFd);
                     socketConnection->setRemoteAddress(typename Socket::SocketAddress(remoteAddress));
                     socketConnection->setLocalAddress(typename Socket::SocketAddress(localAddress));
                     socketConnection->ReadEventReceiver::enable();
                     onConnect(socketConnection);
                 } else {
                     PLOG(ERROR) << "getsockname";
                     shutdown(scFd, SHUT_RDWR);
                     ::close(scFd);
                 }
             } else if (errno != EINTR) {
                 PLOG(ERROR) << "accept";
             }
         }
end()
template<typename SocketConnectionT > void net::socket::stream::SocketListener< SocketConnectionT >::end () inline
Definition at line 160 of file SocketListener.h.
                    {
             AcceptEventReceiver::disable();
         }
listen()
template<typename SocketConnectionT > virtual void net::socket::stream::SocketListener< SocketConnectionT >::listen (const typename SocketConnection::Socket::SocketAddress & localAddress, int backlog, const std::function< void(int err)> & onError) inline virtual
Reimplemented in net::socket::stream::tls::SocketListener< SocketT >.
Definition at line 83 of file SocketListener.h.
{
             Socket::open([this, &localAddress, &backlog, &onError](int errnum) -> void {
                 if (errnum > 0) {
                     onError(errnum);
                 } else {
                     reuseAddress([this, &localAddress, &backlog, &onError](int errnum) -> void {
                         if (errnum != 0) {
                             onError(errnum);
                         } else {
                             Socket::bind(localAddress, [this, &backlog, &onError](int errnum) -> void {
                                 if (errnum > 0) {
                                     onError(errnum);
                                 } else {
                                     int ret = ::listen(Socket::getFd(), backlog);
                                     if (ret < 0) {
                                         onError(errno);
                                     } else {
                                         AcceptEventReceiver::enable();
                                         onError(0);
                                     }
                                 }
                             });
                         }
                     });
                 }
             });
         }
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::listen(), and net::socket::stream::tls::SocketListener< SocketT >::listen().
operator delete()
template<typename SocketConnectionT > void net::socket::stream::SocketListener< SocketConnectionT >::operator delete (void * socketListener_v) inline
Definition at line 51 of file SocketListener.h.
{
             free(socketListener_v);
         }
operator new()
template<typename SocketConnectionT > void* net::socket::stream::SocketListener< SocketConnectionT >::operator new (size_t size) inline
Definition at line 45 of file SocketListener.h.
{
             SocketListener<SocketConnection>::lastAllocAddress = malloc(size);
             return SocketListener<SocketConnection>::lastAllocAddress;
         }
operator=()
template<typename SocketConnectionT > SocketListener& net::socket::stream::SocketListener< SocketConnectionT >::operator= (const SocketListener< SocketConnectionT > &) delete
reuseAddress()
template<typename SocketConnectionT > void net::socket::stream::SocketListener< SocketConnectionT >::reuseAddress (const std::function< void(int errnum)> & onError) inline
Definition at line 114 of file SocketListener.h.
{
             int sockopt = 1;
             if (setsockopt(Socket::getFd(), SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt)) < 0) {
                 onError(errno);
             } else {
                 onError(0);
             }
         }
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::listen().
unobserved()
template<typename SocketConnectionT > void net::socket::stream::SocketListener< SocketConnectionT >::unobserved () inline override private virtual
Implements net::EventReceiver.
Definition at line 165 of file SocketListener.h.
{
             if (isDynamic) {
                 delete this;
             }
         }
Member Data Documentation
isDynamic
template<typename SocketConnectionT > bool net::socket::stream::SocketListener< SocketConnectionT >::isDynamic protected
Definition at line 182 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::unobserved().
lastAllocAddress
template<typename SocketConnectionT > void * net::socket::stream::SocketListener< SocketConnectionT >::lastAllocAddress = nullptr static protected
Definition at line 183 of file SocketListener.h.
onConnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketListener< SocketConnectionT >::onConnect private
Definition at line 173 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onConstruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketListener< SocketConnectionT >::onConstruct private
Definition at line 171 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onDestruct
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketListener< SocketConnectionT >::onDestruct private
Definition at line 172 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onDisconnect
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::SocketListener< SocketConnectionT >::onDisconnect private
Definition at line 174 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onRead
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, const char* junk, ssize_t junkLen)> net::socket::stream::SocketListener< SocketConnectionT >::onRead private
Definition at line 175 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onReadError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketListener< SocketConnectionT >::onReadError private
Definition at line 176 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
onWriteError
template<typename SocketConnectionT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::stream::SocketListener< SocketConnectionT >::onWriteError private
Definition at line 177 of file SocketListener.h.
Referenced by net::socket::stream::SocketListener< net::socket::stream::tls::SocketConnection< SocketT > >::acceptEvent().
options
template<typename SocketConnectionT > std::map<std::string, std::any> net::socket::stream::SocketListener< SocketConnectionT >::options protected
Definition at line 180 of file SocketListener.h.
The documentation for this class was generated from the following file:
net/socket/sock_stream/SocketListener.h