snode.c: net::TimerEventDispatcher Class Reference
net::TimerEventDispatcher Class Reference
#include <TimerEventDispatcher.h>
Classes
class timernode_lt
Public Member Functions
TimerEventDispatcher ()=default
struct timeval getNextTimeout ()
void dispatch ()
void remove (TimerEventReceiver *timer)
void add (TimerEventReceiver *timer)
bool empty ()
void cancelAll ()
Private Attributes
std::list< TimerEventReceiver * > timerList
std::list< TimerEventReceiver * > addedList
std::list< TimerEventReceiver * > removedList
bool timerListDirty = false
Detailed Description
Definition at line 32 of file TimerEventDispatcher.h.
Constructor & Destructor Documentation
TimerEventDispatcher()
net::TimerEventDispatcher::TimerEventDispatcher () default
Member Function Documentation
add()
void net::TimerEventDispatcher::add (TimerEventReceiver * timer)
Definition at line 92 of file TimerEventDispatcher.cpp.
{
         addedList.push_back(timer);
     }
References addedList.
Referenced by net::timer::Timer::intervalTimer(), and net::timer::Timer::singleshotTimer().
cancelAll()
void net::TimerEventDispatcher::cancelAll ()
Definition at line 100 of file TimerEventDispatcher.cpp.
{
         getNextTimeout();
         for (TimerEventReceiver* timer : timerList) {
             remove(timer);
         }
         getNextTimeout();
     }
References getNextTimeout(), remove(), and timerList.
Referenced by net::EventLoop::start().
dispatch()
void net::TimerEventDispatcher::dispatch ()
Definition at line 72 of file TimerEventDispatcher.cpp.
{
         struct timeval currentTime {
             0, 0
         };
         net::system::gettimeofday(&currentTime, nullptr);
         for (TimerEventReceiver* timer : timerList) {
             if (timer->timeout() <= currentTime) {
                 timerListDirty = timer->dispatch();
             } else {
                 break;
             }
         }
     }
References net::system::gettimeofday(), timerList, and timerListDirty.
Referenced by net::EventLoop::tick().
empty()
bool net::TimerEventDispatcher::empty ()
Definition at line 96 of file TimerEventDispatcher.cpp.
{
         return timerList.empty();
     }
References timerList.
Referenced by net::EventLoop::tick().
getNextTimeout()
struct timeval net::TimerEventDispatcher::getNextTimeout ()
Definition at line 1 of file TimerEventDispatcher.cpp.
{
         struct timeval tv {
             LONG_MAX, 0
         };
         for (TimerEventReceiver* timer : addedList) {
             timerList.push_back(timer);
             timerListDirty = true;
         }
         addedList.clear();
         for (TimerEventReceiver* timer : removedList) {
             timerList.remove(timer);
             timerListDirty = true;
         }
         removedList.clear();
         if (!timerList.empty()) {
             if (timerListDirty) {
                 timerList.sort(timernode_lt());
                 timerListDirty = false;
             }
             tv = (*(timerList.begin()))->timeout();
             struct timeval currentTime {
                 0, 0
             };
             net::system::gettimeofday(&currentTime, nullptr);
             if (tv < currentTime) {
                 tv.tv_sec = 0;
                 tv.tv_usec = 0;
             } else {
                 tv = tv - currentTime;
             }
         }
         return tv;
     }
References net::system::gettimeofday().
Referenced by cancelAll(), and net::EventLoop::tick().
remove()
void net::TimerEventDispatcher::remove (TimerEventReceiver * timer)
Definition at line 87 of file TimerEventDispatcher.cpp.
{
         removedList.push_back(timer);
         timer->destroy();
     }
References net::TimerEventReceiver::destroy(), and removedList.
Referenced by net::timer::Timer::cancel(), and cancelAll().
Member Data Documentation
addedList
std::list<TimerEventReceiver*> net::TimerEventDispatcher::addedList private
Definition at line 49 of file TimerEventDispatcher.h.
Referenced by add().
removedList
std::list<TimerEventReceiver*> net::TimerEventDispatcher::removedList private
Definition at line 50 of file TimerEventDispatcher.h.
Referenced by remove().
timerList
std::list<TimerEventReceiver*> net::TimerEventDispatcher::timerList private
Definition at line 48 of file TimerEventDispatcher.h.
Referenced by cancelAll(), dispatch(), and empty().
timerListDirty
bool net::TimerEventDispatcher::timerListDirty = false private
Definition at line 59 of file TimerEventDispatcher.h.
Referenced by dispatch().
The documentation for this class was generated from the following files:
net/TimerEventDispatcher.h
net/TimerEventDispatcher.cpp