snode.c: http::ServerContextBase Class Reference
http::ServerContextBase Class Reference abstract
#include <ServerContext.h>
Public Member Functions
virtual ~ServerContextBase ()=default
virtual void receiveRequestData (const char *junk, std::size_t junkLen)=0
virtual void sendResponseData (const char *buf, std::size_t len)=0
virtual void responseCompleted ()=0
virtual void terminateConnection ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
Detailed Description
Definition at line 38 of file ServerContext.h.
Constructor & Destructor Documentation
~ServerContextBase()
virtual http::ServerContextBase::~ServerContextBase () virtual default
Member Function Documentation
onReadError()
virtual void http::ServerContextBase::onReadError (int errnum) pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
onWriteError()
virtual void http::ServerContextBase::onWriteError (int errnum) pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
receiveRequestData()
virtual void http::ServerContextBase::receiveRequestData (const char * junk, std::size_t junkLen) pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
responseCompleted()
virtual void http::ServerContextBase::responseCompleted () pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
Referenced by http::Response::enqueue().
sendResponseData()
virtual void http::ServerContextBase::sendResponseData (const char * buf, std::size_t len) pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
Referenced by http::Response::enqueue().
terminateConnection()
virtual void http::ServerContextBase::terminateConnection () pure virtual
Implemented in http::ServerContext< RequestT, ResponseT >.
Referenced by http::Response::enqueue(), http::Response::error(), and express::Response::sendFile().
The documentation for this class was generated from the following file:
http/ServerContext.h