snode.c: web::websocket::server::SubProtocolFactorySelector Class Reference
web::websocket::server::SubProtocolFactorySelector Class Reference
#include <SubProtocolFactorySelector.h>
Static Public Member Functions
static SubProtocolFactorySelector * instance ()
static void link (const std::string &subProtocolName, SubProtocolFactory *(*getSubProtocolFactory)())
Private Member Functions
SubProtocolFactorySelector ()
SubProtocolFactorySelector (const SubProtocolFactorySelector &)=delete
SubProtocolFactorySelector & operator= (const SubProtocolFactorySelector &)=delete
SubProtocolFactory * load (const std::string &subProtocolName) override
Friends
template<typename SubProtocolFactory >
class web::websocket::SubProtocolFactorySelector
Additional Inherited Members
Public Types inherited from web::websocket::SubProtocolFactorySelector< web::websocket::server::SubProtocolFactory >
enum class Role
using SubProtocolFactory = web::websocket::server::SubProtocolFactory
Public Member Functions inherited from web::websocket::SubProtocolFactorySelector< web::websocket::server::SubProtocolFactory >
void add (SubProtocolFactory *subProtocolFactory, void *handle=nullptr)
SubProtocolFactory * select (const std::string &subProtocolName)
void unload (SubProtocolFactory *subProtocolFactory)
void allowDlOpen ()
Protected Member Functions inherited from web::websocket::SubProtocolFactorySelector< web::websocket::server::SubProtocolFactory >
SubProtocolFactorySelector ()=default
SubProtocolFactorySelector (const SubProtocolFactorySelector &)=delete
SubProtocolFactorySelector & operator= (const SubProtocolFactorySelector &)=delete
virtual ~SubProtocolFactorySelector ()=default
SubProtocolFactory * load (const std::string &subProtocolName, Role role)
void addSubProtocolSearchPath (const std::string &searchPath)
void linkSubProtocol (const std::string &subProtocolName, SubProtocolFactory *(*linkedPlugin)())
Detailed Description
Definition at line 36 of file SubProtocolFactorySelector.h.
Constructor & Destructor Documentation
SubProtocolFactorySelector() [1/2]
web::websocket::server::SubProtocolFactorySelector::SubProtocolFactorySelector () private
Definition at line 30 of file SubProtocolFactorySelector.cpp.
{
 #ifndef NDEBUG
 #ifdef SUBPROTOCOL_SERVER_COMPILE_PATH
         addSubProtocolSearchPath(SUBPROTOCOL_SERVER_COMPILE_PATH);
 #endif // SUBPROTOCOL_SERVER_COMPILE_PATH
 #endif // NDEBUG
         addSubProtocolSearchPath(SUBPROTOCOL_SERVER_INSTALL_PATH);
     }
References web::websocket::SubProtocolFactorySelector< web::websocket::server::SubProtocolFactory >::addSubProtocolSearchPath().
SubProtocolFactorySelector() [2/2]
web::websocket::server::SubProtocolFactorySelector::SubProtocolFactorySelector (const SubProtocolFactorySelector &) private delete
Member Function Documentation
instance()
SubProtocolFactorySelector * web::websocket::server::SubProtocolFactorySelector::instance () static
Definition at line 42 of file SubProtocolFactorySelector.cpp.
{
         static SubProtocolFactorySelector subProtocolFactorySelector;
         return &subProtocolFactorySelector;
     }
Referenced by web::websocket::server::SocketContextUpgradeFactory::create(), web::websocket::server::SocketContextUpgradeFactory::destroy(), and link().
link()
void web::websocket::server::SubProtocolFactorySelector::link (const std::string & subProtocolName, SubProtocolFactory *(*)() getSubProtocolFactory) static
Definition at line 48 of file SubProtocolFactorySelector.cpp.
{
         SubProtocolFactorySelector::instance()->linkSubProtocol(subProtocolName, getSubProtocolFactory);
     }
References instance(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::linkSubProtocol().
load()
SubProtocolFactory * web::websocket::server::SubProtocolFactorySelector::load (const std::string & subProtocolName) override private virtual
Implements web::websocket::SubProtocolFactorySelector< web::websocket::server::SubProtocolFactory >.
Definition at line 52 of file SubProtocolFactorySelector.cpp.
{
         return load(subProtocolName, Role::SERVER);
     }
operator=()
SubProtocolFactorySelector& web::websocket::server::SubProtocolFactorySelector::operator= (const SubProtocolFactorySelector &) private delete
Friends And Related Function Documentation
web::websocket::SubProtocolFactorySelector
template<typename SubProtocolFactory > friend class web::websocket::SubProtocolFactorySelector friend
Definition at line 54 of file SubProtocolFactorySelector.h.
The documentation for this class was generated from the following files:
web/websocket/server/SubProtocolFactorySelector.h
web/websocket/server/SubProtocolFactorySelector.cpp