snode.c: web::ws::server::WSServerContext< WSServerProtocolT > Class Template Reference
web::ws::server::WSServerContext< WSServerProtocolT > Class Template Reference
#include <WSServerContext.h>
Public Member Functions
WSServerContext ()
~WSServerContext ()
Public Member Functions inherited from net::socket::stream::SocketProtocol
virtual ~SocketProtocol ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void close ()
void setTimeout (int timeout)
void switchSocketProtocol (SocketProtocol *socketProtocol)
Public Member Functions inherited from web::ws::WSReceiver
void receive (char *junk, std::size_t junkLen)
Private Types
using WSServerProtocol = WSServerProtocolT
Private Member Functions
void messageStart (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0) override
void sendFrame (char *message, std::size_t messageLength, uint32_t messageKey=0) override
void messageEnd (char *message, std::size_t messageLength, uint32_t messageKey=0) override
void message (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0) override
void sendPing (char *reason=nullptr, std::size_t reasonLength=0) override
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0) override
std::string getLocalAddressAsString () const override
std::string getRemoteAddressAsString () const override
void replyPong (char *reason=nullptr, std::size_t reasonLength=0)
void onProtocolConnect () override
void onProtocolDisconnect () override
void receiveFromPeer (const char *junk, std::size_t junkLen) override
void onReadError (int errnum) override
void onWriteError (int errnum) override
void onMessageStart (int opCode) override
void onFrameReceived (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
void sendFrameData (uint8_t data) override
void sendFrameData (uint16_t data) override
void sendFrameData (uint32_t data) override
void sendFrameData (uint64_t data) override
void sendFrameData (char *frame, uint64_t frameLength) override
void onFrameReady (char *frame, uint64_t frameLength) override
Private Attributes
WSServerProtocol * wSServerProtocol
bool closeReceived = false
bool closeSent = false
bool pingReceived = false
bool pongReceived = false
Additional Inherited Members
Protected Types inherited from web::ws::WSReceiver
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Protected Member Functions inherited from net::socket::stream::SocketProtocol
void take (const char *junk, std::size_t junkLen)
void setSocketConnection (SocketConnectionBase *socketConnection)
Protected Member Functions inherited from web::ws::WSReceiver
void begin ()
uint64_t readOpcode (char *junk, uint64_t junkLen)
uint64_t readLength (char *junk, uint64_t junkLen)
uint64_t readELength (char *junk, uint64_t junkLen)
uint64_t readMaskingKey (char *junk, uint64_t junkLen)
uint64_t readPayload (char *junk, uint64_t junkLen)
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Protected Member Functions inherited from web::ws::WSTransmitter
void messageStart (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
void sendFrame (char *message, std::size_t messageLength, uint32_t messageKey=0)
void messageEnd (char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
bool markedForDelete = false
Protected Attributes inherited from web::ws::WSReceiver
enum web::ws::WSReceiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
Detailed Description
template<typename WSServerProtocolT>
class web::ws::server::WSServerContext< WSServerProtocolT >
Definition at line 38 of file WSServerContext.h.
Member Typedef Documentation
WSServerProtocol
template<typename WSServerProtocolT > using web::ws::server::WSServerContext< WSServerProtocolT >::WSServerProtocol = WSServerProtocolT private
Definition at line 43 of file WSServerContext.h.
Constructor & Destructor Documentation
WSServerContext()
template<typename WSServerProtocol > web::ws::server::WSServerContext< WSServerProtocol >::WSServerContext
Definition at line 39 of file WSServerContext.hpp.
         : wSServerProtocol(new WSServerProtocol()) {
         wSServerProtocol->wSServerContext = this;
     }
References web::ws::server::WSServerContext< WSServerProtocolT >::wSServerProtocol.
~WSServerContext()
template<typename WSServerProtocol > web::ws::server::WSServerContext< WSServerProtocol >::~WSServerContext
Definition at line 45 of file WSServerContext.hpp.
{
         wSServerProtocol->wSServerContext = nullptr;
         delete wSServerProtocol;
     }
Member Function Documentation
close()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 174 of file WSServerContext.hpp.
{
         char* closePayload = const_cast<char*>(reason);
         std::size_t closePayloadLength = reasonLength;
         if (statusCode != 0) {
             closePayload = new char[reasonLength + 2];
             *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
             closePayloadLength += 2;
             if (reasonLength > 0) {
                 memcpy(closePayload + 2, reason, reasonLength);
             }
         }
         message(8, closePayload, closePayloadLength);
         if (statusCode != 0) {
             delete[] closePayload;
         }
         setTimeout(CLOSE_SOCKET_TIMEOUT);
         closeSent = true;
     }
References CLOSE_SOCKET_TIMEOUT.
getLocalAddressAsString()
template<typename WSServerProtocol > std::string web::ws::server::WSServerContext< WSServerProtocol >::getLocalAddressAsString override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 199 of file WSServerContext.hpp.
{
         return SocketProtocol::getLocalAddressAsString();
     }
getRemoteAddressAsString()
template<typename WSServerProtocol > std::string web::ws::server::WSServerContext< WSServerProtocol >::getRemoteAddressAsString override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 204 of file WSServerContext.hpp.
{
         return SocketProtocol::getLocalAddressAsString();
     }
message()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::message (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 72 of file WSServerContext.hpp.
{
         if (!closeSent) {
             WSTransmitter::message(opCode, message, messageLength, messageKey);
         }
     }
References web::ws::WSTransmitter::message().
messageEnd()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::messageEnd (char * message, std::size_t messageLength, uint32_t messageKey = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 65 of file WSServerContext.hpp.
{
         if (!closeSent) {
             WSTransmitter::messageEnd(message, messageLength, messageKey);
         }
     }
References web::ws::WSTransmitter::messageEnd().
messageStart()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::messageStart (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 51 of file WSServerContext.hpp.
{
         if (!closeSent) {
             WSTransmitter::messageStart(opCode, message, messageLength, messageKey);
         }
     }
References web::ws::WSTransmitter::messageStart().
onFrameReady()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onFrameReady (char * frame, uint64_t frameLength) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 169 of file WSServerContext.hpp.
{
         sendToPeer(frame, static_cast<std::size_t>(frameLength));
     }
onFrameReceived()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onFrameReceived (const char * junk, uint64_t junkLen) override private virtual
Implements web::ws::WSReceiver.
Definition at line 123 of file WSServerContext.hpp.
{
         if (!closeReceived && !pingReceived && !pongReceived) {
             std::size_t junkOffset = 0;
             do {
                 std::size_t sendJunkLen = (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                 wSServerProtocol->onFrameData(junk + junkOffset, sendJunkLen);
                 junkOffset += sendJunkLen;
             } while (junkLen - junkOffset > 0);
         } else {
             // collect data for close and pong
         }
     }
onMessageEnd()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onMessageEnd override private virtual
Implements web::ws::WSReceiver.
Definition at line 138 of file WSServerContext.hpp.
{
         if (closeReceived) {
             closeReceived = false;
             if (closeSent) { // active close
                 closeSent = false;
                 VLOG(0) << "Close confirmed from peer";
             } else { // passive close
                 VLOG(0) << "Close request received - replying with close";
                 close();
             }
             socketConnection->getSocketProtocol()->close();
         } else if (pingReceived) {
             pingReceived = false;
             replyPong();
         } else if (pongReceived) {
             pongReceived = false;
             wSServerProtocol->onPongReceived();
         } else {
             wSServerProtocol->onMessageEnd();
         }
     }
References net::system::close().
onMessageError()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onMessageError (uint16_t errnum) override private virtual
Implements web::ws::WSReceiver.
Definition at line 161 of file WSServerContext.hpp.
{
         VLOG(0) << std::endl << "Message Error";
         wSServerProtocol->onMessageError(errnum);
         close(errnum);
     }
References net::system::close().
onMessageStart()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onMessageStart (int opCode) override private virtual
Implements web::ws::WSReceiver.
Definition at line 104 of file WSServerContext.hpp.
{
         switch (opCode) {
             case 0x08:
                 closeReceived = true;
                 break;
             case 0x09:
                 pingReceived = true;
                 VLOG(0) << "Ping received";
                 break;
             case 0x0A:
                 pongReceived = true;
                 break;
             default:
                 wSServerProtocol->onMessageStart(opCode);
                 break;
         }
     }
onProtocolConnect()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onProtocolConnect override private virtual
Reimplemented from net::socket::stream::SocketProtocol.
Definition at line 79 of file WSServerContext.hpp.
{
         wSServerProtocol->onProtocolConnect();
     }
onProtocolDisconnect()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onProtocolDisconnect override private virtual
Reimplemented from net::socket::stream::SocketProtocol.
Definition at line 84 of file WSServerContext.hpp.
{
         wSServerProtocol->onProtocolDisconnect();
     }
onReadError()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onReadError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 94 of file WSServerContext.hpp.
{
         VLOG(0) << "OnReadError: " << errnum;
     }
onWriteError()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::onWriteError (int errnum) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 99 of file WSServerContext.hpp.
{
         VLOG(0) << "OnWriteError: " << errnum;
     }
receiveFromPeer()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::receiveFromPeer (const char * junk, std::size_t junkLen) override private virtual
Implements net::socket::stream::SocketProtocol.
Definition at line 89 of file WSServerContext.hpp.
{
         WSReceiver::receive(const_cast<char*>(junk), junkLen);
     }
References web::ws::WSReceiver::receive().
replyPong()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::replyPong (char * reason = nullptr, std::size_t reasonLength = 0) private
Definition at line 214 of file WSServerContext.hpp.
{
         message(10, reason, reasonLength);
     }
sendFrame()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrame (char * message, std::size_t messageLength, uint32_t messageKey = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 58 of file WSServerContext.hpp.
{
         if (!closeSent) {
             WSTransmitter::sendFrame(message, messageLength, messageKey);
         }
     }
References web::ws::WSTransmitter::sendFrame().
sendFrameData() [1/5]
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrameData (char * frame, uint64_t frameLength) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 239 of file WSServerContext.hpp.
{
         std::size_t frameOffset = 0;
         do {
             std::size_t sendJunkLen =
                 (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
             sendToPeer(frame + frameOffset, sendJunkLen);
             frameOffset += sendJunkLen;
         } while (frameLength - frameOffset > 0);
     }
sendFrameData() [2/5]
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrameData (uint16_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 224 of file WSServerContext.hpp.
{
         sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint16_t));
     }
sendFrameData() [3/5]
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrameData (uint32_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 229 of file WSServerContext.hpp.
{
         sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint32_t));
     }
sendFrameData() [4/5]
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrameData (uint64_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 234 of file WSServerContext.hpp.
{
         sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint64_t));
     }
sendFrameData() [5/5]
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendFrameData (uint8_t data) override private virtual
Implements web::ws::WSTransmitter.
Definition at line 219 of file WSServerContext.hpp.
{
         sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
     }
sendPing()
template<typename WSServerProtocol > void web::ws::server::WSServerContext< WSServerProtocol >::sendPing (char * reason = nullptr, std::size_t reasonLength = 0) override private virtual
Implements web::ws::server::WSServerContextBase.
Definition at line 209 of file WSServerContext.hpp.
{
         message(9, reason, reasonLength);
     }
Member Data Documentation
closeReceived
template<typename WSServerProtocolT > bool web::ws::server::WSServerContext< WSServerProtocolT >::closeReceived = false private
Definition at line 88 of file WSServerContext.h.
closeSent
template<typename WSServerProtocolT > bool web::ws::server::WSServerContext< WSServerProtocolT >::closeSent = false private
Definition at line 89 of file WSServerContext.h.
pingReceived
template<typename WSServerProtocolT > bool web::ws::server::WSServerContext< WSServerProtocolT >::pingReceived = false private
Definition at line 91 of file WSServerContext.h.
pongReceived
template<typename WSServerProtocolT > bool web::ws::server::WSServerContext< WSServerProtocolT >::pongReceived = false private
Definition at line 92 of file WSServerContext.h.
wSServerProtocol
template<typename WSServerProtocolT > WSServerProtocol* web::ws::server::WSServerContext< WSServerProtocolT >::wSServerProtocol private
Definition at line 86 of file WSServerContext.h.
Referenced by web::ws::server::WSServerContext< WSServerProtocolT >::WSServerContext().
The documentation for this class was generated from the following files:
web/ws/server/WSServerContext.h
web/ws/server/WSServerContext.hpp