snode.c: http::websocket::WSReceiver Class Reference
http::websocket::WSReceiver Class Reference abstract
#include <WSReceiver.h>
Classes
union MaskingKey
Public Member Functions
void receive (char *junk, std::size_t junkLen)
Protected Types
enum class ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Protected Member Functions
void begin ()
uint64_t readOpcode (char *junk, uint64_t junkLen)
uint64_t readLength (char *junk, uint64_t junkLen)
uint64_t readELength (char *junk, uint64_t junkLen)
uint64_t readMaskingKey (char *junk, uint64_t junkLen)
uint64_t readPayload (char *junk, uint64_t junkLen)
virtual void onMessageStart (int opCode)=0
virtual void onFrameData (const char *junk, uint64_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onError (uint16_t errnum)=0
void reset ()
void dumpFrame (char *frame, uint64_t frameLength)
Protected Attributes
enum http::websocket::WSReceiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint64_t length = 0
uint32_t maskingKey = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 0
uint64_t payloadRead = 0
uint16_t errorState = 0
Detailed Description
Definition at line 31 of file WSReceiver.h.
Member Enumeration Documentation
ParserState
enum http::websocket::WSReceiver::ParserState strong protected
Enumerator
BEGIN
OPCODE
LENGTH
ELENGTH
MASKINGKEY
PAYLOAD
ERROR
Definition at line 60 of file WSReceiver.h.
 { BEGIN, OPCODE, LENGTH, ELENGTH, MASKINGKEY, PAYLOAD, ERROR } parserState = ParserState::BEGIN;
Member Function Documentation
begin()
void http::websocket::WSReceiver::begin () inline protected
Definition at line 41 of file WSReceiver.h.
                      {
         }
Referenced by receive().
dumpFrame()
void http::websocket::WSReceiver::dumpFrame (char * frame, uint64_t frameLength) protected
Definition at line 225 of file WSReceiver.cpp.
{
         int modul = 4;
         std::stringstream stringStream;
         for (std::size_t i = 0; i < frameLength; i++) {
             stringStream << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % modul == 0 || i == frameLength) {
                 VLOG(0) << "Frame: " << stringStream.str();
                 stringStream.str("");
             }
         }
     }
onError()
virtual void http::websocket::WSReceiver::onError (uint16_t errnum) protected pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by receive().
onFrameData()
virtual void http::websocket::WSReceiver::onFrameData (const char * junk, uint64_t junkLen) protected pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by readPayload().
onMessageEnd()
virtual void http::websocket::WSReceiver::onMessageEnd () protected pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by readLength(), readMaskingKey(), and readPayload().
onMessageStart()
virtual void http::websocket::WSReceiver::onMessageStart (int opCode) protected pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by readOpcode().
readELength()
uint64_t http::websocket::WSReceiver::readELength (char * junk, uint64_t junkLen) protected
Definition at line 134 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         elengthNumBytesLeft = (elengthNumBytesLeft == 0) ? elengthNumBytes : elengthNumBytesLeft;
         while (consumed < junkLen && elengthNumBytesLeft > 0) {
             length |= static_cast<uint64_t>(*reinterpret_cast<unsigned char*>(junk + consumed))
                       << (elengthNumBytes - elengthNumBytesLeft) * 8;
             consumed++;
             elengthNumBytesLeft--;
         }
         if (elengthNumBytesLeft == 0) {
             switch (elengthNumBytes) {
                 case 2: {
                     length = be16toh(static_cast<uint16_t>(length));
                 } break;
                 case 8:
                     length = be64toh(length);
                     break;
             }
             if (length & static_cast<uint64_t>(0x01) << 63) {
                 parserState = ParserState::ERROR;
                 errorState = 1004;
             } else if (masked) {
                 parserState = ParserState::MASKINGKEY;
             } else {
                 parserState = ParserState::PAYLOAD;
             }
         }
         return consumed;
     }
References elengthNumBytes, elengthNumBytesLeft, ERROR, errorState, length, masked, MASKINGKEY, parserState, and PAYLOAD.
Referenced by receive().
readLength()
uint64_t http::websocket::WSReceiver::readLength (char * junk, uint64_t junkLen) protected
Definition at line 96 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         if (junkLen > 0) {
             uint8_t lengthByte = *reinterpret_cast<uint8_t*>(junk);
             masked = lengthByte & 0b10000000;
             length = lengthByte & 0b01111111;
             if (length > 125) {
                 switch (length) {
                     case 126:
                         elengthNumBytes = 2;
                         break;
                     case 127:
                         elengthNumBytes = 8;
                         break;
                 }
                 parserState = ParserState::ELENGTH;
                 length = 0;
             } else {
                 if (masked) {
                     parserState = ParserState::MASKINGKEY;
                 } else if (length > 0) {
                     parserState = ParserState::PAYLOAD;
                 } else {
                     if (fin) {
                         onMessageEnd();
                     }
                     reset();
                 }
             }
             consumed++;
         }
         return consumed;
     }
References ELENGTH, elengthNumBytes, fin, length, masked, MASKINGKEY, onMessageEnd(), parserState, PAYLOAD, and reset().
Referenced by receive().
readMaskingKey()
uint64_t http::websocket::WSReceiver::readMaskingKey (char * junk, uint64_t junkLen) protected
Definition at line 170 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         maskingKeyNumBytesLeft = (maskingKeyNumBytesLeft == 0) ? maskingKeyNumBytes : maskingKeyNumBytesLeft;
         while (consumed < junkLen && maskingKeyNumBytesLeft > 0) {
             maskingKey |= static_cast<uint32_t>(*reinterpret_cast<unsigned char*>(junk + consumed))
                           << (maskingKeyNumBytes - maskingKeyNumBytesLeft) * 8;
             consumed++;
             maskingKeyNumBytesLeft--;
         }
         if (maskingKeyNumBytesLeft == 0) {
             maskingKey = be32toh(maskingKey);
             if (length > 0) {
                 parserState = ParserState::PAYLOAD;
             } else {
                 if (fin) {
                     onMessageEnd();
                 }
                 reset();
             }
         }
         return consumed;
     }
References fin, length, maskingKey, maskingKeyNumBytes, maskingKeyNumBytesLeft, onMessageEnd(), parserState, PAYLOAD, and reset().
Referenced by receive().
readOpcode()
uint64_t http::websocket::WSReceiver::readOpcode (char * junk, uint64_t junkLen) protected
Definition at line 70 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         if (junkLen > 0) {
             consumed++;
             uint8_t opCodeByte = *reinterpret_cast<uint8_t*>(junk);
             fin = opCodeByte & 0b10000000;
             opCode = opCodeByte & 0b00001111;
             if (!continuation) {
                 onMessageStart(opCode);
                 parserState = ParserState::LENGTH;
             } else if (opCode == 0) {
                 parserState = ParserState::LENGTH;
             } else {
                 parserState = ParserState::ERROR;
                 errorState = 1002;
                 VLOG(0) << "Error opcode in continuation frame";
             }
             continuation = !fin;
         }
         return consumed;
     }
References continuation, ERROR, errorState, fin, LENGTH, onMessageStart(), opCode, and parserState.
Referenced by receive().
readPayload()
uint64_t http::websocket::WSReceiver::readPayload (char * junk, uint64_t junkLen) protected
Definition at line 197 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         if (junkLen > 0 && length - payloadRead > 0) {
             uint64_t numBytesToRead = (junkLen <= length - payloadRead) ? junkLen : length - payloadRead;
             MaskingKey maskingKeyAsArray = {.key = htobe32(maskingKey)};
             for (uint64_t i = 0; i < numBytesToRead; i++) {
                 *(junk + i) = *(junk + i) ^ *(maskingKeyAsArray.keyAsArray + (i + payloadRead) % 4);
             }
             onFrameData(junk, numBytesToRead);
             payloadRead += numBytesToRead;
             consumed = numBytesToRead;
         }
         if (payloadRead == length) {
             if (fin) {
                 onMessageEnd();
             }
             reset();
         }
         return consumed;
     }
References fin, http::websocket::WSReceiver::MaskingKey::key, http::websocket::WSReceiver::MaskingKey::keyAsArray, length, maskingKey, onFrameData(), onMessageEnd(), payloadRead, and reset().
Referenced by receive().
receive()
void http::websocket::WSReceiver::receive (char * junk, std::size_t junkLen)
Definition at line 34 of file WSReceiver.cpp.
{
         uint64_t consumed = 0;
         bool parsingError = false;
         // dumpFrame(junk, junkLen);
         while (consumed < junkLen && !parsingError) {
             switch (parserState) {
                 case ParserState::BEGIN:
                     parserState = ParserState::OPCODE;
                     begin();
                     [[fallthrough]];
                 case ParserState::OPCODE:
                     consumed += readOpcode(junk + consumed, junkLen - consumed);
                     break;
                 case ParserState::LENGTH:
                     consumed += readLength(junk + consumed, junkLen - consumed);
                     break;
                 case ParserState::ELENGTH:
                     consumed += readELength(junk + consumed, junkLen - consumed);
                     break;
                 case ParserState::MASKINGKEY:
                     consumed += readMaskingKey(junk + consumed, junkLen - consumed);
                     break;
                 case ParserState::PAYLOAD:
                     consumed += readPayload(junk + consumed, junkLen - consumed);
                     break;
                 case ParserState::ERROR:
                     onError(errorState);
                     parsingError = true;
                     reset();
                     break;
             };
         }
     }
References begin(), BEGIN, ELENGTH, ERROR, errorState, LENGTH, MASKINGKEY, onError(), OPCODE, parserState, PAYLOAD, readELength(), readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
Referenced by http::websocket::WSServerContext::receiveFromPeer().
reset()
void http::websocket::WSReceiver::reset () protected
Definition at line 240 of file WSReceiver.cpp.
{
         payloadRead = 0;
         opCode = 0;
         parserState = ParserState::BEGIN;
         fin = false;
         masked = false;
         length = 0;
         elengthNumBytes = 0;
         elengthNumBytesLeft = 0;
         maskingKey = 0;
         maskingKeyNumBytes = 4;
         maskingKeyNumBytesLeft = 0;
         payloadRead = 0;
         errorState = 0;
     }
References BEGIN, elengthNumBytes, elengthNumBytesLeft, errorState, fin, length, masked, maskingKey, maskingKeyNumBytes, maskingKeyNumBytesLeft, opCode, parserState, and payloadRead.
Referenced by readLength(), readMaskingKey(), readPayload(), and receive().
Member Data Documentation
continuation
bool http::websocket::WSReceiver::continuation = false protected
Definition at line 63 of file WSReceiver.h.
Referenced by readOpcode().
elengthNumBytes
uint8_t http::websocket::WSReceiver::elengthNumBytes = 0 protected
Definition at line 69 of file WSReceiver.h.
Referenced by readELength(), readLength(), and reset().
elengthNumBytesLeft
uint8_t http::websocket::WSReceiver::elengthNumBytesLeft = 0 protected
Definition at line 70 of file WSReceiver.h.
Referenced by readELength(), and reset().
errorState
uint16_t http::websocket::WSReceiver::errorState = 0 protected
Definition at line 75 of file WSReceiver.h.
Referenced by readELength(), readOpcode(), receive(), and reset().
fin
bool http::websocket::WSReceiver::fin = false protected
Definition at line 62 of file WSReceiver.h.
Referenced by readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
length
uint64_t http::websocket::WSReceiver::length = 0 protected
Definition at line 66 of file WSReceiver.h.
Referenced by readELength(), readLength(), readMaskingKey(), readPayload(), and reset().
masked
bool http::websocket::WSReceiver::masked = false protected
Definition at line 64 of file WSReceiver.h.
Referenced by readELength(), readLength(), and reset().
maskingKey
uint32_t http::websocket::WSReceiver::maskingKey = 0 protected
Definition at line 67 of file WSReceiver.h.
Referenced by readMaskingKey(), readPayload(), and reset().
maskingKeyNumBytes
uint8_t http::websocket::WSReceiver::maskingKeyNumBytes = 4 protected
Definition at line 71 of file WSReceiver.h.
Referenced by readMaskingKey(), and reset().
maskingKeyNumBytesLeft
uint8_t http::websocket::WSReceiver::maskingKeyNumBytesLeft = 0 protected
Definition at line 72 of file WSReceiver.h.
Referenced by readMaskingKey(), and reset().
opCode
uint8_t http::websocket::WSReceiver::opCode = 0 protected
Definition at line 65 of file WSReceiver.h.
Referenced by http::websocket::WSServerContext::message(), http::websocket::WSServerContext::messageStart(), http::websocket::WSServerContext::onMessageStart(), readOpcode(), and reset().
parserState
enum http::websocket::WSReceiver::ParserState http::websocket::WSReceiver::parserState = ParserState::BEGIN protected
Referenced by readELength(), readLength(), readMaskingKey(), readOpcode(), receive(), and reset().
payloadRead
uint64_t http::websocket::WSReceiver::payloadRead = 0 protected
Definition at line 73 of file WSReceiver.h.
Referenced by readPayload(), and reset().
The documentation for this class was generated from the following files:
http/WSReceiver.h
http/WSReceiver.cpp