snode.c: net::socket::Socket< SocketAddressT > Class Template Reference
net::socket::Socket< SocketAddressT > Class Template Reference abstract
#include <Socket.h>
Public Types
enum shutdown { WR = SHUT_WR , RD = SHUT_RD , RDWR = SHUT_RDWR }
using SocketAddress = SocketAddressT
Public Types inherited from net::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Member Functions
Socket ()=default
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
void open (const std::function< void(int)> &onError, int flags=0)
void bind (const SocketAddress &bindAddress, const std::function< void(int)> &onError)
void shutdown (shutdown how)
const SocketAddress & getBindAddress () const
Public Member Functions inherited from net::Descriptor
void attach (int fd, enum Descriptor::FLAGS flags=FLAGS::none)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Protected Member Functions
virtual int create (int flags)=0
Protected Member Functions inherited from net::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
Protected Attributes
SocketAddress bindAddress {}
Additional Inherited Members
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Detailed Description
template<typename SocketAddressT>
class net::socket::Socket< SocketAddressT >
Definition at line 35 of file Socket.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::socket::Socket< SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 37 of file Socket.h.
Member Enumeration Documentation
shutdown
template<typename SocketAddressT > enum net::socket::Socket::shutdown
Enumerator
WR
RD
RDWR
Definition at line 70 of file Socket.h.
 { WR = SHUT_WR, RD = SHUT_RD, RDWR = SHUT_RDWR };
Constructor & Destructor Documentation
Socket() [1/2]
template<typename SocketAddressT > net::socket::Socket< SocketAddressT >::Socket () default
Socket() [2/2]
template<typename SocketAddressT > net::socket::Socket< SocketAddressT >::Socket (const Socket< SocketAddressT > &) delete
Member Function Documentation
bind()
template<typename SocketAddressT > void net::socket::Socket< SocketAddressT >::bind (const SocketAddress & bindAddress, const std::function< void(int)> & onError) inline
Definition at line 59 of file Socket.h.
{
             int ret = net::system::bind(getFd(), &bindAddress.getSockAddr(), sizeof(typename SocketAddress::SockAddr));
             if (ret < 0) {
                 onError(errno);
             } else {
                 this->bindAddress = bindAddress;
                 onError(0);
             }
         }
References net::system::bind(), net::socket::Socket< SocketAddressT >::bindAddress, and net::Descriptor::getFd().
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connect(), and net::socket::stream::SocketListener< SocketConnectionT >::listen().
create()
template<typename SocketAddressT > virtual int net::socket::Socket< SocketAddressT >::create (int flags) protected pure virtual
Implemented in net::socket::bluetooth::l2cap::Socket, net::socket::ip::tcp::ipv6::Socket, net::socket::ip::tcp::ipv4::Socket, and net::socket::bluetooth::rfcomm::Socket.
Referenced by net::socket::Socket< SocketAddressT >::open().
getBindAddress()
template<typename SocketAddressT > const SocketAddress& net::socket::Socket< SocketAddressT >::getBindAddress () const inline
Definition at line 76 of file Socket.h.
{
             return bindAddress;
         }
References net::socket::Socket< SocketAddressT >::bindAddress.
open()
template<typename SocketAddressT > void net::socket::Socket< SocketAddressT >::open (const std::function< void(int)> & onError, int flags = 0) inline
Definition at line 48 of file Socket.h.
{
             int fd = create(flags);
             if (fd >= 0) {
                 attach(fd);
                 onError(0);
             } else {
                 onError(errno);
             }
         }
References net::Descriptor::attach(), net::socket::Socket< SocketAddressT >::create(), and net::Descriptor::fd.
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connect(), and net::socket::stream::SocketListener< SocketConnectionT >::listen().
operator=()
template<typename SocketAddressT > Socket& net::socket::Socket< SocketAddressT >::operator= (const Socket< SocketAddressT > &) delete
shutdown()
template<typename SocketAddressT > void net::socket::Socket< SocketAddressT >::shutdown (shutdown how) inline
Definition at line 72 of file Socket.h.
{
             net::system::shutdown(getFd(), how);
         }
References net::Descriptor::getFd(), and net::system::shutdown().
Member Data Documentation
bindAddress
template<typename SocketAddressT > SocketAddress net::socket::Socket< SocketAddressT >::bindAddress {} protected
Definition at line 81 of file Socket.h.
Referenced by net::socket::Socket< SocketAddressT >::bind(), and net::socket::Socket< SocketAddressT >::getBindAddress().
The documentation for this class was generated from the following file:
net/socket/Socket.h