snode.c: web::http::server::SocketContextFactory< RequestT, ResponseT > Class Template Reference
web::http::server::SocketContextFactory< RequestT, ResponseT > Class Template Reference
#include <SocketContextFactory.h>
Public Types
using Request = RequestT
using Response = ResponseT
Public Member Functions
SocketContextFactory ()
~SocketContextFactory ()
SocketContextFactory (const SocketContextFactory &)=delete
SocketContextFactory & operator= (const SocketContextFactory &)=delete
void setOnRequestReady (const std::function< void(Request &, Response &)> &onRequestReady)
Private Member Functions
net::socket::stream::SocketContext * create (net::socket::stream::SocketConnection *socketConnection) const override
Private Attributes
std::function< void(Request &, Response &)> onRequestReady
Static Private Attributes
static int useCount = 0
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContextFactory
SocketContextFactory ()=default
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::server::SocketContextFactory< RequestT, ResponseT >
Definition at line 37 of file SocketContextFactory.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::server::SocketContextFactory< RequestT, ResponseT >::Request = RequestT
Definition at line 39 of file SocketContextFactory.h.
Response
template<typename RequestT , typename ResponseT > using web::http::server::SocketContextFactory< RequestT, ResponseT >::Response = ResponseT
Definition at line 40 of file SocketContextFactory.h.
Constructor & Destructor Documentation
SocketContextFactory() [1/2]
template<typename RequestT , typename ResponseT > web::http::server::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory () inline
Definition at line 42 of file SocketContextFactory.h.
{
             useCount++;
         }
References web::http::server::SocketContextFactory< RequestT, ResponseT >::useCount.
~SocketContextFactory()
template<typename RequestT , typename ResponseT > web::http::server::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory () inline virtual
Reimplemented from net::socket::stream::SocketContextFactory.
Definition at line 46 of file SocketContextFactory.h.
{
             useCount--;
             if (useCount == 0) {
                 SocketContextUpgradeFactorySelector::instance()->destroy();
             }
         }
References web::http::server::SocketContextUpgradeFactorySelector::destroy(), web::http::server::SocketContextUpgradeFactorySelector::instance(), and web::http::server::SocketContextFactory< RequestT, ResponseT >::useCount.
SocketContextFactory() [2/2]
template<typename RequestT , typename ResponseT > web::http::server::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory (const SocketContextFactory< RequestT, ResponseT > &) delete
Member Function Documentation
create()
template<typename RequestT , typename ResponseT > net::socket::stream::SocketContext* web::http::server::SocketContextFactory< RequestT, ResponseT >::create (net::socket::stream::SocketConnection * socketConnection) const inline override private virtual
Implements net::socket::stream::SocketContextFactory.
Definition at line 57 of file SocketContextFactory.h.
{
             return new SocketContextT<Request, Response>(socketConnection, onRequestReady);
         }
References web::http::server::SocketContextFactory< RequestT, ResponseT >::onRequestReady.
operator=()
template<typename RequestT , typename ResponseT > SocketContextFactory& web::http::server::SocketContextFactory< RequestT, ResponseT >::operator= (const SocketContextFactory< RequestT, ResponseT > &) delete
setOnRequestReady()
template<typename RequestT , typename ResponseT > void web::http::server::SocketContextFactory< RequestT, ResponseT >::setOnRequestReady (const std::function< void(Request &, Response &)> & onRequestReady) inline
Definition at line 62 of file SocketContextFactory.h.
{
             this->onRequestReady = onRequestReady;
         }
References web::http::server::SocketContextFactory< RequestT, ResponseT >::onRequestReady.
Member Data Documentation
onRequestReady
template<typename RequestT , typename ResponseT > std::function<void(Request&, Response&)> web::http::server::SocketContextFactory< RequestT, ResponseT >::onRequestReady private
Definition at line 67 of file SocketContextFactory.h.
Referenced by web::http::server::SocketContextFactory< RequestT, ResponseT >::create(), and web::http::server::SocketContextFactory< RequestT, ResponseT >::setOnRequestReady().
useCount
template<typename RequestT , typename ResponseT > int web::http::server::SocketContextFactory< RequestT, ResponseT >::useCount = 0 static private
Definition at line 69 of file SocketContextFactory.h.
Referenced by web::http::server::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory(), and web::http::server::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
The documentation for this class was generated from the following file:
web/http/server/SocketContextFactory.h