snode.c: net::socket::stream::tls::SocketConnection< SocketT > Class Template Reference
net::socket::stream::tls::SocketConnection< SocketT > Class Template Reference
#include <SocketConnection.h>
Public Types
using Socket = SocketT
Public Types inherited from net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >
using SocketReader = tls::SocketReader< SocketT >
using SocketWriter = tls::SocketWriter< SocketT >
using SocketAddress = SocketT::SocketAddress
Public Types inherited from net::socket::stream::SocketReader< SocketT >
using Socket = SocketT
Public Types inherited from net::socket::stream::SocketWriter< SocketT >
using Socket = SocketT
Public Member Functions
SocketConnection (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection, const char *junk, std::size_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::function< void(SocketConnection *socketConnection)> &onDisconnect)
SSL * getSSL () const
Public Member Functions inherited from net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >
SocketConnection ()=delete
void enqueue (const char *junk, std::size_t junkLen) override
void enqueue (const std::string &data) override
void close (bool instantly=false) final
const SocketAddress & getRemoteAddress () const
void setRemoteAddress (const SocketAddress &remoteAddress)
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress)
Public Member Functions inherited from net::socket::stream::SocketConnectionBase
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &attribute) const
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &&attribute) const
template<utils::InjectableAttribute Attribute>
constexpr bool getContext (const std::function< void(Attribute &)> &onFound) const
template<utils::InjectableAttribute Attribute>
constexpr void getContext (const std::function< void(Attribute &)> &onFound, const std::function< void(const std::string &)> &onNotFound) const
Public Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
~SocketConnection () override
SSL * startSSL (SSL_CTX *ctx)
void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int sslErr)> &onError)
void doSSLHandshake () override
void stopSSL ()
void setSSLError (int sslErr)
Protected Member Functions inherited from net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >
SocketConnection (const std::function< void(const char *junk, std::size_t junkLen)> &onRead, const std::function< void(int errnum)> &onReadError, const std::function< void(int errnum)> &onWriteError, const std::function< void()> &onDisconnect)
Protected Member Functions inherited from net::socket::stream::SocketConnectionBase
SocketConnectionBase ()=default
SocketConnectionBase (const SocketConnectionBase &)=delete
SocketConnectionBase & operator= (const SocketConnectionBase &)=delete
virtual ~SocketConnectionBase ()=default
Protected Member Functions inherited from net::socket::stream::SocketReader< SocketT >
SocketReader ()=delete
SocketReader (const std::function< void(const char *junk, std::size_t junkLen)> &onRead, const std::function< void(int errnum)> &onError)
virtual ~SocketReader ()=default
void shutdown ()
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from net::socket::stream::SocketWriter< SocketT >
SocketWriter ()=delete
SocketWriter (const std::function< void(int errnum)> &onError)
virtual ~SocketWriter ()=default
void enqueue (const char *junk, std::size_t junkLen)
void shutdown ()
Protected Member Functions inherited from net::WriteEventReceiver
WriteEventReceiver (long timeout=60)
Protected Attributes
SSL * ssl = nullptr
std::string serverNameIndication
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from net::socket::stream::tls::SocketReader< SocketT >
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Protected Attributes inherited from net::socket::stream::tls::SocketWriter< SocketT >
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Private Attributes
std::function< void(SocketConnection *socketConnection)> onDestruct
Friends
template<typename Socket >
class SocketListener
template<typename Socket >
class SocketConnector
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketConnection< SocketT >
Definition at line 37 of file SocketConnection.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::tls::SocketConnection< SocketT >::Socket = SocketT
Definition at line 40 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection()
template<typename SocketT > net::socket::stream::tls::SocketConnection< SocketT >::SocketConnection (const std::function< void(SocketConnection< SocketT > *socketConnection)> & onConstruct, const std::function< void(SocketConnection< SocketT > *socketConnection)> & onDestruct, const std::function< void(SocketConnection< SocketT > *socketConnection, const char *junk, std::size_t junkLen)> & onRead, const std::function< void(SocketConnection< SocketT > *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection< SocketT > *socketConnection, int errnum)> & onWriteError, const std::function< void(SocketConnection< SocketT > *socketConnection)> & onDisconnect) inline
Definition at line 43 of file SocketConnection.h.
             : stream::SocketConnection<tls::SocketReader<Socket>, tls::SocketWriter<Socket>, typename Socket::SocketAddress>::
                   SocketConnection(
                       [onRead, this](const char* junk, std::size_t junkLen) -> void {
                           onRead(this, junk, junkLen);
                       },
                       [onReadError, this](int errnum) -> void {
                           sslErr = errnum <= 0 ? -errnum : SSL_ERROR_SYSCALL;
                           onReadError(this, errnum);
                       },
                       [onWriteError, this](int errnum) -> void {
                           sslErr = errnum <= 0 ? -errnum : SSL_ERROR_SYSCALL;
                           onWriteError(this, errnum);
                       },
                       [onDisconnect, this]() -> void {
                           onDisconnect(this);
                       })
             , onDestruct(onDestruct) {
             onConstruct(this);
         }
~SocketConnection()
template<typename SocketT > net::socket::stream::tls::SocketConnection< SocketT >::~SocketConnection () inline override protected virtual
Reimplemented from net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >.
Definition at line 70 of file SocketConnection.h.
{
             onDestruct(this);
         }
Member Function Documentation
doSSLHandshake() [1/2]
template<typename SocketT > void net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake () inline override protected virtual
Implements net::socket::stream::tls::SocketReader< SocketT >.
Definition at line 128 of file SocketConnection.h.
{
             doSSLHandshake(
                 [](void) -> void {
                 },
                 [](void) -> void {
                 },
                 []([[maybe_unused]] int sslErr) -> void {
                 });
         }
doSSLHandshake() [2/2]
template<typename SocketT > void net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int sslErr)> & onError) inline protected
Definition at line 92 of file SocketConnection.h.
{
             SocketConnection::SocketReader::suspend();
             SocketConnection::SocketWriter::suspend();
             TLSHandshake::doHandshake(
                 ssl,
                 [onSuccess, this](void) -> void { // onSuccess
                     SocketConnection::SocketReader::resume();
                     SocketConnection::SocketWriter::resume();
                     onSuccess();
                 },
                 [onTimeout, this](void) -> void { // onTimeout
                     PLOG(ERROR) << "SSL/TLS handshake timeout";
                     if (SocketConnection::SocketReader::isEnabled()) {
                         SocketConnection::SocketReader::disable();
                     }
                     if (SocketConnection::SocketWriter::isEnabled()) {
                         SocketConnection::SocketWriter::disable();
                     }
                     onTimeout();
                 },
                 [onError, this](int sslErr) -> void { // onError
                     ssl_log("SSL/TLS handshake failed", -sslErr);
                     setSSLError(-sslErr);
                     if (SocketConnection::SocketReader::isEnabled()) {
                         SocketConnection::SocketReader::disable();
                     }
                     if (SocketConnection::SocketWriter::isEnabled()) {
                         SocketConnection::SocketWriter::disable();
                     }
                     onError(sslErr);
                 });
         }
References net::DescriptorEventReceiver::disable(), net::socket::stream::tls::TLSHandshake::doHandshake(), net::DescriptorEventReceiver::isEnabled(), net::DescriptorEventReceiver::resume(), net::socket::stream::tls::ssl_log(), and net::DescriptorEventReceiver::suspend().
Referenced by net::socket::stream::tls::SocketConnector< SocketT >::SocketConnector(), and net::socket::stream::tls::SocketListener< SocketT >::SocketListener().
getSSL()
template<typename SocketT > SSL* net::socket::stream::tls::SocketConnection< SocketT >::getSSL () const inline
Definition at line 154 of file SocketConnection.h.
{
             return ssl;
         }
setSSLError()
template<typename SocketT > void net::socket::stream::tls::SocketConnection< SocketT >::setSSLError (int sslErr) inline protected
Definition at line 159 of file SocketConnection.h.
{
             this->sslErr = sslErr;
         }
startSSL()
template<typename SocketT > SSL* net::socket::stream::tls::SocketConnection< SocketT >::startSSL (SSL_CTX * ctx) inline protected
Definition at line 74 of file SocketConnection.h.
{
             if (ctx != nullptr) {
                 ssl = SSL_new(ctx);
                 if (ssl != nullptr) {
                     if (SSL_set_fd(ssl, Socket::getFd()) == 1) {
                         SocketReader<Socket>::ssl = ssl;
                         SocketWriter<Socket>::ssl = ssl;
                     } else {
                         SSL_free(ssl);
                         ssl = nullptr;
                     }
                 }
             }
             return ssl;
         }
References net::Descriptor::getFd().
stopSSL()
template<typename SocketT > void net::socket::stream::tls::SocketConnection< SocketT >::stopSSL () inline protected
Definition at line 138 of file SocketConnection.h.
{
             if (ssl != nullptr) {
                 if (sslErr == 0) {
                     SSL_shutdown(ssl);
                 } else {
                     SSL_set_shutdown(ssl, SSL_SENT_SHUTDOWN | SSL_RECEIVED_SHUTDOWN);
                 }
                 SSL_free(ssl);
                 ssl = nullptr;
                 SocketReader<Socket>::ssl = nullptr;
                 SocketWriter<Socket>::ssl = nullptr;
             }
         }
Friends And Related Function Documentation
SocketConnector
template<typename SocketT > template<typename Socket > friend class SocketConnector friend
Definition at line 176 of file SocketConnection.h.
SocketListener
template<typename SocketT > template<typename Socket > friend class SocketListener friend
Definition at line 173 of file SocketConnection.h.
Member Data Documentation
onDestruct
template<typename SocketT > std::function<void(SocketConnection* socketConnection)> net::socket::stream::tls::SocketConnection< SocketT >::onDestruct private
Definition at line 170 of file SocketConnection.h.
serverNameIndication
template<typename SocketT > std::string net::socket::stream::tls::SocketConnection< SocketT >::serverNameIndication protected
Definition at line 165 of file SocketConnection.h.
Referenced by net::socket::stream::tls::SocketListener< SocketT >::serverNameCallback().
ssl
template<typename SocketT > SSL* net::socket::stream::tls::SocketConnection< SocketT >::ssl = nullptr protected
Definition at line 163 of file SocketConnection.h.
sslErr
template<typename SocketT > int net::socket::stream::tls::SocketConnection< SocketT >::sslErr = SSL_ERROR_NONE protected
Definition at line 167 of file SocketConnection.h.
The documentation for this class was generated from the following file:
net/socket/stream/tls/SocketConnection.h