snode.c: http::WSTransmitter Class Reference
http::WSTransmitter Class Reference abstract
#include <WSTransmitter.h>
Classes
union MaskingKey
Protected Member Functions
virtual void messageStart (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0)
virtual void sendFrame (const char *message, std::size_t messageLength, uint32_t messageKey=0)
virtual void messageEnd (const char *message, std::size_t messageLength, uint32_t messageKey=0)
virtual void message (uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey=0)
Private Member Functions
void sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, const char *payload, uint64_t payloadLength)
void dumpFrame (char *frame, uint64_t frameLength)
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength, uint32_t messageKey)
virtual void onFrameReady (char *frame, uint64_t frameLength)=0
Detailed Description
Definition at line 31 of file WSTransmitter.h.
Member Function Documentation
dumpFrame()
void http::WSTransmitter::dumpFrame (char * frame, uint64_t frameLength) private
Definition at line 124 of file WSTransmitter.cpp.
{
         int modul = 4;
         std::stringstream stringStream;
         for (std::size_t i = 0; i < frameLength; i++) {
             stringStream << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % modul == 0 || i == frameLength) {
                 VLOG(0) << "Frame: " << stringStream.str();
                 stringStream.str("");
             }
         }
     }
message()
void http::WSTransmitter::message (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0) protected virtual
Reimplemented in http::websocket::WSServerContext.
Definition at line 48 of file WSTransmitter.cpp.
{
         send(true, opCode, message, messageLength, messageKey);
     }
References send().
Referenced by http::websocket::WSServerContext::message(), messageEnd(), messageStart(), send(), and sendFrame().
messageEnd()
void http::WSTransmitter::messageEnd (const char * message, std::size_t messageLength, uint32_t messageKey = 0) protected virtual
Reimplemented in http::websocket::WSServerContext.
Definition at line 44 of file WSTransmitter.cpp.
{
         send(true, 0, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by http::websocket::WSServerContext::messageEnd().
messageStart()
void http::WSTransmitter::messageStart (uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey = 0) protected virtual
Reimplemented in http::websocket::WSServerContext.
Definition at line 36 of file WSTransmitter.cpp.
{
         send(false, opCode, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by http::websocket::WSServerContext::messageStart().
onFrameReady()
virtual void http::WSTransmitter::onFrameReady (char * frame, uint64_t frameLength) private pure virtual
Implemented in http::websocket::WSServerContext.
Referenced by sendFrame().
send()
void http::WSTransmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength, uint32_t messageKey) private
Definition at line 52 of file WSTransmitter.cpp.
{
         std::size_t messageOffset = 0;
         do {
             std::size_t sendMessageLength =
                 (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
             bool fin = sendMessageLength == messageLength - messageOffset;
             sendFrame(fin && end, opCode, messageKey, message + messageOffset, sendMessageLength);
             messageOffset += sendMessageLength;
             opCode = 0; // continuation
         } while (messageLength - messageOffset > 0);
     }
References message(), sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by message(), messageEnd(), messageStart(), and sendFrame().
sendFrame() [1/2]
void http::WSTransmitter::sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, const char * payload, uint64_t payloadLength) private
Definition at line 69 of file WSTransmitter.cpp.
{
         uint64_t frameLength = 2 + payloadLength;
         uint8_t opCodeOffset = 0;
         uint8_t lengthOffset = 1;
         uint8_t eLengthOffset = 2;
         uint8_t maskingKeyOffset = 2;
         uint8_t payloadOffset = 2;
         if (maskingKey > 0) {
             frameLength += 4;
             payloadOffset += 4;
         }
         char* frame = nullptr;
         uint64_t length = 0;
         if (payloadLength < 126) {
             frame = new char[frameLength];
             length = payloadLength;
         } else if (payloadLength < 0x10000) {
             frameLength += 2;
             maskingKeyOffset += 2;
             payloadOffset += 2;
             frame = new char[frameLength];
             *reinterpret_cast<uint16_t*>(frame + eLengthOffset) = htobe16(static_cast<uint16_t>(payloadLength));
             length = 126;
         } else {
             frameLength += 8;
             maskingKeyOffset += 8;
             payloadOffset += 8;
             frame = new char[frameLength];
             *reinterpret_cast<uint64_t*>(frame + eLengthOffset) = htobe64(payloadLength);
             length = 127;
         }
         if (maskingKey > 0) {
             *reinterpret_cast<uint32_t*>(frame + maskingKeyOffset) = htobe32(maskingKey);
         }
         *reinterpret_cast<uint8_t*>(frame + opCodeOffset) = static_cast<uint8_t>((fin ? 0b10000000 : 0) | opCode);
         *reinterpret_cast<uint8_t*>(frame + lengthOffset) = static_cast<uint8_t>(((maskingKey > 0) ? 0b10000000 : 0) | length);
         MaskingKey maskingKeyAsArray = {.key = htobe32(maskingKey)};
         for (uint64_t i = 0; i < payloadLength; i++) {
             *(frame + payloadOffset + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsArray + i % 4);
         }
         // dumpFrame(frame, frameLength);
         onFrameReady(frame, frameLength);
         delete[] frame;
     }
References http::WSTransmitter::MaskingKey::key, http::WSTransmitter::MaskingKey::keyAsArray, and onFrameReady().
sendFrame() [2/2]
void http::WSTransmitter::sendFrame (const char * message, std::size_t messageLength, uint32_t messageKey = 0) protected virtual
Reimplemented in http::websocket::WSServerContext.
Definition at line 40 of file WSTransmitter.cpp.
{
         send(false, 0, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by send(), and http::websocket::WSServerContext::sendFrame().
The documentation for this class was generated from the following files:
http/WSTransmitter.h
http/WSTransmitter.cpp