snode.c: net::socket::stream::tls::SocketReader< SocketT > Class Template Reference
net::socket::stream::tls::SocketReader< SocketT > Class Template Reference abstract
#include <SocketReader.h>
Protected Member Functions
virtual void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onError)=0
void setSSLError (int sslErr)
Protected Member Functions inherited from net::socket::stream::SocketReader< SocketT >
SocketReader (const std::function< void(int)> &onError)
virtual ~SocketReader ()=default
void shutdown ()
std::size_t readFromPeer (char *junk, std::size_t junkLen)
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Private Member Functions
ssize_t read (char *junk, std::size_t junkLen) override
int getError () override
Additional Inherited Members
Public Types inherited from net::socket::stream::SocketReader< SocketT >
using Socket = SocketT
Public Member Functions inherited from net::DescriptorEventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketReader< SocketT >
Definition at line 39 of file SocketReader.h.
Member Function Documentation
doSSLHandshake()
template<typename SocketT > virtual void net::socket::stream::tls::SocketReader< SocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onError) protected pure virtual
Implemented in net::socket::stream::tls::SocketConnection< SocketT >.
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read().
getError()
template<typename SocketT > int net::socket::stream::tls::SocketReader< SocketT >::getError () inline override private virtual
Implements net::socket::stream::SocketReader< SocketT >.
Definition at line 89 of file SocketReader.h.
{
             int ret = errno;
             switch (sslErr) {
                 case SSL_ERROR_NONE:
                     [[fallthrough]];
                 case SSL_ERROR_ZERO_RETURN:
                     ret = 0;
                     break;
                 case SSL_ERROR_SYSCALL:
                     break;
                 default:
                     ret = -sslErr;
                     break;
             };
             return ret;
         }
References net::socket::stream::tls::SocketReader< SocketT >::sslErr.
read()
template<typename SocketT > ssize_t net::socket::stream::tls::SocketReader< SocketT >::read (char * junk, std::size_t junkLen) inline override private virtual
Implements net::socket::stream::SocketReader< SocketT >.
Definition at line 43 of file SocketReader.h.
{
             sslErr = 0;
             int ret = SSL_read(ssl, junk, static_cast<int>(junkLen));
             if (ret <= 0) {
                 sslErr = SSL_get_error(ssl, ret);
                 switch (sslErr) {
                     case SSL_ERROR_WANT_WRITE:
                         LOG(INFO) << "SSL/TLS start renegotiation on read";
                         doSSLHandshake(
                             [](void) -> void {
                                 LOG(INFO) << "SSL/TLS renegotiation on read success";
                             },
                             [](void) -> void {
                                 LOG(WARNING) << "SSL/TLS renegotiation on read timed out";
                             },
                             [this](int sslErr) -> void {
                                 ssl_log("SSL/TLS renegotiation", sslErr);
                                 setSSLError(sslErr);
                             });
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_WANT_READ:
                         ret = 0;
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_ZERO_RETURN:
                         ret = 0;
                         errno = 0;
                         break;
                     case SSL_ERROR_SYSCALL:
                         if (errno != 0) {
                             ssl_log("SSL/TLS read failed", sslErr);
                         }
                         break;
                     default:
                         ssl_log("SSL/TLS read failed", sslErr);
                         break;
                 }
             }
             return ret;
         }
References net::socket::stream::tls::SocketReader< SocketT >::doSSLHandshake(), net::socket::stream::tls::SocketReader< SocketT >::setSSLError(), net::socket::stream::tls::SocketReader< SocketT >::ssl, net::socket::stream::tls::ssl_log(), net::ssl::SSL_read(), and net::socket::stream::tls::SocketReader< SocketT >::sslErr.
setSSLError()
template<typename SocketT > void net::socket::stream::tls::SocketReader< SocketT >::setSSLError (int sslErr) inline protected
Definition at line 113 of file SocketReader.h.
{
             this->sslErr = sslErr;
         }
References net::socket::stream::tls::SocketReader< SocketT >::sslErr.
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read().
Member Data Documentation
ssl
template<typename SocketT > SSL* net::socket::stream::tls::SocketReader< SocketT >::ssl = nullptr protected
Definition at line 117 of file SocketReader.h.
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read().
sslErr
template<typename SocketT > int net::socket::stream::tls::SocketReader< SocketT >::sslErr = SSL_ERROR_NONE protected
Definition at line 119 of file SocketReader.h.
Referenced by net::socket::stream::tls::SocketReader< SocketT >::getError(), net::socket::stream::tls::SocketReader< SocketT >::read(), and net::socket::stream::tls::SocketReader< SocketT >::setSSLError().
The documentation for this class was generated from the following file:
net/socket/stream/tls/SocketReader.h