snode.c: net::OutOfBandEventReceiver Class Reference
net::OutOfBandEventReceiver Class Reference abstract
#include <OutOfBandEventReceiver.h>
Public Member Functions
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable (int fd) override
void suspend (int fd) override
void resume (int fd) override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
OutOfBandEventReceiver ()
virtual void outOfBandEvent ()=0
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Friends
template<typename OutOfBandEventReceiver >
class EventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 30 of file OutOfBandEventReceiver.h.
Constructor & Destructor Documentation
OutOfBandEventReceiver()
net::OutOfBandEventReceiver::OutOfBandEventReceiver () protected
Definition at line 26 of file OutOfBandEventReceiver.cpp.
         : EventReceiver(EventLoop::instance().getOutOfBandEventDispatcher().getTimeout()) {
     }
Member Function Documentation
disable()
void net::OutOfBandEventReceiver::disable (int fd) override virtual
Implements net::EventReceiver.
Definition at line 39 of file OutOfBandEventReceiver.cpp.
{
         EventLoop::instance().getOutOfBandEventDispatcher().disable(this, fd);
     }
References net::EventDispatcher< EventReceiverT >::disable(), net::EventLoop::getOutOfBandEventDispatcher(), and net::EventLoop::instance().
dispatchEvent()
void net::OutOfBandEventReceiver::dispatchEvent () inline override protected virtual
Implements net::EventReceiver.
Definition at line 36 of file OutOfBandEventReceiver.h.
{
             outOfBandEvent();
         }
References outOfBandEvent().
enable()
void net::OutOfBandEventReceiver::enable (int fd, long timeout = TIMEOUT::IGNORE) override virtual
Implements net::EventReceiver.
Definition at line 34 of file OutOfBandEventReceiver.cpp.
{
         EventLoop::instance().getOutOfBandEventDispatcher().enable(this, fd);
         setTimeout(timeout);
     }
References net::EventDispatcher< EventReceiverT >::enable(), net::EventLoop::getOutOfBandEventDispatcher(), net::EventLoop::instance(), and setTimeout().
outOfBandEvent()
virtual void net::OutOfBandEventReceiver::outOfBandEvent () protected pure virtual
Referenced by dispatchEvent().
resume()
void net::OutOfBandEventReceiver::resume (int fd) override virtual
Implements net::EventReceiver.
Definition at line 47 of file OutOfBandEventReceiver.cpp.
{
         EventLoop::instance().getOutOfBandEventDispatcher().resume(this, fd);
     }
References net::EventLoop::getOutOfBandEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::resume().
setTimeout()
void net::OutOfBandEventReceiver::setTimeout (long timeout = TIMEOUT::DEFAULT)
Definition at line 30 of file OutOfBandEventReceiver.cpp.
{
         EventReceiver::setTimeout(timeout, EventLoop::instance().getOutOfBandEventDispatcher().getTimeout());
     }
References net::EventReceiver::getTimeout(), net::EventLoop::instance(), and net::EventReceiver::setTimeout().
Referenced by enable().
suspend()
void net::OutOfBandEventReceiver::suspend (int fd) override virtual
Implements net::EventReceiver.
Definition at line 43 of file OutOfBandEventReceiver.cpp.
{
         EventLoop::instance().getOutOfBandEventDispatcher().suspend(this, fd);
     }
References net::EventLoop::getOutOfBandEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::suspend().
Friends And Related Function Documentation
EventDispatcher
template<typename OutOfBandEventReceiver > friend class EventDispatcher friend
Definition at line 50 of file OutOfBandEventReceiver.h.
The documentation for this class was generated from the following files:
net/OutOfBandEventReceiver.h
net/OutOfBandEventReceiver.cpp