snode.c: web::websocket::server::ChannelManager Class Reference
web::websocket::server::ChannelManager Class Reference
#include <ChannelManager.h>
Public Member Functions
void subscribe (const std::string &channel, SubProtocol *subProtocol)
void unsubscribe (SubProtocol *subProtocol)
Static Public Member Functions
static ChannelManager * instance ()
Private Member Functions
ChannelManager ()
ChannelManager (const ChannelManager &)=delete
~ChannelManager ()
ChannelManager & operator= (const ChannelManager &)=delete
void subscribe (SubProtocol *subProtocol)
void sendBroadcast (const std::string &channel, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastStart (const std::string &channel, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcast (const std::string &channel, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastStart (const std::string &channel, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastFrame (const std::string &channel, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastFrame (const std::string &channel, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastEnd (const std::string &channel, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastEnd (const std::string &channel, const std::string &message, const SubProtocol *excludedClient)
void forEachClient (const std::string &channel, const std::function< void(SubProtocol *)> &sendToClient, const SubProtocol *excludedClient)
Private Attributes
std::map< std::string, std::set< SubProtocol * > > channels
Static Private Attributes
static ChannelManager * channelManager = nullptr
Friends
class SubProtocol
Detailed Description
Definition at line 36 of file ChannelManager.h.
Constructor & Destructor Documentation
ChannelManager() [1/2]
web::websocket::server::ChannelManager::ChannelManager () private
Definition at line 31 of file ChannelManager.cpp.
{
         ChannelManager::channelManager = this;
     }
References channelManager.
Referenced by instance().
ChannelManager() [2/2]
web::websocket::server::ChannelManager::ChannelManager (const ChannelManager &) private delete
~ChannelManager()
web::websocket::server::ChannelManager::~ChannelManager () private
Definition at line 35 of file ChannelManager.cpp.
{
         ChannelManager::channelManager = nullptr;
     }
References channelManager.
Member Function Documentation
forEachClient()
void web::websocket::server::ChannelManager::forEachClient (const std::string & channel, const std::function< void(SubProtocol *)> & sendToClient, const SubProtocol * excludedClient) private
Definition at line 161 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     sendToClient(client);
                 }
             }
         }
     }
References channels.
Referenced by web::websocket::server::SubProtocol::forEachClient().
instance()
ChannelManager * web::websocket::server::ChannelManager::instance () static
Definition at line 39 of file ChannelManager.cpp.
{
         return ChannelManager::channelManager == nullptr ? new ChannelManager() : ChannelManager::channelManager;
     }
References ChannelManager(), and channelManager.
Referenced by web::websocket::server::SubProtocol::forEachClient(), web::websocket::server::SubProtocol::sendBroadcast(), web::websocket::server::SubProtocol::sendBroadcastEnd(), web::websocket::server::SubProtocol::sendBroadcastFrame(), web::websocket::server::SubProtocol::sendBroadcastStart(), web::websocket::server::SubProtocol::SubProtocol(), web::websocket::server::SubProtocol::subscribe(), and web::websocket::server::SubProtocol::~SubProtocol().
operator=()
ChannelManager& web::websocket::server::ChannelManager::operator= (const ChannelManager &) private delete
sendBroadcast() [1/2]
void web::websocket::server::ChannelManager::sendBroadcast (const std::string & channel, const char * message, std::size_t messageLength, const SubProtocol * excludedClient) private
Definition at line 75 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessage(message, messageLength);
                 }
             }
         }
     }
References channels.
Referenced by web::websocket::server::SubProtocol::sendBroadcast().
sendBroadcast() [2/2]
void web::websocket::server::ChannelManager::sendBroadcast (const std::string & channel, const std::string & message, const SubProtocol * excludedClient) private
Definition at line 103 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessage(message);
                 }
             }
         }
     }
References channels.
sendBroadcastEnd() [1/2]
void web::websocket::server::ChannelManager::sendBroadcastEnd (const std::string & channel, const char * message, std::size_t messageLength, const SubProtocol * excludedClient) private
Definition at line 143 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessageEnd(message, messageLength);
                 }
             }
         }
     }
References channels.
Referenced by web::websocket::server::SubProtocol::sendBroadcastEnd(), and sendBroadcastEnd().
sendBroadcastEnd() [2/2]
void web::websocket::server::ChannelManager::sendBroadcastEnd (const std::string & channel, const std::string & message, const SubProtocol * excludedClient) private
Definition at line 157 of file ChannelManager.cpp.
{
         sendBroadcastEnd(channel, message.data(), message.length(), excludedClient);
     }
References sendBroadcastEnd().
sendBroadcastFrame() [1/2]
void web::websocket::server::ChannelManager::sendBroadcastFrame (const std::string & channel, const char * message, std::size_t messageLength, const SubProtocol * excludedClient) private
Definition at line 125 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessageFrame(message, messageLength);
                 }
             }
         }
     }
References channels.
Referenced by web::websocket::server::SubProtocol::sendBroadcastFrame(), and sendBroadcastFrame().
sendBroadcastFrame() [2/2]
void web::websocket::server::ChannelManager::sendBroadcastFrame (const std::string & channel, const std::string & message, const SubProtocol * excludedClient) private
Definition at line 139 of file ChannelManager.cpp.
{
         sendBroadcastFrame(channel, message.data(), message.length(), excludedClient);
     }
References sendBroadcastFrame().
sendBroadcastStart() [1/2]
void web::websocket::server::ChannelManager::sendBroadcastStart (const std::string & channel, const char * message, std::size_t messageLength, const SubProtocol * excludedClient) private
Definition at line 89 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessage(message, messageLength);
                 }
             }
         }
     }
References channels.
Referenced by web::websocket::server::SubProtocol::sendBroadcastStart().
sendBroadcastStart() [2/2]
void web::websocket::server::ChannelManager::sendBroadcastStart (const std::string & channel, const std::string & message, const SubProtocol * excludedClient) private
Definition at line 114 of file ChannelManager.cpp.
{
         if (channels.contains(channel)) {
             const std::set<SubProtocol*>& clients = channels[channel];
             for (SubProtocol* client : clients) {
                 if (client != excludedClient) {
                     client->sendMessage(message);
                 }
             }
         }
     }
References channels.
subscribe() [1/2]
void web::websocket::server::ChannelManager::subscribe (const std::string & channel, SubProtocol * subProtocol)
Definition at line 43 of file ChannelManager.cpp.
{
         if (subProtocol->channel != channel) {
             std::string newChannel = subProtocol->getName() + "/" + channel;
             channels[newChannel].insert(subProtocol);
             if (!subProtocol->channel.empty()) {
                 unsubscribe(subProtocol);
             }
             subProtocol->channel = newChannel;
         }
     }
References web::websocket::server::SubProtocol::channel, channels, web::websocket::SubProtocol< SocketContextT >::getName(), and unsubscribe().
Referenced by web::websocket::server::SubProtocol::SubProtocol(), web::websocket::server::SubProtocol::subscribe(), and subscribe().
subscribe() [2/2]
void web::websocket::server::ChannelManager::subscribe (SubProtocol * subProtocol) private
Definition at line 57 of file ChannelManager.cpp.
{
         subscribe(subProtocol->getName(), subProtocol);
     }
References web::websocket::SubProtocol< SocketContextT >::getName(), and subscribe().
unsubscribe()
void web::websocket::server::ChannelManager::unsubscribe (SubProtocol * subProtocol)
Definition at line 61 of file ChannelManager.cpp.
{
         if (channels.contains(subProtocol->channel)) {
             channels[subProtocol->channel].erase(subProtocol);
             if (channels[subProtocol->channel].size() == 0) {
                 channels.erase(subProtocol->channel);
                 if (channels.size() == 0) {
                     delete this;
                 }
             }
         }
     }
References web::websocket::server::SubProtocol::channel, and channels.
Referenced by subscribe(), and web::websocket::server::SubProtocol::~SubProtocol().
Friends And Related Function Documentation
SubProtocol
friend class SubProtocol friend
Definition at line 77 of file ChannelManager.h.
Member Data Documentation
channelManager
ChannelManager * web::websocket::server::ChannelManager::channelManager = nullptr static private
Definition at line 73 of file ChannelManager.h.
Referenced by ChannelManager(), instance(), and ~ChannelManager().
channels
std::map<std::string, std::set<SubProtocol*> > web::websocket::server::ChannelManager::channels private
Definition at line 75 of file ChannelManager.h.
Referenced by forEachClient(), sendBroadcast(), sendBroadcastEnd(), sendBroadcastFrame(), sendBroadcastStart(), subscribe(), and unsubscribe().
The documentation for this class was generated from the following files:
web/websocket/server/ChannelManager.h
web/websocket/server/ChannelManager.cpp