snode.c: web::ws::WSSubProtocol Class Reference
web::ws::WSSubProtocol Class Reference abstract
#include <WSSubProtocol.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
virtual ~WSSubProtocol ()
void sendMessageStart (const char *message, std::size_t messageLength)
void sendMessageStart (const std::string &message)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageFrame (const std::string &message)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendMessageEnd (const std::string &message)
void sendMessage (const char *message, std::size_t messageLength)
void sendMessage (const std::string &message)
void sendPing (char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
const std::string & getName ()
Static Public Member Functions
static void sendBroadcast (const char *message, std::size_t messageLength)
static void sendBroadcast (const std::string &message)
Protected Member Functions
WSSubProtocol (const std::string &name)
Private Member Functions
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *junk, std::size_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onPongReceived ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onProtocolConnected ()=0
virtual void onProtocolDisconnected ()=0
void setWSContext (WSContext *wSServerContext)
Static Private Member Functions
static void broadcast (uint8_t opCode, const char *message, std::size_t messageLength)
Private Attributes
WSContext * wSContext
const std::string name
Static Private Attributes
static std::list< WSSubProtocol * > clients
Friends
class web::ws::WSContext
Detailed Description
Definition at line 37 of file WSSubProtocol.h.
Member Enumeration Documentation
Role
enum web::ws::WSSubProtocol::Role strong
Enumerator
SERVER
CLIENT
Definition at line 39 of file WSSubProtocol.h.
 { SERVER, CLIENT };
Constructor & Destructor Documentation
WSSubProtocol()
web::ws::WSSubProtocol::WSSubProtocol (const std::string & name) protected
Definition at line 32 of file WSSubProtocol.cpp.
         : name(name) {
         clients.push_back(this);
     }
References clients.
~WSSubProtocol()
web::ws::WSSubProtocol::~WSSubProtocol () virtual
Definition at line 37 of file WSSubProtocol.cpp.
{
         clients.remove(this);
     }
References clients.
Member Function Documentation
broadcast()
void web::ws::WSSubProtocol::broadcast (uint8_t opCode, const char * message, std::size_t messageLength) static private
Definition at line 104 of file WSSubProtocol.cpp.
{
         for (WSSubProtocol* client : clients) {
             client->wSContext->sendMessage(opCode, message, messageLength);
         }
     }
References clients.
Referenced by sendBroadcast().
getLocalAddressAsString()
std::string web::ws::WSSubProtocol::getLocalAddressAsString () const
Definition at line 81 of file WSSubProtocol.cpp.
{
         return wSContext->getLocalAddressAsString();
     }
References web::ws::WSContext::getLocalAddressAsString(), and wSContext.
getName()
const std::string & web::ws::WSSubProtocol::getName ()
Definition at line 110 of file WSSubProtocol.cpp.
{
         return name;
     }
References name.
getRemoteAddressAsString()
std::string web::ws::WSSubProtocol::getRemoteAddressAsString () const
Definition at line 85 of file WSSubProtocol.cpp.
{
         return wSContext->getRemoteAddressAsString();
     }
References web::ws::WSContext::getRemoteAddressAsString(), and wSContext.
onMessageData()
virtual void web::ws::WSSubProtocol::onMessageData (const char * junk, std::size_t junkLen) private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onFrameReceived().
onMessageEnd()
virtual void web::ws::WSSubProtocol::onMessageEnd () private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onMessageEnd().
onMessageError()
virtual void web::ws::WSSubProtocol::onMessageError (uint16_t errnum) private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onMessageError().
onMessageStart()
virtual void web::ws::WSSubProtocol::onMessageStart (int opCode) private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onMessageStart().
onPongReceived()
virtual void web::ws::WSSubProtocol::onPongReceived () private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onMessageEnd(), and web::ws::WSContext::onPongReceived().
onProtocolConnected()
virtual void web::ws::WSSubProtocol::onProtocolConnected () private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onProtocolConnected().
onProtocolDisconnected()
virtual void web::ws::WSSubProtocol::onProtocolDisconnected () private pure virtual
Implemented in web::ws::subprotocol::echo::server::Echo.
Referenced by web::ws::WSContext::onProtocolDisconnected().
sendBroadcast() [1/2]
void web::ws::WSSubProtocol::sendBroadcast (const char * message, std::size_t messageLength) static
Definition at line 93 of file WSSubProtocol.cpp.
{
         broadcast(2, message, messageLength);
     }
References broadcast().
sendBroadcast() [2/2]
void web::ws::WSSubProtocol::sendBroadcast (const std::string & message) static
Definition at line 89 of file WSSubProtocol.cpp.
{
         broadcast(1, message.data(), message.length());
     }
References broadcast().
sendClose()
void web::ws::WSSubProtocol::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 77 of file WSSubProtocol.cpp.
{
         wSContext->close(statusCode, reason, reasonLength);
     }
References web::ws::WSContext::close(), and wSContext.
sendMessage() [1/2]
void web::ws::WSSubProtocol::sendMessage (const char * message, std::size_t messageLength)
Definition at line 61 of file WSSubProtocol.cpp.
{
         wSContext->sendMessage(2, msg, messageLength);
     }
References web::ws::WSContext::sendMessage(), and wSContext.
sendMessage() [2/2]
void web::ws::WSSubProtocol::sendMessage (const std::string & message)
Definition at line 57 of file WSSubProtocol.cpp.
{
         wSContext->sendMessage(1, msg.data(), msg.length());
     }
References web::ws::WSContext::sendMessage(), and wSContext.
sendMessageEnd() [1/2]
void web::ws::WSSubProtocol::sendMessageEnd (const char * message, std::size_t messageLength)
Definition at line 69 of file WSSubProtocol.cpp.
{
         wSContext->sendMessageEnd(message, messageLength);
     }
References web::ws::WSContext::sendMessageEnd(), and wSContext.
Referenced by sendMessageEnd().
sendMessageEnd() [2/2]
void web::ws::WSSubProtocol::sendMessageEnd (const std::string & message)
Definition at line 65 of file WSSubProtocol.cpp.
{
         sendMessageEnd(message.data(), message.length());
     }
References sendMessageEnd().
sendMessageFrame() [1/2]
void web::ws::WSSubProtocol::sendMessageFrame (const char * message, std::size_t messageLength)
Definition at line 53 of file WSSubProtocol.cpp.
{
         wSContext->sendMessageFrame(message, messageLength);
     }
References web::ws::WSContext::sendMessageFrame(), and wSContext.
Referenced by sendMessageFrame().
sendMessageFrame() [2/2]
void web::ws::WSSubProtocol::sendMessageFrame (const std::string & message)
Definition at line 49 of file WSSubProtocol.cpp.
{
         sendMessageFrame(message.data(), message.length());
     }
References sendMessageFrame().
sendMessageStart() [1/2]
void web::ws::WSSubProtocol::sendMessageStart (const char * message, std::size_t messageLength)
Definition at line 45 of file WSSubProtocol.cpp.
                                                                                      { // 2
         wSContext->sendMessageStart(2, message, messageLength);
     }
References web::ws::WSContext::sendMessageStart(), and wSContext.
sendMessageStart() [2/2]
void web::ws::WSSubProtocol::sendMessageStart (const std::string & message)
Definition at line 41 of file WSSubProtocol.cpp.
                                                                  { // 1
         wSContext->sendMessageStart(1, message.data(), message.length());
     }
References web::ws::WSContext::sendMessageStart(), and wSContext.
sendPing()
void web::ws::WSSubProtocol::sendPing (char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 73 of file WSSubProtocol.cpp.
{
         wSContext->sendPing(reason, reasonLength);
     }
References web::ws::WSContext::sendPing(), and wSContext.
setWSContext()
void web::ws::WSSubProtocol::setWSContext (WSContext * wSServerContext) private
Definition at line 98 of file WSSubProtocol.cpp.
{
         wSContext = wSServerContext;
     }
References wSContext.
Referenced by web::ws::WSContext::WSContext().
Friends And Related Function Documentation
web::ws::WSContext
friend class web::ws::WSContext friend
Definition at line 94 of file WSSubProtocol.h.
Member Data Documentation
clients
std::list< WSSubProtocol * > web::ws::WSSubProtocol::clients static private
Definition at line 90 of file WSSubProtocol.h.
Referenced by broadcast(), WSSubProtocol(), and ~WSSubProtocol().
name
const std::string web::ws::WSSubProtocol::name private
Definition at line 92 of file WSSubProtocol.h.
Referenced by getName().
wSContext
WSContext* web::ws::WSSubProtocol::wSContext private
Definition at line 88 of file WSSubProtocol.h.
Referenced by getLocalAddressAsString(), getRemoteAddressAsString(), sendClose(), sendMessage(), sendMessageEnd(), sendMessageFrame(), sendMessageStart(), sendPing(), and setWSContext().
The documentation for this class was generated from the following files:
web/ws/WSSubProtocol.h
web/ws/WSSubProtocol.cpp