snode.c: net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT > Class Template Reference
net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT > Class Template Reference
#include <SocketConnection.h>
Public Types
using SocketReader = SocketReaderT
using SocketWriter = SocketWriterT
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketConnection_v)
SocketConnection ()=delete
SocketConnection (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::function< void(SocketConnection *socketConnection)> &onDisconnect)
~SocketConnection () override
void enqueue (const char *junk, size_t junkLen) override
void enqueue (const std::string &data) override
void end (bool instantly=false) override
const InetAddress & getRemoteAddress () const
void setRemoteAddress (const InetAddress &remoteAddress)
Public Member Functions inherited from net::socket::tcp::SocketConnectionBase
SocketConnectionBase ()=default
SocketConnectionBase (const SocketConnectionBase &)=delete
SocketConnectionBase & operator= (const SocketConnectionBase &)=delete
virtual ~SocketConnectionBase ()=default
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &attribute) const
template<utils::InjectableAttribute Attribute>
constexpr void setContext (Attribute &&attribute) const
template<utils::InjectableAttribute Attribute>
constexpr bool getContext (std::function< void(Attribute &)> onFound) const
template<utils::InjectableAttribute Attribute>
constexpr void getContext (std::function< void(Attribute &)> onFound, std::function< void(const std::string &)> onNotFound) const
Private Member Functions
void unobserved () override
Private Attributes
InetAddress remoteAddress {}
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onDisconnect
bool isDynamic
Static Private Attributes
static void * lastAllocAddress = nullptr
Detailed Description
template<typename SocketReaderT, typename SocketWriterT>
class net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >
Definition at line 34 of file SocketConnection.h.
Member Typedef Documentation
SocketReader
template<typename SocketReaderT , typename SocketWriterT > using net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::SocketReader = SocketReaderT
Definition at line 39 of file SocketConnection.h.
SocketWriter
template<typename SocketReaderT , typename SocketWriterT > using net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::SocketWriter = SocketWriterT
Definition at line 40 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection() [1/2]
template<typename SocketReaderT , typename SocketWriterT > net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::SocketConnection () delete
SocketConnection() [2/2]
template<typename SocketReaderT , typename SocketWriterT > net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::SocketConnection (const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection)> & onConstruct, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection)> & onDestruct, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection, int errnum)> & onWriteError, const std::function< void(SocketConnection< SocketReaderT, SocketWriterT > *socketConnection)> & onDisconnect) inline
Definition at line 54 of file SocketConnection.h.
             : SocketReader(
                   [this, onRead](const char* junk, ssize_t junkLen) -> void {
                       onRead(this, junk, junkLen);
                   },
                   [this, onReadError](int errnum) -> void {
                       onReadError(this, errnum);
                   })
             , SocketWriter([this, onWriteError](int errnum) -> void {
                 onWriteError(this, errnum);
             })
             , onDestruct(onDestruct)
             , onDisconnect(onDisconnect)
             , isDynamic(this == lastAllocAddress) {
             onConstruct(this);
         }
~SocketConnection()
template<typename SocketReaderT , typename SocketWriterT > net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::~SocketConnection () inline override
Definition at line 76 of file SocketConnection.h.
{
             onDestruct(this);
         }
References net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::onDestruct.
Member Function Documentation
end()
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::end (bool instantly = false) inline override virtual
Implements net::socket::tcp::SocketConnectionBase.
Definition at line 98 of file SocketConnection.h.
{
             SocketReaderT::disable();
             if (instantly) {
                 SocketWriterT::disable();
             }
         }
enqueue() [1/2]
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::enqueue (const char * junk, size_t junkLen) inline override virtual
Implements net::socket::tcp::SocketConnectionBase.
Definition at line 90 of file SocketConnection.h.
{
             SocketWriterT::enqueue(junk, junkLen);
         }
Referenced by net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::enqueue().
enqueue() [2/2]
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::enqueue (const std::string & data) inline override virtual
Implements net::socket::tcp::SocketConnectionBase.
Definition at line 94 of file SocketConnection.h.
{
             enqueue(data.c_str(), data.size());
         }
References net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::enqueue().
getRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT > const InetAddress& net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::getRemoteAddress () const inline
Definition at line 105 of file SocketConnection.h.
{
             return remoteAddress;
         }
References net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::remoteAddress.
operator delete()
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::operator delete (void * socketConnection_v) inline
Definition at line 48 of file SocketConnection.h.
{
             free(socketConnection_v);
         }
operator new()
template<typename SocketReaderT , typename SocketWriterT > void* net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::operator new (size_t size) inline
Definition at line 42 of file SocketConnection.h.
{
             SocketConnection<SocketReader, SocketWriter>::lastAllocAddress = malloc(size);
             return SocketConnection<SocketReader, SocketWriter>::lastAllocAddress;
         }
setRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::setRemoteAddress (const InetAddress & remoteAddress) inline
Definition at line 109 of file SocketConnection.h.
{
             this->remoteAddress = remoteAddress;
         }
References net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::remoteAddress.
Referenced by net::socket::tcp::SocketListener< net::socket::tcp::legacy::SocketConnection >::acceptEvent(), and net::socket::tcp::SocketClient< legacy::SocketConnection >::connect().
unobserved()
template<typename SocketReaderT , typename SocketWriterT > void net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::unobserved () inline override private
Definition at line 81 of file SocketConnection.h.
{
             onDisconnect(this);
             if (isDynamic) {
                 delete this;
             }
         }
References net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::isDynamic, and net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::onDisconnect.
Member Data Documentation
isDynamic
template<typename SocketReaderT , typename SocketWriterT > bool net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::isDynamic private
Definition at line 118 of file SocketConnection.h.
Referenced by net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::unobserved().
lastAllocAddress
template<typename SocketReader , typename SocketWriter > void * net::socket::tcp::SocketConnection< SocketReader, SocketWriter >::lastAllocAddress = nullptr static private
Definition at line 119 of file SocketConnection.h.
onDestruct
template<typename SocketReaderT , typename SocketWriterT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::onDestruct private
Definition at line 115 of file SocketConnection.h.
Referenced by net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::~SocketConnection().
onDisconnect
template<typename SocketReaderT , typename SocketWriterT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::onDisconnect private
Definition at line 116 of file SocketConnection.h.
Referenced by net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::unobserved().
remoteAddress
template<typename SocketReaderT , typename SocketWriterT > InetAddress net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::remoteAddress {} private
Definition at line 114 of file SocketConnection.h.
Referenced by net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::getRemoteAddress(), and net::socket::tcp::SocketConnection< SocketReaderT, SocketWriterT >::setRemoteAddress().
The documentation for this class was generated from the following file:
net/socket/tcp/SocketConnection.h