snode.c: net::EventReceiver Class Reference
net::EventReceiver Class Reference abstract
#include <EventReceiver.h>
Classes
class TIMEOUT
Public Member Functions
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual void dispatchEvent ()=0
virtual void timeoutEvent ()
virtual bool continueImmediately ()=0
void enabled ()
void disabled ()
void suspended ()
void resumed ()
struct timeval getTimeout () const
struct timeval getLastTriggered ()
void triggered (struct timeval lastTriggered={time(nullptr), 0})
virtual void unobserved ()=0
Private Attributes
EventDispatcher & descriptorEventDispatcher
int fd = -1
bool _enabled = false
bool _suspended = false
long maxInactivity = LONG_MAX
const long initialTimeout
Friends
class EventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Detailed Description
Definition at line 45 of file EventReceiver.h.
Constructor & Destructor Documentation
EventReceiver() [1/2]
net::EventReceiver::EventReceiver (const EventReceiver &) private delete
EventReceiver() [2/2]
net::EventReceiver::EventReceiver (EventDispatcher & descriptorEventDispatcher, long timeout = TIMEOUT::DISABLE) explicit protected
Definition at line 29 of file EventReceiver.cpp.
         : descriptorEventDispatcher(descriptorEventDispatcher)
         , maxInactivity(timeout)
         , initialTimeout(timeout) {
     }
~EventReceiver()
virtual net::EventReceiver::~EventReceiver () protected virtual default
Member Function Documentation
continueImmediately()
virtual bool net::EventReceiver::continueImmediately () private pure virtual
Implemented in net::WriteEventReceiver, net::ReadEventReceiver, net::ExceptionalConditionEventReceiver, net::ConnectEventReceiver, and net::AcceptEventReceiver.
disable()
void net::EventReceiver::disable ()
Definition at line 41 of file EventReceiver.cpp.
{
         descriptorEventDispatcher.disable(this, fd);
         _enabled = false;
     }
References _enabled, descriptorEventDispatcher, net::EventDispatcher::disable(), and fd.
Referenced by net::AcceptEventReceiver::acceptTimeout(), net::ConnectEventReceiver::connectTimeout(), net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::SocketWriter< SocketT >::doWrite(), net::socket::stream::SocketListener< SocketConnectionT >::end(), net::pipe::PipeSource::eof(), net::ExceptionalConditionEventReceiver::outOfBandTimeout(), net::pipe::PipeSink::readEvent(), net::socket::stream::tls::TLSHandshake::readEvent(), net::socket::stream::SocketReader< SocketT >::readFromPeer(), net::ReadEventReceiver::readTimeout(), net::socket::stream::tls::TLSHandshake::readTimeout(), net::socket::stream::tls::TLSHandshake::TLSHandshake(), net::pipe::PipeSource::writeEvent(), net::socket::stream::tls::TLSHandshake::writeEvent(), net::WriteEventReceiver::writeTimeout(), and net::socket::stream::tls::TLSHandshake::writeTimeout().
disabled()
void net::EventReceiver::disabled () private
Definition at line 59 of file EventReceiver.cpp.
{
         this->fd = -1;
         ObservationCounter::observationCounter--;
     }
References fd, and net::ObservationCounter::observationCounter.
Referenced by net::EventDispatcher::disable().
dispatchEvent()
virtual void net::EventReceiver::dispatchEvent () private pure virtual
Implemented in net::WriteEventReceiver, net::ReadEventReceiver, net::ExceptionalConditionEventReceiver, net::ConnectEventReceiver, and net::AcceptEventReceiver.
enable()
void net::EventReceiver::enable (int fd)
Definition at line 35 of file EventReceiver.cpp.
{
         this->fd = fd;
         descriptorEventDispatcher.enable(this, fd);
         _enabled = true;
     }
References _enabled, descriptorEventDispatcher, net::EventDispatcher::enable(), and fd.
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connect(), net::socket::stream::SocketListener< SocketConnectionT >::listen(), net::pipe::PipeSink::PipeSink(), net::pipe::PipeSource::PipeSource(), and net::socket::stream::tls::TLSHandshake::TLSHandshake().
enabled()
void net::EventReceiver::enabled () private
Definition at line 54 of file EventReceiver.cpp.
{
         ObservationCounter::observationCounter++;
         lastTriggered = {time(nullptr), 0};
     }
References net::ObservationCounter::lastTriggered, net::ObservationCounter::observationCounter, and net::system::time().
Referenced by net::EventDispatcher::enable().
getLastTriggered()
timeval net::EventReceiver::getLastTriggered () private
Definition at line 100 of file EventReceiver.cpp.
{
         return lastTriggered;
     }
References net::ObservationCounter::lastTriggered.
getTimeout()
timeval net::EventReceiver::getTimeout () const private
Definition at line 89 of file EventReceiver.cpp.
{
         return {maxInactivity, 0};
     }
References maxInactivity.
isEnabled()
bool net::EventReceiver::isEnabled () const protected
Definition at line 64 of file EventReceiver.cpp.
{
         return _enabled;
     }
References _enabled.
Referenced by net::EventDispatcher::disable(), net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::EventDispatcher::enable(), net::socket::stream::SocketReader< SocketT >::shutdown(), and net::socket::stream::SocketWriter< SocketT >::shutdown().
isSuspended()
bool net::EventReceiver::isSuspended () const protected
Definition at line 77 of file EventReceiver.cpp.
{
         return _suspended;
     }
References _suspended.
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::tls::TLSHandshake::readTimeout(), net::EventDispatcher::resume(), net::pipe::PipeSource::send(), net::socket::stream::SocketWriter< SocketT >::sendToPeer(), net::socket::stream::SocketReader< SocketT >::shutdown(), net::socket::stream::SocketWriter< SocketT >::shutdown(), net::EventDispatcher::suspend(), and net::socket::stream::tls::TLSHandshake::writeTimeout().
operator=()
EventReceiver& net::EventReceiver::operator= (const EventReceiver &) private delete
resume()
void net::EventReceiver::resume ()
Definition at line 50 of file EventReceiver.cpp.
{
         descriptorEventDispatcher.resume(this, fd);
     }
References descriptorEventDispatcher, fd, and net::EventDispatcher::resume().
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::tls::TLSHandshake::readEvent(), net::pipe::PipeSource::send(), net::socket::stream::SocketWriter< SocketT >::sendToPeer(), net::socket::stream::tls::TLSHandshake::TLSHandshake(), and net::socket::stream::tls::TLSHandshake::writeEvent().
resumed()
void net::EventReceiver::resumed () private
Definition at line 72 of file EventReceiver.cpp.
{
         _suspended = false;
         lastTriggered = {time(nullptr), 0};
     }
References _suspended, net::ObservationCounter::lastTriggered, and net::system::time().
Referenced by net::EventDispatcher::resume().
setTimeout()
void net::EventReceiver::setTimeout (long timeout) protected
Definition at line 81 of file EventReceiver.cpp.
{
         if (timeout != TIMEOUT::DEFAULT) {
             this->maxInactivity = timeout;
         } else {
             this->maxInactivity = initialTimeout;
         }
     }
References net::EventReceiver::TIMEOUT::DEFAULT, initialTimeout, and maxInactivity.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::setTimeout().
suspend()
void net::EventReceiver::suspend ()
Definition at line 46 of file EventReceiver.cpp.
{
         descriptorEventDispatcher.suspend(this, fd);
     }
References descriptorEventDispatcher, fd, and net::EventDispatcher::suspend().
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::SocketWriter< SocketT >::doWrite(), net::pipe::PipeSource::eof(), net::pipe::PipeSource::PipeSource(), net::pipe::PipeSink::readEvent(), net::socket::stream::tls::TLSHandshake::readEvent(), net::socket::stream::tls::TLSHandshake::readTimeout(), net::socket::stream::tls::TLSHandshake::TLSHandshake(), net::pipe::PipeSource::writeEvent(), net::socket::stream::tls::TLSHandshake::writeEvent(), and net::socket::stream::tls::TLSHandshake::writeTimeout().
suspended()
void net::EventReceiver::suspended () private
Definition at line 68 of file EventReceiver.cpp.
{
         _suspended = true;
     }
References _suspended.
Referenced by net::EventDispatcher::suspend().
timeoutEvent()
void net::EventReceiver::timeoutEvent () private virtual
Reimplemented in net::WriteEventReceiver, net::ReadEventReceiver, net::ExceptionalConditionEventReceiver, net::ConnectEventReceiver, and net::AcceptEventReceiver.
Definition at line 93 of file EventReceiver.cpp.
{
     }
triggered()
void net::EventReceiver::triggered (struct timeval lastTriggered = {time(nullptr), 0}) private
Definition at line 96 of file EventReceiver.cpp.
{
         this->lastTriggered = lastTriggered;
     }
References net::ObservationCounter::lastTriggered.
unobserved()
virtual void net::EventReceiver::unobserved () private pure virtual
Implemented in net::socket::stream::tls::TLSHandshake, net::socket::stream::SocketListener< SocketConnectionT >, net::socket::stream::SocketListener< stream::legacy::SocketConnection< SocketT > >, net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >, net::socket::stream::SocketConnector< SocketConnectionT >, net::socket::stream::SocketConnector< stream::legacy::SocketConnection< SocketT > >, net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >, net::socket::stream::SocketConnectionT< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, net::socket::stream::SocketConnectionT< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >, net::pipe::PipeSource, net::pipe::PipeSink, and FileReader.
Friends And Related Function Documentation
EventDispatcher
friend class EventDispatcher friend
Definition at line 102 of file EventReceiver.h.
Member Data Documentation
_enabled
bool net::EventReceiver::_enabled = false private
Definition at line 96 of file EventReceiver.h.
Referenced by disable(), enable(), and isEnabled().
_suspended
bool net::EventReceiver::_suspended = false private
Definition at line 97 of file EventReceiver.h.
Referenced by isSuspended(), resumed(), and suspended().
descriptorEventDispatcher
EventDispatcher& net::EventReceiver::descriptorEventDispatcher private
Definition at line 92 of file EventReceiver.h.
Referenced by disable(), enable(), resume(), and suspend().
fd
int net::EventReceiver::fd = -1 private
Definition at line 94 of file EventReceiver.h.
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), disable(), disabled(), enable(), resume(), and suspend().
initialTimeout
const long net::EventReceiver::initialTimeout private
Definition at line 100 of file EventReceiver.h.
Referenced by setTimeout().
maxInactivity
long net::EventReceiver::maxInactivity = LONG_MAX private
Definition at line 99 of file EventReceiver.h.
Referenced by getTimeout(), and setTimeout().
The documentation for this class was generated from the following files:
net/EventReceiver.h
net/EventReceiver.cpp