snode.c: web::ws::server::SubProtocolSelector Class Reference
web::ws::server::SubProtocolSelector Class Reference
#include <SubProtocolSelector.h>
Public Member Functions
web::ws::SubProtocol * select (const std::string &subProtocolName, web::http::server::Request &req, web::http::server::Response &res)
void destroy (web::ws::SubProtocol *subProtocol)
Public Member Functions inherited from web::ws::SubProtocolSelector
void loadSubProtocols ()
void loadSubProtocol (const std::string &filePath)
void loadSubProtocols (const std::string &directoryPath)
void registerSubProtocol (SubProtocolInterface *subProtocolPluginInterface, void *handle=nullptr)
void unloadSubProtocols ()
Static Public Member Functions
static std::shared_ptr< SubProtocolSelector > instance ()
Static Private Attributes
static std::shared_ptr< SubProtocolSelector > subProtocolSelector = nullptr
Additional Inherited Members
Protected Member Functions inherited from web::ws::SubProtocolSelector
SubProtocolSelector ()=default
virtual ~SubProtocolSelector ()=default
SubProtocolSelector (const SubProtocolSelector &)=delete
SubProtocolSelector & operator= (const SubProtocolSelector &)=delete
Protected Attributes inherited from web::ws::SubProtocolSelector
std::map< std::string, SubProtocolPlugin > serverSubprotocols
std::map< std::string, SubProtocolPlugin > clientSubprotocols
Detailed Description
Definition at line 38 of file SubProtocolSelector.h.
Member Function Documentation
destroy()
void web::ws::server::SubProtocolSelector::destroy (web::ws::SubProtocol * subProtocol)
Definition at line 64 of file SubProtocolSelector.cpp.
{
         if (serverSubprotocols.contains(subProtocol->getName())) {
             web::ws::SubProtocolInterface* subProtocolInterface =
                 static_cast<SubProtocolInterface*>(serverSubprotocols.find(subProtocol->getName())->second.subprotocolPluginInterface);
             subProtocolInterface->destroy(subProtocol);
         }
     }
References web::ws::SubProtocolInterface::destroy(), web::ws::SubProtocol::getName(), and web::ws::SubProtocolSelector::serverSubprotocols.
instance()
std::shared_ptr< SubProtocolSelector > web::ws::server::SubProtocolSelector::instance () static
Definition at line 36 of file SubProtocolSelector.cpp.
{
         if (subProtocolSelector == nullptr) {
             subProtocolSelector = std::make_shared<SubProtocolSelector>();
         }
         return subProtocolSelector;
     }
References subProtocolSelector.
Referenced by web::ws::server::SocketContext::create(), web::ws::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory(), web::ws::server::SocketContext::~SocketContext(), and web::ws::server::SocketContextUpgradeFactory::~SocketContextUpgradeFactory().
select()
web::ws::SubProtocol * web::ws::server::SubProtocolSelector::select (const std::string & subProtocolName, web::http::server::Request & req, web::http::server::Response & res)
Definition at line 45 of file SubProtocolSelector.cpp.
{
         web::ws::server::SubProtocol* subProtocol = nullptr;
         if (serverSubprotocols.contains(subProtocolName)) {
             SubProtocolInterface* subProtocolInterface =
                 static_cast<SubProtocolInterface*>(serverSubprotocols.find(subProtocolName)->second.subprotocolPluginInterface);
             if (subProtocolInterface != nullptr) {
                 subProtocol = static_cast<web::ws::server::SubProtocol*>(subProtocolInterface->create(req, res));
                 if (subProtocol != nullptr) {
                     subProtocol->setClients(subProtocolInterface->getClients());
                 }
             }
         }
         return subProtocol;
     }
References web::ws::SubProtocolInterface::create(), web::ws::server::SubProtocolInterface::getClients(), web::ws::SubProtocolSelector::serverSubprotocols, and web::ws::server::SubProtocol::setClients().
Member Data Documentation
subProtocolSelector
std::shared_ptr< SubProtocolSelector > web::ws::server::SubProtocolSelector::subProtocolSelector = nullptr static private
Definition at line 47 of file SubProtocolSelector.h.
Referenced by instance().
The documentation for this class was generated from the following files:
web/ws/server/SubProtocolSelector.h
web/ws/server/SubProtocolSelector.cpp