snode.c: web::ws::SocketContext Class Reference
web::ws::SocketContext Class Reference
#include <SocketContext.h>
Public Member Functions
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void replyPong (const char *reason=nullptr, std::size_t reasonLength=0)
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketProtocol (const SocketContextFactory &socketProtocolFactory)
void setTimeout (int timeout)
Public Member Functions inherited from web::ws::Receiver
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Public Member Functions inherited from web::ws::Transmitter
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Protected Member Functions
SocketContext (net::socket::stream::SocketConnectionBase *socketConnection, web::ws::SubProtocol *subProtocol, bool masking)
SocketContext ()=delete
SocketContext (const SocketContext &)=delete
SocketContext & operator= (const SocketContext &)=delete
virtual ~SocketContext ()=default
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnectionBase *socketConnection)
Protected Member Functions inherited from web::ws::Transmitter
Transmitter (bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Protected Attributes
web::ws::SubProtocol * subProtocol
Private Member Functions
void close (const char *reason, std::size_t reasonLength)
void onMessageStart (int opCode) override
void onFrameReceived (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onPongReceived ()
void onMessageError (uint16_t errnum) override
std::size_t readFrameData (char *junk, std::size_t junkLen) override
void onProtocolConnected () override
void onProtocolDisconnected () override
void sendFrameData (uint8_t data) override
void sendFrameData (uint16_t data) override
void sendFrameData (uint32_t data) override
void sendFrameData (uint64_t data) override
void sendFrameData (const char *frame, uint64_t frameLength) override
void onReceiveFromPeer () override
void onReadError (int errnum) override
void onWriteError (int errnum) override
Private Attributes
bool closeReceived = false
bool closeSent = false
bool pingReceived = false
bool pongReceived = false
std::string pongCloseData
Detailed Description
Definition at line 44 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext() [1/3]
web::ws::SocketContext::SocketContext (net::socket::stream::SocketConnectionBase * socketConnection, web::ws::SubProtocol * subProtocol, bool masking) protected
Definition at line 35 of file SocketContext.cpp.
         : net::socket::stream::SocketContext(socketConnection)
         , Transmitter(masking)
         , subProtocol(subProtocol) {
         subProtocol->setWSContext(this);
     }
References web::ws::SubProtocol::setWSContext(), and subProtocol.
SocketContext() [2/3]
web::ws::SocketContext::SocketContext () protected delete
SocketContext() [3/3]
web::ws::SocketContext::SocketContext (const SocketContext &) protected delete
~SocketContext()
virtual web::ws::SocketContext::~SocketContext () protected virtual default
Reimplemented from net::socket::stream::SocketContext.
Reimplemented in web::ws::server::SocketContext.
Member Function Documentation
close() [1/2]
void web::ws::SocketContext::close (const char * reason, std::size_t reasonLength) private
Definition at line 169 of file SocketContext.cpp.
{
         sendMessage(8, message, messageLength);
     }
References sendMessage().
close() [2/2]
void web::ws::SocketContext::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 145 of file SocketContext.cpp.
{
         char* closePayload = const_cast<char*>(reason);
         std::size_t closePayloadLength = reasonLength;
         if (statusCode != 0) {
             closePayload = new char[reasonLength + 2];
             *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
             closePayloadLength += 2;
             if (reasonLength > 0) {
                 memcpy(closePayload + 2, reason, reasonLength);
             }
         }
         close(closePayload, closePayloadLength);
         if (statusCode != 0) {
             delete[] closePayload;
         }
         setTimeout(CLOSE_SOCKET_TIMEOUT);
         closeSent = true;
     }
References net::socket::stream::SocketContext::close(), CLOSE_SOCKET_TIMEOUT, closeSent, and net::socket::stream::SocketContext::setTimeout().
Referenced by web::ws::SubProtocol::sendClose().
getLocalAddressAsString()
std::string web::ws::SocketContext::getLocalAddressAsString () const
Definition at line 229 of file SocketContext.cpp.
{
         return net::socket::stream::SocketContext::getLocalAddressAsString();
     }
References net::socket::stream::SocketContext::getLocalAddressAsString().
Referenced by web::ws::SubProtocol::getLocalAddressAsString().
getRemoteAddressAsString()
std::string web::ws::SocketContext::getRemoteAddressAsString () const
Definition at line 233 of file SocketContext.cpp.
{
         return net::socket::stream::SocketContext::getRemoteAddressAsString();
     }
References net::socket::stream::SocketContext::getRemoteAddressAsString().
Referenced by web::ws::SubProtocol::getRemoteAddressAsString().
onFrameReceived()
void web::ws::SocketContext::onFrameReceived (const char * junk, uint64_t junkLen) override private virtual
Implements web::ws::Receiver.
Definition at line 78 of file SocketContext.cpp.
{
         if (!closeReceived && !pingReceived && !pongReceived) {
             std::size_t junkOffset = 0;
             do {
                 std::size_t sendJunkLen = (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                 subProtocol->onMessageData(junk + junkOffset, sendJunkLen);
                 junkOffset += sendJunkLen;
             } while (junkLen - junkOffset > 0);
         } else {
             pongCloseData += std::string(junk, static_cast<std::size_t>(junkLen));
         }
     }
References closeReceived, web::ws::SubProtocol::onMessageData(), pingReceived, pongCloseData, pongReceived, and subProtocol.
onMessageEnd()
void web::ws::SocketContext::onMessageEnd () override private virtual
Implements web::ws::Receiver.
Definition at line 92 of file SocketContext.cpp.
{
         if (closeReceived) {
             closeReceived = false;
             if (closeSent) { // active close
                 closeSent = false;
                 VLOG(0) << "Close confirmed from peer";
             } else { // passive close
                 VLOG(0) << "Close request received - replying with close";
                 close(pongCloseData.data(), pongCloseData.length());
                 pongCloseData.clear();
             }
             close();
         } else if (pingReceived) {
             pingReceived = false;
             replyPong(pongCloseData.data(), pongCloseData.length());
             pongCloseData.clear();
         } else if (pongReceived) {
             pongReceived = false;
             subProtocol->onPongReceived();
         } else {
             subProtocol->onMessageEnd();
         }
     }
References net::socket::stream::SocketContext::close(), closeReceived, closeSent, web::ws::SubProtocol::onMessageEnd(), web::ws::SubProtocol::onPongReceived(), pingReceived, pongCloseData, pongReceived, replyPong(), and subProtocol.
onMessageError()
void web::ws::SocketContext::onMessageError (uint16_t errnum) override private virtual
Implements web::ws::Receiver.
Definition at line 120 of file SocketContext.cpp.
{
         subProtocol->onMessageError(errnum);
         close(errnum);
     }
References net::socket::stream::SocketContext::close(), web::ws::SubProtocol::onMessageError(), and subProtocol.
onMessageStart()
void web::ws::SocketContext::onMessageStart (int opCode) override private virtual
Implements web::ws::Receiver.
Definition at line 60 of file SocketContext.cpp.
{
         switch (opCode) {
             case 0x08:
                 closeReceived = true;
                 break;
             case 0x09:
                 pingReceived = true;
                 VLOG(0) << "Ping received";
                 break;
             case 0x0A:
                 pongReceived = true;
                 break;
             default:
                 subProtocol->onMessageStart(opCode);
                 break;
         }
     }
References closeReceived, web::ws::SubProtocol::onMessageStart(), web::ws::Receiver::opCode, pingReceived, pongReceived, and subProtocol.
onPongReceived()
void web::ws::SocketContext::onPongReceived () private
Definition at line 116 of file SocketContext.cpp.
{
         subProtocol->onPongReceived();
     }
References web::ws::SubProtocol::onPongReceived(), and subProtocol.
onProtocolConnected()
void web::ws::SocketContext::onProtocolConnected () override private virtual
Reimplemented from net::socket::stream::SocketContext.
Definition at line 129 of file SocketContext.cpp.
{
         subProtocol->onProtocolConnected();
     }
References web::ws::SubProtocol::onProtocolConnected(), and subProtocol.
onProtocolDisconnected()
void web::ws::SocketContext::onProtocolDisconnected () override private virtual
Reimplemented from net::socket::stream::SocketContext.
Definition at line 133 of file SocketContext.cpp.
{
         subProtocol->onProtocolDisconnected();
     }
References web::ws::SubProtocol::onProtocolDisconnected(), and subProtocol.
onReadError()
void web::ws::SocketContext::onReadError (int errnum) override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 217 of file SocketContext.cpp.
{
         if (errnum != 0) {
             PLOG(INFO) << "OnReadError:";
         }
     }
onReceiveFromPeer()
void web::ws::SocketContext::onReceiveFromPeer () override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 213 of file SocketContext.cpp.
{
         Receiver::receive();
     }
References web::ws::Receiver::receive().
onWriteError()
void web::ws::SocketContext::onWriteError (int errnum) override private virtual
Implements net::socket::stream::SocketContext.
Definition at line 223 of file SocketContext.cpp.
{
         if (errnum != 0) {
             PLOG(INFO) << "OnWriteError:";
         }
     }
operator=()
SocketContext& web::ws::SocketContext::operator= (const SocketContext &) protected delete
readFrameData()
std::size_t web::ws::SocketContext::readFrameData (char * junk, std::size_t junkLen) override private virtual
Implements web::ws::Receiver.
Definition at line 125 of file SocketContext.cpp.
{
         return readFromPeer(junk, junkLen);
     }
References net::socket::stream::SocketContext::readFromPeer().
replyPong()
void web::ws::SocketContext::replyPong (const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 141 of file SocketContext.cpp.
{
         sendMessage(10, reason, reasonLength);
     }
References sendMessage().
Referenced by onMessageEnd().
sendFrameData() [1/5]
void web::ws::SocketContext::sendFrameData (const char * frame, uint64_t frameLength) override private virtual
Implements web::ws::Transmitter.
Definition at line 200 of file SocketContext.cpp.
{
         if (!closeSent) {
             std::size_t frameOffset = 0;
             do {
                 std::size_t sendJunkLen =
                     (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                 sendToPeer(frame + frameOffset, sendJunkLen);
                 frameOffset += sendJunkLen;
             } while (frameLength - frameOffset > 0);
         }
     }
References closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [2/5]
void web::ws::SocketContext::sendFrameData (uint16_t data) override private virtual
Implements web::ws::Transmitter.
Definition at line 179 of file SocketContext.cpp.
{
         if (!closeSent) {
             uint16_t sendData = htobe16(data);
             sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint16_t));
         }
     }
References closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [3/5]
void web::ws::SocketContext::sendFrameData (uint32_t data) override private virtual
Implements web::ws::Transmitter.
Definition at line 186 of file SocketContext.cpp.
{
         if (!closeSent) {
             uint32_t sendData = htobe32(data);
             sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint32_t));
         }
     }
References closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [4/5]
void web::ws::SocketContext::sendFrameData (uint64_t data) override private virtual
Implements web::ws::Transmitter.
Definition at line 193 of file SocketContext.cpp.
{
         if (!closeSent) {
             uint64_t sendData = htobe64(data);
             sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint64_t));
         }
     }
References closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendFrameData() [5/5]
void web::ws::SocketContext::sendFrameData (uint8_t data) override private virtual
Implements web::ws::Transmitter.
Definition at line 173 of file SocketContext.cpp.
{
         if (!closeSent) {
             sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
         }
     }
References closeSent, and net::socket::stream::SocketContext::sendToPeer().
sendMessage()
void web::ws::SocketContext::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength)
Definition at line 56 of file SocketContext.cpp.
{
         Transmitter::sendMessage(opCode, message, messageLength);
     }
References web::ws::Receiver::opCode, and web::ws::Transmitter::sendMessage().
Referenced by close(), replyPong(), web::ws::SubProtocol::sendMessage(), and sendPing().
sendMessageEnd()
void web::ws::SocketContext::sendMessageEnd (const char * message, std::size_t messageLength)
Definition at line 52 of file SocketContext.cpp.
{
         Transmitter::sendMessageEnd(message, messageLength);
     }
References web::ws::Transmitter::sendMessageEnd().
Referenced by web::ws::SubProtocol::sendMessageEnd().
sendMessageFrame()
void web::ws::SocketContext::sendMessageFrame (const char * message, std::size_t messageLength)
Definition at line 48 of file SocketContext.cpp.
{
         Transmitter::sendMessageFrame(message, messageLength);
     }
References web::ws::Transmitter::sendMessageFrame().
Referenced by web::ws::SubProtocol::sendMessageFrame().
sendMessageStart()
void web::ws::SocketContext::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength)
Definition at line 44 of file SocketContext.cpp.
{
         Transmitter::sendMessageStart(opCode, message, messageLength);
     }
References web::ws::Receiver::opCode, and web::ws::Transmitter::sendMessageStart().
Referenced by web::ws::SubProtocol::sendMessageStart().
sendPing()
void web::ws::SocketContext::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 137 of file SocketContext.cpp.
{
         sendMessage(9, reason, reasonLength);
     }
References sendMessage().
Referenced by web::ws::SubProtocol::sendPing().
Member Data Documentation
closeReceived
bool web::ws::SocketContext::closeReceived = false private
Definition at line 103 of file SocketContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
closeSent
bool web::ws::SocketContext::closeSent = false private
Definition at line 104 of file SocketContext.h.
Referenced by close(), onMessageEnd(), and sendFrameData().
pingReceived
bool web::ws::SocketContext::pingReceived = false private
Definition at line 106 of file SocketContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
pongCloseData
std::string web::ws::SocketContext::pongCloseData private
Definition at line 109 of file SocketContext.h.
Referenced by onFrameReceived(), and onMessageEnd().
pongReceived
bool web::ws::SocketContext::pongReceived = false private
Definition at line 107 of file SocketContext.h.
Referenced by onFrameReceived(), onMessageEnd(), and onMessageStart().
subProtocol
web::ws::SubProtocol* web::ws::SocketContext::subProtocol protected
Definition at line 73 of file SocketContext.h.
Referenced by web::ws::server::SocketContext::create(), onFrameReceived(), onMessageEnd(), onMessageError(), onMessageStart(), onPongReceived(), onProtocolConnected(), onProtocolDisconnected(), SocketContext(), and web::ws::server::SocketContext::~SocketContext().
The documentation for this class was generated from the following files:
web/ws/SocketContext.h
web/ws/SocketContext.cpp