snode.c: web::http::client::ResponseParser Class Reference
web::http::client::ResponseParser Class Reference
#include <ResponseParser.h>
Public Member Functions
ResponseParser (net::socket::stream::SocketContext *socketContext, const std::function< void(void)> &onStart, const std::function< void(const std::string &, const std::string &, const std::string &)> &onResponse, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, web::http::CookieOptions > &)> &onHeader, const std::function< void(char *, std::size_t)> &onContent, const std::function< void(ResponseParser &)> &onParsed, const std::function< void(int, const std::string &)> &onError)
void begin () override
enum Parser::ParserState parseStartLine (const std::string &line) override
enum Parser::ParserState parseHeader () override
enum Parser::ParserState parseContent (char *content, std::size_t size) override
enum Parser::ParserState parsingError (int code, const std::string &reason) override
void reset () override
Public Member Functions inherited from web::http::Parser
Parser (net::socket::stream::SocketContext *socketContext, const enum HTTPCompliance &compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()=default
void parse ()
Protected Member Functions
void parsingFinished ()
Protected Attributes
std::string httpVersion
std::string statusCode
std::string reason
std::map< std::string, CookieOptions > cookies
std::function< void(void)> onStart
std::function< void(const std::string &, const std::string &, const std::string &)> onResponse
std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, web::http::CookieOptions > &)> onHeader
std::function< void(char *, std::size_t)> onContent
std::function< void(ResponseParser &)> onParsed
std::function< void(int, const std::string &)> onError
Protected Attributes inherited from web::http::Parser
enum web::http::Parser::HTTPCompliance hTTPCompliance
enum web::http::Parser::ParserState parserState = ParserState::BEGIN
char * content = nullptr
std::size_t contentLength = 0
std::map< std::string, std::string > headers
Additional Inherited Members
Protected Types inherited from web::http::Parser
enum class HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum class ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Static Protected Attributes inherited from web::http::Parser
static std::regex httpVersionRegex
Detailed Description
Definition at line 40 of file ResponseParser.h.
Constructor & Destructor Documentation
ResponseParser()
web::http::client::ResponseParser::ResponseParser (net::socket::stream::SocketContext * socketContext, const std::function< void(void)> & onStart, const std::function< void(const std::string &, const std::string &, const std::string &)> & onResponse, const std::function< void(const std::map< std::string, std::string > &, const std::map< std::string, web::http::CookieOptions > &)> & onHeader, const std::function< void(char *, std::size_t)> & onContent, const std::function< void(ResponseParser &)> & onParsed, const std::function< void(int, const std::string &)> & onError)
Definition at line 35 of file ResponseParser.cpp.
         : Parser(socketContext)
         , onStart(onStart)
         , onResponse(onResponse)
         , onHeader(onHeader)
         , onContent(onContent)
         , onParsed(onParsed)
         , onError(onError) {
     }
Member Function Documentation
begin()
void web::http::client::ResponseParser::begin () override virtual
Implements web::http::Parser.
Definition at line 60 of file ResponseParser.cpp.
{
         onStart();
     }
References onStart.
parseContent()
enum Parser::ParserState web::http::client::ResponseParser::parseContent (char * content, std::size_t size) override virtual
Implements web::http::Parser.
Definition at line 60 of file ResponseParser.cpp.
{
         onContent(content, size);
         parsingFinished();
         return ParserState::BEGIN;
     }
parseHeader()
enum Parser::ParserState web::http::client::ResponseParser::parseHeader () override virtual
Implements web::http::Parser.
Definition at line 60 of file ResponseParser.cpp.
{
         for (const auto& [field, value] : Parser::headers) {
             if (field != "set-cookie") {
                 if (field == "content-length") {
                     Parser::contentLength = static_cast<std::size_t>(std::stoi(value));
                 }
             } else {
                 std::string cookiesLine = value;
                 while (!cookiesLine.empty()) {
                     std::string cookieLine;
                     std::tie(cookieLine, cookiesLine) = httputils::str_split(cookiesLine, ',');
                     std::string cookieOptions;
                     std::string cookie;
                     std::tie(cookie, cookieOptions) = httputils::str_split(cookieLine, ';');
                     std::string name;
                     std::string value;
                     std::tie(name, value) = httputils::str_split(cookie, '=');
                     httputils::str_trimm(name);
                     httputils::str_trimm(value);
                     std::map<std::string, CookieOptions>::iterator cookieElement;
                     bool inserted;
                     std::tie(cookieElement, inserted) = cookies.insert({name, CookieOptions(value)});
                     while (!cookieOptions.empty()) {
                         std::string option;
                         std::tie(option, cookieOptions) = httputils::str_split(cookieOptions, ';');
                         std::string optionName;
                         std::string optionValue;
                         std::tie(optionName, optionValue) = httputils::str_split(option, '=');
                         httputils::str_trimm(optionName);
                         httputils::str_trimm(optionValue);
                         cookieElement->second.setOption(optionName, optionValue);
                     }
                 }
             }
         }
         Parser::headers.erase("set-cookie");
         onHeader(Parser::headers, cookies);
         enum Parser::ParserState parserState = Parser::ParserState::BODY;
         if (contentLength == 0) {
             parsingFinished();
             parserState = ParserState::BEGIN;
         }
         return parserState;
     }
parseStartLine()
enum Parser::ParserState web::http::client::ResponseParser::parseStartLine (const std::string & line) override virtual
Implements web::http::Parser.
Definition at line 60 of file ResponseParser.cpp.
{
         enum Parser::ParserState parserState = Parser::ParserState::HEADER;
         if (!line.empty()) {
             std::string remaining;
             std::tie(httpVersion, remaining) = httputils::str_split(line, ' ');
             std::smatch httpVersionMatch;
             if (!std::regex_match(httpVersion, httpVersionMatch, httpVersionRegex)) {
                 parserState = parsingError(400, "Wrong protocol version");
             } else {
                 std::tie(statusCode, reason) = httputils::str_split(remaining, ' ');
                 if (StatusCode::contains(std::stoi(statusCode))) {
                     if (!reason.empty()) {
                         onResponse(httpVersion, statusCode, reason);
                     } else {
                         parserState = parsingError(400, "No reason phrase");
                     }
                 } else {
                     parserState = parsingError(400, "Unknown status code");
                 }
             }
         } else {
             parserState = parsingError(400, "Response line empty");
         }
         return parserState;
     }
parsingError()
enum Parser::ParserState web::http::client::ResponseParser::parsingError (int code, const std::string & reason) override virtual
Implements web::http::Parser.
Definition at line 60 of file ResponseParser.cpp.
{
         onError(code, reason);
         return ParserState::ERROR;
     }
parsingFinished()
void web::http::client::ResponseParser::parsingFinished () protected
Definition at line 162 of file ResponseParser.cpp.
{
         onParsed(*this);
     }
References onParsed.
reset()
void web::http::client::ResponseParser::reset () override virtual
Reimplemented from web::http::Parser.
Definition at line 52 of file ResponseParser.cpp.
{
         Parser::reset();
         httpVersion.clear();
         statusCode.clear();
         reason.clear();
         cookies.clear();
     }
References cookies, httpVersion, reason, web::http::Parser::reset(), and statusCode.
Member Data Documentation
cookies
std::map<std::string, CookieOptions> web::http::client::ResponseParser::cookies protected
Definition at line 67 of file ResponseParser.h.
Referenced by reset().
httpVersion
std::string web::http::client::ResponseParser::httpVersion protected
Definition at line 64 of file ResponseParser.h.
Referenced by reset().
onContent
std::function<void(char*, std::size_t)> web::http::client::ResponseParser::onContent protected
Definition at line 72 of file ResponseParser.h.
onError
std::function<void(int, const std::string&)> web::http::client::ResponseParser::onError protected
Definition at line 74 of file ResponseParser.h.
onHeader
std::function<void(const std::map<std::string, std::string>&, const std::map<std::string, web::http::CookieOptions>&)> web::http::client::ResponseParser::onHeader protected
Definition at line 71 of file ResponseParser.h.
onParsed
std::function<void(ResponseParser&)> web::http::client::ResponseParser::onParsed protected
Definition at line 73 of file ResponseParser.h.
Referenced by parsingFinished().
onResponse
std::function<void(const std::string&, const std::string&, const std::string&)> web::http::client::ResponseParser::onResponse protected
Definition at line 70 of file ResponseParser.h.
onStart
std::function<void(void)> web::http::client::ResponseParser::onStart protected
Definition at line 69 of file ResponseParser.h.
Referenced by begin().
reason
std::string web::http::client::ResponseParser::reason protected
Definition at line 66 of file ResponseParser.h.
Referenced by reset().
statusCode
std::string web::http::client::ResponseParser::statusCode protected
Definition at line 65 of file ResponseParser.h.
Referenced by reset().
The documentation for this class was generated from the following files:
web/http/client/ResponseParser.h
web/http/client/ResponseParser.cpp