snode.c: http::client::ClientContext Class Reference
http::client::ClientContext Class Reference
#include <ClientContext.h>
Public Types
using SocketConnection = net::socket::stream::SocketConnectionBase
Public Member Functions
ClientContext (SocketConnection *socketConnection, const std::function< void(Response &)> &onResponse, const std::function< void(int status, const std::string &reason)> &onError)
void receiveResponseData (const char *junk, std::size_t junkLen)
void sendRequestData (const char *buf, std::size_t len)
Request & getRequest ()
void terminateConnection ()
void requestCompleted ()
Protected Attributes
SocketConnection * socketConnection
Request request
Response response
Private Attributes
ResponseParser parser
Detailed Description
Definition at line 40 of file ClientContext.h.
Member Typedef Documentation
SocketConnection
using http::client::ClientContext::SocketConnection = net::socket::stream::SocketConnectionBase
Definition at line 42 of file ClientContext.h.
Constructor & Destructor Documentation
ClientContext()
http::client::ClientContext::ClientContext (SocketConnection * socketConnection, const std::function< void(Response &)> & onResponse, const std::function< void(int status, const std::string &reason)> & onError)
Definition at line 32 of file ClientContext.cpp.
         : socketConnection(socketConnection)
         , request(this)
         , parser(
               [](void) -> void {
               },
               [this](const std::string& httpVersion, const std::string& statusCode, const std::string& reason) -> void {
                   response.httpVersion = httpVersion;
                   response.statusCode = statusCode;
                   response.reason = reason;
               },
               [this](const std::map<std::string, std::string>& headers, const std::map<std::string, http::CookieOptions>& cookies) -> void {
                   response.headers = &headers;
                   response.cookies = &cookies;
               },
               [this](char* content, std::size_t contentLength) -> void {
                   response.body = content;
                   response.contentLength = contentLength;
               },
               [this, onResponse](http::client::ResponseParser& parser) -> void {
                   onResponse(response);
                   parser.reset();
                   request.reset();
                   response.reset();
               },
               [onError](int status, const std::string& reason) -> void {
                   onError(status, reason);
               }) {
     }
Member Function Documentation
getRequest()
Request & http::client::ClientContext::getRequest ()
Definition at line 75 of file ClientContext.cpp.
{
         return request;
     }
receiveResponseData()
void http::client::ClientContext::receiveResponseData (const char * junk, std::size_t junkLen)
Definition at line 67 of file ClientContext.cpp.
{
         parser.parse(junk, junkLen);
     }
requestCompleted()
void http::client::ClientContext::requestCompleted ()
Definition at line 64 of file ClientContext.cpp.
{
     }
Referenced by http::client::Request::enqueue().
sendRequestData()
void http::client::ClientContext::sendRequestData (const char * buf, std::size_t len)
Definition at line 71 of file ClientContext.cpp.
{
         socketConnection->enqueue(buf, len);
     }
References net::socket::stream::SocketConnectionBase::enqueue().
Referenced by http::client::Request::enqueue().
terminateConnection()
void http::client::ClientContext::terminateConnection ()
Definition at line 80 of file ClientContext.cpp.
{
         socketConnection->close();
     }
References net::socket::stream::SocketConnectionBase::close().
Referenced by http::client::Request::enqueue(), and http::client::Request::error().
Member Data Documentation
parser
ResponseParser http::client::ClientContext::parser private
Definition at line 64 of file ClientContext.h.
request
Request http::client::ClientContext::request protected
Definition at line 60 of file ClientContext.h.
response
Response http::client::ClientContext::response protected
Definition at line 61 of file ClientContext.h.
socketConnection
SocketConnection* http::client::ClientContext::socketConnection protected
Definition at line 58 of file ClientContext.h.
The documentation for this class was generated from the following files:
http/client/ClientContext.h
http/client/ClientContext.cpp