snode.c: net::socket::tcp::SocketServer< SocketListenerT > Class Template Reference
net::socket::tcp::SocketServer< SocketListenerT > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketListener = SocketListenerT
using SocketConnection = typename SocketListener::SocketConnection
Public Member Functions
void * operator new (size_t size)
void operator delete (void *socketServer_v)
SocketServer (const std::function< void(SocketConnection *socketConnection)> &onConstruct, const std::function< void(SocketConnection *socketConnection)> &onDestruct, const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options={{}})
SocketServer ()=delete
SocketServer (const SocketServer &)=delete
SocketServer & operator= (const SocketServer &)=delete
virtual ~SocketServer ()=default
void listen (const InetAddress &localAddress, int backlog, const std::function< void(int err)> &onError)
void listen (unsigned short port, int backlog, const std::function< void(int err)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, int backlog, const std::function< void(int err)> &onError)
Protected Attributes
std::map< std::string, std::any > options
bool isDynamic
Static Protected Attributes
static void * lastAllocAddress = nullptr
Private Attributes
std::function< void(SocketConnection *socketConnection)> onConstruct
std::function< void(SocketConnection *socketConnection)> onDestruct
std::function< void(SocketConnection *socketConnection)> onConnect
std::function< void(SocketConnection *socketConnection)> onDisconnect
std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> onRead
std::function< void(SocketConnection *socketConnection, int errnum)> onReadError
std::function< void(SocketConnection *socketConnection, int errnum)> onWriteError
Detailed Description
template<typename SocketListenerT>
class net::socket::tcp::SocketServer< SocketListenerT >
Definition at line 38 of file SocketServer.h.
Member Typedef Documentation
SocketConnection
template<typename SocketListenerT > using net::socket::tcp::SocketServer< SocketListenerT >::SocketConnection = typename SocketListener::SocketConnection
Definition at line 41 of file SocketServer.h.
SocketListener
template<typename SocketListenerT > using net::socket::tcp::SocketServer< SocketListenerT >::SocketListener = SocketListenerT
Definition at line 40 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer() [1/3]
template<typename SocketListenerT > net::socket::tcp::SocketServer< SocketListenerT >::SocketServer (const std::function< void(SocketConnection *socketConnection)> & onConstruct, const std::function< void(SocketConnection *socketConnection)> & onDestruct, const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 53 of file SocketServer.h.
                                                                 {{}})
             : onConstruct(onConstruct)
             , onDestruct(onDestruct)
             , onConnect(onConnect)
             , onDisconnect(onDisconnect)
             , onRead(onRead)
             , onReadError(onReadError)
             , onWriteError(onWriteError)
             , options(options)
             , isDynamic(this == SocketServer::lastAllocAddress) {
         }
SocketServer() [2/3]
template<typename SocketListenerT > net::socket::tcp::SocketServer< SocketListenerT >::SocketServer () delete
SocketServer() [3/3]
template<typename SocketListenerT > net::socket::tcp::SocketServer< SocketListenerT >::SocketServer (const SocketServer< SocketListenerT > &) delete
~SocketServer()
template<typename SocketListenerT > virtual net::socket::tcp::SocketServer< SocketListenerT >::~SocketServer () virtual default
Member Function Documentation
listen() [1/3]
template<typename SocketListenerT > void net::socket::tcp::SocketServer< SocketListenerT >::listen (const InetAddress & localAddress, int backlog, const std::function< void(int err)> & onError) inline
Definition at line 80 of file SocketServer.h.
{
             SocketListener* socketListener =
                 new SocketListener(onConstruct, onDestruct, onConnect, onDisconnect, onRead, onReadError, onWriteError, options);
             socketListener->listen(localAddress, backlog, onError);
         }
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
listen() [2/3]
template<typename SocketListenerT > void net::socket::tcp::SocketServer< SocketListenerT >::listen (const std::string & ipOrHostname, uint16_t port, int backlog, const std::function< void(int err)> & onError) inline
Definition at line 91 of file SocketServer.h.
{
             listen(InetAddress(ipOrHostname, port), backlog, onError);
         }
listen() [3/3]
template<typename SocketListenerT > void net::socket::tcp::SocketServer< SocketListenerT >::listen (unsigned short port, int backlog, const std::function< void(int err)> & onError) inline
Definition at line 87 of file SocketServer.h.
{
             listen(InetAddress(port), backlog, onError);
         }
operator delete()
template<typename SocketListenerT > void net::socket::tcp::SocketServer< SocketListenerT >::operator delete (void * socketServer_v) inline
Definition at line 49 of file SocketServer.h.
{
             free(socketServer_v);
         }
operator new()
template<typename SocketListenerT > void* net::socket::tcp::SocketServer< SocketListenerT >::operator new (size_t size) inline
Definition at line 43 of file SocketServer.h.
{
             SocketServer<SocketListener>::lastAllocAddress = malloc(size);
             return SocketServer<SocketListener>::lastAllocAddress;
         }
operator=()
template<typename SocketListenerT > SocketServer& net::socket::tcp::SocketServer< SocketListenerT >::operator= (const SocketServer< SocketListenerT > &) delete
Member Data Documentation
isDynamic
template<typename SocketListenerT > bool net::socket::tcp::SocketServer< SocketListenerT >::isDynamic protected
Definition at line 107 of file SocketServer.h.
lastAllocAddress
template<typename SocketListener > void * net::socket::tcp::SocketServer< SocketListener >::lastAllocAddress = nullptr static protected
Definition at line 108 of file SocketServer.h.
onConnect
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketServer< SocketListenerT >::onConnect private
Definition at line 98 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onConstruct
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketServer< SocketListenerT >::onConstruct private
Definition at line 96 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onDestruct
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketServer< SocketListenerT >::onDestruct private
Definition at line 97 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onDisconnect
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection)> net::socket::tcp::SocketServer< SocketListenerT >::onDisconnect private
Definition at line 99 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onRead
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, const char* junk, ssize_t junkLen)> net::socket::tcp::SocketServer< SocketListenerT >::onRead private
Definition at line 100 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onReadError
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketServer< SocketListenerT >::onReadError private
Definition at line 101 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
onWriteError
template<typename SocketListenerT > std::function<void(SocketConnection* socketConnection, int errnum)> net::socket::tcp::SocketServer< SocketListenerT >::onWriteError private
Definition at line 102 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
options
template<typename SocketListenerT > std::map<std::string, std::any> net::socket::tcp::SocketServer< SocketListenerT >::options protected
Definition at line 105 of file SocketServer.h.
Referenced by net::socket::tcp::SocketServer< legacy::SocketListener >::listen().
The documentation for this class was generated from the following file:
net/socket/tcp/SocketServer.h