snode.c: net::DescriptorEventReceiver Class Reference
net::DescriptorEventReceiver Class Reference abstract
#include <DescriptorEventReceiver.h>
Classes
class TIMEOUT
Public Member Functions
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
virtual void dispatchEvent ()=0
virtual void timeoutEvent ()
void enabled ()
void disabled ()
void suspended ()
void resumed ()
struct timeval getTimeout () const
struct timeval getLastTriggered ()
void triggered (struct timeval lastTriggered={time(nullptr), 0})
virtual void unobserved ()=0
Private Attributes
DescriptorEventDispatcher & descriptorEventDispatcher
int fd = -1
bool _enabled = false
bool _suspended = false
long maxInactivity = LONG_MAX
const long initialTimeout
Friends
class DescriptorEventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Detailed Description
Definition at line 45 of file DescriptorEventReceiver.h.
Constructor & Destructor Documentation
DescriptorEventReceiver() [1/2]
net::DescriptorEventReceiver::DescriptorEventReceiver (const DescriptorEventReceiver &) private delete
DescriptorEventReceiver() [2/2]
net::DescriptorEventReceiver::DescriptorEventReceiver (DescriptorEventDispatcher & descriptorEventDispatcher, long timeout = TIMEOUT::DISABLE) explicit protected
Definition at line 29 of file DescriptorEventReceiver.cpp.
         : descriptorEventDispatcher(descriptorEventDispatcher)
         , maxInactivity(timeout)
         , initialTimeout(timeout) {
     }
~DescriptorEventReceiver()
virtual net::DescriptorEventReceiver::~DescriptorEventReceiver () protected virtual default
Member Function Documentation
disable()
void net::DescriptorEventReceiver::disable ()
Definition at line 40 of file DescriptorEventReceiver.cpp.
{
         descriptorEventDispatcher.disable(this, fd);
     }
References descriptorEventDispatcher, net::DescriptorEventDispatcher::disable(), and fd.
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::SocketWriter< SocketT >::doWrite(), net::socket::stream::SocketListener< SocketConnectionT >::end(), net::pipe::PipeSource::eof(), net::pipe::PipeSink::readEvent(), net::socket::stream::tls::TLSHandshake::readEvent(), net::socket::stream::SocketReader< SocketT >::readFromPeer(), net::pipe::PipeSource::writeEvent(), and net::socket::stream::tls::TLSHandshake::writeEvent().
disabled()
void net::DescriptorEventReceiver::disabled () private
Definition at line 58 of file DescriptorEventReceiver.cpp.
{
         this->fd = -1;
         ObservationCounter::observationCounter--;
         _enabled = false;
     }
References _enabled, fd, and net::ObservationCounter::observationCounter.
Referenced by net::DescriptorEventDispatcher::disable().
dispatchEvent()
virtual void net::DescriptorEventReceiver::dispatchEvent () private pure virtual
Implemented in net::WriteEventReceiver, net::ReadEventReceiver, net::ExceptionalConditionEventReceiver, net::ConnectEventReceiver, and net::AcceptEventReceiver.
enable()
void net::DescriptorEventReceiver::enable (int fd)
Definition at line 35 of file DescriptorEventReceiver.cpp.
{
         this->fd = fd;
         descriptorEventDispatcher.enable(this, fd);
     }
References descriptorEventDispatcher, net::DescriptorEventDispatcher::enable(), and fd.
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connect(), net::socket::stream::SocketListener< SocketConnectionT >::listen(), net::pipe::PipeSink::PipeSink(), net::pipe::PipeSource::PipeSource(), net::socket::stream::tls::TLSHandshake::readEvent(), net::socket::stream::tls::TLSHandshake::TLSHandshake(), and net::socket::stream::tls::TLSHandshake::writeEvent().
enabled()
void net::DescriptorEventReceiver::enabled () private
Definition at line 52 of file DescriptorEventReceiver.cpp.
{
         ObservationCounter::observationCounter++;
         _enabled = true;
         lastTriggered = {time(nullptr), 0};
     }
References _enabled, net::ObservationCounter::lastTriggered, net::ObservationCounter::observationCounter, and net::system::time().
Referenced by net::DescriptorEventDispatcher::enable().
getLastTriggered()
timeval net::DescriptorEventReceiver::getLastTriggered () private
Definition at line 100 of file DescriptorEventReceiver.cpp.
{
         return lastTriggered;
     }
References net::ObservationCounter::lastTriggered.
getTimeout()
timeval net::DescriptorEventReceiver::getTimeout () const private
Definition at line 89 of file DescriptorEventReceiver.cpp.
{
         return {maxInactivity, 0};
     }
References maxInactivity.
isEnabled()
bool net::DescriptorEventReceiver::isEnabled () const protected
Definition at line 64 of file DescriptorEventReceiver.cpp.
{
         return _enabled;
     }
References _enabled.
Referenced by net::DescriptorEventDispatcher::disable(), net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), and net::DescriptorEventDispatcher::enable().
isSuspended()
bool net::DescriptorEventReceiver::isSuspended () const protected
Definition at line 77 of file DescriptorEventReceiver.cpp.
{
         return _suspended;
     }
References _suspended.
Referenced by net::DescriptorEventDispatcher::resume(), net::pipe::PipeSource::send(), net::socket::stream::SocketWriter< SocketT >::sendToPeer(), net::socket::stream::SocketReader< SocketT >::shutdown(), net::socket::stream::SocketWriter< SocketT >::shutdown(), and net::DescriptorEventDispatcher::suspend().
operator=()
DescriptorEventReceiver& net::DescriptorEventReceiver::operator= (const DescriptorEventReceiver &) private delete
resume()
void net::DescriptorEventReceiver::resume ()
Definition at line 48 of file DescriptorEventReceiver.cpp.
{
         descriptorEventDispatcher.resume(this, fd);
     }
References descriptorEventDispatcher, fd, and net::DescriptorEventDispatcher::resume().
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::pipe::PipeSource::send(), and net::socket::stream::SocketWriter< SocketT >::sendToPeer().
resumed()
void net::DescriptorEventReceiver::resumed () private
Definition at line 72 of file DescriptorEventReceiver.cpp.
{
         _suspended = false;
         lastTriggered = {time(nullptr), 0};
     }
References _suspended, net::ObservationCounter::lastTriggered, and net::system::time().
Referenced by net::DescriptorEventDispatcher::resume().
setTimeout()
void net::DescriptorEventReceiver::setTimeout (long timeout) protected
Definition at line 81 of file DescriptorEventReceiver.cpp.
{
         if (timeout != TIMEOUT::DEFAULT) {
             this->maxInactivity = timeout;
         } else {
             this->maxInactivity = initialTimeout;
         }
     }
References net::DescriptorEventReceiver::TIMEOUT::DEFAULT, initialTimeout, and maxInactivity.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::setTimeout().
suspend()
void net::DescriptorEventReceiver::suspend ()
Definition at line 44 of file DescriptorEventReceiver.cpp.
{
         descriptorEventDispatcher.suspend(this, fd);
     }
References descriptorEventDispatcher, fd, and net::DescriptorEventDispatcher::suspend().
Referenced by net::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), net::socket::stream::SocketWriter< SocketT >::doWrite(), net::pipe::PipeSource::eof(), net::pipe::PipeSource::PipeSource(), net::pipe::PipeSink::readEvent(), net::socket::stream::tls::TLSHandshake::timeoutEvent(), and net::pipe::PipeSource::writeEvent().
suspended()
void net::DescriptorEventReceiver::suspended () private
Definition at line 68 of file DescriptorEventReceiver.cpp.
{
         _suspended = true;
     }
References _suspended.
Referenced by net::DescriptorEventDispatcher::suspend().
timeoutEvent()
void net::DescriptorEventReceiver::timeoutEvent () private virtual
Reimplemented in net::socket::stream::tls::TLSHandshake.
Definition at line 93 of file DescriptorEventReceiver.cpp.
{
     }
triggered()
void net::DescriptorEventReceiver::triggered (struct timeval lastTriggered = {time(nullptr), 0}) private
Definition at line 96 of file DescriptorEventReceiver.cpp.
{
         this->lastTriggered = lastTriggered;
     }
References net::ObservationCounter::lastTriggered.
unobserved()
virtual void net::DescriptorEventReceiver::unobserved () private pure virtual
Implemented in net::socket::stream::tls::TLSHandshake, net::socket::stream::SocketListener< SocketConnectionT >, net::socket::stream::SocketListener< stream::legacy::SocketConnection< SocketT > >, net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >, net::socket::stream::SocketConnector< SocketConnectionT >, net::socket::stream::SocketConnector< stream::legacy::SocketConnection< SocketT > >, net::socket::stream::SocketConnector< stream::tls::SocketConnection< SocketT > >, net::socket::stream::SocketConnectionT< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, net::socket::stream::SocketConnectionT< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >, net::pipe::PipeSource, net::pipe::PipeSink, and FileReader.
Friends And Related Function Documentation
DescriptorEventDispatcher
friend class DescriptorEventDispatcher friend
Definition at line 101 of file DescriptorEventReceiver.h.
Member Data Documentation
_enabled
bool net::DescriptorEventReceiver::_enabled = false private
Definition at line 95 of file DescriptorEventReceiver.h.
Referenced by disabled(), enabled(), and isEnabled().
_suspended
bool net::DescriptorEventReceiver::_suspended = false private
Definition at line 96 of file DescriptorEventReceiver.h.
Referenced by isSuspended(), resumed(), and suspended().
descriptorEventDispatcher
DescriptorEventDispatcher& net::DescriptorEventReceiver::descriptorEventDispatcher private
Definition at line 91 of file DescriptorEventReceiver.h.
Referenced by disable(), enable(), resume(), and suspend().
fd
int net::DescriptorEventReceiver::fd = -1 private
Definition at line 93 of file DescriptorEventReceiver.h.
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), disable(), disabled(), enable(), resume(), and suspend().
initialTimeout
const long net::DescriptorEventReceiver::initialTimeout private
Definition at line 99 of file DescriptorEventReceiver.h.
Referenced by setTimeout().
maxInactivity
long net::DescriptorEventReceiver::maxInactivity = LONG_MAX private
Definition at line 98 of file DescriptorEventReceiver.h.
Referenced by getTimeout(), and setTimeout().
The documentation for this class was generated from the following files:
net/DescriptorEventReceiver.h
net/DescriptorEventReceiver.cpp