snode.c: StatusCode Class Reference
StatusCode Class Reference
#include <StatusCodes.h>
Static Public Member Functions
static std::string reason (int status)
static bool contains (int status)
Static Private Attributes
static std::map< int, std::string > statusCode
Detailed Description
Definition at line 29 of file StatusCodes.h.
Member Function Documentation
contains()
bool StatusCode::contains (int status) static
Definition at line 99 of file StatusCodes.cpp.
{
     return statusCode.contains(status);
 }
References statusCode.
Referenced by reason().
reason()
std::string StatusCode::reason (int status) static
Definition at line 89 of file StatusCodes.cpp.
{
     std::string reasonPhrase = "unknown status code";
     if (StatusCode::contains(status)) {
         reasonPhrase = statusCode[status];
     }
     return reasonPhrase;
 }
References contains(), and statusCode.
Referenced by http::server::Response::sendHeader(), and express::Response::sendStatus().
Member Data Documentation
statusCode
std::map< int, std::string > StatusCode::statusCode static private
Definition at line 36 of file StatusCodes.h.
Referenced by contains(), and reason().
The documentation for this class was generated from the following files:
http/StatusCodes.h
http/StatusCodes.cpp