snode.c: net::socket::bluetooth::address::L2CapAddress Class Reference
net::socket::bluetooth::address::L2CapAddress Class Reference
#include <L2CapAddress.h>
Public Member Functions
L2CapAddress ()
L2CapAddress (const L2CapAddress &bta)
L2CapAddress (const std::string &btAddress)
L2CapAddress (const std::string &btAddress, uint16_t psm)
L2CapAddress (uint16_t psm)
L2CapAddress (const struct sockaddr_l2 &addr)
uint16_t psm () const
std::string address () const
L2CapAddress & operator= (const L2CapAddress &bta)
const struct sockaddr_l2 & getSockAddrRc () const
Public Member Functions inherited from net::socket::SocketAddress< struct sockaddr_l2 >
const struct sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from net::socket::SocketAddress< struct sockaddr_l2 >
using SockAddr = struct sockaddr_l2
Protected Attributes inherited from net::socket::SocketAddress< struct sockaddr_l2 >
SockAddr sockAddr
Detailed Description
Definition at line 37 of file L2CapAddress.h.
Constructor & Destructor Documentation
L2CapAddress() [1/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress ()
Definition at line 30 of file L2CapAddress.cpp.
{
         sockAddr.l2_family = AF_BLUETOOTH;
         sockAddr.l2_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.l2_psm = htobs(0);
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
L2CapAddress() [2/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress (const L2CapAddress & bta)
Definition at line 36 of file L2CapAddress.cpp.
{
         memcpy(&sockAddr, &bta.sockAddr, sizeof(sockAddr));
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
L2CapAddress() [3/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress (const std::string & btAddress) explicit
Definition at line 44 of file L2CapAddress.cpp.
{
         sockAddr.l2_family = AF_BLUETOOTH;
         str2ba(btAddress.c_str(), &sockAddr.l2_bdaddr);
         sockAddr.l2_psm = htobs(0);
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
L2CapAddress() [4/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress (const std::string & btAddress, uint16_t psm)
Definition at line 56 of file L2CapAddress.cpp.
{
         sockAddr.l2_family = AF_BLUETOOTH;
         str2ba(btAddress.c_str(), &sockAddr.l2_bdaddr);
         sockAddr.l2_psm = htobs(psm);
     }
References psm(), and net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
L2CapAddress() [5/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress (uint16_t psm) explicit
Definition at line 50 of file L2CapAddress.cpp.
{
         sockAddr.l2_family = AF_BLUETOOTH;
         sockAddr.l2_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.l2_psm = htobs(psm);
     }
References psm(), and net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
L2CapAddress() [6/6]
net::socket::bluetooth::address::L2CapAddress::L2CapAddress (const struct sockaddr_l2 & addr) explicit
Definition at line 40 of file L2CapAddress.cpp.
{
         memcpy(&sockAddr, &addr, sizeof(sockAddr));
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Member Function Documentation
address()
std::string net::socket::bluetooth::address::L2CapAddress::address () const
Definition at line 66 of file L2CapAddress.cpp.
{
         char ip[256];
         ba2str(&sockAddr.l2_bdaddr, ip);
         return std::string(ip);
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
getSockAddrRc()
const struct sockaddr_l2 & net::socket::bluetooth::address::L2CapAddress::getSockAddrRc () const
Definition at line 81 of file L2CapAddress.cpp.
{
         return sockAddr;
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
operator=()
L2CapAddress & net::socket::bluetooth::address::L2CapAddress::operator= (const L2CapAddress & bta)
Definition at line 73 of file L2CapAddress.cpp.
{
         if (this != &bta) {
             memcpy(&sockAddr, &bta.sockAddr, sizeof(sockAddr));
         }
         return *this;
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
psm()
uint16_t net::socket::bluetooth::address::L2CapAddress::psm () const
Definition at line 62 of file L2CapAddress.cpp.
{
         return btohs(sockAddr.l2_psm);
     }
References net::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Referenced by L2CapAddress().
The documentation for this class was generated from the following files:
net/socket/bluetooth/address/L2CapAddress.h
net/socket/bluetooth/address/L2CapAddress.cpp