snode.c: web::http::server::Response Class Reference
web::http::server::Response Class Reference
#include <Response.h>
Public Member Functions
void send (const char *junk, std::size_t junkLen)
void send (const std::string &junk)
void end ()
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=true)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & type (const std::string &type)
void upgrade (Request &req)
Public Member Functions inherited from net::pipe::Sink
Sink ()
virtual ~Sink ()
void connect (Source &source)
void disconnect (Source &source)
Protected Member Functions
Response (SocketContext *serverContext)
virtual void reset ()
Protected Attributes
SocketContext * serverContext
int responseStatus = 200
std::map< std::string, std::string > headers
std::map< std::string, web::http::CookieOptions > cookies
Protected Attributes inherited from net::pipe::Sink
Source * source
Private Member Functions
void enqueue (const char *junk, std::size_t junkLen)
void enqueue (const std::string &junk)
void sendHeader ()
void receive (const char *junk, std::size_t junkLen) override
void eof () override
void error (int errnum) override
Private Attributes
ConnectionState connectionState = ConnectionState::Default
bool sendHeaderInProgress = false
bool headersSent = false
std::size_t contentSent = 0
std::size_t contentLength = 0
Friends
template<typename Request , typename Response >
class SocketContextT
Detailed Description
Definition at line 39 of file Response.h.
Constructor & Destructor Documentation
Response()
web::http::server::Response::Response (SocketContext * serverContext) explicit protected
Definition at line 39 of file Response.cpp.
         : serverContext(serverContext) {
     }
Member Function Documentation
append()
Response & web::http::server::Response::append (const std::string & field, const std::string & value)
Definition at line 93 of file Response.cpp.
{
         std::map<std::string, std::string>::iterator it = headers.find(field);
         if (it != headers.end()) {
             it->second += ", " + value;
         } else {
             set(field, value);
         }
         return *this;
     }
References headers, and set().
clearCookie()
Response & web::http::server::Response::clearCookie (const std::string & name, const std::map< std::string, std::string > & options = {})
Definition at line 139 of file Response.cpp.
{
         std::map<std::string, std::string> opts = options;
         opts.erase("Max-Age");
         time_t time = 0;
         opts["Expires"] = httputils::to_http_date(net::system::gmtime(&time));
         return cookie(name, "", opts);
     }
References cookie(), net::system::gmtime(), net::system::time(), and httputils::to_http_date().
cookie()
Response & web::http::server::Response::cookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 133 of file Response.cpp.
{
         cookies.insert({name, CookieOptions(value, options)});
         return *this;
     }
References cookies.
Referenced by clearCookie(), and sendHeader().
end()
void web::http::server::Response::end ()
Definition at line 83 of file Response.cpp.
{
         send("");
     }
References send().
Referenced by web::websocket::server::SocketContext::create(), express::Response::redirect(), express::Response::sendFile(), and upgrade().
enqueue() [1/2]
void web::http::server::Response::enqueue (const char * junk, std::size_t junkLen) private
Definition at line 43 of file Response.cpp.
{
         if (!headersSent && !sendHeaderInProgress) {
             sendHeaderInProgress = true;
             sendHeader();
             sendHeaderInProgress = false;
             headersSent = true;
         }
         serverContext->sendToPeer(junk, junkLen);
         if (headersSent) {
             contentSent += junkLen;
             if (contentSent == contentLength) {
                 serverContext->sendToPeerCompleted();
             } else if (contentSent > contentLength) {
                 serverContext->terminateConnection();
             }
         }
     }
References contentLength, contentSent, headersSent, sendHeader(), sendHeaderInProgress, net::socket::stream::SocketContext::sendToPeer(), web::http::server::SocketContext::sendToPeerCompleted(), serverContext, and web::http::server::SocketContext::terminateConnection().
Referenced by enqueue(), receive(), send(), and sendHeader().
enqueue() [2/2]
void web::http::server::Response::enqueue (const std::string & junk) private
Definition at line 63 of file Response.cpp.
{
         enqueue(junk.data(), junk.size());
     }
References enqueue().
eof()
void web::http::server::Response::eof () override private virtual
Implements net::pipe::Sink.
Definition at line 199 of file Response.cpp.
{
         LOG(INFO) << "Stream EOF";
     }
error()
void web::http::server::Response::error (int errnum) override private virtual
Implements net::pipe::Sink.
Definition at line 203 of file Response.cpp.
{
         PLOG(ERROR) << "Stream error: ";
         serverContext->terminateConnection();
     }
References serverContext, and web::http::server::SocketContext::terminateConnection().
receive()
void web::http::server::Response::receive (const char * junk, std::size_t junkLen) override private virtual
Implements net::pipe::Sink.
Definition at line 195 of file Response.cpp.
{
         enqueue(junk, junkLen);
     }
References enqueue().
reset()
void web::http::server::Response::reset () protected virtual
Reimplemented in express::Response.
Definition at line 208 of file Response.cpp.
{
         headersSent = false;
         sendHeaderInProgress = false;
         contentSent = 0;
         responseStatus = 200;
         contentLength = 0;
         connectionState = ConnectionState::Default;
         headers.clear();
         cookies.clear();
     }
References connectionState, contentLength, contentSent, cookies, web::http::Default, headers, headersSent, responseStatus, and sendHeaderInProgress.
Referenced by express::Response::reset().
send() [1/2]
void web::http::server::Response::send (const char * junk, std::size_t junkLen)
Definition at line 67 of file Response.cpp.
{
         if (junkLen > 0) {
             set("Content-Type", "application/octet-stream", false);
         }
         set("Content-Length", std::to_string(junkLen));
         enqueue(junk, junkLen);
     }
References enqueue(), and set().
Referenced by end(), send(), and express::Response::sendStatus().
send() [2/2]
void web::http::server::Response::send (const std::string & junk)
Definition at line 76 of file Response.cpp.
{
         if (junk.size() > 0) {
             set("Content-Type", "text/html; charset=utf-8");
         }
         send(junk.data(), junk.size());
     }
References send(), and set().
sendHeader()
void web::http::server::Response::sendHeader () private
Definition at line 165 of file Response.cpp.
{
         enqueue("HTTP/1.1 " + std::to_string(responseStatus) + " " + StatusCode::reason(responseStatus) + "\r\n");
         enqueue("Date: " + httputils::to_http_date() + "\r\n");
         set({{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}});
         for (auto& [field, value] : headers) {
             enqueue(field + ": " + value + "\r\n");
         }
         for (auto& [cookie, cookieValue] : cookies) {
             std::string cookieString =
                 std::accumulate(cookieValue.getOptions().begin(),
                                 cookieValue.getOptions().end(),
                                 cookie + "=" + cookieValue.getValue(),
                                 [](const std::string& str, const std::pair<const std::string&, const std::string&> option) -> std::string {
                                     return str + "; " + option.first + (!option.second.empty() ? "=" + option.second : "");
                                 });
             enqueue("Set-Cookie: " + cookieString + "\r\n");
         }
         enqueue("\r\n");
         if (headers.find("Content-Length") != headers.end()) {
             contentLength = std::stoul(headers.find("Content-Length")->second);
         } else {
             contentLength = 0;
         }
     }
References contentLength, cookie(), cookies, enqueue(), headers, web::http::StatusCode::reason(), responseStatus, set(), and httputils::to_http_date().
Referenced by enqueue().
set() [1/2]
Response & web::http::server::Response::set (const std::map< std::string, std::string > & headers, bool overwrite = true)
Definition at line 105 of file Response.cpp.
{
         for (auto& [field, value] : headers) {
             set(field, value, overwrite);
         }
         return *this;
     }
References headers, and set().
set() [2/2]
Response & web::http::server::Response::set (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 113 of file Response.cpp.
{
         if (overwrite || headers.find(field) == headers.end()) {
             headers.insert_or_assign(field, value);
             if (field == "Content-Length") {
                 contentLength = std::stoul(value);
             } else if (field == "Connection" && httputils::ci_contains(value, "close")) {
                 connectionState = ConnectionState::Close;
             } else if (field == "Connection" && httputils::ci_contains(value, "keep-alive")) {
                 connectionState = ConnectionState::Keep;
             }
         }
         return *this;
     }
References httputils::ci_contains(), web::http::Close, connectionState, contentLength, headers, and web::http::Keep.
Referenced by append(), web::websocket::server::SocketContext::create(), express::Response::download(), express::Response::redirect(), send(), sendHeader(), set(), and type().
status()
Response & web::http::server::Response::status (int status)
Definition at line 87 of file Response.cpp.
{
         responseStatus = status;
         return *this;
     }
References responseStatus.
Referenced by web::websocket::server::SocketContext::create(), express::Response::redirect(), express::Response::sendStatus(), and upgrade().
type()
Response & web::http::server::Response::type (const std::string & type)
Definition at line 129 of file Response.cpp.
{
         return set("Content-Type", type);
     }
References set().
upgrade()
void web::http::server::Response::upgrade (Request & req)
Definition at line 149 of file Response.cpp.
{
         if (httputils::ci_contains(req.header("connection"), "Upgrade")) {
             web::http::server::SocketContextUpgradeFactory* socketContextUpgradeFactory =
                 web::http::server::SocketContextUpgradeFactorySelector::instance()->select(req, *this);
             if (socketContextUpgradeFactory != nullptr) {
                 serverContext->switchSocketContext(*socketContextUpgradeFactory);
             } else {
                 this->status(404).end();
             }
         } else {
             this->status(400).end();
         }
     }
References httputils::ci_contains(), end(), web::http::server::Request::header(), web::http::server::SocketContextUpgradeFactorySelector::instance(), web::http::server::SocketContextUpgradeFactorySelector::select(), serverContext, status(), and net::socket::stream::SocketContext::switchSocketContext().
Friends And Related Function Documentation
SocketContextT
template<typename Request , typename Response > friend class SocketContextT friend
Definition at line 87 of file Response.h.
Member Data Documentation
connectionState
ConnectionState web::http::server::Response::connectionState = ConnectionState::Default private
Definition at line 70 of file Response.h.
Referenced by reset(), and set().
contentLength
std::size_t web::http::server::Response::contentLength = 0 private
Definition at line 76 of file Response.h.
Referenced by enqueue(), reset(), sendHeader(), and set().
contentSent
std::size_t web::http::server::Response::contentSent = 0 private
Definition at line 75 of file Response.h.
Referenced by enqueue(), and reset().
cookies
std::map<std::string, web::http::CookieOptions> web::http::server::Response::cookies protected
Definition at line 67 of file Response.h.
Referenced by cookie(), reset(), and sendHeader().
headers
std::map<std::string, std::string> web::http::server::Response::headers protected
Definition at line 66 of file Response.h.
Referenced by append(), reset(), express::Response::sendFile(), sendHeader(), and set().
headersSent
bool web::http::server::Response::headersSent = false private
Definition at line 73 of file Response.h.
Referenced by enqueue(), and reset().
responseStatus
int web::http::server::Response::responseStatus = 200 protected
Definition at line 64 of file Response.h.
Referenced by reset(), express::Response::sendFile(), sendHeader(), and status().
sendHeaderInProgress
bool web::http::server::Response::sendHeaderInProgress = false private
Definition at line 72 of file Response.h.
Referenced by enqueue(), and reset().
serverContext
SocketContext* web::http::server::Response::serverContext protected
Definition at line 62 of file Response.h.
Referenced by enqueue(), error(), express::Response::sendFile(), and upgrade().
The documentation for this class was generated from the following files:
web/http/server/Response.h
web/http/server/Response.cpp