snode.c: net::WriteEventReceiver Class Reference
net::WriteEventReceiver Class Reference abstract
#include <WriteEventReceiver.h>
Public Member Functions
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::EventReceiver
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
WriteEventReceiver ()
virtual void writeEvent ()=0
void dispatchEvent () override
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Friends
template<typename WriteEventReceiver >
class EventDispatcher
Additional Inherited Members
Protected Attributes inherited from net::EventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 30 of file WriteEventReceiver.h.
Constructor & Destructor Documentation
WriteEventReceiver()
net::WriteEventReceiver::WriteEventReceiver () protected
Definition at line 26 of file WriteEventReceiver.cpp.
         : EventReceiver(EventLoop::instance().getWriteEventDispatcher().getTimeout()) {
     }
Member Function Documentation
disable()
void net::WriteEventReceiver::disable () override virtual
Implements net::EventReceiver.
Definition at line 39 of file WriteEventReceiver.cpp.
{
         EventLoop::instance().getWriteEventDispatcher().disable(this, fd);
     }
References net::EventDispatcher< EventReceiverT >::disable(), net::EventReceiver::fd, net::EventLoop::getWriteEventDispatcher(), and net::EventLoop::instance().
Referenced by net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >::close(), net::socket::stream::tls::SocketWriter< SocketT >::write(), net::socket::stream::SocketWriter< SocketT >::writeEvent(), and net::socket::stream::tls::TLSHandshake::writeEvent().
dispatchEvent()
void net::WriteEventReceiver::dispatchEvent () inline override protected virtual
Implements net::EventReceiver.
Definition at line 36 of file WriteEventReceiver.h.
{
             writeEvent();
         }
References writeEvent().
enable()
void net::WriteEventReceiver::enable (int fd, long timeout = TIMEOUT::IGNORE) override virtual
Implements net::EventReceiver.
Definition at line 34 of file WriteEventReceiver.cpp.
{
         EventLoop::instance().getWriteEventDispatcher().enable(this, fd);
         setTimeout(timeout);
     }
References net::EventDispatcher< EventReceiverT >::enable(), net::EventReceiver::fd, net::EventLoop::getWriteEventDispatcher(), net::EventLoop::instance(), setTimeout(), and net::EventReceiver::timeout().
Referenced by net::socket::stream::SocketWriter< SocketT >::enqueue(), net::socket::stream::tls::TLSHandshake::readEvent(), and net::socket::stream::tls::TLSHandshake::TLSHandshake().
resume()
void net::WriteEventReceiver::resume () override virtual
Implements net::EventReceiver.
Definition at line 47 of file WriteEventReceiver.cpp.
{
         EventLoop::instance().getWriteEventDispatcher().resume(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getWriteEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::resume().
Referenced by net::socket::stream::tls::SocketWriter< SocketT >::write().
setTimeout()
void net::WriteEventReceiver::setTimeout (long timeout = TIMEOUT::DEFAULT)
Definition at line 30 of file WriteEventReceiver.cpp.
{
         EventReceiver::setTimeout(timeout, EventLoop::instance().getWriteEventDispatcher().getTimeout());
     }
References net::EventReceiver::getTimeout(), net::EventLoop::instance(), net::EventReceiver::setTimeout(), and net::EventReceiver::timeout().
Referenced by enable(), and net::socket::stream::tls::TLSHandshake::TLSHandshake().
suspend()
void net::WriteEventReceiver::suspend () override virtual
Implements net::EventReceiver.
Definition at line 43 of file WriteEventReceiver.cpp.
{
         EventLoop::instance().getWriteEventDispatcher().suspend(this, fd);
     }
References net::EventReceiver::fd, net::EventLoop::getWriteEventDispatcher(), net::EventLoop::instance(), and net::EventDispatcher< EventReceiverT >::suspend().
Referenced by net::socket::stream::tls::TLSHandshake::timeout(), and net::socket::stream::tls::SocketWriter< SocketT >::write().
writeEvent()
virtual void net::WriteEventReceiver::writeEvent () protected pure virtual
Implemented in net::socket::stream::tls::TLSHandshake, and net::socket::stream::SocketWriter< SocketT >.
Referenced by dispatchEvent().
Friends And Related Function Documentation
EventDispatcher
template<typename WriteEventReceiver > friend class EventDispatcher friend
Definition at line 50 of file WriteEventReceiver.h.
The documentation for this class was generated from the following files:
net/WriteEventReceiver.h
net/WriteEventReceiver.cpp