snode.c: net::socket::tcp::tls::SocketListener Class Reference
net::socket::tcp::tls::SocketListener Class Reference
#include <SocketListener.h>
Public Types
using SocketConnection = net::socket::tcp::tls::SocketConnection
Public Types inherited from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >
using SocketConnection = net::socket::tcp::tls::SocketConnection
Public Types inherited from net::Descriptor
enum FLAGS : unsigned short { FLAGS::none = 0, FLAGS::dontClose = 0x01 << 0 }
Public Member Functions
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
~SocketListener () override
void listen (const InetAddress &localAddress, int backlog, const std::function< void(int err)> &onError) override
Public Member Functions inherited from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >
void * operator new (size_t size)
void operator delete (void *socketListener_v)
SocketListener (const std::function< void(SocketConnection *socketConnection)> &onConnect, const std::function< void(SocketConnection *socketConnection)> &onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> &onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> &onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> &onWriteError, const std::map< std::string, std::any > &options)
SocketListener ()=delete
SocketListener (const SocketListener &)=delete
SocketListener & operator= (const SocketListener &)=delete
void reuseAddress (const std::function< void(int errnum)> &onError)
void acceptEvent () override
void end ()
Public Member Functions inherited from net::AcceptEventReceiver
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (long timeout=TIMEOUT::IGNORE) override
void disable () override
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Public Member Functions inherited from net::socket::tcp::Socket
Socket ()=default
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
virtual ~Socket ()
void open (const std::function< void(int errnum)> &onError, int flags=0)
void bind (const InetAddress &localAddress, const std::function< void(int errnum)> &onError)
const InetAddress & getLocalAddress () const
void setLocalAddress (const InetAddress &localAddress)
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
~Descriptor ()
void open (int fd, FLAGS flags=FLAGS::none)
int getFd () const
bool dontClose () const
Private Attributes
SSL_CTX * ctx = nullptr
unsigned long sslErr = 0
Additional Inherited Members
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (long timeout)
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual ~EventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
Protected Member Functions inherited from net::Descriptor
Descriptor ()=default
Protected Attributes inherited from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >
std::map< std::string, std::any > options
bool isDynamic
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Protected Attributes inherited from net::socket::tcp::Socket
InetAddress localAddress {}
Static Protected Attributes inherited from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >
static void * lastAllocAddress
Detailed Description
Definition at line 31 of file SocketListener.h.
Member Typedef Documentation
SocketConnection
using net::socket::tcp::tls::SocketListener::SocketConnection = net::socket::tcp::tls::SocketConnection
Definition at line 33 of file SocketListener.h.
Constructor & Destructor Documentation
SocketListener()
net::socket::tcp::tls::SocketListener::SocketListener (const std::function< void(SocketConnection *socketConnection)> & onConnect, const std::function< void(SocketConnection *socketConnection)> & onDisconnect, const std::function< void(SocketConnection *socketConnection, const char *junk, ssize_t junkLen)> & onRead, const std::function< void(SocketConnection *socketConnection, int errnum)> & onReadError, const std::function< void(SocketConnection *socketConnection, int errnum)> & onWriteError, const std::map< std::string, std::any > & options)
Definition at line 35 of file SocketListener.cpp.
         : net::socket::tcp::SocketListener<SocketConnection>(
               [&ctx = this->ctx, onConnect](SocketConnection* socketConnection) -> void {
                   socketConnection->startSSL(ctx);
                   class Acceptor
                       : public ReadEventReceiver
                       , public WriteEventReceiver
                       , public Socket {
                   public:
                       Acceptor(SocketConnection* socketConnection, const std::function<void(SocketConnection* socketConnection)>& onConnect)
                           : socketConnection(socketConnection)
                           , onConnect(onConnect)
                           , timeOut(net::timer::Timer::singleshotTimer(
                                 [this](const void*) -> void {
                                     ReadEventReceiver::disable();
                                     WriteEventReceiver::disable();
                                     this->socketConnection->ReadEventReceiver::disable();
                                 },
                                 (struct timeval){TLSACCEPT_TIMEOUT, 0},
                                 nullptr)) {
                           open(socketConnection->getFd(), FLAGS::dontClose);
                           ssl = socketConnection->getSSL();
                           if (ssl != nullptr) {
                               int err = SSL_accept(ssl);
                               int sslErr = SSL_get_error(ssl, err);
                               if (sslErr == SSL_ERROR_WANT_READ) {
                                   ReadEventReceiver::enable();
                               } else if (sslErr == SSL_ERROR_WANT_WRITE) {
                                   WriteEventReceiver::enable();
                               } else {
                                   if (sslErr == SSL_ERROR_NONE) {
                                       onConnect(socketConnection);
                                   }
                                   timeOut.cancel();
                                   unobserved();
                               }
                           } else {
                               onConnect(socketConnection);
                               socketConnection->ReadEventReceiver::disable();
                               timeOut.cancel();
                               unobserved();
                           }
                       }
                       void readEvent() override {
                           int err = SSL_accept(ssl);
                           int sslErr = SSL_get_error(ssl, err);
                           if (sslErr != SSL_ERROR_WANT_READ) {
                               if (sslErr == SSL_ERROR_WANT_WRITE) {
                                   ReadEventReceiver::disable();
                                   WriteEventReceiver::enable();
                               } else {
                                   timeOut.cancel();
                                   ReadEventReceiver::disable();
                                   if (sslErr == SSL_ERROR_NONE) {
                                       onConnect(socketConnection);
                                   } else {
                                       socketConnection->ReadEventReceiver::disable();
                                   }
                               }
                           }
                       }
                       void writeEvent() override {
                           int err = SSL_accept(ssl);
                           int sslErr = SSL_get_error(ssl, err);
                           if (sslErr != SSL_ERROR_WANT_WRITE) {
                               if (sslErr == SSL_ERROR_WANT_READ) {
                                   WriteEventReceiver::disable();
                                   ReadEventReceiver::enable();
                               } else {
                                   timeOut.cancel();
                                   WriteEventReceiver::disable();
                                   if (sslErr == SSL_ERROR_NONE) {
                                       onConnect(socketConnection);
                                   } else {
                                       socketConnection->WriteEventReceiver::disable();
                                   }
                               }
                           }
                       }
                       void unobserved() override {
                           delete this;
                       }
                   private:
                       SocketConnection* socketConnection = nullptr;
                       SSL* ssl = nullptr;
                       std::function<void(SocketConnection* socketConnection)> onConnect;
                       net::timer::Timer& timeOut;
                   };
                   new Acceptor(socketConnection, onConnect);
               },
               onDisconnect,
               onRead,
               onReadError,
               onWriteError,
               options)
         , ctx(nullptr) {
         ctx = SSL_CTX_new(TLS_server_method());
         sslErr = net::socket::tcp::tls::ssl_init_ctx(ctx, options, true);
     }
References ctx, net::ReadEventReceiver::disable(), net::WriteEventReceiver::disable(), net::Descriptor::dontClose, net::ReadEventReceiver::enable(), net::WriteEventReceiver::enable(), net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >::onConnect, net::socket::tcp::Socket::open(), net::timer::Timer::singleshotTimer(), sslErr, TLSACCEPT_TIMEOUT, and net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >::unobserved().
~SocketListener()
net::socket::tcp::tls::SocketListener::~SocketListener () override virtual
Reimplemented from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >.
Definition at line 149 of file SocketListener.cpp.
{
         if (ctx != nullptr) {
             SSL_CTX_free(ctx);
         }
     }
References ctx.
Member Function Documentation
listen()
void net::socket::tcp::tls::SocketListener::listen (const InetAddress & localAddress, int backlog, const std::function< void(int err)> & onError) override virtual
Reimplemented from net::socket::tcp::SocketListener< net::socket::tcp::tls::SocketConnection >.
Definition at line 155 of file SocketListener.cpp.
{
         if (sslErr != 0) {
             onError(-sslErr);
         } else {
             socket::tcp::SocketListener<SocketConnection>::listen(localAddress, backlog, onError);
         }
     }
References net::socket::tcp::SocketListener< SocketConnectionT >::listen(), net::socket::tcp::Socket::localAddress, and sslErr.
Member Data Documentation
ctx
SSL_CTX* net::socket::tcp::tls::SocketListener::ctx = nullptr private
Definition at line 47 of file SocketListener.h.
Referenced by SocketListener(), and ~SocketListener().
sslErr
unsigned long net::socket::tcp::tls::SocketListener::sslErr = 0 private
Definition at line 48 of file SocketListener.h.
Referenced by listen(), and SocketListener().
The documentation for this class was generated from the following files:
net/socket/tcp/tls/SocketListener.h
net/socket/tcp/tls/SocketListener.cpp