snode.c: web::ws::server::WSServerProtocol Class Reference
web::ws::server::WSServerProtocol Class Reference abstract
#include <WSServerProtocol.h>
Public Member Functions
WSServerProtocol ()
virtual ~WSServerProtocol ()
void messageStart (char *message, std::size_t messageLength, uint32_t messageKey=0)
void messageStart (const std::string &message, uint32_t messageKey=0)
void sendFrame (char *message, std::size_t messageLength, uint32_t messageKey=0)
void sendFrame (const std::string &message, uint32_t messageKey=0)
void messageEnd (char *message, std::size_t messageLength, uint32_t messageKey=0)
void messageEnd (const std::string &message, uint32_t messageKey=0)
void message (char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (const std::string &message, uint32_t messageKey=0)
void sendPing (char *reason=nullptr, std::size_t reasonLength=0)
void close (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
virtual void onMessageStart (int opCode)=0
virtual void onFrameData (const char *junk, std::size_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onPongReceived ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onProtocolConnect ()=0
virtual void onProtocolDisconnect ()=0
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
Static Public Member Functions
static void broadcast (char *message, std::size_t messageLength, uint32_t messageKey=0)
static void broadcast (const std::string &message, uint32_t messageKey=0)
Protected Attributes
WSServerContextBase * wSServerContext
Private Member Functions
void messageStart (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
Static Private Member Functions
static void broadcast (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
Static Private Attributes
static std::list< WSServerProtocol * > clients
Friends
template<typename WSServerProtocolT >
class WSServerContext
Detailed Description
Definition at line 37 of file WSServerProtocol.h.
Constructor & Destructor Documentation
WSServerProtocol()
web::ws::server::WSServerProtocol::WSServerProtocol ()
Definition at line 32 of file WSServerProtocol.cpp.
{
         clients.push_back(this);
     }
References clients.
~WSServerProtocol()
web::ws::server::WSServerProtocol::~WSServerProtocol () virtual
Definition at line 36 of file WSServerProtocol.cpp.
{
         clients.remove(this);
     }
References clients.
Member Function Documentation
broadcast() [1/3]
void web::ws::server::WSServerProtocol::broadcast (char * message, std::size_t messageLength, uint32_t messageKey = 0) static
Definition at line 72 of file WSServerProtocol.cpp.
{
         broadcast(2, message, messageLength, messageKey);
     }
References message().
Referenced by broadcast().
broadcast() [2/3]
void web::ws::server::WSServerProtocol::broadcast (const std::string & message, uint32_t messageKey = 0) static
Definition at line 75 of file WSServerProtocol.cpp.
{
         broadcast(1, const_cast<std::string&>(message).data(), message.length(), messageKey);
     }
References broadcast(), and message().
broadcast() [3/3]
void web::ws::server::WSServerProtocol::broadcast (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) static private
Definition at line 98 of file WSServerProtocol.cpp.
{
         for (WSServerProtocol* client : clients) {
             client->message(opCode, message, messageLength, messageKey);
         }
     }
References clients, and message().
close()
void web::ws::server::WSServerProtocol::close (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 83 of file WSServerProtocol.cpp.
{
         wSServerContext->close(statusCode, reason, reasonLength);
     }
References web::ws::server::WSServerContextBase::close(), and wSServerContext.
getLocalAddressAsString()
std::string web::ws::server::WSServerProtocol::getLocalAddressAsString () const
Definition at line 104 of file WSServerProtocol.cpp.
{
         return wSServerContext->getLocalAddressAsString();
     }
References web::ws::server::WSServerContextBase::getLocalAddressAsString(), and wSServerContext.
getRemoteAddressAsString()
std::string web::ws::server::WSServerProtocol::getRemoteAddressAsString () const
Definition at line 107 of file WSServerProtocol.cpp.
{
         return wSServerContext->getRemoteAddressAsString();
     }
References web::ws::server::WSServerContextBase::getRemoteAddressAsString(), and wSServerContext.
message() [1/3]
void web::ws::server::WSServerProtocol::message (char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 48 of file WSServerProtocol.cpp.
{
         messageStart(2, message, messageLength, messageKey);
     }
References messageStart().
Referenced by broadcast(), message(), messageEnd(), messageStart(), and sendFrame().
message() [2/3]
void web::ws::server::WSServerProtocol::message (const std::string & message, uint32_t messageKey = 0)
Definition at line 64 of file WSServerProtocol.cpp.
{
         message(1, const_cast<std::string&>(msg).data(), msg.length(), messageKey);
     }
References message().
message() [3/3]
void web::ws::server::WSServerProtocol::message (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) private
Definition at line 92 of file WSServerProtocol.cpp.
{
         wSServerContext->message(opCode, message, messageLength, messageKey);
     }
References message(), web::ws::server::WSServerContextBase::message(), and wSServerContext.
messageEnd() [1/2]
void web::ws::server::WSServerProtocol::messageEnd (char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 52 of file WSServerProtocol.cpp.
{
         wSServerContext->messageEnd(message, messageLength, messageKey);
     }
References message(), web::ws::server::WSServerContextBase::messageEnd(), and wSServerContext.
Referenced by messageEnd().
messageEnd() [2/2]
void web::ws::server::WSServerProtocol::messageEnd (const std::string & message, uint32_t messageKey = 0)
Definition at line 68 of file WSServerProtocol.cpp.
{
         messageEnd(const_cast<std::string&>(message).data(), message.length(), messageKey);
     }
References message(), and messageEnd().
messageStart() [1/3]
void web::ws::server::WSServerProtocol::messageStart (char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 40 of file WSServerProtocol.cpp.
                                                                                                    { // 2
         messageStart(2, message, messageLength, messageKey);
     }
References message().
Referenced by message(), and messageStart().
messageStart() [2/3]
void web::ws::server::WSServerProtocol::messageStart (const std::string & message, uint32_t messageKey = 0)
Definition at line 56 of file WSServerProtocol.cpp.
                                                                                      { // 1
         messageStart(1, const_cast<std::string&>(message).data(), message.length(), messageKey);
     }
References message(), and messageStart().
messageStart() [3/3]
void web::ws::server::WSServerProtocol::messageStart (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) private
Definition at line 88 of file WSServerProtocol.cpp.
{
         wSServerContext->messageStart(opCode, message, messageLength, messageKey);
     }
References message(), web::ws::server::WSServerContextBase::messageStart(), and wSServerContext.
onFrameData()
virtual void web::ws::server::WSServerProtocol::onFrameData (const char * junk, std::size_t junkLen) pure virtual
onMessageEnd()
virtual void web::ws::server::WSServerProtocol::onMessageEnd () pure virtual
onMessageError()
virtual void web::ws::server::WSServerProtocol::onMessageError (uint16_t errnum) pure virtual
onMessageStart()
virtual void web::ws::server::WSServerProtocol::onMessageStart (int opCode) pure virtual
onPongReceived()
virtual void web::ws::server::WSServerProtocol::onPongReceived () pure virtual
onProtocolConnect()
virtual void web::ws::server::WSServerProtocol::onProtocolConnect () pure virtual
onProtocolDisconnect()
virtual void web::ws::server::WSServerProtocol::onProtocolDisconnect () pure virtual
sendFrame() [1/2]
void web::ws::server::WSServerProtocol::sendFrame (char * message, std::size_t messageLength, uint32_t messageKey = 0)
Definition at line 44 of file WSServerProtocol.cpp.
{
         wSServerContext->sendFrame(message, messageLength, messageKey);
     }
References message(), web::ws::server::WSServerContextBase::sendFrame(), and wSServerContext.
Referenced by sendFrame().
sendFrame() [2/2]
void web::ws::server::WSServerProtocol::sendFrame (const std::string & message, uint32_t messageKey = 0)
Definition at line 60 of file WSServerProtocol.cpp.
{
         sendFrame(const_cast<std::string&>(message).data(), message.length(), messageKey);
     }
References message(), and sendFrame().
sendPing()
void web::ws::server::WSServerProtocol::sendPing (char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 79 of file WSServerProtocol.cpp.
{
         wSServerContext->sendPing(reason, reasonLength);
     }
References web::ws::server::WSServerContextBase::sendPing(), and wSServerContext.
Friends And Related Function Documentation
WSServerContext
template<typename WSServerProtocolT > friend class WSServerContext friend
Definition at line 84 of file WSServerProtocol.h.
Member Data Documentation
clients
std::list< WSServerProtocol * > web::ws::server::WSServerProtocol::clients static private
Definition at line 87 of file WSServerProtocol.h.
Referenced by broadcast(), WSServerProtocol(), and ~WSServerProtocol().
wSServerContext
WSServerContextBase* web::ws::server::WSServerProtocol::wSServerContext protected
Definition at line 81 of file WSServerProtocol.h.
Referenced by close(), getLocalAddressAsString(), getRemoteAddressAsString(), message(), messageEnd(), messageStart(), sendFrame(), and sendPing().
The documentation for this class was generated from the following files:
web/ws/server/WSServerProtocol.h
web/ws/server/WSServerProtocol.cpp