snode.c: net::socket::stream::SocketConnectionBase Class Reference
net::socket::stream::SocketConnectionBase Class Reference abstract
#include <SocketConnectionBase.h>
Public Member Functions
SocketContext * getSocketContext ()
virtual std::string getLocalAddressAsString () const =0
virtual std::string getRemoteAddressAsString () const =0
virtual void enqueue (const char *junk, std::size_t junkLen)=0
virtual void enqueue (const std::string &data)=0
virtual std::size_t doRead (char *junk, std::size_t junkLen)=0
virtual void close ()=0
virtual void setTimeout (int timeout)=0
Protected Member Functions
SocketConnectionBase (const std::shared_ptr< const SocketContextFactory > &socketContextFactory)
virtual ~SocketConnectionBase ()
void switchSocketProtocol (const SocketContextFactory &socketContextFactory)
Protected Attributes
SocketContext * socketContext = nullptr
friend SocketContext
Private Member Functions
SocketConnectionBase (const SocketConnectionBase &)=delete
SocketConnectionBase & operator= (const SocketConnectionBase &)=delete
Detailed Description
Definition at line 37 of file SocketConnectionBase.h.
Constructor & Destructor Documentation
SocketConnectionBase() [1/2]
net::socket::stream::SocketConnectionBase::SocketConnectionBase (const SocketConnectionBase &) private delete
SocketConnectionBase() [2/2]
net::socket::stream::SocketConnectionBase::SocketConnectionBase (const std::shared_ptr< const SocketContextFactory > & socketContextFactory) protected
Definition at line 30 of file SocketConnectionBase.cpp.
{
         socketContext = socketContextFactory->create(this);
     }
References socketContext.
~SocketConnectionBase()
net::socket::stream::SocketConnectionBase::~SocketConnectionBase () protected virtual
Definition at line 34 of file SocketConnectionBase.cpp.
{
         delete socketContext;
     }
References socketContext.
Member Function Documentation
close()
virtual void net::socket::stream::SocketConnectionBase::close () pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::close().
doRead()
virtual std::size_t net::socket::stream::SocketConnectionBase::doRead (char * junk, std::size_t junkLen) pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::readFromPeer().
enqueue() [1/2]
virtual void net::socket::stream::SocketConnectionBase::enqueue (const char * junk, std::size_t junkLen) pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::sendToPeer().
enqueue() [2/2]
virtual void net::socket::stream::SocketConnectionBase::enqueue (const std::string & data) pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
getLocalAddressAsString()
virtual std::string net::socket::stream::SocketConnectionBase::getLocalAddressAsString () const pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::getLocalAddressAsString().
getRemoteAddressAsString()
virtual std::string net::socket::stream::SocketConnectionBase::getRemoteAddressAsString () const pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::getRemoteAddressAsString().
getSocketContext()
SocketContext * net::socket::stream::SocketConnectionBase::getSocketContext ()
Definition at line 48 of file SocketConnectionBase.cpp.
{
         return socketContext;
     }
References socketContext.
operator=()
SocketConnectionBase& net::socket::stream::SocketConnectionBase::operator= (const SocketConnectionBase &) private delete
setTimeout()
virtual void net::socket::stream::SocketConnectionBase::setTimeout (int timeout) pure virtual
Implemented in net::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, net::socket::stream::SocketConnection< tls::SocketReader< SocketT >, tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and net::socket::stream::SocketConnection< legacy::SocketReader< SocketT >, legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by net::socket::stream::SocketContext::setTimeout().
switchSocketProtocol()
void net::socket::stream::SocketConnectionBase::switchSocketProtocol (const SocketContextFactory & socketContextFactory) protected
Definition at line 38 of file SocketConnectionBase.cpp.
{
         SocketContext* newSocketContext = socketContextFactory.create(this);
         if (newSocketContext != nullptr) {
             socketContext->onProtocolDisconnected();
             socketContext = newSocketContext;
             socketContext->onProtocolConnected();
         }
     }
References net::socket::stream::SocketContextFactory::create(), net::socket::stream::SocketContext::onProtocolConnected(), net::socket::stream::SocketContext::onProtocolDisconnected(), and socketContext.
Referenced by net::socket::stream::SocketContext::switchSocketProtocol().
Member Data Documentation
socketContext
SocketContext* net::socket::stream::SocketConnectionBase::socketContext = nullptr protected
Definition at line 64 of file SocketConnectionBase.h.
Referenced by getSocketContext(), SocketConnectionBase(), switchSocketProtocol(), and ~SocketConnectionBase().
SocketContext
friend net::socket::stream::SocketConnectionBase::SocketContext protected
Definition at line 66 of file SocketConnectionBase.h.
The documentation for this class was generated from the following files:
net/socket/stream/SocketConnectionBase.h
net/socket/stream/SocketConnectionBase.cpp