snode.c: express::Router Class Reference
express::Router Class Reference
#include <Router.h>
Public Member Functions
Router ()
Router (const Router &router)
Router & operator= (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & use (const std::string &path, const Router &router)
Router & use (const Router &router)
Router & use (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & use (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & all (const std::string &path, const Router &router)
Router & all (const Router &router)
Router & all (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & all (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & get (const std::string &path, const Router &router)
Router & get (const Router &router)
Router & get (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & get (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & put (const std::string &path, const Router &router)
Router & put (const Router &router)
Router & put (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & put (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & post (const std::string &path, const Router &router)
Router & post (const Router &router)
Router & post (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & post (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & del (const std::string &path, const Router &router)
Router & del (const Router &router)
Router & del (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & del (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & connect (const std::string &path, const Router &router)
Router & connect (const Router &router)
Router & connect (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & connect (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & options (const std::string &path, const Router &router)
Router & options (const Router &router)
Router & options (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & options (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & trace (const std::string &path, const Router &router)
Router & trace (const Router &router)
Router & trace (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & trace (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & patch (const std::string &path, const Router &router)
Router & patch (const Router &router)
Router & patch (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & patch (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res)> &dispatcher)
Router & head (const std::string &path, const Router &router)
Router & head (const Router &router)
Router & head (const std::string &path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Router & head (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> &dispatcher)
Protected Member Functions
void dispatch (express::Request &req, express::Response &res)
Private Attributes
std::map< const http::server::Request *, Request * > reqestMap
std::map< const http::server::Response *, Response * > responseMap
std::shared_ptr< RouterDispatcher > routerDispatcher
Detailed Description
Definition at line 55 of file Router.h.
Constructor & Destructor Documentation
Router() [1/2]
express::Router::Router ()
Definition at line 276 of file Router.cpp.
         : routerDispatcher(new RouterDispatcher()) {
     }
Router() [2/2]
express::Router::Router (const Router & router)
Definition at line 280 of file Router.cpp.
         : routerDispatcher(router.routerDispatcher) {
     }
Member Function Documentation
all() [1/6]
Router & express::Router::all (const Router & router)
Definition at line 321 of file Router.cpp.
all() [2/6]
Router & express::Router::all (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 321 of file Router.cpp.
all() [3/6]
Router & express::Router::all (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 321 of file Router.cpp.
all() [4/6]
Router & express::Router::all (const std::string & path, const Router & router)
Definition at line 321 of file Router.cpp.
all() [5/6]
Router & express::Router::all (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 321 of file Router.cpp.
all() [6/6]
Router & express::Router::all (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 321 of file Router.cpp.
connect() [1/6]
Router & express::Router::connect (const Router & router)
Definition at line 326 of file Router.cpp.
connect() [2/6]
Router & express::Router::connect (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 326 of file Router.cpp.
connect() [3/6]
Router & express::Router::connect (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 326 of file Router.cpp.
connect() [4/6]
Router & express::Router::connect (const std::string & path, const Router & router)
Definition at line 326 of file Router.cpp.
connect() [5/6]
Router & express::Router::connect (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 326 of file Router.cpp.
connect() [6/6]
Router & express::Router::connect (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 326 of file Router.cpp.
del() [1/6]
Router & express::Router::del (const Router & router)
Definition at line 325 of file Router.cpp.
del() [2/6]
Router & express::Router::del (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 325 of file Router.cpp.
del() [3/6]
Router & express::Router::del (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 325 of file Router.cpp.
del() [4/6]
Router & express::Router::del (const std::string & path, const Router & router)
Definition at line 325 of file Router.cpp.
del() [5/6]
Router & express::Router::del (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 325 of file Router.cpp.
del() [6/6]
Router & express::Router::del (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 325 of file Router.cpp.
dispatch()
void express::Router::dispatch (express::Request & req, express::Response & res) protected
Definition at line 289 of file Router.cpp.
{
         static_cast<void>(routerDispatcher->dispatch(MountPoint("use", "/"), "/", req, res));
     }
References routerDispatcher.
get() [1/6]
Router & express::Router::get (const Router & router)
Definition at line 322 of file Router.cpp.
get() [2/6]
Router & express::Router::get (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 322 of file Router.cpp.
get() [3/6]
Router & express::Router::get (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 322 of file Router.cpp.
get() [4/6]
Router & express::Router::get (const std::string & path, const Router & router)
Definition at line 322 of file Router.cpp.
get() [5/6]
Router & express::Router::get (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 322 of file Router.cpp.
get() [6/6]
Router & express::Router::get (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 322 of file Router.cpp.
head() [1/6]
Router & express::Router::head (const Router & router)
Definition at line 330 of file Router.cpp.
head() [2/6]
Router & express::Router::head (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 330 of file Router.cpp.
head() [3/6]
Router & express::Router::head (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 330 of file Router.cpp.
head() [4/6]
Router & express::Router::head (const std::string & path, const Router & router)
Definition at line 330 of file Router.cpp.
head() [5/6]
Router & express::Router::head (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 330 of file Router.cpp.
head() [6/6]
Router & express::Router::head (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 330 of file Router.cpp.
operator=()
Router & express::Router::operator= (const Router & router)
Definition at line 284 of file Router.cpp.
{
         routerDispatcher = router.routerDispatcher;
         return *this;
     }
References routerDispatcher.
options() [1/6]
Router & express::Router::options (const Router & router)
Definition at line 327 of file Router.cpp.
options() [2/6]
Router & express::Router::options (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 327 of file Router.cpp.
options() [3/6]
Router & express::Router::options (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 327 of file Router.cpp.
options() [4/6]
Router & express::Router::options (const std::string & path, const Router & router)
Definition at line 327 of file Router.cpp.
options() [5/6]
Router & express::Router::options (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 327 of file Router.cpp.
Referenced by express::middleware::StaticMiddleware::StaticMiddleware().
options() [6/6]
Router & express::Router::options (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 327 of file Router.cpp.
patch() [1/6]
Router & express::Router::patch (const Router & router)
Definition at line 329 of file Router.cpp.
patch() [2/6]
Router & express::Router::patch (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 329 of file Router.cpp.
patch() [3/6]
Router & express::Router::patch (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 329 of file Router.cpp.
patch() [4/6]
Router & express::Router::patch (const std::string & path, const Router & router)
Definition at line 329 of file Router.cpp.
patch() [5/6]
Router & express::Router::patch (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 329 of file Router.cpp.
patch() [6/6]
Router & express::Router::patch (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 329 of file Router.cpp.
post() [1/6]
Router & express::Router::post (const Router & router)
Definition at line 324 of file Router.cpp.
post() [2/6]
Router & express::Router::post (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 324 of file Router.cpp.
post() [3/6]
Router & express::Router::post (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 324 of file Router.cpp.
post() [4/6]
Router & express::Router::post (const std::string & path, const Router & router)
Definition at line 324 of file Router.cpp.
post() [5/6]
Router & express::Router::post (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 324 of file Router.cpp.
post() [6/6]
Router & express::Router::post (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 324 of file Router.cpp.
put() [1/6]
Router & express::Router::put (const Router & router)
Definition at line 323 of file Router.cpp.
put() [2/6]
Router & express::Router::put (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 323 of file Router.cpp.
put() [3/6]
Router & express::Router::put (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 323 of file Router.cpp.
put() [4/6]
Router & express::Router::put (const std::string & path, const Router & router)
Definition at line 323 of file Router.cpp.
put() [5/6]
Router & express::Router::put (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 323 of file Router.cpp.
put() [6/6]
Router & express::Router::put (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 323 of file Router.cpp.
trace() [1/6]
Router & express::Router::trace (const Router & router)
Definition at line 328 of file Router.cpp.
trace() [2/6]
Router & express::Router::trace (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 328 of file Router.cpp.
trace() [3/6]
Router & express::Router::trace (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 328 of file Router.cpp.
trace() [4/6]
Router & express::Router::trace (const std::string & path, const Router & router)
Definition at line 328 of file Router.cpp.
trace() [5/6]
Router & express::Router::trace (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 328 of file Router.cpp.
trace() [6/6]
Router & express::Router::trace (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 328 of file Router.cpp.
use() [1/6]
Router & express::Router::use (const Router & router)
Definition at line 320 of file Router.cpp.
use() [2/6]
Router & express::Router::use (const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 320 of file Router.cpp.
use() [3/6]
Router & express::Router::use (const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 320 of file Router.cpp.
use() [4/6]
Router & express::Router::use (const std::string & path, const Router & router)
Definition at line 320 of file Router.cpp.
use() [5/6]
Router & express::Router::use (const std::string & path, const std::function< void(Request &req, Response &res)> & dispatcher)
Definition at line 320 of file Router.cpp.
Referenced by express::middleware::JsonMiddleware::JsonMiddleware(), and express::middleware::StaticMiddleware::StaticMiddleware().
use() [6/6]
Router & express::Router::use (const std::string & path, const std::function< void(Request &req, Response &res, const std::function< void(void)> &next)> & dispatcher)
Definition at line 320 of file Router.cpp.
Member Data Documentation
reqestMap
std::map<const http::server::Request*, Request*> express::Router::reqestMap private
Definition at line 86 of file Router.h.
responseMap
std::map<const http::server::Response*, Response*> express::Router::responseMap private
Definition at line 87 of file Router.h.
routerDispatcher
std::shared_ptr<RouterDispatcher> express::Router::routerDispatcher private
Definition at line 88 of file Router.h.
Referenced by dispatch(), and operator=().
The documentation for this class was generated from the following files:
express/Router.h
express/Router.cpp