snode.c: net::socket::stream::SocketWriter< SocketT > Class Template Reference
net::socket::stream::SocketWriter< SocketT > Class Template Reference abstract
#include <SocketWriter.h>
Public Types
using Socket = SocketT
Protected Member Functions
SocketWriter (const std::function< void(int)> &onError)
virtual ~SocketWriter ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void shutdown ()
void doWrite ()
Protected Member Functions inherited from net::WriteEventReceiver
WriteEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
SocketWriter ()=delete
virtual ssize_t write (const char *junk, std::size_t junkLen)=0
virtual int getError ()=0
Private Attributes
std::function< void(int)> onError
std::vector< char > writeBuffer
bool markShutdown = false
Additional Inherited Members
Public Member Functions inherited from net::DescriptorEventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Detailed Description
template<typename SocketT>
class net::socket::stream::SocketWriter< SocketT >
Definition at line 40 of file SocketWriter.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::SocketWriter< SocketT >::Socket = SocketT
Definition at line 46 of file SocketWriter.h.
Constructor & Destructor Documentation
SocketWriter() [1/2]
template<typename SocketT > net::socket::stream::SocketWriter< SocketT >::SocketWriter () private delete
SocketWriter() [2/2]
template<typename SocketT > net::socket::stream::SocketWriter< SocketT >::SocketWriter (const std::function< void(int)> & onError) inline explicit protected
Definition at line 49 of file SocketWriter.h.
             : onError(onError) {
         }
~SocketWriter()
template<typename SocketT > virtual net::socket::stream::SocketWriter< SocketT >::~SocketWriter () protected virtual default
Member Function Documentation
doWrite()
template<typename SocketT > void net::socket::stream::SocketWriter< SocketT >::doWrite () inline protected
Definition at line 75 of file SocketWriter.h.
{
             if (writeBuffer.empty()) {
                 WriteEventReceiver::suspend();
             } else {
                 ssize_t ret = write(writeBuffer.data(), (writeBuffer.size() < MAX_SEND_JUNKSIZE) ? writeBuffer.size() : MAX_SEND_JUNKSIZE);
                 if (ret > 0) {
                     writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + ret);
                     if (writeBuffer.empty()) {
                         WriteEventReceiver::suspend();
                         if (markShutdown) {
                             Socket::shutdown(Socket::shutdown::WR);
                             markShutdown = false;
                         }
                     }
                 } else if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
                     WriteEventReceiver::disable();
                     onError(getError());
                 }
             }
         }
References net::DescriptorEventReceiver::disable(), net::socket::stream::SocketWriter< SocketT >::getError(), net::socket::stream::SocketWriter< SocketT >::markShutdown, MAX_SEND_JUNKSIZE, net::socket::stream::SocketWriter< SocketT >::onError, net::DescriptorEventReceiver::suspend(), net::socket::stream::SocketWriter< SocketT >::write(), and net::socket::stream::SocketWriter< SocketT >::writeBuffer.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::writeEvent().
getError()
template<typename SocketT > virtual int net::socket::stream::SocketWriter< SocketT >::getError () private pure virtual
Implemented in net::socket::stream::tls::SocketWriter< SocketT >, and net::socket::stream::legacy::SocketWriter< SocketT >.
Referenced by net::socket::stream::SocketWriter< SocketT >::doWrite().
sendToPeer()
template<typename SocketT > void net::socket::stream::SocketWriter< SocketT >::sendToPeer (const char * junk, std::size_t junkLen) inline protected
Definition at line 55 of file SocketWriter.h.
{
             writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
             if (WriteEventReceiver::isSuspended()) {
                 WriteEventReceiver::resume();
             }
         }
References net::DescriptorEventReceiver::isSuspended(), net::DescriptorEventReceiver::resume(), and net::socket::stream::SocketWriter< SocketT >::writeBuffer.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::sendToPeer().
shutdown()
template<typename SocketT > void net::socket::stream::SocketWriter< SocketT >::shutdown () inline protected
Definition at line 63 of file SocketWriter.h.
{
             if (isSuspended()) {
                 Socket::shutdown(Socket::shutdown::WR);
             } else {
                 markShutdown = true;
             }
         }
References net::DescriptorEventReceiver::isSuspended(), and net::socket::stream::SocketWriter< SocketT >::markShutdown.
Referenced by net::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::close().
write()
template<typename SocketT > virtual ssize_t net::socket::stream::SocketWriter< SocketT >::write (const char * junk, std::size_t junkLen) private pure virtual
Implemented in net::socket::stream::tls::SocketWriter< SocketT >, and net::socket::stream::legacy::SocketWriter< SocketT >.
Referenced by net::socket::stream::SocketWriter< SocketT >::doWrite().
Member Data Documentation
markShutdown
template<typename SocketT > bool net::socket::stream::SocketWriter< SocketT >::markShutdown = false private
Definition at line 105 of file SocketWriter.h.
Referenced by net::socket::stream::SocketWriter< SocketT >::doWrite(), and net::socket::stream::SocketWriter< SocketT >::shutdown().
onError
template<typename SocketT > std::function<void(int)> net::socket::stream::SocketWriter< SocketT >::onError private
Definition at line 101 of file SocketWriter.h.
Referenced by net::socket::stream::SocketWriter< SocketT >::doWrite().
writeBuffer
template<typename SocketT > std::vector<char> net::socket::stream::SocketWriter< SocketT >::writeBuffer private
Definition at line 103 of file SocketWriter.h.
Referenced by net::socket::stream::SocketWriter< SocketT >::doWrite(), and net::socket::stream::SocketWriter< SocketT >::sendToPeer().
The documentation for this class was generated from the following file:
net/socket/stream/SocketWriter.h