snode.c: net::stream::PipeSink Class Reference
net::stream::PipeSink Class Reference
#include <PipeSink.h>
Public Member Functions
PipeSink (int fd)
PipeSink (const PipeSink &)=delete
PipeSink & operator= (const PipeSink &)=delete
void setOnData (const std::function< void(const char *junk, std::size_t junkLen)> &onData)
void setOnEof (const std::function< void()> &onEof)
void setOnError (const std::function< void(int errnum)> &onError)
Public Member Functions inherited from net::Descriptor
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
void attach (int fd, enum Descriptor::FLAGS flags=FLAGS::none)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Public Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
void readEvent () override
void unobserved () override
Protected Member Functions inherited from net::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
Protected Member Functions inherited from net::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
std::function< void(const char *junk, std::size_t junkLen)> onData
std::function< void()> onEof
std::function< void(int errnum)> onError
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Additional Inherited Members
Public Types inherited from net::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Attributes inherited from net::Descriptor
enum net::Descriptor::FLAGS none
Detailed Description
Definition at line 34 of file PipeSink.h.
Constructor & Destructor Documentation
PipeSink() [1/2]
net::stream::PipeSink::PipeSink (int fd)
Definition at line 34 of file PipeSink.cpp.
         : Descriptor(fd) {
         ReadEventReceiver::enable(fd);
     }
References net::DescriptorEventReceiver::enable(), and net::Descriptor::fd.
PipeSink() [2/2]
net::stream::PipeSink::PipeSink (const PipeSink &) delete
Member Function Documentation
operator=()
PipeSink& net::stream::PipeSink::operator= (const PipeSink &) delete
readEvent()
void net::stream::PipeSink::readEvent () override protected virtual
Implements net::ReadEventReceiver.
Definition at line 39 of file PipeSink.cpp.
{
         errno = 0;
         // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, hicpp-avoid-c-arrays, modernize-avoid-c-arrays)
         static char junk[MAX_READ_JUNKSIZE];
         ssize_t ret = ::read(getFd(), junk, MAX_READ_JUNKSIZE);
         if (ret > 0) {
             if (onData) {
                 onData(junk, ret);
             }
         } else if (ret == 0) {
             ReadEventReceiver::disable();
             ReadEventReceiver::suspend();
             if (onEof) {
                 onEof();
             }
         } else {
             ReadEventReceiver::disable();
             ReadEventReceiver::suspend();
             if (onError) {
                 onError(errno);
             }
         }
     }
References net::DescriptorEventReceiver::disable(), net::Descriptor::getFd(), MAX_READ_JUNKSIZE, onData, onEof, onError, and net::DescriptorEventReceiver::suspend().
setOnData()
void net::stream::PipeSink::setOnData (const std::function< void(const char *junk, std::size_t junkLen)> & onData)
Definition at line 68 of file PipeSink.cpp.
{
         this->onData = onData;
     }
References onData.
setOnEof()
void net::stream::PipeSink::setOnEof (const std::function< void()> & onEof)
Definition at line 72 of file PipeSink.cpp.
{
         this->onEof = onEof;
     }
References onEof.
setOnError()
void net::stream::PipeSink::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 76 of file PipeSink.cpp.
{
         this->onError = onError;
     }
References onError.
unobserved()
void net::stream::PipeSink::unobserved () override protected virtual
Implements net::DescriptorEventReceiver.
Definition at line 80 of file PipeSink.cpp.
{
         delete this;
     }
Member Data Documentation
onData
std::function<void(const char* junk, std::size_t junkLen)> net::stream::PipeSink::onData protected
Definition at line 51 of file PipeSink.h.
Referenced by readEvent(), and setOnData().
onEof
std::function<void()> net::stream::PipeSink::onEof protected
Definition at line 52 of file PipeSink.h.
Referenced by readEvent(), and setOnEof().
onError
std::function<void(int errnum)> net::stream::PipeSink::onError protected
Definition at line 53 of file PipeSink.h.
Referenced by readEvent(), and setOnError().
The documentation for this class was generated from the following files:
net/stream/PipeSink.h
net/stream/PipeSink.cpp