snode.c: web::http::client::SocketContext Class Reference
web::http::client::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContext (net::socket::stream::SocketConnection *socketConnection)
virtual ~SocketContext ()=default
virtual Request & getRequest ()=0
virtual void sendToPeerCompleted ()=0
virtual void terminateConnection ()=0
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketContext (const SocketContextFactory &socketContextFactory)
void setTimeout (int timeout)
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
virtual void onConnected ()
virtual void onDisconnected ()
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnection *socketConnection)
Detailed Description
Definition at line 43 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
web::http::client::SocketContext::SocketContext (net::socket::stream::SocketConnection * socketConnection) inline explicit
Definition at line 45 of file SocketContext.h.
             : net::socket::stream::SocketContext(socketConnection) {
         }
~SocketContext()
virtual web::http::client::SocketContext::~SocketContext () virtual default
Reimplemented from net::socket::stream::SocketContext.
Member Function Documentation
getRequest()
virtual Request& web::http::client::SocketContext::getRequest () pure virtual
Implemented in web::http::client::SocketContextT< RequestT, ResponseT >.
sendToPeerCompleted()
virtual void web::http::client::SocketContext::sendToPeerCompleted () pure virtual
Implemented in web::http::client::SocketContextT< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue().
terminateConnection()
virtual void web::http::client::SocketContext::terminateConnection () pure virtual
Implemented in web::http::client::SocketContextT< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue(), and web::http::client::Request::error().
The documentation for this class was generated from the following file:
web/http/client/SocketContext.h