snode.c: http::server::HTTPServerContextBase Class Reference
http::server::HTTPServerContextBase Class Reference abstract
#include <HTTPServerContext.h>
Public Types
using SocketConnection = net::socket::stream::SocketConnectionBase
Public Member Functions
virtual void sendResponseData (const char *buf, std::size_t len)=0
virtual void responseCompleted ()=0
virtual void terminateConnection ()=0
Public Member Functions inherited from net::socket::stream::SocketProtocol
virtual ~SocketProtocol ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
void close ()
virtual void receiveFromPeer (const char *junk, std::size_t junkLen)=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
void switchSocketProtocol (SocketProtocol *socketProtocol)
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketProtocol
void take (const char *junk, std::size_t junkLen)
void setSocketConnection (SocketConnectionBase *socketConnection)
Protected Attributes inherited from net::socket::stream::SocketProtocol
SocketConnectionBase * socketConnection
bool markedForDelete = false
Detailed Description
Definition at line 39 of file HTTPServerContext.h.
Member Typedef Documentation
SocketConnection
using http::server::HTTPServerContextBase::SocketConnection = net::socket::stream::SocketConnectionBase
Definition at line 41 of file HTTPServerContext.h.
Member Function Documentation
responseCompleted()
virtual void http::server::HTTPServerContextBase::responseCompleted () pure virtual
Implemented in http::server::HTTPServerContext< RequestT, ResponseT >.
Referenced by http::server::Response::enqueue().
sendResponseData()
virtual void http::server::HTTPServerContextBase::sendResponseData (const char * buf, std::size_t len) pure virtual
Implemented in http::server::HTTPServerContext< RequestT, ResponseT >.
Referenced by http::server::Response::enqueue().
terminateConnection()
virtual void http::server::HTTPServerContextBase::terminateConnection () pure virtual
Implemented in http::server::HTTPServerContext< RequestT, ResponseT >.
Referenced by http::server::Response::enqueue(), http::server::Response::error(), and express::Response::sendFile().
The documentation for this class was generated from the following file:
http/server/http/HTTPServerContext.h