snode.c: web::http::client::SocketContextBase Class Reference
web::http::client::SocketContextBase Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContextBase (net::socket::stream::SocketConnectionBase *socketConnection)
virtual ~SocketContextBase ()=default
virtual Request & getRequest ()=0
virtual void terminateConnection ()=0
virtual void requestCompleted ()=0
Public Member Functions inherited from net::socket::stream::SocketContext
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
std::size_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void switchSocketProtocol (const SocketContextFactory &socketProtocolFactory)
void setTimeout (int timeout)
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
virtual void onProtocolConnected ()
virtual void onProtocolDisconnected ()
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketContext
SocketContext (SocketConnectionBase *socketConnection)
virtual ~SocketContext ()=default
Detailed Description
Definition at line 42 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContextBase()
web::http::client::SocketContextBase::SocketContextBase (net::socket::stream::SocketConnectionBase * socketConnection) inline explicit
Definition at line 44 of file SocketContext.h.
             : net::socket::stream::SocketContext(socketConnection) {
         }
~SocketContextBase()
virtual web::http::client::SocketContextBase::~SocketContextBase () virtual default
Member Function Documentation
getRequest()
virtual Request& web::http::client::SocketContextBase::getRequest () pure virtual
Implemented in web::http::client::SocketContext< RequestT, ResponseT >.
requestCompleted()
virtual void web::http::client::SocketContextBase::requestCompleted () pure virtual
Implemented in web::http::client::SocketContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue().
terminateConnection()
virtual void web::http::client::SocketContextBase::terminateConnection () pure virtual
Implemented in web::http::client::SocketContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue(), and web::http::client::Request::error().
The documentation for this class was generated from the following file:
web/http/client/SocketContext.h