snode.c: web::ws::WSTransmitter Class Reference
web::ws::WSTransmitter Class Reference abstract
#include <WSTransmitter.h>
Protected Member Functions
void messageStart (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
void sendFrame (char *message, std::size_t messageLength, uint32_t messageKey=0)
void messageEnd (char *message, std::size_t messageLength, uint32_t messageKey=0)
void message (uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey=0)
Private Member Functions
void send (bool end, uint8_t opCode, char *message, std::size_t messageLength, uint32_t messageKey)
void sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, char *payload, uint64_t payloadLength)
void dumpFrame (char *frame, uint64_t frameLength)
virtual void sendFrameData (uint8_t data)=0
virtual void sendFrameData (uint16_t data)=0
virtual void sendFrameData (uint32_t data)=0
virtual void sendFrameData (uint64_t data)=0
virtual void sendFrameData (char *frame, uint64_t frameLength)=0
virtual void onFrameReady (char *frame, uint64_t frameLength)=0
void sendFrame1 (bool fin, uint8_t opCode, uint32_t maskingKey, char *payload, uint64_t payloadLength)
Detailed Description
Definition at line 31 of file WSTransmitter.h.
Member Function Documentation
dumpFrame()
void web::ws::WSTransmitter::dumpFrame (char * frame, uint64_t frameLength) private
Definition at line 173 of file WSTransmitter.cpp.
{
         int modul = 4;
         std::stringstream stringStream;
         for (std::size_t i = 0; i < frameLength; i++) {
             stringStream << std::setfill('0') << std::setw(2) << std::hex << (unsigned int) (unsigned char) frame[i] << " ";
             if ((i + 1) % modul == 0 || i == frameLength) {
                 VLOG(0) << "Frame: " << stringStream.str();
                 stringStream.str("");
             }
         }
     }
message()
void web::ws::WSTransmitter::message (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) protected
Definition at line 48 of file WSTransmitter.cpp.
{
         send(true, opCode, message, messageLength, messageKey);
     }
References send().
Referenced by web::ws::server::WSServerContext< WSServerProtocolT >::message(), messageEnd(), messageStart(), send(), and sendFrame().
messageEnd()
void web::ws::WSTransmitter::messageEnd (char * message, std::size_t messageLength, uint32_t messageKey = 0) protected
Definition at line 44 of file WSTransmitter.cpp.
{
         send(true, 0, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by web::ws::server::WSServerContext< WSServerProtocolT >::messageEnd().
messageStart()
void web::ws::WSTransmitter::messageStart (uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey = 0) protected
Definition at line 36 of file WSTransmitter.cpp.
{
         send(false, opCode, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by web::ws::server::WSServerContext< WSServerProtocolT >::messageStart().
onFrameReady()
virtual void web::ws::WSTransmitter::onFrameReady (char * frame, uint64_t frameLength) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by sendFrame1().
send()
void web::ws::WSTransmitter::send (bool end, uint8_t opCode, char * message, std::size_t messageLength, uint32_t messageKey) private
Definition at line 52 of file WSTransmitter.cpp.
{
         std::size_t messageOffset = 0;
         do {
             std::size_t sendMessageLength =
                 (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
             bool fin = sendMessageLength == messageLength - messageOffset;
             sendFrame(fin && end, opCode, messageKey, message + messageOffset, sendMessageLength);
             messageOffset += sendMessageLength;
             opCode = 0; // continuation
         } while (messageLength - messageOffset > 0);
     }
References message(), sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by message(), messageEnd(), messageStart(), and sendFrame().
sendFrame() [1/2]
void web::ws::WSTransmitter::sendFrame (bool fin, uint8_t opCode, uint32_t maskingKey, char * payload, uint64_t payloadLength) private
Definition at line 129 of file WSTransmitter.cpp.
{
         uint64_t length = 0;
         if (payloadLength < 126) {
             length = payloadLength;
         } else if (payloadLength < 0x10000) {
             length = 126;
         } else {
             length = 127;
         }
         char header[2];
         header[0] = static_cast<char>((fin ? 0b10000000 : 0) | opCode);
         header[1] = static_cast<char>(((maskingKey > 0) ? 0b10000000 : 0) | length);
         sendFrameData(header, 2);
         switch (length) {
             case 126:
                 sendFrameData(htobe16(static_cast<uint16_t>(payloadLength)));
                 break;
             case 127:
                 sendFrameData(htobe64(static_cast<uint64_t>(payloadLength)));
                 break;
         }
         if (maskingKey > 0) {
             sendFrameData(htobe32(maskingKey));
         }
         union MaskingKey {
             uint32_t keyAsValue;
             char keyAsBytes[4];
         };
         MaskingKey maskingKeyAsArray = {.keyAsValue = htobe32(maskingKey)};
         for (uint64_t i = 0; i < payloadLength; i++) {
             *(payload + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4);
         }
         sendFrameData(payload, payloadLength);
     }
References sendFrameData().
sendFrame() [2/2]
void web::ws::WSTransmitter::sendFrame (char * message, std::size_t messageLength, uint32_t messageKey = 0) protected
Definition at line 40 of file WSTransmitter.cpp.
{
         send(false, 0, message, messageLength, messageKey);
     }
References message(), and send().
Referenced by send(), and web::ws::server::WSServerContext< WSServerProtocolT >::sendFrame().
sendFrame1()
void web::ws::WSTransmitter::sendFrame1 (bool fin, uint8_t opCode, uint32_t maskingKey, char * payload, uint64_t payloadLength) private
Definition at line 69 of file WSTransmitter.cpp.
{
         uint64_t frameLength = 2 + payloadLength;
         uint8_t opCodeOffset = 0;
         uint8_t lengthOffset = 1;
         uint8_t eLengthOffset = 2;
         uint8_t maskingKeyOffset = 2;
         uint8_t payloadOffset = 2;
         if (maskingKey > 0) {
             frameLength += 4;
             payloadOffset += 4;
         }
         char* frame = nullptr;
         uint64_t length = 0;
         if (payloadLength < 126) {
             frame = new char[frameLength];
             length = payloadLength;
         } else if (payloadLength < 0x10000) {
             frameLength += 2;
             maskingKeyOffset += 2;
             payloadOffset += 2;
             frame = new char[frameLength];
             *reinterpret_cast<uint16_t*>(frame + eLengthOffset) = htobe16(static_cast<uint16_t>(payloadLength));
             length = 126;
         } else {
             frameLength += 8;
             maskingKeyOffset += 8;
             payloadOffset += 8;
             frame = new char[frameLength];
             *reinterpret_cast<uint64_t*>(frame + eLengthOffset) = htobe64(payloadLength);
             length = 127;
         }
         if (maskingKey > 0) {
             *reinterpret_cast<uint32_t*>(frame + maskingKeyOffset) = htobe32(maskingKey);
         }
         *reinterpret_cast<uint8_t*>(frame + opCodeOffset) = static_cast<uint8_t>((fin ? 0b10000000 : 0) | opCode);
         *reinterpret_cast<uint8_t*>(frame + lengthOffset) = static_cast<uint8_t>(((maskingKey > 0) ? 0b10000000 : 0) | length);
         union MaskingKey {
             uint32_t key;
             char keyAsArray[4];
         };
         MaskingKey maskingKeyAsArray = {.key = htobe32(maskingKey)};
         for (uint64_t i = 0; i < payloadLength; i++) {
             *(frame + payloadOffset + i) = *(payload + i) ^ *(maskingKeyAsArray.keyAsArray + i % 4);
         }
         // dumpFrame(frame, frameLength);
         onFrameReady(frame, frameLength);
         delete[] frame;
     }
References onFrameReady().
sendFrameData() [1/5]
virtual void web::ws::WSTransmitter::sendFrameData (char * frame, uint64_t frameLength) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
sendFrameData() [2/5]
virtual void web::ws::WSTransmitter::sendFrameData (uint16_t data) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
sendFrameData() [3/5]
virtual void web::ws::WSTransmitter::sendFrameData (uint32_t data) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
sendFrameData() [4/5]
virtual void web::ws::WSTransmitter::sendFrameData (uint64_t data) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
sendFrameData() [5/5]
virtual void web::ws::WSTransmitter::sendFrameData (uint8_t data) private pure virtual
Implemented in web::ws::server::WSServerContext< WSServerProtocolT >.
Referenced by sendFrame().
The documentation for this class was generated from the following files:
web/ws/WSTransmitter.h
web/ws/WSTransmitter.cpp