snode.c: net::SNodeC Class Reference
net::SNodeC Class Reference
#include <SNodeC.h>
Static Public Member Functions
static void init (int argc, char *argv[])
static int start (struct timeval timeOut={LONG_MAX, 0})
static void stop ()
static TickStatus tick (struct timeval timeOut={0, 0})
static void free ()
Private Member Functions
SNodeC ()=delete
~SNodeC ()=delete
void * operator new (std::size_t count)=delete
Detailed Description
Definition at line 34 of file SNodeC.h.
Constructor & Destructor Documentation
SNodeC()
net::SNodeC::SNodeC () private delete
~SNodeC()
net::SNodeC::~SNodeC () private delete
Member Function Documentation
free()
void net::SNodeC::free () static
Definition at line 45 of file SNodeC.cpp.
                       {
         EventLoop::free();
     }
References net::EventLoop::free().
init()
void net::SNodeC::init (int argc, char * argv[]) static
Definition at line 30 of file SNodeC.cpp.
{
         EventLoop::init(argc, argv);
     }
References net::EventLoop::init().
Referenced by express::WebApp::init().
operator new()
void* net::SNodeC::operator new (std::size_t count) private delete
start()
int net::SNodeC::start (struct timeval timeOut = {LONG_MAX, 0}) static
Definition at line 34 of file SNodeC.cpp.
{
         return EventLoop::start(timeOut);
     }
References net::EventLoop::start().
Referenced by express::WebApp::start().
stop()
void net::SNodeC::stop () static
Definition at line 37 of file SNodeC.cpp.
                       {
         EventLoop::stop();
     }
References net::EventLoop::stop().
Referenced by express::WebApp::stop().
tick()
TickStatus net::SNodeC::tick (struct timeval timeOut = {0, 0}) static
Definition at line 41 of file SNodeC.cpp.
{
         return EventLoop::tick(timeOut);
     }
References net::EventLoop::tick().
The documentation for this class was generated from the following files:
net/SNodeC.h
net/SNodeC.cpp