snode.c: web::http::client::SocketContextUpgradeFactorySelector Class Reference
web::http::client::SocketContextUpgradeFactorySelector Class Reference
#include <SocketContextUpgradeFactorySelector.h>
Public Member Functions
void registerSocketContextUpgradeFactory (web::http::client::SocketContextUpgradeFactory *socketContextUpgradeFactory)
void registerSocketContextUpgradeFactory (web::http::client::SocketContextUpgradeFactory *socketContextUpgradeFactory, void *handler)
void loadSocketContexts ()
void unloadSocketContexts ()
web::http::client::SocketContextUpgradeFactory * select (const std::string &subProtocolName, web::http::client::Request &req, web::http::client::Response &res)
Static Public Member Functions
static SocketContextUpgradeFactorySelector * instance ()
Static Public Attributes
static SocketContextUpgradeFactorySelector * socketContextUpgradeFactorySelector = nullptr
Protected Attributes
std::map< std::string, SocketContextPlugin > serverSocketContextPlugins
std::map< std::string, SocketContextPlugin > clientSocketContextPlugins
Private Member Functions
SocketContextUpgradeFactorySelector ()=default
~SocketContextUpgradeFactorySelector ()=default
Detailed Description
Definition at line 42 of file SocketContextUpgradeFactorySelector.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactorySelector()
web::http::client::SocketContextUpgradeFactorySelector::SocketContextUpgradeFactorySelector () private default
Referenced by instance().
~SocketContextUpgradeFactorySelector()
web::http::client::SocketContextUpgradeFactorySelector::~SocketContextUpgradeFactorySelector () private default
Member Function Documentation
instance()
SocketContextUpgradeFactorySelector * web::http::client::SocketContextUpgradeFactorySelector::instance () static
Definition at line 69 of file SocketContextUpgradeFactorySelector.cpp.
{
         if (socketContextUpgradeFactorySelector == nullptr) {
             socketContextUpgradeFactorySelector = new SocketContextUpgradeFactorySelector();
         }
         return socketContextUpgradeFactorySelector;
     }
References SocketContextUpgradeFactorySelector(), and socketContextUpgradeFactorySelector.
Referenced by loadSocketContexts(), web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory(), and web::http::client::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
loadSocketContexts()
void web::http::client::SocketContextUpgradeFactorySelector::loadSocketContexts ()
Definition at line 36 of file SocketContextUpgradeFactorySelector.cpp.
{
         void* handle = dlopen("/usr/local/lib/snode.c/web/ws/libwebsocket.so", RTLD_LAZY | RTLD_GLOBAL);
         if (handle != nullptr) {
             SocketContextUpgradeInterface* (*plugin)() = reinterpret_cast<SocketContextUpgradeInterface* (*) ()>(dlsym(handle, "plugin"));
             SocketContextUpgradeInterface* socketContextUpgradeInterface = plugin();
             SocketContextUpgradeFactorySelector::instance()->registerSocketContextUpgradeFactory(socketContextUpgradeInterface->create(),
                                                                                                  handle);
             delete socketContextUpgradeInterface;
         }
     }
References instance(), web::ws::client::plugin(), and registerSocketContextUpgradeFactory().
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory().
registerSocketContextUpgradeFactory() [1/2]
void web::http::client::SocketContextUpgradeFactorySelector::registerSocketContextUpgradeFactory (web::http::client::SocketContextUpgradeFactory * socketContextUpgradeFactory)
Definition at line 76 of file SocketContextUpgradeFactorySelector.cpp.
{
         registerSocketContextUpgradeFactory(socketContextUpgradeFactory, nullptr);
     }
Referenced by loadSocketContexts().
registerSocketContextUpgradeFactory() [2/2]
void web::http::client::SocketContextUpgradeFactorySelector::registerSocketContextUpgradeFactory (web::http::client::SocketContextUpgradeFactory * socketContextUpgradeFactory, void * handler)
Definition at line 81 of file SocketContextUpgradeFactorySelector.cpp.
{
         SocketContextPlugin socketContextPlugin = {.socketContextUpgradeFactory = socketContextUpgradeFactory, .handle = handle};
         if (socketContextUpgradeFactory->role() == SocketContextUpgradeFactory::ROLE::SERVER) {
             const auto [it, success] = serverSocketContextPlugins.insert({socketContextUpgradeFactory->name(), socketContextPlugin});
             if (!success) {
                 VLOG(0) << "UpgradeSocketContext already existing: not using " << socketContextUpgradeFactory->name();
                 socketContextUpgradeFactory->destroy();
                 if (handle != nullptr) {
                     dlclose(handle);
                 }
             }
         } else if (socketContextUpgradeFactory->role() == SocketContextUpgradeFactory::ROLE::CLIENT) {
             const auto [it, success] = clientSocketContextPlugins.insert({socketContextUpgradeFactory->name(), socketContextPlugin});
             if (!success) {
                 VLOG(0) << "UpgradeSocketContext already existing: not using " << socketContextUpgradeFactory->name();
                 socketContextUpgradeFactory->destroy();
                 if (handle != nullptr) {
                     dlclose(handle);
                 }
             }
         }
     }
References web::http::client::SocketContextUpgradeFactory::CLIENT, clientSocketContextPlugins, web::http::client::SocketContextUpgradeFactory::destroy(), web::http::client::SocketContextUpgradeFactory::name(), web::http::client::SocketContextUpgradeFactory::role(), web::http::client::SocketContextUpgradeFactory::SERVER, serverSocketContextPlugins, and web::http::client::SocketContextPlugin::socketContextUpgradeFactory.
select()
web::http::client::SocketContextUpgradeFactory * web::http::client::SocketContextUpgradeFactorySelector::select (const std::string & subProtocolName, web::http::client::Request & req, web::http::client::Response & res)
Definition at line 106 of file SocketContextUpgradeFactorySelector.cpp.
{
         web::http::client::SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
         if (serverSocketContextPlugins.contains(name)) {
             socketContextUpgradeFactory = serverSocketContextPlugins[name].socketContextUpgradeFactory;
             socketContextUpgradeFactory->prepare(req, res);
         }
         return socketContextUpgradeFactory;
     }
References web::http::client::SocketContextUpgradeFactory::prepare(), and serverSocketContextPlugins.
unloadSocketContexts()
void web::http::client::SocketContextUpgradeFactorySelector::unloadSocketContexts ()
Definition at line 51 of file SocketContextUpgradeFactorySelector.cpp.
{
         for (const auto& [name, socketContextPlugin] : serverSocketContextPlugins) {
             socketContextPlugin.socketContextUpgradeFactory->destroy();
             if (socketContextPlugin.handle != nullptr) {
                 dlclose(socketContextPlugin.handle);
             }
         }
         for (const auto& [name, socketContextPlugin] : clientSocketContextPlugins) {
             socketContextPlugin.socketContextUpgradeFactory->destroy();
             if (socketContextPlugin.handle != nullptr) {
                 dlclose(socketContextPlugin.handle);
             }
         }
         delete this;
     }
References clientSocketContextPlugins, and serverSocketContextPlugins.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory().
Member Data Documentation
clientSocketContextPlugins
std::map<std::string, SocketContextPlugin> web::http::client::SocketContextUpgradeFactorySelector::clientSocketContextPlugins protected
Definition at line 62 of file SocketContextUpgradeFactorySelector.h.
Referenced by registerSocketContextUpgradeFactory(), and unloadSocketContexts().
serverSocketContextPlugins
std::map<std::string, SocketContextPlugin> web::http::client::SocketContextUpgradeFactorySelector::serverSocketContextPlugins protected
Definition at line 61 of file SocketContextUpgradeFactorySelector.h.
Referenced by registerSocketContextUpgradeFactory(), select(), and unloadSocketContexts().
socketContextUpgradeFactorySelector
SocketContextUpgradeFactorySelector * web::http::client::SocketContextUpgradeFactorySelector::socketContextUpgradeFactorySelector = nullptr static
Definition at line 65 of file SocketContextUpgradeFactorySelector.h.
Referenced by instance().
The documentation for this class was generated from the following files:
web/http/client/SocketContextUpgradeFactorySelector.h
web/http/client/SocketContextUpgradeFactorySelector.cpp