snode.c: http::Parser Class Reference
http::Parser Class Reference abstract
#include <Parser.h>
Public Member Functions
Parser (enum HTTPCompliance compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()=default
void parse (const char *buf, std::size_t count)
Protected Types
enum class HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum class ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Protected Member Functions
virtual void reset ()
virtual void begin ()=0
virtual enum ParserState parseStartLine (const std::string &line)=0
virtual enum ParserState parseHeader ()=0
virtual enum ParserState parseContent (char *content, std::size_t size)=0
virtual enum ParserState parsingError (int code, const std::string &reason)=0
Protected Attributes
enum http::Parser::HTTPCompliance HTTPCompliance
enum http::Parser::ParserState parserState = ParserState::BEGIN
char * content = nullptr
std::size_t contentLength = 0
std::map< std::string, std::string > headers
Static Protected Attributes
static std::regex httpVersionRegex
Private Member Functions
std::size_t readStartLine (const char *buf, std::size_t count)
std::size_t readHeaderLine (const char *buf, std::size_t count)
void splitHeaderLine (const std::string &line)
std::size_t readContent (const char *buf, std::size_t count)
Private Attributes
bool EOL {false}
std::string line
std::size_t contentRead = 0
Friends
enum HTTPCompliance operator| (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
enum HTTPCompliance operator& (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
Detailed Description
Definition at line 33 of file Parser.h.
Member Enumeration Documentation
HTTPCompliance
enum http::Parser::HTTPCompliance : unsigned short strong protected
Enumerator
RFC1945
RFC2616
RFC7230
RFC7231
RFC7232
RFC7233
RFC7234
RFC7235
RFC7540
RFC7541
Definition at line 35 of file Parser.h.
                                    : unsigned short {
             RFC1945 = 0x01 << 0, // HTTP 1.0
             RFC2616 = 0x01 << 1, // HTTP 1.1
             RFC7230 = 0x01 << 2, // Message Syntax and Routing
             RFC7231 = 0x01 << 3, // Semantics and Content
             RFC7232 = 0x01 << 4, // Conditional Requests
             RFC7233 = 0x01 << 5, // Range Requests
             RFC7234 = 0x01 << 6, // Caching
             RFC7235 = 0x01 << 7, // Authentication
             RFC7540 = 0x01 << 8, // HTTP 2.0
             RFC7541 = 0x01 << 9  // Header Compression
         } HTTPCompliance;
ParserState
enum http::Parser::ParserState strong protected
Enumerator
BEGIN
FIRSTLINE
HEADER
BODY
ERROR
Definition at line 58 of file Parser.h.
 {BEGIN, FIRSTLINE, HEADER, BODY, ERROR} parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
Parser()
http::Parser::Parser (enum HTTPCompliance compliance = HTTPCompliance::RFC2616 | HTTPCompliance::RFC7230) inline explicit
Definition at line 49 of file Parser.h.
             : HTTPCompliance(compliance) {
         }
~Parser()
virtual http::Parser::~Parser () virtual default
Member Function Documentation
begin()
virtual void http::Parser::begin () protected pure virtual
Implemented in http::ResponseParser, and http::RequestParser.
Referenced by parse().
parse()
void http::Parser::parse (const char * buf, std::size_t count)
Definition at line 45 of file Parser.cpp.
{
         std::size_t consumed = 0;
         while (consumed < count && parserState != ParserState::ERROR) {
             switch (parserState) {
                 case ParserState::BEGIN:
                     parserState = ParserState::FIRSTLINE;
                     begin();
                     [[fallthrough]];
                 case ParserState::FIRSTLINE:
                     consumed += readStartLine(buf + consumed, count - consumed);
                     break;
                 case ParserState::HEADER:
                     consumed += readHeaderLine(buf + consumed, count - consumed);
                     break;
                 case ParserState::BODY:
                     consumed += readContent(buf + consumed, count - consumed);
                     break;
                 case ParserState::ERROR:
                     break;
             };
         }
     }
References BEGIN, begin(), BODY, ERROR, FIRSTLINE, HEADER, parserState, readContent(), readHeaderLine(), and readStartLine().
parseContent()
virtual enum ParserState http::Parser::parseContent (char * content, std::size_t size) protected pure virtual
Implemented in http::ResponseParser, and http::RequestParser.
parseHeader()
virtual enum ParserState http::Parser::parseHeader () protected pure virtual
Implemented in http::ResponseParser, and http::RequestParser.
Referenced by readHeaderLine().
parseStartLine()
virtual enum ParserState http::Parser::parseStartLine (const std::string & line) protected pure virtual
Implemented in http::ResponseParser, and http::RequestParser.
Referenced by readStartLine().
parsingError()
virtual enum ParserState http::Parser::parsingError (int code, const std::string & reason) protected pure virtual
Implemented in http::ResponseParser, and http::RequestParser.
Referenced by readHeaderLine(), and splitHeaderLine().
readContent()
std::size_t http::Parser::readContent (const char * buf, std::size_t count) private
Definition at line 160 of file Parser.cpp.
{
         if (contentRead == 0) {
             content = new char[contentLength];
         }
         if (contentRead + count <= contentLength) {
             memcpy(content + contentRead, buf, count); // NOLINT(clang-analyzer-core.NonNullParamChecker)
             contentRead += count;
             if (contentRead == contentLength) {
                 parserState = parseContent(content, contentLength);
                 delete[] content;
                 content = nullptr;
                 contentRead = 0;
             }
         } else {
             parserState = parsingError(400, "Content to long");
             if (content != nullptr) {
                 delete[] content;
                 content = nullptr;
             }
         }
         return count;
     }
Referenced by parse().
readHeaderLine()
std::size_t http::Parser::readHeaderLine (const char * buf, std::size_t count) private
Definition at line 88 of file Parser.cpp.
{
         std::size_t consumed = 0;
         while (consumed < count && parserState == ParserState::HEADER) {
             char ch = buf[consumed];
             if (ch == '\r' || ch == '\n') {
                 consumed++;
                 if (ch == '\n') {
                     if (EOL) {
                         splitHeaderLine(line);
                         line.clear();
                         parserState = parseHeader();
                         EOL = false;
                     } else {
                         if (line.empty()) {
                             parserState = parseHeader();
                         } else {
                             EOL = true;
                         }
                     }
                 }
             } else if (EOL) {
                 if (std::isblank(ch)) {
                     if ((HTTPCompliance & HTTPCompliance::RFC7230) == HTTPCompliance::RFC7230) {
                         parserState = parsingError(400, "Header Folding");
                     } else {
                         line += ch;
                         consumed++;
                     }
                 } else {
                     splitHeaderLine(line);
                     line.clear();
                 }
                 EOL = false;
             } else {
                 line += ch;
                 consumed++;
             }
         }
         return consumed;
     }
References EOL, HEADER, line, parseHeader(), parserState, parsingError(), RFC7230, and splitHeaderLine().
Referenced by parse().
readStartLine()
std::size_t http::Parser::readStartLine (const char * buf, std::size_t count) private
Definition at line 69 of file Parser.cpp.
{
         std::size_t consumed = 0;
         while (consumed < count && parserState == ParserState::FIRSTLINE) {
             char ch = buf[consumed++];
             if (ch == '\r' || ch == '\n') {
                 if (ch == '\n') {
                     parserState = parseStartLine(line);
                     line.clear();
                 }
             } else {
                 line += ch;
             }
         }
         return consumed;
     }
References FIRSTLINE, line, parserState, and parseStartLine().
Referenced by parse().
reset()
void http::Parser::reset () protected virtual
Reimplemented in http::ResponseParser, and http::RequestParser.
Definition at line 35 of file Parser.cpp.
{
         parserState = ParserState::BEGIN;
         headers.clear();
         contentLength = 0;
         if (content != nullptr) {
             delete[] content;
             content = nullptr;
         }
     }
References BEGIN, content, contentLength, headers, and parserState.
Referenced by http::RequestParser::reset(), and http::ResponseParser::reset().
splitHeaderLine()
void http::Parser::splitHeaderLine (const std::string & line) private
Definition at line 132 of file Parser.cpp.
{
         if (!line.empty()) {
             std::string field;
             std::string value;
             std::tie(field, value) = httputils::str_split(line, ':');
             if (field.empty()) {
                 parserState = parsingError(400, "Header-field empty");
             } else if (std::isblank(field.back()) || std::isblank(field.front())) {
                 parserState = parsingError(400, "White space before or after header-field");
             } else if (value.empty()) {
                 parserState = parsingError(400, "Header-value of field \"" + field + "\" empty");
             } else {
                 httputils::to_lower(field);
                 httputils::str_trimm(value);
                 httputils::to_lower(value);
                 if (headers.find(field) == headers.end()) {
                     headers.insert({field, value});
                 } else {
                     headers[field] += "," + value;
                 }
             }
         } else {
             parserState = parsingError(400, "Header-line empty");
         }
     }
References headers, line, parserState, parsingError(), httputils::str_split(), httputils::str_trimm(), and httputils::to_lower().
Referenced by readHeaderLine().
Friends And Related Function Documentation
operator&
enum HTTPCompliance operator& (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 160 of file Parser.cpp.
{
         return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) & static_cast<unsigned short>(c2));
     }
operator|
enum HTTPCompliance operator| (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 160 of file Parser.cpp.
{
         return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) | static_cast<unsigned short>(c2));
     }
Member Data Documentation
content
char* http::Parser::content = nullptr protected
Definition at line 70 of file Parser.h.
Referenced by reset().
contentLength
std::size_t http::Parser::contentLength = 0 protected
Definition at line 71 of file Parser.h.
Referenced by reset().
contentRead
std::size_t http::Parser::contentRead = 0 private
Definition at line 85 of file Parser.h.
EOL
bool http::Parser::EOL {false} private
Definition at line 81 of file Parser.h.
Referenced by readHeaderLine().
headers
std::map<std::string, std::string> http::Parser::headers protected
Definition at line 72 of file Parser.h.
Referenced by reset(), and splitHeaderLine().
HTTPCompliance
enum http::Parser::HTTPCompliance http::Parser::HTTPCompliance protected
httpVersionRegex
std::regex http::Parser::httpVersionRegex static protected
Definition at line 59 of file Parser.h.
line
std::string http::Parser::line private
Definition at line 84 of file Parser.h.
Referenced by readHeaderLine(), readStartLine(), and splitHeaderLine().
parserState
enum http::Parser::ParserState http::Parser::parserState = ParserState::BEGIN protected
Referenced by parse(), readHeaderLine(), readStartLine(), reset(), and splitHeaderLine().
The documentation for this class was generated from the following files:
http/Parser.h
http/Parser.cpp