snode.c: http::client::Request Class Reference
http::client::Request Class Reference
#include <Request.h>
Public Member Functions
Request & setHost (const std::string &host)
Request & append (const std::string &field, const std::string &value)
Request & set (const std::string &field, const std::string &value, bool overwrite=false)
Request & set (const std::map< std::string, std::string > &headers, bool overwrite=false)
Request & cookie (const std::string &name, const std::string &value)
Request & cookie (const std::map< std::string, std::string > &cookies)
Request & type (const std::string &type)
void send (const char *junk, std::size_t junkLen)
void send (const std::string &junk)
void sendHeader ()
void end ()
Public Member Functions inherited from net::stream::Sink
Sink ()
virtual ~Sink ()
void connect (Source &source)
void disconnect (Source &source)
Public Attributes
std::string method = "GET"
std::string url
std::string host
int httpMajor = 1
int httpMinor = 1
ConnectionState connectionState = ConnectionState::Default
Protected Member Functions
Request (ClientContextBase *clientContext)
void enqueue (const char *junk, std::size_t junkLen)
void enqueue (const std::string &data)
virtual void reset ()
void receive (const char *junk, std::size_t junkLen) override
void eof () override
void error (int errnum) override
Protected Attributes
bool sendHeaderInProgress = false
bool headersSent = false
std::size_t contentSent = 0
std::size_t contentLength = 0
ClientContextBase * clientContext
std::map< std::string, std::string > queries
std::map< std::string, std::string > headers
std::map< std::string, std::string > cookies
std::string nullstr = ""
Protected Attributes inherited from net::stream::Sink
Source * source
Friends
template<typename Request , typename Response >
class ClientContext
Detailed Description
Definition at line 37 of file Request.h.
Constructor & Destructor Documentation
Request()
http::client::Request::Request (ClientContextBase * clientContext) explicit protected
Definition at line 33 of file Request.cpp.
         : clientContext(clientContext) {
     }
Member Function Documentation
append()
Request & http::client::Request::append (const std::string & field, const std::string & value)
Definition at line 43 of file Request.cpp.
{
         std::map<std::string, std::string>::iterator it = headers.find(field);
         if (it != headers.end()) {
             it->second += ", " + value;
         } else {
             set(field, value);
         }
         return *this;
     }
References headers, and set().
cookie() [1/2]
Request & http::client::Request::cookie (const std::map< std::string, std::string > & cookies)
Definition at line 87 of file Request.cpp.
{
         for (auto& [name, value] : cookies) {
             cookie(name, value);
         }
         return *this;
     }
References cookie(), and cookies.
cookie() [2/2]
Request & http::client::Request::cookie (const std::string & name, const std::string & value)
Definition at line 81 of file Request.cpp.
{
         cookies.insert({name, value});
         return *this;
     }
References cookies.
Referenced by cookie().
end()
void http::client::Request::end ()
Definition at line 203 of file Request.cpp.
                       {
         send("");
     }
References send().
enqueue() [1/2]
void http::client::Request::enqueue (const char * junk, std::size_t junkLen) protected
Definition at line 117 of file Request.cpp.
{
         if (!headersSent && !sendHeaderInProgress) {
             sendHeaderInProgress = true;
             sendHeader();
             sendHeaderInProgress = false;
             headersSent = true;
         }
         clientContext->sendRequestData(junk, junkLen);
         if (headersSent) {
             contentSent += junkLen;
             if (contentSent == contentLength) {
                 clientContext->requestCompleted();
             } else if (contentSent > contentLength) {
                 clientContext->terminateConnection();
             }
         }
     }
References clientContext, contentLength, contentSent, headersSent, http::client::ClientContextBase::requestCompleted(), sendHeader(), sendHeaderInProgress, http::client::ClientContextBase::sendRequestData(), and http::client::ClientContextBase::terminateConnection().
Referenced by enqueue(), receive(), send(), and sendHeader().
enqueue() [2/2]
void http::client::Request::enqueue (const std::string & data) protected
Definition at line 137 of file Request.cpp.
{
         enqueue(data.data(), data.size());
     }
References enqueue().
eof()
void http::client::Request::eof () override protected virtual
Implements net::stream::Sink.
Definition at line 211 of file Request.cpp.
                       {
         LOG(INFO) << "Stream EOF";
     }
error()
void http::client::Request::error (int errnum) override protected virtual
Implements net::stream::Sink.
Definition at line 215 of file Request.cpp.
{
         PLOG(ERROR) << "Stream error: ";
         clientContext->terminateConnection();
     }
References clientContext, and http::client::ClientContextBase::terminateConnection().
receive()
void http::client::Request::receive (const char * junk, std::size_t junkLen) override protected virtual
Implements net::stream::Sink.
Definition at line 207 of file Request.cpp.
{
         enqueue(junk, junkLen);
     }
References enqueue().
reset()
void http::client::Request::reset () protected virtual
Definition at line 100 of file Request.cpp.
{
         method = "GET";
         url.clear();
         httpMajor = 1;
         httpMinor = 1;
         host.clear();
         queries.clear();
         headers.clear();
         cookies.clear();
         headersSent = false;
         sendHeaderInProgress = false;
         contentLength = 0;
         contentSent = 0;
         connectionState = ConnectionState::Default;
     }
References connectionState, contentLength, contentSent, cookies, Default, headers, headersSent, host, httpMajor, httpMinor, method, queries, sendHeaderInProgress, and url.
send() [1/2]
void http::client::Request::send (const char * junk, std::size_t junkLen)
Definition at line 187 of file Request.cpp.
{
         if (junkLen > 0) {
             headers.insert({"Content-Type", "application/octet-stream"});
         }
         headers.insert_or_assign("Content-Length", std::to_string(junkLen));
         enqueue(junk, junkLen);
     }
References enqueue(), and headers.
Referenced by end(), and send().
send() [2/2]
void http::client::Request::send (const std::string & junk)
Definition at line 196 of file Request.cpp.
{
         if (junk.size() > 0) {
             headers.insert({"Content-Type", "text/html; charset=utf-8"});
         }
         send(junk.data(), junk.size());
     }
References headers, and send().
sendHeader()
void http::client::Request::sendHeader ()
Definition at line 141 of file Request.cpp.
{
         std::string httpVersion = "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
         std::string queryString = "";
         if (queries.size() > 0) {
             queryString += "?";
             for (auto& [key, value] : queries) {
                 queryString += httputils::url_encode(key) + "=" + httputils::url_encode(value) + "&";
             }
             queryString.pop_back();
         }
         enqueue(method + " " + url + queryString + " " + httpVersion + "\r\n");
         enqueue("Host: " + host + "\r\n");
         enqueue("Date: " + httputils::to_http_date() + "\r\n");
         headers.insert({{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}});
         for (auto& [field, value] : headers) {
             enqueue(field + ":" + value + "\r\n");
         }
         if (contentLength != 0) {
             enqueue("Content-Length: " + std::to_string(contentLength) + "\r\n");
         }
         if (connectionState == ConnectionState::Keep) {
             enqueue("Connection: keep-alive\r\n");
         } else {
             enqueue("Connection: close\r\n");
         }
         for (auto& [name, value] : cookies) {
             enqueue("Cookie:" + name + "=" + value + "\r\n");
         }
         enqueue("\r\n");
         if (headers.find("Content-Length") != headers.end()) {
             contentLength = std::stoi(headers.find("Content-Length")->second);
         } else {
             contentLength = 0;
         }
     }
References connectionState, contentLength, cookies, enqueue(), headers, host, httpMajor, httpMinor, Keep, method, queries, httputils::to_http_date(), url, and httputils::url_encode().
Referenced by enqueue().
set() [1/2]
Request & http::client::Request::set (const std::map< std::string, std::string > & headers, bool overwrite = false)
Definition at line 55 of file Request.cpp.
{
         for (auto& [field, value] : headers) {
             set(field, value, overwrite);
         }
         return *this;
     }
References headers, and set().
set() [2/2]
Request & http::client::Request::set (const std::string & field, const std::string & value, bool overwrite = false)
Definition at line 63 of file Request.cpp.
{
         if (overwrite) {
             headers.insert_or_assign(field, value);
         } else {
             headers.insert({field, value});
         }
         if (field == "Content-Length") {
             contentLength = std::stol(value);
         } else if (field == "Connection" && httputils::ci_comp(value, "close")) {
             connectionState = ConnectionState::Close;
         } else if (field == "Connection" && httputils::ci_comp(value, "keep-alive")) {
             connectionState = ConnectionState::Keep;
         }
         return *this;
     }
References httputils::ci_comp(), Close, connectionState, contentLength, headers, and Keep.
Referenced by append(), and set().
setHost()
Request & http::client::Request::setHost (const std::string & host)
Definition at line 37 of file Request.cpp.
{
         this->host = host;
         return *this;
     }
References host.
type()
Request & http::client::Request::type (const std::string & type)
Definition at line 94 of file Request.cpp.
{
         headers.insert({"Content-Type", type});
         return *this;
     }
References headers.
Friends And Related Function Documentation
ClientContext
template<typename Request , typename Response > friend class ClientContext friend
Definition at line 89 of file Request.h.
Member Data Documentation
clientContext
ClientContextBase* http::client::Request::clientContext protected
Definition at line 74 of file Request.h.
Referenced by enqueue(), and error().
connectionState
ConnectionState http::client::Request::connectionState = ConnectionState::Default
Definition at line 48 of file Request.h.
Referenced by reset(), sendHeader(), and set().
contentLength
std::size_t http::client::Request::contentLength = 0 protected
Definition at line 72 of file Request.h.
Referenced by enqueue(), reset(), sendHeader(), and set().
contentSent
std::size_t http::client::Request::contentSent = 0 protected
Definition at line 71 of file Request.h.
Referenced by enqueue(), and reset().
cookies
std::map<std::string, std::string> http::client::Request::cookies protected
Definition at line 80 of file Request.h.
Referenced by cookie(), reset(), and sendHeader().
headers
std::map<std::string, std::string> http::client::Request::headers protected
Definition at line 79 of file Request.h.
Referenced by append(), reset(), send(), sendHeader(), set(), and type().
headersSent
bool http::client::Request::headersSent = false protected
Definition at line 70 of file Request.h.
Referenced by enqueue(), and reset().
host
std::string http::client::Request::host
Definition at line 44 of file Request.h.
Referenced by reset(), sendHeader(), and setHost().
httpMajor
int http::client::Request::httpMajor = 1
Definition at line 45 of file Request.h.
Referenced by reset(), and sendHeader().
httpMinor
int http::client::Request::httpMinor = 1
Definition at line 46 of file Request.h.
Referenced by reset(), and sendHeader().
method
std::string http::client::Request::method = "GET"
Definition at line 42 of file Request.h.
Referenced by reset(), and sendHeader().
nullstr
std::string http::client::Request::nullstr = "" protected
Definition at line 82 of file Request.h.
queries
std::map<std::string, std::string> http::client::Request::queries protected
Definition at line 78 of file Request.h.
Referenced by reset(), and sendHeader().
sendHeaderInProgress
bool http::client::Request::sendHeaderInProgress = false protected
Definition at line 69 of file Request.h.
Referenced by enqueue(), and reset().
url
std::string http::client::Request::url
Definition at line 43 of file Request.h.
Referenced by reset(), and sendHeader().
The documentation for this class was generated from the following files:
http/client/Request.h
http/client/Request.cpp