snode.c: net::socket::bluetooth::address::RfCommAddress Class Reference
net::socket::bluetooth::address::RfCommAddress Class Reference
#include <RfCommAddress.h>
Public Member Functions
RfCommAddress ()
RfCommAddress (const RfCommAddress &bta)
RfCommAddress (const std::string &btAddress)
RfCommAddress (const std::string &btAddress, uint8_t channel)
RfCommAddress (uint8_t port)
RfCommAddress (const struct sockaddr_rc &addr)
uint8_t channel () const
std::string address () const
RfCommAddress & operator= (const RfCommAddress &bta)
const struct sockaddr_rc & getSockAddrRc () const
Public Member Functions inherited from net::socket::SocketAddress< struct sockaddr_rc >
const struct sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from net::socket::SocketAddress< struct sockaddr_rc >
using SockAddr = struct sockaddr_rc
Protected Attributes inherited from net::socket::SocketAddress< struct sockaddr_rc >
SockAddr sockAddr
Detailed Description
Definition at line 37 of file RfCommAddress.h.
Constructor & Destructor Documentation
RfCommAddress() [1/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress ()
Definition at line 30 of file RfCommAddress.cpp.
{
         sockAddr.rc_family = AF_BLUETOOTH;
         sockAddr.rc_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.rc_channel = (uint8_t) 0;
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
RfCommAddress() [2/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress (const RfCommAddress & bta)
Definition at line 36 of file RfCommAddress.cpp.
{
         memcpy(&sockAddr, &bta.sockAddr, sizeof(sockAddr));
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
RfCommAddress() [3/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress (const std::string & btAddress) explicit
Definition at line 44 of file RfCommAddress.cpp.
{
         sockAddr.rc_family = AF_BLUETOOTH;
         str2ba(btAddress.c_str(), &sockAddr.rc_bdaddr);
         sockAddr.rc_channel = (uint8_t) 0;
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
RfCommAddress() [4/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress (const std::string & btAddress, uint8_t channel)
Definition at line 56 of file RfCommAddress.cpp.
{
         sockAddr.rc_family = AF_BLUETOOTH;
         str2ba(btAddress.c_str(), &sockAddr.rc_bdaddr);
         sockAddr.rc_channel = channel;
     }
References channel(), and net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
RfCommAddress() [5/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress (uint8_t port) explicit
Definition at line 50 of file RfCommAddress.cpp.
{
         sockAddr.rc_family = AF_BLUETOOTH;
         sockAddr.rc_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.rc_channel = channel;
     }
References channel(), and net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
RfCommAddress() [6/6]
net::socket::bluetooth::address::RfCommAddress::RfCommAddress (const struct sockaddr_rc & addr) explicit
Definition at line 40 of file RfCommAddress.cpp.
{
         memcpy(&sockAddr, &addr, sizeof(sockAddr));
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
Member Function Documentation
address()
std::string net::socket::bluetooth::address::RfCommAddress::address () const
Definition at line 66 of file RfCommAddress.cpp.
{
         char ip[256];
         ba2str(&sockAddr.rc_bdaddr, ip);
         return std::string(ip);
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
channel()
uint8_t net::socket::bluetooth::address::RfCommAddress::channel () const
Definition at line 62 of file RfCommAddress.cpp.
{
         return sockAddr.rc_channel;
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
Referenced by RfCommAddress().
getSockAddrRc()
const struct sockaddr_rc & net::socket::bluetooth::address::RfCommAddress::getSockAddrRc () const
Definition at line 81 of file RfCommAddress.cpp.
{
         return sockAddr;
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr.
operator=()
RfCommAddress & net::socket::bluetooth::address::RfCommAddress::operator= (const RfCommAddress & bta)
Definition at line 73 of file RfCommAddress.cpp.
{
         if (this != &bta) {
             memcpy(&sockAddr, &bta.sockAddr, sizeof(sockAddr));
         }
         return *this;
     }
References net::socket::SocketAddress< struct sockaddr_rc >::sockAddr, and net::socket::SocketAddress< SockAddrT >::sockAddr.
The documentation for this class was generated from the following files:
net/socket/bluetooth/address/RfCommAddress.h
net/socket/bluetooth/address/RfCommAddress.cpp