snode.c: net::AcceptEventReceiver Class Reference
net::AcceptEventReceiver Class Reference abstract
#include <AcceptEventReceiver.h>
Public Member Functions
void setTimeout (long timeout=TIMEOUT::DEFAULT)
void enable (int fd, long timeout=TIMEOUT::IGNORE) override
void disable () override
void suspend () override
void resume () override
Public Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
AcceptEventReceiver ()
virtual void acceptEvent ()=0
Protected Member Functions inherited from net::DescriptorEventReceiver
DescriptorEventReceiver (long timeout)
virtual ~DescriptorEventReceiver ()=default
void setTimeout (long timeout, long defaultTimeout)
bool isEnabled () const
bool isSuspended () const
Private Member Functions
void dispatchEvent () override
Additional Inherited Members
Protected Attributes inherited from net::DescriptorEventReceiver
int fd = -1
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
Detailed Description
Definition at line 30 of file AcceptEventReceiver.h.
Constructor & Destructor Documentation
AcceptEventReceiver()
net::AcceptEventReceiver::AcceptEventReceiver () protected
Definition at line 33 of file AcceptEventReceiver.cpp.
         : DescriptorEventReceiver(MAX_ACCEPT_INACTIVITY) {
     }
Member Function Documentation
acceptEvent()
virtual void net::AcceptEventReceiver::acceptEvent () protected pure virtual
Implemented in net::socket::stream::SocketListener< SocketConnectionT >, net::socket::stream::SocketListener< stream::legacy::SocketConnection< SocketT > >, and net::socket::stream::SocketListener< stream::tls::SocketConnection< SocketT > >.
Referenced by dispatchEvent().
disable()
void net::AcceptEventReceiver::disable () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 50 of file AcceptEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().disable(this, fd);
     }
References net::DescriptorEventDispatcher::disable(), net::DescriptorEventReceiver::fd, net::EventLoop::getReadEventDispatcher(), and net::EventLoop::instance().
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::end().
dispatchEvent()
void net::AcceptEventReceiver::dispatchEvent () override private virtual
Implements net::DescriptorEventReceiver.
Definition at line 41 of file AcceptEventReceiver.cpp.
{
         acceptEvent();
     }
References acceptEvent().
enable()
void net::AcceptEventReceiver::enable (int fd, long timeout = TIMEOUT::IGNORE) override virtual
Implements net::DescriptorEventReceiver.
Definition at line 45 of file AcceptEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().enable(this, fd);
         setTimeout(timeout);
     }
References net::DescriptorEventDispatcher::enable(), net::DescriptorEventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), setTimeout(), and net::DescriptorEventReceiver::timeout().
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::listen().
resume()
void net::AcceptEventReceiver::resume () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 58 of file AcceptEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().resume(this, fd);
     }
References net::DescriptorEventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), and net::DescriptorEventDispatcher::resume().
setTimeout()
void net::AcceptEventReceiver::setTimeout (long timeout = TIMEOUT::DEFAULT)
Definition at line 37 of file AcceptEventReceiver.cpp.
{
         DescriptorEventReceiver::setTimeout(timeout, MAX_ACCEPT_INACTIVITY);
     }
References MAX_ACCEPT_INACTIVITY, net::DescriptorEventReceiver::setTimeout(), and net::DescriptorEventReceiver::timeout().
Referenced by enable().
suspend()
void net::AcceptEventReceiver::suspend () override virtual
Implements net::DescriptorEventReceiver.
Definition at line 54 of file AcceptEventReceiver.cpp.
{
         EventLoop::instance().getReadEventDispatcher().suspend(this, fd);
     }
References net::DescriptorEventReceiver::fd, net::EventLoop::getReadEventDispatcher(), net::EventLoop::instance(), and net::DescriptorEventDispatcher::suspend().
The documentation for this class was generated from the following files:
net/AcceptEventReceiver.h
net/AcceptEventReceiver.cpp