snode.c: utils/instrumentation.cpp File Reference
instrumentation.cpp File Reference
#include <cstdio>
#include <dlfcn.h>
Functions
static void __attribute__ ((no_instrument_function)) _print_pretty(void *this_fn
if (rc==0)
for (int iter=0;iter< in_spaces;++iter)
printf ("[%s] %s\n", is_enter ? "+" :"-", info.dli_sname)
Variables
static int spaces = 0
static void bool is_enter
static void bool int in_spaces
int rc = 0
void void * call_site
Function Documentation
__attribute__()
void __attribute__ ((no_instrument_function)) static
for()
for ()
Definition at line 15 of file instrumentation.cpp.
{
             printf(" ");
         }
References printf().
Referenced by express::middleware::StaticMiddleware::StaticMiddleware().
if()
if (rc = = 0)
Definition at line 12 of file instrumentation.cpp.
                      {
             printf("couldn't decode: %p\n", __builtin_return_address(0));
         }
References printf().
printf()
printf (" %s\n" [%s], is_enter ? "+" :"-" , info. dli_sname)
Referenced by for(), and if().
Variable Documentation
call_site
void void * call_site
Initial value:
{
        _print_pretty(this_fn, true, spaces++)
Definition at line 21 of file instrumentation.cpp.
in_spaces
void bool int in_spaces
Initial value:
{
        Dl_info info
Definition at line 8 of file instrumentation.cpp.
is_enter
void bool is_enter
Definition at line 8 of file instrumentation.cpp.
rc
rc = 0
Definition at line 10 of file instrumentation.cpp.
spaces
int spaces = 0 static
Definition at line 6 of file instrumentation.cpp.