snode.c: web::ws Namespace Reference
web::ws Namespace Reference
Namespaces
client
server
subprotocol
Classes
class Receiver
class SocketContext
class SubProtocol
class SubProtocolInterface
struct SubProtocolPlugin
class SubProtocolSelector
class Transmitter
Functions
unsigned char * decode64 (const char *input, int length)
char * base64 (const unsigned char *input, int length)
void serverWebSocketKey (const std::string &clientWebSocketKey, const std::function< void(char *)> &returnKey)
Function Documentation
base64()
char * web::ws::base64 (const unsigned char * input, int length)
Definition at line 42 of file ws_utils.cpp.
{
         const int pl = 4 * ((length + 2) / 3);
         char* output = reinterpret_cast<char*>(calloc(pl + 1, 1)); //+1 for the terminating null that EVP_EncodeBlock adds on
         const int ol = EVP_EncodeBlock(reinterpret_cast<unsigned char*>(output), input, length);
         if (pl != ol) {
             LOG(ERROR) << "Whoops, encode predicted " << pl << " but we got " << ol;
         }
         return output;
     }
Referenced by serverWebSocketKey().
decode64()
unsigned char * web::ws::decode64 (const char * input, int length)
Definition at line 32 of file ws_utils.cpp.
{
         const int pl = 3 * length / 4;
         unsigned char* output = reinterpret_cast<unsigned char*>(calloc(pl + 1, 1));
         const int ol = EVP_DecodeBlock(output, reinterpret_cast<const unsigned char*>(input), length);
         if (pl != ol) {
             LOG(ERROR) << "Whoops, decode predicted " << pl << " but we got " << ol;
         }
         return output;
     }
serverWebSocketKey()
void web::ws::serverWebSocketKey (const std::string & clientWebSocketKey, const std::function< void(char *)> & returnKey)
Definition at line 52 of file ws_utils.cpp.
{
         std::string GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
         std::string serverWebSocketKey(clientWebSocketKey + GUID);
         unsigned char digest[SHA_DIGEST_LENGTH];
         SHA1(reinterpret_cast<const unsigned char*>(serverWebSocketKey.c_str()),
              serverWebSocketKey.length(),
              reinterpret_cast<unsigned char*>(&digest));
         char* key = base64(digest, SHA_DIGEST_LENGTH);
         returnKey(key);
         free(key);
     }
References base64().
Referenced by web::ws::server::SocketContext::create().