snode.c: express Namespace Reference
express Namespace Reference
Namespaces
legacy
middleware
tls
Classes
class Request
class Response
struct MountPoint
class Route
class MiddlewareDispatcher
class ApplicationDispatcher
class State
class Dispatcher
class RouterDispatcher
class Router
class WebApp
class WebAppT
Functions
static const std::string path_concat (const std::vector< std::string > &stringvec)
static const std::vector< std::string > explode (const std::string &s, char delim)
static const std::smatch matchResult (const std::string &cpath)
static bool hasResult (const std::string &cpath)
static bool matchFunction (const std::string &cpath, const std::string &reqpath)
static void setParams (const std::string &cpath, Request &req)
static bool checkForUrlMatch (const std::string &cpath, const std::string &reqpath)
static std::string path_concat (const std::string &first, const std::string &second)
Variables
static std::regex pathregex = std::regex(":[a-zA-Z0-9]+(\\‍(.+?\\‍))?")
Function Documentation
checkForUrlMatch()
static bool express::checkForUrlMatch (const std::string & cpath, const std::string & reqpath) static
Definition at line 129 of file Router.cpp.
{
         bool hasRegex = hasResult(cpath);
         return (!hasRegex && cpath == reqpath) || (hasRegex && matchFunction(cpath, reqpath));
     }
References hasResult(), and matchFunction().
Referenced by express::MiddlewareDispatcher::dispatch(), and express::ApplicationDispatcher::dispatch().
explode()
static const std::vector<std::string> express::explode (const std::string & s, char delim) static
Definition at line 54 of file Router.cpp.
{
         std::vector<std::string> result;
         std::istringstream iss(s);
         for (std::string token; std::getline(iss, token, delim);) {
             result.push_back(std::move(token));
         }
         return result;
     }
Referenced by matchFunction(), and setParams().
hasResult()
static bool express::hasResult (const std::string & cpath) static
Definition at line 73 of file Router.cpp.
{
         std::smatch smatch;
         return std::regex_search(cpath, smatch, pathregex);
     }
References pathregex.
Referenced by checkForUrlMatch(), express::MiddlewareDispatcher::dispatch(), and express::ApplicationDispatcher::dispatch().
matchFunction()
static bool express::matchFunction (const std::string & cpath, const std::string & reqpath) static
Definition at line 79 of file Router.cpp.
{
         std::vector<std::string> explodedString = explode(cpath, '/');
         for (std::vector<std::string>::size_type i = 0; i < explodedString.size(); i++) {
             if (explodedString[i].front() == ':') {
                 std::smatch smatch = matchResult(explodedString[i]);
                 std::string regex = "(.*)";
                 if (smatch.size() > 1) {
                     if (smatch[1] != "") {
                         regex = smatch[1];
                     }
                 }
                 explodedString[i] = regex;
             }
         }
         std::string regexPath = path_concat(explodedString);
         return std::regex_match(reqpath, std::regex(regexPath));
     }
References explode(), matchResult(), and path_concat().
Referenced by checkForUrlMatch().
matchResult()
static const std::smatch express::matchResult (const std::string & cpath) static
Definition at line 65 of file Router.cpp.
{
         std::smatch smatch;
         std::regex_search(cpath, smatch, pathregex);
         return smatch;
     }
References pathregex.
Referenced by matchFunction(), and setParams().
path_concat() [1/2]
static std::string express::path_concat (const std::string & first, const std::string & second) inline static
Definition at line 134 of file Router.cpp.
{
         std::string result;
         if (first.back() == '/' && second.front() == '/') {
             result = first + second.substr(1);
         } else if (first.back() != '/' && second.front() != '/') {
             result = first + '/' + second;
         } else {
             result = first + second;
         }
         if (result.length() > 1 && result.back() == '/') {
             result.pop_back();
         }
         return result;
     }
path_concat() [2/2]
static const std::string express::path_concat (const std::vector< std::string > & stringvec) static
Definition at line 42 of file Router.cpp.
{
         std::string s;
         for (std::vector<std::string>::size_type i = 0; i < stringvec.size(); i++) {
             if (!stringvec[i].empty() && stringvec[i].front() != ' ') {
                 s += "\\/" + stringvec[i];
             }
         }
         return s;
     }
Referenced by express::MiddlewareDispatcher::dispatch(), express::ApplicationDispatcher::dispatch(), express::RouterDispatcher::dispatch(), and matchFunction().
setParams()
static void express::setParams (const std::string & cpath, Request & req) static
Definition at line 102 of file Router.cpp.
{
         std::vector<std::string> explodedString = explode(cpath, '/');
         std::vector<std::string> explodedReqString = explode(req.url, '/');
         for (std::vector<std::string>::size_type i = 0; i < explodedString.size() && i < explodedReqString.size(); i++) {
             if (explodedString[i].front() == ':') {
                 std::smatch smatch = matchResult(explodedString[i]);
                 std::string regex = "(.*)";
                 if (smatch.size() > 1) {
                     if (smatch[1] != "") {
                         regex = smatch[1];
                     }
                 }
                 if (std::regex_match(explodedReqString[i], std::regex(regex))) {
                     std::string attributeName = smatch[0];
                     attributeName.erase(0, 1);
                     attributeName.erase((attributeName.length() - static_cast<std::size_t>(smatch[1].length())),
                                         static_cast<std::size_t>(smatch[1].length()));
                     req.params[attributeName] = explodedReqString[i];
                 }
             }
         }
     }
References explode(), matchResult(), express::Request::params, and web::http::server::Request::url.
Referenced by express::MiddlewareDispatcher::dispatch(), and express::ApplicationDispatcher::dispatch().
Variable Documentation
pathregex
std::regex express::pathregex = std::regex(":[a-zA-Z0-9]+(\\‍(.+?\\‍))?") static
Definition at line 40 of file Router.cpp.
Referenced by hasResult(), and matchResult().