snode.c: web::websocket Namespace Reference
web::websocket Namespace Reference
Namespaces
client
server
subprotocol
Classes
class Receiver
class SocketContext
class SubProtocol
class SubProtocolFactory
struct SubProtocolPlugin
class SubProtocolFactorySelector
class Transmitter
Functions
unsigned char * decode64 (const char *input, int length)
char * base64 (const unsigned char *input, int length)
void serverWebSocketKey (const std::string &clientWebSocketKey, const std::function< void(char *)> &returnKey)
std::string serverWebSocketKey (const std::string &clientWebSocketKey)
static bool is_base64 (char c)
std::string base64_encode (const unsigned char *bytes_to_encode, int length)
std::string base64_decode (const std::string &encoded_string)
Function Documentation
base64()
char * web::websocket::base64 (const unsigned char * input, int length)
Definition at line 45 of file ws_utils.cpp.
{
         const int pl = 4 * ((length + 2) / 3);
         char* output =
             reinterpret_cast<char*>(calloc(static_cast<std::size_t>(pl + 1), 1)); //+1 for the terminating null that EVP_EncodeBlock adds on
         const int ol = EVP_EncodeBlock(reinterpret_cast<unsigned char*>(output), input, length);
         if (pl != ol) {
             LOG(ERROR) << "Whoops, encode predicted " << pl << " but we got " << ol;
         }
         return output;
     }
Referenced by serverWebSocketKey().
base64_decode()
std::string web::websocket::base64_decode (const std::string & encoded_string)
Definition at line 133 of file ws_utils.cpp.
{
         static const std::string base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                                 "abcdefghijklmnopqrstuvwxyz"
                                                 "0123456789+/";
         std::string::size_type in_len = encoded_string.size();
         std::string::size_type i = 0;
         std::string::size_type in_ = 0;
         char char_array_4[4], char_array_3[3];
         std::string ret;
         while (in_len-- && (encoded_string[in_] != '=') && is_base64(encoded_string[in_])) {
             char_array_4[i++] = encoded_string[in_];
             in_++;
             if (i == 4) {
                 for (i = 0; i < 4; i++) {
                     char_array_4[i] = static_cast<char>(base64_chars.find(char_array_4[i]));
                 }
                 char_array_3[0] = static_cast<char>((char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4));
                 char_array_3[1] = static_cast<char>(((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2));
                 char_array_3[2] = static_cast<char>(((char_array_4[2] & 0x3) << 6) + char_array_4[3]);
                 for (i = 0; (i < 3); i++) {
                     ret += char_array_3[i];
                 }
                 i = 0;
             }
         }
         if (i != 0) {
             for (std::string::size_type j = i; j < 4; j++) {
                 char_array_4[j] = 0;
             }
             for (std::string::size_type j = 0; j < 4; j++) {
                 char_array_4[j] = static_cast<char>(base64_chars.find(char_array_4[j]));
             }
             char_array_3[0] = static_cast<char>((char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4));
             char_array_3[1] = static_cast<char>(((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2));
             char_array_3[2] = static_cast<char>(((char_array_4[2] & 0x3) << 6) + char_array_4[3]);
             for (std::string::size_type j = 0; j < i - 1; j++) {
                 ret += char_array_3[j];
             }
         }
         return ret;
     }
References is_base64().
base64_encode()
std::string web::websocket::base64_encode (const unsigned char * bytes_to_encode, int length)
Definition at line 88 of file ws_utils.cpp.
{
         static const std::string base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                                 "abcdefghijklmnopqrstuvwxyz"
                                                 "0123456789+/";
         std::string ret;
         int i = 0;
         unsigned char char_array_3[3];
         unsigned char char_array_4[4];
         while (length--) {
             char_array_3[i++] = *(bytes_to_encode++);
             if (i == 3) {
                 char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
                 char_array_4[1] = static_cast<unsigned char>(((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4));
                 char_array_4[2] = static_cast<unsigned char>(((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6));
                 char_array_4[3] = char_array_3[2] & 0x3f;
                 for (i = 0; (i < 4); i++)
                     ret += base64_chars[char_array_4[i]];
                 i = 0;
             }
         }
         if (i != 0) {
             for (int j = i; j < 3; j++) {
                 char_array_3[j] = '\0';
             }
             char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
             char_array_4[1] = static_cast<unsigned char>(((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4));
             char_array_4[2] = static_cast<unsigned char>(((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6));
             char_array_4[3] = char_array_3[2] & 0x3f;
             for (int j = 0; j < i + 1; j++) {
                 ret += base64_chars[char_array_4[j]];
             }
             while (i++ < 3) {
                 ret += '=';
             }
         }
         return ret;
     }
Referenced by serverWebSocketKey().
decode64()
unsigned char * web::websocket::decode64 (const char * input, int length)
Definition at line 35 of file ws_utils.cpp.
{
         const int pl = 3 * length / 4;
         unsigned char* output = reinterpret_cast<unsigned char*>(calloc(static_cast<std::size_t>(pl + 1), 1));
         const int ol = EVP_DecodeBlock(output, reinterpret_cast<const unsigned char*>(input), length);
         if (pl != ol) {
             LOG(ERROR) << "Whoops, decode predicted " << pl << " but we got " << ol;
         }
         return output;
     }
is_base64()
static bool web::websocket::is_base64 (char c) inline static
Definition at line 84 of file ws_utils.cpp.
{
         return (isalnum(c) || (c == '+') || (c == '/'));
     }
Referenced by base64_decode().
serverWebSocketKey() [1/2]
std::string web::websocket::serverWebSocketKey (const std::string & clientWebSocketKey)
Definition at line 71 of file ws_utils.cpp.
{
         std::string GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
         std::string serverWebSocketKey(clientWebSocketKey + GUID);
         unsigned char digest[SHA_DIGEST_LENGTH];
         SHA1(reinterpret_cast<const unsigned char*>(serverWebSocketKey.c_str()), serverWebSocketKey.length(), digest);
         VLOG(0) << "+++++++ " << base64_encode(digest, SHA_DIGEST_LENGTH);
         return base64_encode(digest, SHA_DIGEST_LENGTH);
     }
References base64_encode(), and serverWebSocketKey().
serverWebSocketKey() [2/2]
void web::websocket::serverWebSocketKey (const std::string & clientWebSocketKey, const std::function< void(char *)> & returnKey)
Definition at line 56 of file ws_utils.cpp.
{
         std::string GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
         std::string serverWebSocketKey(clientWebSocketKey + GUID);
         unsigned char digest[SHA_DIGEST_LENGTH];
         SHA1(reinterpret_cast<const unsigned char*>(serverWebSocketKey.c_str()),
              serverWebSocketKey.length(),
              reinterpret_cast<unsigned char*>(&digest));
         char* key = base64(digest, SHA_DIGEST_LENGTH);
         returnKey(key);
         free(key);
     }
References base64().
Referenced by web::websocket::server::SocketContext::create(), and serverWebSocketKey().