snode.c: net::system Namespace Reference
net::system Namespace Reference
Functions
void * dlopen (const char *filename, int flags)
int dlclose (void *handle)
void * dlsym (void *handle, const char *symbol)
char * dlerror (void)
int getaddrinfo (const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res)
void freeaddrinfo (struct addrinfo *res)
int getnameinfo (const struct sockaddr *addr, socklen_t addrlen, char *host, socklen_t hostlen, char *serv, socklen_t servlen, int flags)
int select (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
sighandler_t signal (int signum, sighandler_t handler)
int socket (int domain, int type, int protocol)
int bind (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int listen (int sockfd, int backlog)
int accept4 (int sockfd, struct sockaddr *addr, socklen_t *addrlen, int flags)
int connect (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int getsockname (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
int getpeername (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
ssize_t recv (int sockfd, void *buf, std::size_t len, int flags)
ssize_t send (int sockfd, const void *buf, std::size_t len, int flags)
int getsockopt (int sockfd, int level, int optname, void *optval, socklen_t *optlen)
int setsockopt (int sockfd, int level, int optname, const void *optval, socklen_t optlen)
int shutdown (int sockfd, int how)
time_t time (time_t *tloc)
int gettimeofday (struct timeval *tv, struct timezone *tz)
struct tm * gmtime (const time_t *timep)
time_t mktime (struct tm *tm)
int open (const char *pathname, int flags)
ssize_t read (int fd, void *buf, std::size_t count)
ssize_t write (int fd, const void *buf, std::size_t count)
int close (int fd)
int pipe2 (int pipefd[2], int flags)
Function Documentation
accept4()
int net::system::accept4 (int sockfd, struct sockaddr * addr, socklen_t * addrlen, int flags)
Definition at line 44 of file socket.cpp.
{
         errno = 0;
         return ::accept4(sockfd, addr, addrlen, flags);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent().
bind()
int net::system::bind (int sockfd, const struct sockaddr * addr, socklen_t addrlen)
Definition at line 34 of file socket.cpp.
{
         errno = 0;
         return ::bind(sockfd, addr, addrlen);
     }
Referenced by net::socket::Socket< SocketAddressT >::bind().
close()
int net::system::close (int fd)
Definition at line 44 of file unistd.cpp.
                       {
         errno = 0;
         return ::close(fd);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), web::http::client::SocketContext< RequestT, ResponseT >::terminateConnection(), web::http::server::SocketContext< RequestT, ResponseT >::terminateConnection(), and net::Descriptor::~Descriptor().
connect()
int net::system::connect (int sockfd, const struct sockaddr * addr, socklen_t addrlen)
Definition at line 48 of file socket.cpp.
{
         errno = 0;
         return ::connect(sockfd, addr, addrlen);
     }
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connect(), and FileReader::FileReader().
dlclose()
int net::system::dlclose (void * handle)
Definition at line 31 of file dlfcn.cpp.
{
         return ::dlclose(handle);
     }
Referenced by net::DynamicLoader::execDlClose().
dlerror()
char * net::system::dlerror (void)
Definition at line 39 of file dlfcn.cpp.
{
         return ::dlerror();
     }
Referenced by net::DynamicLoader::dlError().
dlopen()
void * net::system::dlopen (const char * filename, int flags)
Definition at line 27 of file dlfcn.cpp.
{
         return ::dlopen(filename, flags);
     }
Referenced by net::DynamicLoader::dlOpen().
dlsym()
void * net::system::dlsym (void * handle, const char * symbol)
Definition at line 35 of file dlfcn.cpp.
{
         return ::dlsym(handle, symbol);
     }
Referenced by net::DynamicLoader::dlSym().
freeaddrinfo()
void net::system::freeaddrinfo (struct addrinfo * res)
Definition at line 34 of file netdb.cpp.
{
         errno = 0;
         return ::freeaddrinfo(res);
     }
Referenced by net::socket::ip::address::ipv4::InetAddress::InetAddress(), and net::socket::ip::address::ipv6::InetAddress::InetAddress().
getaddrinfo()
int net::system::getaddrinfo (const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
Definition at line 29 of file netdb.cpp.
{
         errno = 0;
         return ::getaddrinfo(node, service, hints, res);
     }
Referenced by net::socket::ip::address::ipv4::InetAddress::InetAddress(), and net::socket::ip::address::ipv6::InetAddress::InetAddress().
getnameinfo()
int net::system::getnameinfo (const struct sockaddr * addr, socklen_t addrlen, char * host, socklen_t hostlen, char * serv, socklen_t servlen, int flags)
Definition at line 40 of file netdb.cpp.
{
         errno = 0;
         return ::getnameinfo(addr, addrlen, host, hostlen, serv, servlen, flags);
     }
Referenced by net::socket::ip::address::ipv4::InetAddress::host(), net::socket::ip::address::ipv6::InetAddress::host(), net::socket::ip::address::ipv4::InetAddress::ip(), net::socket::ip::address::ipv6::InetAddress::ip(), net::socket::ip::address::ipv4::InetAddress::serv(), and net::socket::ip::address::ipv6::InetAddress::serv().
getpeername()
int net::system::getpeername (int sockfd, struct sockaddr * addr, socklen_t * addrlen)
Definition at line 58 of file socket.cpp.
{
         errno = 0;
         return ::getpeername(sockfd, addr, addrlen);
     }
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connectEvent().
getsockname()
int net::system::getsockname (int sockfd, struct sockaddr * addr, socklen_t * addrlen)
Definition at line 53 of file socket.cpp.
{
         errno = 0;
         return ::getsockname(sockfd, addr, addrlen);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), and net::socket::stream::SocketConnector< SocketConnectionT >::connectEvent().
getsockopt()
int net::system::getsockopt (int sockfd, int level, int optname, void * optval, socklen_t * optlen)
Definition at line 73 of file socket.cpp.
{
         errno = 0;
         return ::getsockopt(sockfd, level, optname, optval, optlen);
     }
Referenced by net::socket::stream::SocketConnector< SocketConnectionT >::connectEvent().
gettimeofday()
int net::system::gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 34 of file time.cpp.
{
         errno = 0;
         return ::gettimeofday(tv, tz);
     }
Referenced by net::TimerEventDispatcher::dispatch(), net::TimerEventDispatcher::getNextTimeout(), and net::timer::Timer::Timer().
gmtime()
struct tm * net::system::gmtime (const time_t * timep)
Definition at line 39 of file time.cpp.
{
         errno = 0;
         return ::gmtime(timep);
     }
Referenced by web::http::server::Response::clearCookie(), httputils::file_mod_http_date(), and httputils::from_http_date().
listen()
int net::system::listen (int sockfd, int backlog)
Definition at line 39 of file socket.cpp.
{
         errno = 0;
         return ::listen(sockfd, backlog);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::listen().
mktime()
time_t net::system::mktime (struct tm * tm)
Definition at line 44 of file time.cpp.
{
         errno = 0;
         return ::mktime(tm);
     }
Referenced by httputils::from_http_date().
open()
int net::system::open (const char * pathname, int flags)
Definition at line 29 of file unistd.cpp.
{
         errno = 0;
         return ::open(pathname, flags);
     }
Referenced by FileReader::connect().
pipe2()
int net::system::pipe2 (int pipefd[2], int flags)
Definition at line 49 of file unistd.cpp.
{
         errno = 0;
         return ::pipe2(pipefd, flags);
     }
Referenced by net::pipe::Pipe::Pipe().
read()
ssize_t net::system::read (int fd, void * buf, std::size_t count)
Definition at line 34 of file unistd.cpp.
{
         errno = 0;
         return ::read(fd, buf, count);
     }
Referenced by FileReader::readEvent(), and net::pipe::PipeSink::readEvent().
recv()
ssize_t net::system::recv (int sockfd, void * buf, std::size_t len, int flags)
Definition at line 63 of file socket.cpp.
{
         errno = 0;
         return ::recv(sockfd, buf, len, flags);
     }
Referenced by net::socket::stream::legacy::SocketReader< SocketT >::read().
select()
int net::system::select (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
Definition at line 29 of file select.cpp.
{
         errno = 0;
         return ::select(nfds, readfds, writefds, exceptfds, timeout);
     }
Referenced by net::EventLoop::_tick().
send()
ssize_t net::system::send (int sockfd, const void * buf, std::size_t len, int flags)
Definition at line 68 of file socket.cpp.
{
         errno = 0;
         return ::send(sockfd, buf, len, flags);
     }
Referenced by net::socket::stream::legacy::SocketWriter< SocketT >::write().
setsockopt()
int net::system::setsockopt (int sockfd, int level, int optname, const void * optval, socklen_t optlen)
Definition at line 78 of file socket.cpp.
{
         errno = 0;
         return ::setsockopt(sockfd, level, optname, optval, optlen);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::reuseAddress().
shutdown()
int net::system::shutdown (int sockfd, int how)
Definition at line 83 of file socket.cpp.
{
         errno = 0;
         return ::shutdown(sockfd, how);
     }
Referenced by net::socket::stream::SocketListener< SocketConnectionT >::acceptEvent(), and net::socket::Socket< SocketAddressT >::shutdown().
signal()
sighandler_t net::system::signal (int signum, sighandler_t handler)
Definition at line 29 of file signal.cpp.
{
         errno = 0;
         return ::signal(signum, handler);
     }
Referenced by net::EventLoop::start(), and net::EventLoop::tick().
socket()
int net::system::socket (int domain, int type, int protocol)
Definition at line 29 of file socket.cpp.
{
         errno = 0;
         return ::socket(domain, type, protocol);
     }
Referenced by net::socket::bluetooth::rfcomm::Socket::create(), net::socket::ip::tcp::ipv4::Socket::create(), net::socket::ip::tcp::ipv6::Socket::create(), and net::socket::bluetooth::l2cap::Socket::create().
time()
time_t net::system::time (time_t * tloc)
Definition at line 29 of file time.cpp.
{
         errno = 0;
         return ::time(tloc);
     }
Referenced by net::EventLoop::_tick(), web::http::server::Response::clearCookie(), net::DescriptorEventReceiver::enabled(), httputils::from_http_date(), and net::DescriptorEventReceiver::resumed().
write()
ssize_t net::system::write (int fd, const void * buf, std::size_t count)
Definition at line 39 of file unistd.cpp.
{
         errno = 0;
         return ::write(fd, buf, count);
     }
Referenced by net::pipe::PipeSource::writeEvent().