snode.c: base64 Namespace Reference
base64 Namespace Reference
Functions
std::string serverWebSocketKey (const std::string &clientWebSocketKey)
static bool is_base64 (char c)
std::string base64_encode (const unsigned char *bytes_to_encode, std::size_t length)
std::string base64_decode (const std::string &encoded_string)
Function Documentation
base64_decode()
std::string base64::base64_decode (const std::string & encoded_string)
Definition at line 90 of file base64.cpp.
{
         static const std::string base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                                 "abcdefghijklmnopqrstuvwxyz"
                                                 "0123456789+/";
         std::string::size_type in_len = encoded_string.size();
         std::string::size_type i = 0;
         std::string::size_type in_ = 0;
         char char_array_4[4], char_array_3[3];
         std::string ret;
         while (in_len-- && (encoded_string[in_] != '=') && is_base64(encoded_string[in_])) {
             char_array_4[i++] = encoded_string[in_];
             in_++;
             if (i == 4) {
                 for (i = 0; i < 4; i++) {
                     char_array_4[i] = static_cast<char>(base64_chars.find(char_array_4[i]));
                 }
                 char_array_3[0] = static_cast<char>((char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4));
                 char_array_3[1] = static_cast<char>(((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2));
                 char_array_3[2] = static_cast<char>(((char_array_4[2] & 0x3) << 6) + char_array_4[3]);
                 for (i = 0; (i < 3); i++) {
                     ret += char_array_3[i];
                 }
                 i = 0;
             }
         }
         if (i != 0) {
             for (std::string::size_type j = i; j < 4; j++) {
                 char_array_4[j] = 0;
             }
             for (std::string::size_type j = 0; j < 4; j++) {
                 char_array_4[j] = static_cast<char>(base64_chars.find(char_array_4[j]));
             }
             char_array_3[0] = static_cast<char>((char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4));
             char_array_3[1] = static_cast<char>(((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2));
             char_array_3[2] = static_cast<char>(((char_array_4[2] & 0x3) << 6) + char_array_4[3]);
             for (std::string::size_type j = 0; j < i - 1; j++) {
                 ret += char_array_3[j];
             }
         }
         return ret;
     }
References is_base64().
base64_encode()
std::string base64::base64_encode (const unsigned char * bytes_to_encode, std::size_t length)
Definition at line 45 of file base64.cpp.
{
         static const std::string base64_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                                 "abcdefghijklmnopqrstuvwxyz"
                                                 "0123456789+/";
         std::string ret;
         int i = 0;
         unsigned char char_array_3[3];
         unsigned char char_array_4[4];
         while (length--) {
             char_array_3[i++] = *(bytes_to_encode++);
             if (i == 3) {
                 char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
                 char_array_4[1] = static_cast<unsigned char>(((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4));
                 char_array_4[2] = static_cast<unsigned char>(((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6));
                 char_array_4[3] = char_array_3[2] & 0x3f;
                 for (i = 0; (i < 4); i++)
                     ret += base64_chars[char_array_4[i]];
                 i = 0;
             }
         }
         if (i != 0) {
             for (int j = i; j < 3; j++) {
                 char_array_3[j] = '\0';
             }
             char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
             char_array_4[1] = static_cast<unsigned char>(((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4));
             char_array_4[2] = static_cast<unsigned char>(((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6));
             char_array_4[3] = char_array_3[2] & 0x3f;
             for (int j = 0; j < i + 1; j++) {
                 ret += base64_chars[char_array_4[j]];
             }
             while (i++ < 3) {
                 ret += '=';
             }
         }
         return ret;
     }
Referenced by web::websocket::client::SocketContextUpgradeFactory::prepare(), and serverWebSocketKey().
is_base64()
static bool base64::is_base64 (char c) static
Definition at line 41 of file base64.cpp.
{
         return (isalnum(c) || (c == '+') || (c == '/'));
     }
Referenced by base64_decode().
serverWebSocketKey()
std::string base64::serverWebSocketKey (const std::string & clientWebSocketKey)
Definition at line 32 of file base64.cpp.
{
         std::string GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
         std::string serverWebSocketKey(clientWebSocketKey + GUID);
         std::string digest = sha1(serverWebSocketKey);
         return base64_encode(reinterpret_cast<unsigned char*>(digest.data()), digest.length());
     }
References base64_encode(), and sha1().
Referenced by web::websocket::server::SocketContextUpgradeFactory::create().