snode.c: web::ws::subprotocol::echo::server Namespace Reference
web::ws::subprotocol::echo::server Namespace Reference
Classes
class Echo
Functions
web::ws::WSSubProtocol * create ()
const char * name ()
void destroy (web::ws::WSSubProtocol *echo)
web::ws::WSSubProtocol::Role role ()
struct WSSubProtocolPluginInterface plugin (void *handle)
Function Documentation
create()
web::ws::WSSubProtocol* web::ws::subprotocol::echo::server::create ()
Definition at line 33 of file Echo.cpp.
{
         return new Echo();
     }
destroy()
void web::ws::subprotocol::echo::server::destroy (web::ws::WSSubProtocol * echo)
Definition at line 41 of file Echo.cpp.
{
         delete echo;
     }
name()
const char* web::ws::subprotocol::echo::server::name ()
Definition at line 37 of file Echo.cpp.
{
         return NAME;
     }
References NAME.
Referenced by express::middleware::StaticMiddleware::appendStdCookie(), web::http::server::Response::clearCookie(), web::http::client::Request::cookie(), web::http::server::Response::cookie(), utils::MultibleAttributeInjector::delAttribute(), express::Response::download(), utils::MultibleAttributeInjector::getAttribute(), utils::SingleAttributeInjector::getAttribute(), utils::MultibleAttributeInjector::hasAttribute(), express::Response::redirect(), web::http::client::Request::sendHeader(), utils::MultibleAttributeInjector::setAttribute(), utils::SingleAttributeInjector::setAttribute(), net::socket::stream::tls::ssl_ctx_new(), and web::ws::subprotocol::WSSubProtocolSelector::~WSSubProtocolSelector().
plugin()
struct web::ws::subprotocol::WSSubProtocolPluginInterface web::ws::subprotocol::echo::server::plugin (void * handle)
Definition at line 45 of file Echo.cpp.
{
             return WSSubProtocolPluginInterface{.name = name, .role = role, .create = create, .destroy = destroy, .handle = handle};
         }
References web::ws::WSSubProtocol::SERVER.
role()
web::ws::WSSubProtocol::Role web::ws::subprotocol::echo::server::role ()
Definition at line 45 of file Echo.cpp.
{
         return web::ws::WSSubProtocol::Role::SERVER;
     }
Referenced by web::ws::subprotocol::WSSubProtocolSelector::select().