snode.c: net::socket::stream::tls Namespace Reference
net::socket::stream::tls Namespace Reference
Classes
class SocketClient
class SocketConnection
class SocketConnector
class SocketListener
class SocketReader
class SocketServer
class SocketWriter
class TLSHandshake
Functions
static int password_callback (char *buf, int size, int, void *u)
static int verify_callback ([[maybe_unused]] int preverify_ok, [[maybe_unused]] X509_STORE_CTX *ctx)
SSL_CTX * ssl_ctx_new (const std::map< std::string, std::any > &options, bool server)
void ssl_ctx_free (SSL_CTX *ctx)
void ssl_set_sni (SSL *ssl, std::map< std::string, std::any > &options)
void ssl_log (const std::string &message, int sslErr)
void ssl_log_error (const std::string &message)
void ssl_log_warning (const std::string &message)
void ssl_log_info (const std::string &message)
Variables
static int sslSessionCtxId = 1
Function Documentation
password_callback()
static int net::socket::stream::tls::password_callback (char * buf, int size, int , void * u) static
Definition at line 41 of file ssl_utils.cpp.
{
         strncpy(buf, static_cast<char*>(u), static_cast<std::size_t>(size));
         buf[size - 1] = '\0';
         memset(u, 0, ::strlen(static_cast<char*>(u))); // garble password
         free(u);
         return static_cast<int>(::strlen(buf));
     }
Referenced by ssl_ctx_new().
ssl_ctx_free()
void net::socket::stream::tls::ssl_ctx_free (SSL_CTX * ctx)
Definition at line 140 of file ssl_utils.cpp.
{
         if (ctx != nullptr) {
             SSL_CTX_free(ctx);
         }
     }
Referenced by net::socket::stream::tls::SocketConnector< SocketT >::~SocketConnector(), and net::socket::stream::tls::SocketListener< SocketT >::~SocketListener().
ssl_ctx_new()
SSL_CTX * net::socket::stream::tls::ssl_ctx_new (const std::map< std::string, std::any > & options, bool server)
Definition at line 57 of file ssl_utils.cpp.
{
         std::string certChain;
         std::string keyPEM;
         std::string password;
         std::string caFile;
         std::string caDir;
         bool useDefaultCADir = false;
         for (const auto& [name, value] : options) {
             if (name == "certChain") {
                 certChain = std::any_cast<const char*>(value);
             } else if (name == "keyPEM") {
                 keyPEM = std::any_cast<const char*>(value);
             } else if (name == "password") {
                 password = std::any_cast<const char*>(value);
             } else if (name == "caFile") {
                 caFile = std::any_cast<const char*>(value);
             } else if (name == "caDir") {
                 caDir = std::any_cast<const char*>(value);
             } else if (name == "useDefaultCADir") {
                 useDefaultCADir = std::any_cast<bool>(value);
             }
         }
         SSL_CTX* ctx = SSL_CTX_new(server ? TLS_server_method() : TLS_client_method());
         if (ctx != nullptr) {
             bool sslErr = false;
             if (server) {
                 SSL_CTX_set_session_id_context(ctx, (const unsigned char*) &sslSessionCtxId, sizeof(sslSessionCtxId));
                 sslSessionCtxId++;
             }
             if (!caFile.empty() || !caDir.empty()) {
                 if (!SSL_CTX_load_verify_locations(
                         ctx, !caFile.empty() ? caFile.c_str() : nullptr, !caDir.empty() ? caDir.c_str() : nullptr)) {
                     ssl_log_error("Can not load CA file or non default CA directory");
                     sslErr = true;
                 }
             }
             if (!sslErr && useDefaultCADir) {
                 if (!SSL_CTX_set_default_verify_paths(ctx)) {
                     ssl_log_error("Can not load default CA directory");
                     sslErr = true;
                 }
             }
             if (!sslErr) {
                 if (server && (useDefaultCADir || !caFile.empty() || !caDir.empty())) {
                     SSL_CTX_set_verify_depth(ctx, 5);
                     SSL_CTX_set_verify(ctx, SSL_VERIFY_FLAGS, verify_callback);
                 }
                 if (!certChain.empty()) {
                     if (SSL_CTX_use_certificate_chain_file(ctx, certChain.c_str()) != 1) {
                         ssl_log_error("Can not load certificate chain");
                         sslErr = true;
                     } else if (!keyPEM.empty()) {
                         if (!password.empty()) {
                             SSL_CTX_set_default_passwd_cb(ctx, password_callback);
                             SSL_CTX_set_default_passwd_cb_userdata(ctx, ::strdup(password.c_str()));
                         }
                         if (SSL_CTX_use_PrivateKey_file(ctx, keyPEM.c_str(), SSL_FILETYPE_PEM) != 1) {
                             errno = EINVAL;
                             ssl_log_error("Can not load private key");
                             sslErr = true;
                         } else if (!SSL_CTX_check_private_key(ctx)) {
                             errno = EINVAL;
                             ssl_log_error("Private key not consistent with CA files");
                             sslErr = true;
                         }
                     }
                 }
             }
             if (sslErr) {
                 SSL_CTX_free(ctx);
                 ctx = nullptr;
             }
         } else {
             ssl_log_error("SSL CTX not created");
         }
         return ctx;
     }
References password_callback(), ssl_log_error(), SSL_VERIFY_FLAGS, sslSessionCtxId, and verify_callback().
ssl_log()
void net::socket::stream::tls::ssl_log (const std::string & message, int sslErr)
Definition at line 152 of file ssl_utils.cpp.
{
         switch (sslErr) {
             case SSL_ERROR_NONE:
                 [[fallthrough]];
             case SSL_ERROR_ZERO_RETURN:
                 ssl_log_info(message);
                 break;
             case SSL_ERROR_SYSCALL:
                 if (errno != 0) {
                     ssl_log_error(message);
                 }
                 break;
             default:
                 ssl_log_warning(message);
                 break;
         };
     }
References ssl_log_error(), ssl_log_info(), and ssl_log_warning().
Referenced by net::socket::stream::tls::SocketReader< SocketT >::read(), net::socket::stream::tls::SocketConnector< SocketT >::SocketConnector(), net::socket::stream::tls::SocketListener< SocketT >::SocketListener(), and net::socket::stream::tls::SocketWriter< SocketT >::write().
ssl_log_error()
void net::socket::stream::tls::ssl_log_error (const std::string & message)
Definition at line 170 of file ssl_utils.cpp.
{
         PLOG(ERROR) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(ERROR) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
Referenced by ssl_ctx_new(), and ssl_log().
ssl_log_info()
void net::socket::stream::tls::ssl_log_info (const std::string & message)
Definition at line 188 of file ssl_utils.cpp.
{
         PLOG(INFO) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(INFO) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
Referenced by ssl_log().
ssl_log_warning()
void net::socket::stream::tls::ssl_log_warning (const std::string & message)
Definition at line 179 of file ssl_utils.cpp.
{
         LOG(WARNING) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(WARNING) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
Referenced by ssl_log().
ssl_set_sni()
void net::socket::stream::tls::ssl_set_sni (SSL * ssl, std::map< std::string, std::any > & options)
Definition at line 146 of file ssl_utils.cpp.
{
         if (options.contains("Host")) {
             SSL_set_tlsext_host_name(ssl, std::any_cast<const char*>(options["Host"]));
         }
     }
Referenced by net::socket::stream::tls::SocketConnector< SocketT >::SocketConnector().
verify_callback()
static int net::socket::stream::tls::verify_callback ([[maybe_unused] ] int preverify_ok, [[maybe_unused] ] X509_STORE_CTX * ctx) static
Definition at line 51 of file ssl_utils.cpp.
{
         return 1;
     }
Referenced by ssl_ctx_new().
Variable Documentation
sslSessionCtxId
int net::socket::stream::tls::sslSessionCtxId = 1 static
Definition at line 55 of file ssl_utils.cpp.
Referenced by ssl_ctx_new().