snode.c: utils/sha1.h File Reference
sha1.h File Reference
#include <cstddef>
#include <cstdint>
#include <iostream>
#include <string>
Classes
class SHA1
Functions
std::string sha1 (const std::string &string)
Function Documentation
sha1()
std::string sha1 (const std::string & string)
Definition at line 270 of file sha1.cpp.
{
     SHA1 checksum;
     checksum.update(string);
     return transform_to_binary(checksum.final());
 }
References SHA1::final(), transform_to_binary(), and SHA1::update().
Referenced by base64::serverWebSocketKey().