snode.c: web::ws::subprotocol::WSSubProtocolPluginInterface Struct Reference
web::ws::subprotocol::WSSubProtocolPluginInterface Struct Reference
#include <WSSubProtocolPluginInterface.h>
Public Attributes
const char *(* name)()
web::ws::WSSubProtocol::Role(* role)()
web::ws::WSSubProtocol *(* create)()
void(* destroy)(web::ws::WSSubProtocol *)
void * handle
Detailed Description
Definition at line 31 of file WSSubProtocolPluginInterface.h.
Member Data Documentation
create
web::ws::WSSubProtocol*(* web::ws::subprotocol::WSSubProtocolPluginInterface::create) ()
Definition at line 34 of file WSSubProtocolPluginInterface.h.
Referenced by web::ws::server::WSContext::create().
destroy
void(* web::ws::subprotocol::WSSubProtocolPluginInterface::destroy) (web::ws::WSSubProtocol *)
Definition at line 35 of file WSSubProtocolPluginInterface.h.
handle
void* web::ws::subprotocol::WSSubProtocolPluginInterface::handle
Definition at line 36 of file WSSubProtocolPluginInterface.h.
Referenced by web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocol().
name
const char*(* web::ws::subprotocol::WSSubProtocolPluginInterface::name) ()
Definition at line 32 of file WSSubProtocolPluginInterface.h.
Referenced by web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocol().
role
web::ws::WSSubProtocol::Role(* web::ws::subprotocol::WSSubProtocolPluginInterface::role) ()
Definition at line 33 of file WSSubProtocolPluginInterface.h.
Referenced by web::ws::subprotocol::WSSubProtocolSelector::loadSubProtocol().
The documentation for this struct was generated from the following file:
web/ws/subprotocol/WSSubProtocolPluginInterface.h